In [8]:
pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.6.1-cp39-cp39-win_amd64.whl (11.2 MB)
Collecting joblib>=1.2.0
  Downloading joblib-1.5.3-py3-none-any.whl (309 kB)
     -------------------------------------- 309.1/309.1 KB 9.6 MB/s eta 0:00:00
Collecting threadpoolctl>=3.1.0
  Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Requirement already satisfied: scipy>=1.6.0 in c:\users\samue\documents\datascientest-lol-draft_analyzer\env_csv\lib\site-packages (from scikit-learn) (1.13.1)
Requirement already satisfied: numpy>=1.19.5 in c:\users\samue\documents\datascientest-lol-draft_analyzer\env_csv\lib\site-packages (from scikit-learn) (2.0.2)
Installing collected packages: threadpoolctl, joblib, scikit-learn
Successfully installed joblib-1.5.3 scikit-learn-1.6.1 threadpoolctl-3.6.0
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 22.0.4; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\samue\Documents\datascientest-lol-draft_analyzer\env_csv\Scripts\python.exe -m pip install --upgrade pip' command.

In [1]:
import pandas as pd
import numpy as np
import glob
import os

from itertools import combinations
from scipy.stats import beta

from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss, roc_auc_score

In [2]:
# data path
DATA_PATH = r"D:\lol draft analyzer - datascientest\AA- toutes les donnees au propre - lecture-ecriture"

# Games
GAMES_PATH = f"{DATA_PATH}\\les matchs\\200k_games\\draft_simple.csv"
df_games = pd.read_csv(GAMES_PATH)

# Games pro
GAMES_PRO_PATH = f"{DATA_PATH}\\les matchs\\games pro 2025 complet\\games_pro_2025_very_light.csv"
df_games_pro = pd.read_csv(GAMES_PRO_PATH)

# # Invocateurs
# SUMMONERS_PATH = f"{DATA_PATH}\\les stats invocateurs\\summoners_

# Champions
CHAMPS_PATH = f"{DATA_PATH}\\les stats champions\\champions_15.1.1_15.24.1.csv"
df_champs = pd.read_csv(CHAMPS_PATH, encoding="utf-8")

# WR simples
SIMPLE_WR_PATH = f"{DATA_PATH}\\les winrates simples\\données raffinées\\df_Simple_WR_FULL.csv"
df_simple_wr = pd.read_csv(SIMPLE_WR_PATH, encoding="utf-8")


def load_all_csvs(folder_path):
    all_files = glob.glob(os.path.join(folder_path, "**/*.csv"), recursive=True)
    df_list = [pd.read_csv(f) for f in all_files]
    return pd.concat(df_list, ignore_index=True)


PATH = r"D:\lol draft analyzer - datascientest\AA- toutes les donnees au propre - lecture-ecriture\les winrates matchups\TOUTTOUT15.24"
matchups_df = load_all_csvs(os.path.join(PATH, "matchups/"))
synergies_df = load_all_csvs(os.path.join(PATH, "synergies/"))

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\3173685338.py:6: DtypeWarning: Columns (10,11,12,13,14,20,21,22,23,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df_games = pd.read_csv(GAMES_PATH)

In [3]:
import os
import glob
import pandas as pd
from collections import defaultdict

def print_csv_line_stats(folder_path):
    # dictionnaire pour stocker stats par sous-dossier
    stats = defaultdict(lambda: defaultdict(int))

    # récupérer tous les fichiers csv récursivement
    all_files = glob.glob(os.path.join(folder_path, "**/*.csv"), recursive=True)

    for f in all_files:
        # trouver le sous-dossier relatif
        subfolder = os.path.relpath(os.path.dirname(f), folder_path)
        try:
            df = pd.read_csv(f)
            n_lines = len(df)
            stats[subfolder]['total_files'] += 1
            stats[subfolder][f"{n_lines}_lines"] += 1
        except Exception as e:
            print(f"Erreur avec le fichier {f}: {e}")

    # print des stats
    for subfolder, counts in stats.items():
        print(f"--- {subfolder} ---")
        print(f"Total files: {counts['total_files']}")
        for k, v in counts.items():
            if k != 'total_files':
                print(f"Files with {k}: {v}")
        print()

    return stats

# Exemple d'utilisation
folder_path = os.path.join(PATH, "matchups/")
stats = print_csv_line_stats(folder_path)

--- adc matchup ---
Total files: 44
Files with 5_lines: 42
Files with 4_lines: 2

--- jun matchup ---
Total files: 44
Files with 5_lines: 43
Files with 4_lines: 1

--- mid matchup ---
Total files: 44
Files with 5_lines: 42
Files with 2_lines: 1
Files with 4_lines: 1

--- sup matchup ---
Total files: 44
Files with 5_lines: 42
Files with 4_lines: 2

--- top matchup ---
Total files: 44
Files with 5_lines: 43
Files with 4_lines: 1

In [ ]:
il manque donc des lignes dans df_matchups : il y a des lignes qui ont mal été scrappées...

In [4]:
pd.set_option('display.max_columns', None)   # affiche toutes les colonnes
pd.set_option('display.max_rows', None)      # si besoin
pd.set_option('display.width', None)         # évite le retour à la ligne forcé
pd.set_option('display.max_colwidth', None)  # affiche le contenu complet des cellules

print(df_games.head())
print("=========================================")
print(df_champs.head())
print("=========================================")
print(df_simple_wr.head())
print("=========================================")
print(matchups_df.head())
print("=========================================")
print(synergies_df.head())
print("=========================================")
print(df_games_pro.head())

          match_id serveur           patch       elo  blue_side_win  \
0  EUW1_7517331727    euw1  15.17.708.5788  HIGH_ELO          False
1  EUW1_7509322616    euw1  15.17.706.7412  HIGH_ELO          False
2  EUW1_7509243675    euw1  15.17.706.7412  HIGH_ELO          False
3  EUW1_7509193063    euw1  15.17.706.7412  HIGH_ELO          False
4  EUW1_7508909082    euw1  15.17.706.7412  HIGH_ELO          False

  blue_top_champion blue_jungle_champion blue_mid_champion blue_adc_champion  \
0              Sett                Talon             Diana              Jinx
1       Mordekaiser               Qiyana             Yasuo             Corki
2           Smolder              Kindred             Galio              Jinx
3           Warwick              Nidalee             Akali            Yunara
4            Aurora              XinZhao            Twitch            Yunara

  blue_support_champion blue_top_puuid blue_jungle_puuid blue_mid_puuid  \
0                  Rell            NaN               NaN            NaN
1                  Nami            NaN               NaN            NaN
2                 Milio            NaN               NaN            NaN
3                 Rakan            NaN               NaN            NaN
4                 Rakan            NaN               NaN            NaN

  blue_adc_puuid blue_support_puuid red_top_champion red_jungle_champion  \
0            NaN                NaN            Yasuo        FiddleSticks
1            NaN                NaN              Jax             Hecarim
2            NaN                NaN            Quinn                Kayn
3            NaN                NaN          Chogath              RekSai
4            NaN                NaN            Jayce                Sett

  red_mid_champion red_adc_champion red_support_champion red_top_puuid  \
0       Cassiopeia         Aphelios                 Bard           NaN
1           Syndra            Senna                 Bard           NaN
2           Xerath      MissFortune                Rakan           NaN
3           Xerath            Kaisa                 Sona           NaN
4            Akali           Lucian                Milio           NaN

  red_jungle_puuid red_mid_puuid red_adc_puuid red_support_puuid blue_ban_1  \
0              NaN           NaN           NaN               NaN       Lulu
1              NaN           NaN           NaN               NaN     Yunara
2              NaN           NaN           NaN               NaN  Dr. Mundo
3              NaN           NaN           NaN               NaN      Sivir
4              NaN           NaN           NaN               NaN     Draven

  blue_ban_2 blue_ban_3 blue_ban_4 blue_ban_5     red_ban_1   red_ban_2  \
0      Fiora     Rengar        Vex      Poppy     Dr. Mundo       Garen
1       Pyke       Gwen      Kayle    Smolder     Master Yi    Pantheon
2     Rengar      Fiora  Master Yi      Yasuo     Master Yi      Twitch
3     Qiyana    Naafiri     Draven     Twitch  Fiddlesticks  Blitzcrank
4   Kassadin      Shaco       Ahri      Senna      Nocturne     Evelynn

  red_ban_3 red_ban_4 red_ban_5
0     Milio       Zoe    Draven
1    Twitch    Draven     Fiora
2     Akali    Draven    Aatrox
3       Mel  Volibear    Darius
4     Galio     Yasuo     Riven
=========================================
    patch       id  key     name                 title        partype  \
0  15.1.1   Aatrox  266   Aatrox       Épée des Darkin  Puits de sang
1  15.1.1     Ahri  103     Ahri  Renard à neuf queues           Mana
2  15.1.1    Akali   84    Akali      Assassin rebelle        Énergie
3  15.1.1   Akshan  166   Akshan    Sentinelle rebelle           Mana
4  15.1.1  Alistar   12  Alistar             Minotaure           Mana

                       tags  \
0               ["Fighter"]
1      ["Mage", "Assassin"]
2              ["Assassin"]
3  ["Marksman", "Assassin"]
4       ["Tank", "Support"]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  lore  \
0  Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des siècles d'emprisonnement, Aatrox fut le premier à retrouver sa liberté, en corrompant et transformant les mortels assez stupides pour tenter de s'emparer de l'arme magique qui contenait son essence. Désormais en possession d'un corps qu'il a approximativement transformé pour rappeler son ancienne forme, il arpente Runeterra en cherchant à assouvir sa vengeance apocalyptique.
1                                                                                                                                                                                                           Connectée à la magie du royaume spirituel, Ahri est une mystérieuse Vastaya aux traits de renard qui peut manipuler les émotions de sa proie et consumer son essence, afin de recevoir des fragments de sa mémoire. Ahri fut un temps un terrifiant prédateur, mais elle voyage désormais à la recherche des vestiges de ses ancêtres tout en essayant de remplacer les souvenirs qu'elle a volés par sa propre expérience de l'existence.
2                                                                                                                                                                                                                            Ayant abandonné l'Ordre Kinkou et le titre de Poing de l'ombre, Akali combat aujourd'hui seule, prête à devenir l'arme mortelle dont son peuple a besoin. Bien qu'elle n'oublie rien de tout ce que son maître Shen lui a enseigné, elle a juré de défendre Ionia contre ses ennemis, une élimination après l'autre. Akali tue sans faire de bruit, mais son message est fort et clair : craignez l'assassin sans maître.
3                                                                                                                          Se jouant du danger, Akshan combat le mal sans jamais se départir de son charisme (il ne faut jamais sous-estimer l'importance de la cape) et de sa droiture. Il est passé maître dans l'art du combat furtif, ce qui lui permet d'échapper au regard de ses ennemis et de réapparaître lorsqu'ils s'y attendent le moins. À l'aide de son sens aigu de la justice et d'une arme légendaire défiant la mort elle-même, il redresse les torts des nombreux vauriens de Runeterra. Sa règle d'or : « ne sois pas crapuleux. »
4                                                                                                                                                                                                                        Alistar est un guerrier redoutable cherchant à se venger de l'empire noxien qui a détruit son clan. Bien qu'il ait été réduit en esclavage et forcé de vivre une vie de gladiateur, sa volonté de fer lui a permis de ne pas succomber à la folie bestiale qui le menaçait. Maintenant qu'il a retrouvé la liberté, il combat au nom des faibles et des opprimés. Ses seules armes sont ses cornes, ses sabots et ses poings.

                                                                                                                                                                                                                                                              blurb  \
0      Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des...
1  Connectée à la magie du royaume spirituel, Ahri est une mystérieuse Vastaya aux traits de renard qui peut manipuler les émotions de sa proie et consumer son essence, afin de recevoir des fragments de sa mémoire. Ahri fut un temps un terrifiant prédateur...
2    Ayant abandonné l'Ordre Kinkou et le titre de Poing de l'ombre, Akali combat aujourd'hui seule, prête à devenir l'arme mortelle dont son peuple a besoin. Bien qu'elle n'oublie rien de tout ce que son maître Shen lui a enseigné, elle a juré de défendre...
3   Se jouant du danger, Akshan combat le mal sans jamais se départir de son charisme (il ne faut jamais sous-estimer l'importance de la cape) et de sa droiture. Il est passé maître dans l'art du combat furtif, ce qui lui permet d'échapper au regard de ses...
4     Alistar est un guerrier redoutable cherchant à se venger de l'empire noxien qui a détruit son clan. Bien qu'il ait été réduit en esclavage et forcé de vivre une vie de gladiateur, sa volonté de fer lui a permis de ne pas succomber à la folie bestiale...

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          allytips  \
0                                                                                                                                                                             ["Utilisez Ruée obscure tout en lançant Épée des Darkin pour augmenter vos chances de toucher l'ennemi.", "Facilitez Épée des Darkin avec des compétences de contrôle de foule, telles que Chaînes infernales, ou avec les effets immobilisants de vos alliés.", "Lancez Fossoyeur des mondes quand vous êtes certain de pouvoir forcer le combat."]
1                                                                                                                       ["Utilisez Charme pour préparer vos combos, cela facilitera grandement l'utilisation d'Orbe d'illusion et de Lucioles.", "Initiez les combats d'équipe avec Charme et poursuivez les retardataires avec Assaut spirituel.", "Assaut spirituel ouvre la voie aux compétences d'Ahri, permet d'activer Charme, aide à frapper deux fois avec Orbe d'illusion et permet d'approcher pour utiliser Lucioles."]
2                                                                                                                                                                                                                            ["Akali peut facilement tuer les champions fragiles. Laissez votre équipe engager le combat, puis frappez les adversaires en retrait.", "Linceul nébuleux vous protège même dans les situations les plus dangereuses. Profitez-en pour refaire le plein d'énergie avant de lancer un nouvel assaut."]
3  ["Se jouant du danger, Akshan combat le mal sans jamais se départir de son charisme (il ne faut jamais sous-estimer l'importance de la cape) et de sa droiture. Il est passé maître dans l'art du combat furtif, ce qui lui permet d'échapper au regard de ses ennemis et de réapparaître lorsqu'ils s'y attendent le moins. À l'aide de son sens aigu de la justice et d'une arme légendaire défiant la mort elle-même, il redresse les torts des nombreux vauriens de Runeterra. Sa règle d'or : « ne sois pas crapuleux. »"]
4                                                                                                                                                                                                                                ["Atomisation peut vous aider à mieux vous placer pour un Coup de tête.", "La vitesse de déplacement est très importante pour Alistar. Achetez les bonnes bottes.", "Saut éclair vous permet de surprendre votre cible ; repoussez-la ensuite vers vos alliés avec Atomisation et Coup de tête."]

                                                                                                                                                                                                                                                                                                                                                                                                                                                   enemytips  \
0                                                                                                                                                              ["Les attaques d'Aatrox sont prévisibles. Profitez-en pour esquiver ses zones d'impact.", "Il est plus facile de fuir les Chaînes infernales d'Aatrox en courant vers un côté ou vers Aatrox.", "Quand Aatrox utilise son ultime, gardez vos distances pour l'empêcher de revenir à la vie."]
1                                                                                                                                                                                 ["Les capacités de survie d'Ahri sont considérablement réduites quand sa compétence ultime, Assaut spirituel, n'est pas disponible.", "Restez derrière les sbires pour éviter que Charme ne vous touche facilement. Cela réduit grandement le potentiel offensif d'Ahri."]
2  ["Quand Akali est occultée par Linceul nébuleux, elle peut toujours être touchée par les effets de zone. Cela révèle momentanément sa position.", "La Vague de kunais d'Akali est puissante quand elle est utilisée à portée maximale et avec le maximum d'énergie. Attaquez-la quand il lui reste peu d'énergie pour accroître vos chances de gagner vos échanges de coups.", "Rentrez à la base si vos PV sont bas et si Akali dispose de son ultime."]
3                                                                                                                                                                                                                                                                                                                                                                                                                                                         []
4                                                                                                                  ["Alistar peut être dangereux, mais il est solide et il est préférable de l'ignorer au profit de cibles plus fragiles.", "Attention à la combinaison Atomisation-Coup de tête à proximité des tourelles.", "Quand Alistar utilise son ultime, il est préférable de s'éloigner et d'attendre que l'effet se dissipe avant de l'attaquer."]

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      skins  \
0                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            [{"id": "266000", "num": 0, "name": "default", "chromas": false}, {"id": "266001", "num": 1, "name": "Aatrox justicier", "chromas": false}, {"id": "266002", "num": 2, "name": "Mecha Aatrox", "chromas": true}, {"id": "266003", "num": 3, "name": "Aatrox chasseur marin", "chromas": false}, {"id": "266007", "num": 7, "name": "Aatrox lune de sang", "chromas": false}, {"id": "266008", "num": 8, "name": "Aatrox lune de sang prestige", "chromas": false}, {"id": "266009", "num": 9, "name": "Aatrox héros de guerre", "chromas": true}, {"id": "266011", "num": 11, "name": "Aatrox de l'Odyssée", "chromas": true}, {"id": "266020", "num": 20, "name": "Aatrox lune de sang prestige (2022)", "chromas": false}, {"id": "266021", "num": 21, "name": "Aatrox de l'éclipse lunaire", "chromas": true}, {"id": "266030", "num": 30, "name": "DRX Aatrox", "chromas": true}, {"id": "266031", "num": 31, "name": "DRX Aatrox prestige", "chromas": false}, {"id": "266033", "num": 33, "name": "Aatrox primordien", "chromas": true}]
1                                                                                   [{"id": "103000", "num": 0, "name": "default", "chromas": false}, {"id": "103001", "num": 1, "name": "Ahri dynastique", "chromas": true}, {"id": "103002", "num": 2, "name": "Ahri de minuit", "chromas": true}, {"id": "103003", "num": 3, "name": "Ahri renard du feu", "chromas": true}, {"id": "103004", "num": 4, "name": "Ahri popstar", "chromas": true}, {"id": "103005", "num": 5, "name": "Ahri challenger", "chromas": true}, {"id": "103006", "num": 6, "name": "Ahrithmétique", "chromas": true}, {"id": "103007", "num": 7, "name": "Ahri arcade", "chromas": true}, {"id": "103014", "num": 14, "name": "Ahri gardienne des étoiles", "chromas": true}, {"id": "103015", "num": 15, "name": "K/DA Ahri", "chromas": true}, {"id": "103016", "num": 16, "name": "K/DA Ahri prestige", "chromas": false}, {"id": "103017", "num": 17, "name": "Ahri sylvestre", "chromas": true}, {"id": "103027", "num": 27, "name": "Ahri fleur spirituelle", "chromas": true}, {"id": "103028", "num": 28, "name": "K/DA ALL OUT Ahri", "chromas": true}, {"id": "103042", "num": 42, "name": "Ahri de l'assemblée", "chromas": true}, {"id": "103065", "num": 65, "name": "K/DA Ahri prestige (2022)", "chromas": false}, {"id": "103066", "num": 66, "name": "Ahri des arcanes", "chromas": true}, {"id": "103076", "num": 76, "name": "Ahri lune de neige", "chromas": true}, {"id": "103085", "num": 85, "name": "Ahri légende transcendée", "chromas": false}, {"id": "103086", "num": 86, "name": "Ahri légende immortalisée", "chromas": false}]

In [5]:
print(df_games.columns.tolist())
print("=========================================")
print(df_champs.columns.tolist())
print("=========================================")
print(df_simple_wr.columns.tolist())
print("=========================================")
print(matchups_df.columns.tolist())
print("=========================================")
print(synergies_df.columns.tolist())

['match_id', 'serveur', 'patch', 'elo', 'blue_side_win', 'blue_top_champion', 'blue_jungle_champion', 'blue_mid_champion', 'blue_adc_champion', 'blue_support_champion', 'blue_top_puuid', 'blue_jungle_puuid', 'blue_mid_puuid', 'blue_adc_puuid', 'blue_support_puuid', 'red_top_champion', 'red_jungle_champion', 'red_mid_champion', 'red_adc_champion', 'red_support_champion', 'red_top_puuid', 'red_jungle_puuid', 'red_mid_puuid', 'red_adc_puuid', 'red_support_puuid', 'blue_ban_1', 'blue_ban_2', 'blue_ban_3', 'blue_ban_4', 'blue_ban_5', 'red_ban_1', 'red_ban_2', 'red_ban_3', 'red_ban_4', 'red_ban_5']
=========================================
['patch', 'id', 'key', 'name', 'title', 'partype', 'tags', 'lore', 'blurb', 'allytips', 'enemytips', 'skins', 'skins_count', 'info_attack', 'info_defense', 'info_magic', 'info_difficulty', 'stats_hp', 'stats_hpperlevel', 'stats_mp', 'stats_mpperlevel', 'stats_movespeed', 'stats_armor', 'stats_armorperlevel', 'stats_spellblock', 'stats_spellblockperlevel', 'stats_attackrange', 'stats_hpregen', 'stats_hpregenperlevel', 'stats_mpregen', 'stats_mpregenperlevel', 'stats_crit', 'stats_critperlevel', 'stats_attackdamage', 'stats_attackdamageperlevel', 'stats_attackspeedperlevel', 'stats_attackspeed', 'passive_name', 'passive_description', 'passive_image', 'spell_q_id', 'spell_q_name', 'spell_q_description', 'spell_q_tooltip', 'spell_q_leveltip', 'spell_q_maxrank', 'spell_q_cooldown', 'spell_q_cooldownBurn', 'spell_q_cost', 'spell_q_costBurn', 'spell_q_datavalues', 'spell_q_effect', 'spell_q_effectBurn', 'spell_q_vars', 'spell_q_costType', 'spell_q_maxammo', 'spell_q_range', 'spell_q_rangeBurn', 'spell_q_image', 'spell_q_resource', 'spell_w_id', 'spell_w_name', 'spell_w_description', 'spell_w_tooltip', 'spell_w_leveltip', 'spell_w_maxrank', 'spell_w_cooldown', 'spell_w_cooldownBurn', 'spell_w_cost', 'spell_w_costBurn', 'spell_w_datavalues', 'spell_w_effect', 'spell_w_effectBurn', 'spell_w_vars', 'spell_w_costType', 'spell_w_maxammo', 'spell_w_range', 'spell_w_rangeBurn', 'spell_w_image', 'spell_w_resource', 'spell_e_id', 'spell_e_name', 'spell_e_description', 'spell_e_tooltip', 'spell_e_leveltip', 'spell_e_maxrank', 'spell_e_cooldown', 'spell_e_cooldownBurn', 'spell_e_cost', 'spell_e_costBurn', 'spell_e_datavalues', 'spell_e_effect', 'spell_e_effectBurn', 'spell_e_vars', 'spell_e_costType', 'spell_e_maxammo', 'spell_e_range', 'spell_e_rangeBurn', 'spell_e_image', 'spell_e_resource', 'spell_r_id', 'spell_r_name', 'spell_r_description', 'spell_r_tooltip', 'spell_r_leveltip', 'spell_r_maxrank', 'spell_r_cooldown', 'spell_r_cooldownBurn', 'spell_r_cost', 'spell_r_costBurn', 'spell_r_datavalues', 'spell_r_effect', 'spell_r_effectBurn', 'spell_r_vars', 'spell_r_costType', 'spell_r_maxammo', 'spell_r_range', 'spell_r_rangeBurn', 'spell_r_image', 'spell_r_resource', 'winrate']
=========================================
['elo', 'server', 'patch', 'label', 'name', 'role', 'role_pickrate', 'tier', 'winrate', 'winrate_evol', 'pickrate', 'games']
=========================================

In [6]:
print("============================================================================================================================================================")
print("df_games")
for col in df_games.columns:
    if df_games[col].dtype == "object":
        print("=================================")
        print(f"Colonne: {col}")
        print(df_games[col].value_counts().head(20))
    else:
        print("=================================")
        print(f"Colonne: {col}")
        print(df_games[col].describe())

print("============================================================================================================================================================")
print("df_champs")

for col in df_champs.columns:
    if df_champs[col].dtype == "object":
        print("=================================")
        print(f"Colonne: {col}")
        print(df_champs[col].value_counts().head(20))
    else:
        print("=================================")
        print(f"Colonne: {col}")
        print(df_champs[col].describe())

print("============================================================================================================================================================")
print("df_simple_wr")

for col in df_simple_wr.columns:
    if df_simple_wr[col].dtype == "object":
        print("=================================")
        print(f"Colonne: {col}")
        print(df_simple_wr[col].value_counts().head(20))
    else:
        print("=================================")
        print(f"Colonne: {col}")
        print(df_simple_wr[col].describe())

print("============================================================================================================================================================")
print("matchups_df")

for col in matchups_df.columns:
    if matchups_df[col].dtype == "object":
        print("=================================")
        print(f"Colonne: {col}")
        print(matchups_df[col].value_counts().head(20))
    else:
        print("=================================")
        print(f"Colonne: {col}")
        print(matchups_df[col].describe())

print("============================================================================================================================================================")
print("synergies_df")

for col in synergies_df.columns:
    if synergies_df[col].dtype == "object":
        print("=================================")
        print(f"Colonne: {col}")
        print(synergies_df[col].value_counts().head(20))
    else:
        print("=================================")
        print(f"Colonne: {col}")
        print(synergies_df[col].describe())

============================================================================================================================================================
df_games
=================================
Colonne: match_id
match_id
EUW1_7669371997    1
EUW1_7517331727    1
EUW1_7509322616    1
EUW1_7509243675    1
EUW1_7673883729    1
EUW1_7674151970    1
EUW1_7674154199    1
EUW1_7674137373    1
EUW1_7674129238    1
EUW1_7673471161    1
EUW1_7674146207    1
EUW1_7673652514    1
EUW1_7674071739    1
EUW1_7673845393    1
EUW1_7673962946    1
EUW1_7673663220    1
EUW1_7674002935    1
EUW1_7674067704    1
EUW1_7673406800    1
EUW1_7674135619    1
Name: count, dtype: int64
=================================
Colonne: serveur
serveur
euw1    185653
kr       68378
eun1     26965
Name: count, dtype: int64
=================================
Colonne: patch
patch
15.24.734.7485    73361
15.23.728.3286    52068
15.24.732.64      44383
15.24.731.5210    20608
15.22.724.5161    17896
15.24.733.6673    13259
15.24.730.7955    11699
15.24.733.5841    11342
15.21.721.8442     8973
15.24.730.505      6845
15.23.726.9074     6172
15.20.719.545      2840
15.19.715.1836     1591
15.20.717.2831     1584
15.24.731.2566     1263
15.18.710.2811     1062
15.22.723.8534     1017
15.21.720.925       983
15.21.721.4012      660
15.22.723.1955      579
Name: count, dtype: int64
=================================
Colonne: elo
elo
MASTER         137469
HIGH_ELO        96522
GRANDMASTER     24486
CHALLENGER      13805
DIAMOND          6933
UNKNOWN          1781
Name: count, dtype: int64
=================================
Colonne: blue_side_win
count     280996
unique         2
top         True
freq      145137
Name: blue_side_win, dtype: object
=================================
Colonne: blue_top_champion
blue_top_champion
Zaahen       17403
Ambessa      15589
KSante        9618
Jax           8941
Sion          8830
Jayce         8789
Aatrox        8693
Riven         8512
Fiora         8175
Rumble        7845
Renekton      7807
Darius        7083
Malphite      6765
Shen          5719
Irelia        5640
Ornn          5199
Garen         5106
Gangplank     5048
Camille       4983
Gwen          4606
Name: count, dtype: int64
=================================
Colonne: blue_jungle_champion
blue_jungle_champion
Sylas       14582
LeeSin      14578
Viego       13456
JarvanIV    12855
Qiyana      12528
Talon       10528
Aatrox       9769
Jayce        9397
Diana        9077
Nidalee      8531
Khazix       7798
Rengar       7656
Hecarim      7335
Zed          6774
Ekko         6708
XinZhao      6569
Ambessa      5780
Graves       5102
Shaco        5034
RekSai       4634
Name: count, dtype: int64
=================================
Colonne: blue_mid_champion
blue_mid_champion
Syndra         15711
Orianna        14771
Ahri           10816
Viktor         10662
Katarina        9889
Sylas           9613
Akali           9485
Mel             8168
Yasuo           7619
Ryze            7212
Akshan          7047
Zed             6604
Yone            6469
Zoe             6457
Taliyah         6318
Galio           6100
Leblanc         5977
Hwei            5676
Ekko            5667
TwistedFate     5554
Name: count, dtype: int64
=================================
Colonne: blue_adc_champion
blue_adc_champion
Kaisa          27500
MissFortune    24404
Yunara         19217
Jhin           18475
Ezreal         15909
Tristana       13440
Lucian         12769
Aphelios       12310
Ashe           12115
Caitlyn        10324
Jinx           10110
Smolder         9453
Draven          9106
Sivir           7874
Zeri            6642
Corki           6232
Twitch          5939
Vayne           5839
Varus           5690
Xayah           5313
Name: count, dtype: int64
=================================
Colonne: blue_support_champion
blue_support_champion
Nami          18162
Nautilus      17591
Bard          16190
Karma         15627
Lulu          13365
Thresh        12555
Janna         12475
Rakan         11313
Alistar       10721
Braum         10325
Rell          10243
Leona         10086
Pyke          10067
Milio          8568
Blitzcrank     7902
Neeko          6755
Elise          6365
Soraka         6215
Sona           5774
Poppy          5615
Name: count, dtype: int64
=================================
Colonne: blue_top_puuid
blue_top_puuid
leciJR8I__opgUUSqdPY_CGG_-M7FVFwaxzz2fAGp8cM4z02jEMr-IUEY0QlwYljJ_bgJ1tHDhl5zg    62
iWyqewexBce8K3DzYoaOsphTEYlndMvjQOx1blh7B9APfHachkk19oLBj7AFPhkX_saCEUqIaAX0eg    60
fkRKB_Ssd1vbOnnJLyEFHHAL8rIDrk7Fkt7-XP_zyVjyv4DBx37VG1U0JbBgpVvsiHfqxdbK8BMdpw    59
Dv6gCEb_PxTaSa-hWd2Ejxa4xsCaVkiDNv6wreLsUY-n5vp7UpUA-qk2bsMpxqQAK3377cgYELNBxQ    59
y79WEXMxrWM4uiHWqHRvmevIsEwCuk7bYe7rcFLeAbCju1101_kALraVFwIHUd26SG0vHZ6Ov2weoA    58
_NCxW1KAez-b2QzmmUiPQcabjApjetKiUh82wPncvdKcqMoX1m_7AcdZWL7lS6lsVmTEn51tOkXeYQ    58
At7Ou_yEGRLiwvICU8EYqI-Bhyr8eS9-OS1JT245jqs5srhtJqxy-e8la0q4sG-uFH5g5aRT_zPxRQ    57
j217gbdL8G-YCHvnYrJW-Nq_7pOhKHmD2dQU6-k1wXKztKc-pcLG0eiRKCD8x3475XuNKKJTTztv6A    56
RqmRpJ4fSd3k_QAm89bb33He2CV3zD3dM9POQFtICw629ZHy3OxOaTH5SxFlapaHO6llXYwZ0k7lSg    56
pEYmbuGd-zzCM4vzK6NUxGIBEN2XA7SH_WSHP3Y1XD9iy-AfG2zUmxMLfxNmgA6OveT7i26SJa00wg    56
k_jfHRw3dIPfnsnH06FRQPAToYIObLqflygrAr_uh3TMrAWLIH4PvaJDBxquf9QDjgvEWOMtVC7PkQ    55
iAqcm-gQpl0j4QTF_n1KCfftwxAuhC1N0FGwwIY21DPTeRjbPP4gthbPHqB3UBwt9BJFoheYpWkGjw    55
1_0DjVuQn-hudiWGUosQZyo2T4do263GssvHEVcvygzCzkbtcD6jHQjEPLDDBLmyJrxTlsP-ABPJcw    55
gK31usGtjNwCZB5fEDzD4mF26AZEBi1E62aCtI16vrgQKumwaMzaT8NA14DwB63KtOY3DqQZP-ex4g    54
TwXUuwYz_TZSKfZQeDR2xwDh79KUYjAWIz92-Zmprl9kKRKkVUGR08roZLA2IJnpvEZQSCwe6B1r6Q    53
coAtXnc0wH8VtwJCYCJUG5utc4ADUjPryOHBDHS55znVDEE6ab3QQwERbVmOavhxoeXSsebKyueWDw    52
wHjwV_t8e58OSMNH2ajv0BxVVDYaXtcWDos2zZE4m6l_Tu0B-HmS9hWAWCa7XUGyTMIqXIkShCwSpQ    52
e-pZGm9OSDDHwUyGgDbnp0aszWY-txscXJ4iVt_DMt8LwrULD3eh1Y6yn-zCNzqnQFeGIZ2IM7w3kw    51
lG6GnAmfS4CpoKvhw1TKZ0hA5-KQoE9gzxc4vsPu7MspALNp38Ego1U3NazDyu_Yr5XhLEBkQgXUQA    51
3oMv7c4b1eBtArFKuICPxPoZ_U5V-MEhN4jzhZ9BgxAhZ3ycN5oTHWf_JGwLLRWOfqaK30fcI5VdWQ    51
Name: count, dtype: int64
=================================
Colonne: blue_jungle_puuid
blue_jungle_puuid
wj4_z4rGj8BktyvEcp13lQo_gKuYswwq-5vTmdQ2XlnzoW8N8YCdOLnDuH99szaC2qqkPo7lfMMucw    88
upPYyFrCM0ITvfsu3AUD2Bj-OK9kQ4tOPI47P2ZkEXAOr12q2h11Jl6CwQfa0E7QsaRQLrDma_wnQA    83
zwZYFPx5rLsPGyXMQ-6M2bxjBjmYkRJmRvB31NpTG2imWXayazKX_hmInTCwutJmJvXCrGdmuE7WGw    76
VXXNN9PJ10bXALbZYRRGaDL61Bg12S-lmn7IFS9QTptSh8jSrGnx-LwFvmPWfMeARsVoORUJttoGPQ    68
vqC3LKD9Udsba1UdTHjKyvB_KDTgDjmAI_ZxXuiaRvkkRSiugouf_vTNcNQSTycLs_5LvoeWVFrckg    66
U8GADbSZEE_DzePUdztQP9jlNBvy9M1MaI79jHbV-ctodpp4E7eVWAOTi_XYZnarSmgYTk1Lu7S0Jg    63
AWz58Bfpc17YAL44oYjlorAc18E5RqiXk-2Uic1a6DqEfw59gQvkX1p7JQq4aZ0iy0HSMQWv5_u4sA    60
_QRftjSXNQP-Ge5AO5tST3MVOUfDI5qre7Zs2kAZ2rwm_z5AL5xrIPVFMmQ73dxLJbZRNNtbQPs4Sg    58
YCCAgjQHjz523Voi6FVDPnnRrNT7AvwLC1SjtPIiaSB5rOaJMupaCTidBSPCSn9iDri2Rc4waGZOdA    58
mBM52ZOa36B6M4IifSITV_uy7ab-t2gPDDaNHFNNjdTO6vCdR8MqNcJBkWoRbqbl18JhSW2i737xwg    56
9-AJeV1EpKVjUiBwCj4gEbEiJu4Wq7T0gNnLzLqvoHGEiNuTOncSrzXFpOph-42zk0q0k6nwFbhFDw    55
ooj3p0hHN6FkoEhvPQVn3IhPYdVDbt2faJyjtLNaar4Ot3l36Ch-qO1pk4xji9hozJfbhIfbKDjG0w    55
Ws4IBBnnf2GY2ODJC9WXrC5pEkUHCXEUk__Ge4NolfPQSAJufrwljiwZzdX9Dy4cFOWbc5hqLb5XGw    54
Rt4g-yvL-1u4VpZv6VyzK2pgpKnI1IA4VjG42LrMBUGKdr74qrxi5En_fTXBJCrHbfxLuOGEDHeQqQ    53
FfL7qhxBAU7ow39Cdq-1DekVvHgNHw0QVAglMwxd6ZH4sW9wW-cpF2kQFgOVDHPbJLba-8vWZaaBsA    53
fQd4T78-hOGn6rqeGhcTo0yTz9uqn7KHt4nvJGxXoxIEOeGyl8cTfZ1qJJVuQ0mCl0LSfdrt9V-bAw    52
py5xK-kiY13joGHyRDY_nnrdePpzleu9FNk8_75YaH6dnogexxay0cb67Lj-lxhiVBQ--8N93DbUrQ    50
kHM1v40oDL6zJtFPUnUYpEpxsm1Ply30d1KMhyDQ03oFZixT5qZfO8Brqem09UGkMWeMsgF-uxYyvw    50
C6IpCd4njcFPZBxKgG7f0BLNf7icUY9OwVxofRczvpeztnaOMrqyhVoLcoem_qOZZbJos7DTNhGFHA    49
9syquUQY8HU7jqAdywN-1lCCp8m7Ny_eyhf51AfzS7B7D8j4I7VeI6o-Hr6thT76YipT1Q90gvgIDQ    48
Name: count, dtype: int64
=================================
Colonne: blue_mid_puuid
blue_mid_puuid
s2CXAwiIbj3Ow7Hc41_t1goQzhzzFnPQnhbhJc69Qy2EolhTPL20tAjAN85-_rpnKh6ankQcZBOqKQ    67
VZi_oHA7AE7UsEGW6A7n38uzMTlEPkUHXvY0QSC3IipGPzK84kFiLT3rfZmtcNqcTOHON0cmt3-hXg    54
OvYEAWp9bd1ipRVScIZ-mjpOLHrGFrMPTSHLF6NsrRUPtlKq5XmxAXVN_N8jXkFy4sZJylJFdnKyuA    54
RVkSNEGJvj9Bh_cMeIRISMC_laCF0wH6DjyfPJ2xNPb3JsHD6o8ZcMlJqKHbewpepGZHlNAsUrspAQ    49
US6BTiTeOItHppNT3vwsIDPJcfDAU_z0NzUQH0A20WUs7FMxvuIfpE_aqXdtVHxS1Gm2icuLrJmufA    48
jqPA7CW7RPx-D3CZmXeDYo2rmSg09BN2X2dhhKZbnSTzY7FYvVjXGhsAYayZcF7h5D0Oknke-EjO_w    48
JBCLrSa5Yv0P2VkWLJbmaFH4toCUXoxZtjFYFGxIcc4ZxRisIedRDD8noNuReRFHKOsGT4ffWhqDsg    47
t086uiKZSMkDPXN5B8y1sQD2bXdCMxDBOtZaCo5vAqtG1Htp7ZInJGNAo8eL4t4bGSSxopHQrwMD7g    46
WaQJCbEf7FtCMVuVSJ2SZ_mPU0qWkuEIDtX3UfRrL5Y2AD8V4S2JBdrTLZWSUz1CMAhbL-5jcBeAJA    45
8coF_-oxWBK53QfP7LSD4SRYcoaL6nNckvdpiXMEPOO04aFnIRqugkdgceiayal_sqpmY-M4L76Q6A    45
qfK0--BJ_gWhWz8kqgwrc9de6fpZoWxEZ9hI47_4zmOsdQPDV6_yVQ7RRLshqX8ONKRIS9InpW87hA    45
gMWx1XHfhlrpuRX9SH7t3z6DTGzR1n1LviPDaGwgzyQVfHFsacy7J501-OsOEjfbI2nPNeqE2pWqsA    45
Zsqf9AU1MHaMoAZQzxOzhsCildToSmjpdQ4UrWqrcJOKQ6r3KqsQlRgynFHxpAtLtrKu3hNNhNqwig    43
CKzXArF7oDJZtMZN57kWwHvmb4M5qHYKkk4_HA7rK14WDLlewqmJOnBY3vFe2uTxj58LrMOU8jyUlA    43
La6aLyUC4zmch7JjOfcHxYXtKi3WyiEFdIZjYncvkbIJUf8EgN7d6ZKhkojTmtRVZddSQkuXnBbhRA    43
hA9KZ4Zh08oi9xW6NB8SB9Hm3_yw8W9LrxDsLsOSFqw5OJvRA2ehR993o3Hu5JqjJLM1BsMvgaYDFA    43
LlQTTeXnQr51zC-pjkd_G3OvSsv67qLvrBOpll_pDUGLqlD89HJj7jkW2ruSfuef52p05BUuOMSc-Q    43
MfgbhmWHbIORmDY-SRDgaPIW2mUknQQ-oQ6rGv1ASeX_aMj5nLcxcEygvvPr6e7POJejPqU8m3qSTA    43
R7F7Du2I2w1yRIE9yhpHpzWPcHO7s0l05mMaypSNChDBsOSiuBXjMobhTYRF_PUlE_4yTAtTMcvdxQ    43
t0Oy8DqAFIsIDEuYrgSXuGjOerZWtIXBDoPjzIMjfXXjBUT16aOWTzabcV8iwkjD-JoEhZq3DM-VVA    43
Name: count, dtype: int64
=================================
Colonne: blue_adc_puuid
blue_adc_puuid
9HsV1ws2DVuAfXlnfsidhgSLhRR3W7YzU-Wh8qdU__F2RmD9_mp5dTXhrqI0LdieXFvD5rV83scjpA    76
wQBv_wY8C3ym7aQ00qBdYZO2qqaMwHSI645hBt1DVkUHEqMnhHGRQooaqnS0bhvci4PPl-8Zqr3lDQ    72
RqqAHdLhTc6Q24lRUvUqb_5yGRW9a6VXTfFlXuF5x-tZHTx5UsCRCXAItTk7OiRnKHo52rMXrXTJUA    67
ZNGx6x8QfQk0U0tWJRNUbO1aLDxJNdn0VwxkbMkOs42fWX43FI483Urhnw_OUPyO9zkjWC2HUDe1OQ    62
S8iUEXzZ8jCCPry5YD3erckiWxRbQ0PP1DFsSX99ouf-amld10R-gYUoYtMmNaLS6mcnNRCbJIcmww    61
G80MJ8wxfXDP1tWRAGwEXfcog5TyVb3ESBExG68sPHm64-w5PmQlMyXW8dyBp9aLGTOvaedwkx1nbA    58
yymHXRMFQk7kpx3GiWO0gtqcBY7t6LCdUjuWfuxOPPkV0oLhPddqD5c49juMGTHdvQw7r3q_XvZQoA    57
zPZGtqVzjZhKSG98VaXQTN4QVHbBzbtAz1jEpF5m8Px2aPu0CRGBh2d_-zS36d6BKiN7HuGP0oC60g    56
ao5_7ZxPqTBURzIDJIUzqESTEnDMNErIR2ZCgy_YnTqefIcJ0V0CkhQ6pXMMd6-v9eFOcAl1eB_jng    53
5w8inXencqpEmO8xZiG9ai21RvL2dObqVEGl_vfJTSX-bx73nQ-8-qJNFKkQ3KZJIoLKOSQKQSWOwA    53
WyVVqFpJDuaQtztqSVewgUs2j9SrkC_wycrdhWrV3o1szU7hmF2PMBD4T1hEaZZwi6alh0svgrCphg    53
NFUfYlqROrGzTjpk0qanJb447yDV4q0KSRFrFHyvtm0XObpEGfoDrYh9CYkKEVRCwFsAsSGMoYz-HA    52
vxrUMFGIfe2NdJvq7RO4zTDMl646GQho31QuwjsQ73XEl_uIPxtcyUcr75ilcAKiITft1zxmh_ef-w    52
JrTXYLrSYv3Tkpl4xmV8p6pJwSItHNqXSYlnELiMgiRRYSdbI9fjeJSSAPYWvcER79FqyH7hpL8Zrg    50
w95hKt-3hlPP12VGVYs5gomVR2R6IfoAP_7_JY9Kzmfq10gJCe_4_KeIHTyaLq3uxFpSVqMjbs7T6w    49
r7GmSdvJrPV7zd2SC2_clOCU1PbA1b_xViPKpSIXz-Lt-4s6Lb6FkSUDMKRmwxjeulbB8Dl6C3YQTg    49
Rmu8U39CnjUrM_IPZQb3jDiM2Cyx4SXRpMuXiYFZYnYtV8VLZmVru2U1BdC-3HY7-KsBr4Z9Q2A8wg    48
OhLX3F36513Uh_V1vnCNJnyOAHBwOPSQPP9piQlcuq9zkcy9GJ2esHgzXRhdrLRvkcluzyebT3blag    46
l7oQQDEN0cziw_KQ9ku1PexYABnjRz3pk0r3TCczR6O7F3OouItJCRk4mTdR3l_pb06BolmlanKi1w    46
4XDR9i7IwNFvGDz6h8OngQrqgDZ4icJY3f8UARr1m6A3O7KsVoDi00VIMP-Mdv92p13B6F0j1XdA6g    45
Name: count, dtype: int64
=================================
Colonne: blue_support_puuid
blue_support_puuid
L6ST9k-yfy8vfFpG0pfQiWtZH42W_6YsyctswYWPm6G_C7kGBux_XRnvv8ELRFEsdqgG3Mzy9ko_ew    63
pcBaB0TPflrwi6-6DZZ5DM4Az8W85uudJPkLeLLQ6DeeQqJ5k9ssjqWGYCWPAqLhFfvqn-CdL8g5nw    59
qHDkKU4yLLG7jEV702_A948hpObsbcc9lc5QpytHjGSU451ZbQfrxJjnp7aSZWRo0LEPJJtKXKHyTA    54
G4hRLoYqrPGdEnn1CyHF39_txJZUgcJH6aW4AjKl7Bbrs2t8Uh_BFQZd6soKNK_afpOnJbmDJfEyXg    53
YjdAx5KXVAC-iJXGZP94QUia733Gmcgg4W4uAv2_JmR09Ks9D7YlGZWLvED7gtjG_rC0OPYSL-9VYg    52
u6vHFu-WHupMLUZHznZTYPv4keWXmoab4CxqSbLFU8v23mqDyVG5B17Fdnh8mt83YdtDTODxVUf_0Q    52
M5M2P7mKxSTMpWubYOKB638x9ZXxKCqwIw3IV92KzaLYrm_CQ_KQCARK0DqRbkeJyFGc3cclPWyBdQ    51
bNGO2mV7h_mjUcbyB69vcOeD5ZI_jBfJX_p946DxAhRLuHXVxgkKQoaevWFqmPjG4s5sZloKahdqiw    51
hui7WeMacXr57VmOkqvKSSLYerrhxc_aAo3HlDwi2PVMPi3stHKka3m5ZvSLl75p5uN5F_Jfa1UL3A    50
CINQlkm8iVblU2cO9rf8Zsau8PDVo-g5Np2-ds1QPpkykX0HRWceXMwg0NtPB83J4Z4AqZ5zSLmsIw    50
Yh30-hTt6KaehHtXjCfnli9CsMMlV7o0lbrAiAlccTdX65Fuhw34lQ0KLbjf94c33pIn8CtUrjRmjg    49
aEel0U9_x6fbQVVivxgsajmRfNrmz6C_fPxZabbRHWJLi1lA3VoqnwzSB-sZzoV0KbUXLqUJEanzfA    49
mWi83LrUS95lWad8lYxB4Ey61PMjhCtywmZu1TzC5ws46X2sKeNz5AUq6zviRnYVJrU0lgHYUi2dhg    48
19GWAsed5FoRXL-yyeAHFGgvWSz4JmUCIfrX_jC4yc5Vzwu0s8TJbIA5nnkGHnTJUGBtp5Ms7bxlDA    48
eTWfxsV6G3fjiZ2257qUnG04XAnVxQGr21csX4oxcPobN0ooAeYWS4zsqaPTLw4GYvlAcW4F_X5Fnw    47
XIPjB7UfdxkUlP52VOSnrAKdchkmQJ0curYvDW1Bx1y9ZpJG-8Z-GuapcQEJkkxU7BPCrY0XzoPSDQ    47
aO2lx-BrHTMHQoAX3A2PqbaS4EhUP_Wb2sVeHwkw5tBMlaPf1W0Jn0eOSIu3jZuQXxbeaVv8JK-Y-Q    47
_UivHGzmBg9q92lMAb5kdU2oOJmmwoHaxy1FmZtNXasLvOdYoK4bXPPFHujILJ_3m70STAutiNwTjg    47
BXs8trt3tGn9EVgiJ0csP6JYgVsuKZNoFM8393J5RAmtkH5bJn55oaJbZpSyIzQC6TDB9_UsyFBh6A    47
kMtMfhpZ7Xwgj5BpO-qTfqaHOSIATtq5DuTqQDtWqxXpy29Z7_HUyUlOV21gy2pUt_qpRGW47q8oLQ    46
Name: count, dtype: int64
=================================
Colonne: red_top_champion
red_top_champion
Zaahen      13860
Ambessa     11688
Malphite     9240
Jax          9237
KSante       8626
Riven        8489
Fiora        8420
Renekton     8372
Aatrox       8107
Darius       7713
Jayce        7694
Sion         7061
Irelia       6540
Rumble       6444
Gwen         5711
Garen        5332
Shen         5252
Camille      5124
Gnar         4969
DrMundo      4940
Name: count, dtype: int64
=================================
Colonne: red_jungle_champion
red_jungle_champion
Sylas       15203
LeeSin      14840
Viego       13727
JarvanIV    12770
Qiyana      11249
Talon       10299
Aatrox       9604
Diana        9118
Nidalee      8524
Jayce        8151
Khazix       8037
Rengar       7823
Hecarim      7250
Zed          6813
Ekko         6781
XinZhao      6779
Ambessa      5826
Graves       5010
Shaco        4939
RekSai       4856
Name: count, dtype: int64
=================================
Colonne: red_mid_champion
red_mid_champion
Syndra         15839
Orianna        14564
Viktor         10943
Ahri           10766
Katarina        9807
Sylas           9640
Akali           9425
Mel             8194
Yasuo           7726
Akshan          7249
Ryze            7196
Zed             6729
Yone            6589
Zoe             6353
Taliyah         6321
Leblanc         6228
Galio           6053
Ekko            5731
TwistedFate     5581
Kassadin        5522
Name: count, dtype: int64
=================================
Colonne: red_adc_champion
red_adc_champion
Kaisa          28141
MissFortune    22767
Yunara         19500
Jhin           18319
Ezreal         15647
Tristana       14076
Lucian         13189
Aphelios       12913
Ashe           12086
Caitlyn        10139
Jinx           10126
Smolder         9591
Draven          8834
Sivir           7913
Zeri            6569
Twitch          6139
Corki           6087
Vayne           6082
Varus           5628
Xayah           5242
Name: count, dtype: int64
=================================
Colonne: red_support_champion
red_support_champion
Nami          18435
Nautilus      17621
Bard          16090
Karma         15471
Lulu          13799
Thresh        12683
Janna         12492
Rakan         11108
Alistar       10564
Braum         10446
Pyke          10055
Leona         10051
Rell          10034
Milio          8700
Blitzcrank     8129
Neeko          6822
Soraka         6477
Elise          6192
Sona           5903
Poppy          5812
Name: count, dtype: int64
=================================
Colonne: red_top_puuid
red_top_puuid
1_0DjVuQn-hudiWGUosQZyo2T4do263GssvHEVcvygzCzkbtcD6jHQjEPLDDBLmyJrxTlsP-ABPJcw    72
e-pZGm9OSDDHwUyGgDbnp0aszWY-txscXJ4iVt_DMt8LwrULD3eh1Y6yn-zCNzqnQFeGIZ2IM7w3kw    69
7kdwJvqME6WdkGeq6EAUoWhar6UmE7tzyOcn2CLhlKJUX1YY3jNHQHScdBg8mD09HXfGDTToHX8BCA    62
f-DR8oxkVjYry5fPCWuB4vfm8Dz_6JlV_6vaoOg0v3zYq9hUpigIBtATRQmiuO9-2_lp2fIj7n5L_A    62
pEYmbuGd-zzCM4vzK6NUxGIBEN2XA7SH_WSHP3Y1XD9iy-AfG2zUmxMLfxNmgA6OveT7i26SJa00wg    61
TwXUuwYz_TZSKfZQeDR2xwDh79KUYjAWIz92-Zmprl9kKRKkVUGR08roZLA2IJnpvEZQSCwe6B1r6Q    60
At7Ou_yEGRLiwvICU8EYqI-Bhyr8eS9-OS1JT245jqs5srhtJqxy-e8la0q4sG-uFH5g5aRT_zPxRQ    55
6nEAYv3q3c_3DozFMfILqmGviVjui26yrmN9wVV6r2hoMDAz85_e3fiwvJ4CYwm7JNxUggZwvzzxVA    55
y79WEXMxrWM4uiHWqHRvmevIsEwCuk7bYe7rcFLeAbCju1101_kALraVFwIHUd26SG0vHZ6Ov2weoA    53
j217gbdL8G-YCHvnYrJW-Nq_7pOhKHmD2dQU6-k1wXKztKc-pcLG0eiRKCD8x3475XuNKKJTTztv6A    53
Uz9Amb0btSMAxqRqlEHPcwu8BWxFnnakJ64X7EbmqNP8A_zmhU6lAbloJlxoqijJdrci81zrMvijuw    53
R7Jk486_JNRegUYaTzUxl9QzGV23KM_s3CC6MojroMSzBN7UwxWzxBwj8p_cbLuPoS9Gw-P6yB8tlQ    52
3jfXEFnG4bVRIhvUTaR6oystsNWUdONFzXyo35RLQgw7KIW4sWhhLRX0hiOTi3ZABxDP4bj7BMv0SA    52
fkRKB_Ssd1vbOnnJLyEFHHAL8rIDrk7Fkt7-XP_zyVjyv4DBx37VG1U0JbBgpVvsiHfqxdbK8BMdpw    52
JhvnrLV0KhxxPu-U3CDV6yiqM6RvdxM0HjQ0M6fsnho6G_AKldmSG_xlq0RHbWt3RFPbV4dlkAv9eQ    52
avuayPsY_ZrcnebozYDnRg7gZbIm9IbAbYuXucXNUWPVor7EuufoVYdtgUkMBzy96rEKoh66O2gBbg    51
9rVsTAwj2AzYwfokrQaCVQmjqVvY8BXkF3ASqqdWLInilKMVu1VNjDNfZ3cZ3M3bF0VftQrPbvjpmQ    50
RrMHsH9-YgMlsNybVchgxrY_3CJzohQ12QwCoaI-5lj41cwCYAa2lOKpPZ3h9WgwMzWy_kcAJaaztg    50
pLf6whqssOG42hcvP_yPKdyWgxXeEi5PqS6ZTRp0SqUSqmpQbQL8DiVcVyZB0VpcEoeE-uXt_o945A    49
FMHw_ZVbdlVV91Q9D59VncRw8XT0MphM-n2iWCEQikWH_fqYQzWwDyKx5yZ3JM8zmqhUNjIyY7g1ag    49
Name: count, dtype: int64
=================================
Colonne: red_jungle_puuid
red_jungle_puuid
wj4_z4rGj8BktyvEcp13lQo_gKuYswwq-5vTmdQ2XlnzoW8N8YCdOLnDuH99szaC2qqkPo7lfMMucw    87
upPYyFrCM0ITvfsu3AUD2Bj-OK9kQ4tOPI47P2ZkEXAOr12q2h11Jl6CwQfa0E7QsaRQLrDma_wnQA    80
zwZYFPx5rLsPGyXMQ-6M2bxjBjmYkRJmRvB31NpTG2imWXayazKX_hmInTCwutJmJvXCrGdmuE7WGw    80
TzdwndhMtbCLMgb9n6vHKzH_vRUxx2c-I7MYd9Z2y9RSlvIT0zLf8nxHOGE1Fh7jiebZt-0EhQtOYg    69
VXXNN9PJ10bXALbZYRRGaDL61Bg12S-lmn7IFS9QTptSh8jSrGnx-LwFvmPWfMeARsVoORUJttoGPQ    69
U8GADbSZEE_DzePUdztQP9jlNBvy9M1MaI79jHbV-ctodpp4E7eVWAOTi_XYZnarSmgYTk1Lu7S0Jg    66
ooj3p0hHN6FkoEhvPQVn3IhPYdVDbt2faJyjtLNaar4Ot3l36Ch-qO1pk4xji9hozJfbhIfbKDjG0w    63
9-AJeV1EpKVjUiBwCj4gEbEiJu4Wq7T0gNnLzLqvoHGEiNuTOncSrzXFpOph-42zk0q0k6nwFbhFDw    60
_jGq2yyQP0SdR_OJaqooEt-Ikt0HwQ70fQ20vIRN_zM26pNyojCm6gs2-vIn1SN-b6jSJeVBdrmV7A    57
YCCAgjQHjz523Voi6FVDPnnRrNT7AvwLC1SjtPIiaSB5rOaJMupaCTidBSPCSn9iDri2Rc4waGZOdA    55
Ws4IBBnnf2GY2ODJC9WXrC5pEkUHCXEUk__Ge4NolfPQSAJufrwljiwZzdX9Dy4cFOWbc5hqLb5XGw    54
OuQwGA55-iTq2RQkY8WkSWCxfouUWa8ExdJptPUa6IltvmfUlXoLjYJpaN_LwgI4AzS1ktD_cdc-bg    54
vqC3LKD9Udsba1UdTHjKyvB_KDTgDjmAI_ZxXuiaRvkkRSiugouf_vTNcNQSTycLs_5LvoeWVFrckg    54
mwqhpwAY0LZSnmry51iwcthhbUhFlMeCvEtE3nFL4nNGe1pCep2tbwD99PwMHVoh2oIgDgrBqdha-w    54
py5xK-kiY13joGHyRDY_nnrdePpzleu9FNk8_75YaH6dnogexxay0cb67Lj-lxhiVBQ--8N93DbUrQ    53
SVrwqp54IY3FF5EK6Ubr4tLArWLU8z8tpMIRw_iYKpzbS4RuC6H-bRc_tk_BkRjU7G0W4MnX31epmw    53
yGX-TiyuPDLlvWEW9lbHkNKBQYhspjOjX_pAty9YgmXnM5NoJi8AWBSkU_EhvY0knSPyeVKCss0UNg    53
C6IpCd4njcFPZBxKgG7f0BLNf7icUY9OwVxofRczvpeztnaOMrqyhVoLcoem_qOZZbJos7DTNhGFHA    52
rmIF6ahLwvS-hiXKM7fY_qKGwzgkmoZlA8GQj9vEbnRA_5cucbv_tOHQlYGHnB2Fp8VdITarJ5XWHw    52
mBM52ZOa36B6M4IifSITV_uy7ab-t2gPDDaNHFNNjdTO6vCdR8MqNcJBkWoRbqbl18JhSW2i737xwg    51
Name: count, dtype: int64
=================================
Colonne: red_mid_puuid
red_mid_puuid
9lvxtuhVR3N6frkCAyCXFEmryC3Z1Ra-GIy6NomaI9Aia1VmN_BicQZQNjGlNWSBUJRXrN-hP_2_bw    64
OvYEAWp9bd1ipRVScIZ-mjpOLHrGFrMPTSHLF6NsrRUPtlKq5XmxAXVN_N8jXkFy4sZJylJFdnKyuA    64
gMWx1XHfhlrpuRX9SH7t3z6DTGzR1n1LviPDaGwgzyQVfHFsacy7J501-OsOEjfbI2nPNeqE2pWqsA    59
jqPA7CW7RPx-D3CZmXeDYo2rmSg09BN2X2dhhKZbnSTzY7FYvVjXGhsAYayZcF7h5D0Oknke-EjO_w    54
CkTelo4BQDZBgPQgILa1Hp5acJD3VaDomQSC3jbQQ_QNobcu5iPOuCHWkbOkBtNFiyTuUK_NLt5UKQ    50
0MBm9BofoxyeGOA3h6CxzkyOc2LQHz9ZaGBPdurmI0WWC6uaRPgsW35kbSrGhDrLD9Qwhwbku7Qbnw    49

In [6]:
print(df_games.iloc[0])
print("=========================================")
print(df_champs.iloc[0])
print("=========================================")
print(df_simple_wr.iloc[0])
print("=========================================")
print(matchups_df.iloc[0])
print("=========================================")
print(synergies_df.iloc[0])

match_id                 EUW1_7517331727
serveur                             euw1
patch                     15.17.708.5788
elo                             HIGH_ELO
blue_side_win                      False
blue_top_champion                   Sett
blue_jungle_champion               Talon
blue_mid_champion                  Diana
blue_adc_champion                   Jinx
blue_support_champion               Rell
blue_top_puuid                       NaN
blue_jungle_puuid                    NaN
blue_mid_puuid                       NaN
blue_adc_puuid                       NaN
blue_support_puuid                   NaN
red_top_champion                   Yasuo
red_jungle_champion         FiddleSticks
red_mid_champion              Cassiopeia
red_adc_champion                Aphelios
red_support_champion                Bard
red_top_puuid                        NaN
red_jungle_puuid                     NaN
red_mid_puuid                        NaN
red_adc_puuid                        NaN
red_support_puuid                    NaN
blue_ban_1                          Lulu
blue_ban_2                         Fiora
blue_ban_3                        Rengar
blue_ban_4                           Vex
blue_ban_5                         Poppy
red_ban_1                      Dr. Mundo
red_ban_2                          Garen
red_ban_3                          Milio
red_ban_4                            Zoe
red_ban_5                         Draven
Name: 0, dtype: object
=========================================
patch                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 15.1.1
id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Aatrox
key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      266
name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Aatrox
title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Épée des Darkin
partype                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Puits de sang
tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ["Fighter"]
lore                                                                                                                                                                                                                                                                                                                                                                                                                     Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des siècles d'emprisonnement, Aatrox fut le premier à retrouver sa liberté, en corrompant et transformant les mortels assez stupides pour tenter de s'emparer de l'arme magique qui contenait son essence. Désormais en possession d'un corps qu'il a approximativement transformé pour rappeler son ancienne forme, il arpente Runeterra en cherchant à assouvir sa vengeance apocalyptique.
blurb                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Autrefois, Aatrox et ses frères étaient honorés pour avoir défendu Shurima contre le Néant. Mais ils finirent par devenir une menace plus grande encore pour Runeterra : la ruse et la sorcellerie furent employées pour les battre. Cependant, après des...
allytips                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ["Utilisez Ruée obscure tout en lançant Épée des Darkin pour augmenter vos chances de toucher l'ennemi.", "Facilitez Épée des Darkin avec des compétences de contrôle de foule, telles que Chaînes infernales, ou avec les effets immobilisants de vos alliés.", "Lancez Fossoyeur des mondes quand vous êtes certain de pouvoir forcer le combat."]
enemytips                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      ["Les attaques d'Aatrox sont prévisibles. Profitez-en pour esquiver ses zones d'impact.", "Il est plus facile de fuir les Chaînes infernales d'Aatrox en courant vers un côté ou vers Aatrox.", "Quand Aatrox utilise son ultime, gardez vos distances pour l'empêcher de revenir à la vie."]
skins                         [{"id": "266000", "num": 0, "name": "default", "chromas": false}, {"id": "266001", "num": 1, "name": "Aatrox justicier", "chromas": false}, {"id": "266002", "num": 2, "name": "Mecha Aatrox", "chromas": true}, {"id": "266003", "num": 3, "name": "Aatrox chasseur marin", "chromas": false}, {"id": "266007", "num": 7, "name": "Aatrox lune de sang", "chromas": false}, {"id": "266008", "num": 8, "name": "Aatrox lune de sang prestige", "chromas": false}, {"id": "266009", "num": 9, "name": "Aatrox héros de guerre", "chromas": true}, {"id": "266011", "num": 11, "name": "Aatrox de l'Odyssée", "chromas": true}, {"id": "266020", "num": 20, "name": "Aatrox lune de sang prestige (2022)", "chromas": false}, {"id": "266021", "num": 21, "name": "Aatrox de l'éclipse lunaire", "chromas": true}, {"id": "266030", "num": 30, "name": "DRX Aatrox", "chromas": true}, {"id": "266031", "num": 31, "name": "DRX Aatrox prestige", "chromas": false}, {"id": "266033", "num": 33, "name": "Aatrox primordien", "chromas": true}]
skins_count                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               13
info_attack                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                8
info_defense                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4
info_magic                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
info_difficulty                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            4

In [ ]:
# merci. pourrais tu me faire un script pour aggreger toutes mes données en un seul vecteur. aumgenter la donnée autour de la game quoi : 

# match_id                 EUW1_7517331727
# serveur                             euw1
# patch                     15.17.708.5788
# elo                             HIGH_ELO
# blue_side_win                      False
# blue_top_champion                   Sett
# blue_jungle_champion               Talon
# blue_mid_champion                  Diana
# blue_adc_champion                   Jinx
# blue_support_champion               Rell
# blue_top_puuid                       NaN
# blue_jungle_puuid                    NaN
# blue_mid_puuid                       NaN
# blue_adc_puuid                       NaN
# blue_support_puuid                   NaN
# red_top_champion                   Yasuo
# red_jungle_champion         FiddleSticks
# red_mid_champion              Cassiopeia
# red_adc_champion                Aphelios
# red_support_champion                Bard
# red_top_puuid                        NaN
# red_jungle_puuid                     NaN
# red_mid_puuid                        NaN
# red_adc_puuid                        NaN
# red_support_puuid                    NaN
# blue_ban_1                          Lulu
# blue_ban_2                         Fiora
# blue_ban_3                        Rengar
# blue_ban_4                           Vex
# blue_ban_5                         Poppy
# red_ban_1                      Dr. Mundo
# red_ban_2                          Garen
# red_ban_3                          Milio
# red_ban_4                            Zoe
# red_ban_5                         Draven
# Name: 0, dtype: object
# =========================================
# patch                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 15.1.1
# id                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    Aatrox
# key                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      266
# name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Aatrox
# title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Épée des Darkin
# partype                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Puits de sang
# tags                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             ["Fighter"]
# info_attack                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                8
# info_defense                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               4
# info_magic                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 3
# info_difficulty                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            4
# stats_hp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 650
# stats_hpperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         114
# stats_mp                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   0
# stats_mpperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0.0
# stats_movespeed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          345
# stats_armor                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               38
# stats_armorperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      4.8
# stats_spellblock                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          32
# stats_spellblockperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2.05
# stats_attackrange                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        175
# stats_hpregen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            3.0
# stats_hpregenperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.5
# stats_mpregen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            0.0
# stats_mpregenperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    0.0
# stats_crit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 0
# stats_critperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         0
# stats_attackdamage                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        60
# stats_attackdamageperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               5.0
# stats_attackspeedperlevel                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                2.5
# stats_attackspeed                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      0.651
# passive_description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Régulièrement, la prochaine attaque de base d'Aatrox inflige des <physicalDamage>dégâts physiques</physicalDamage> supplémentaires et le soigne, selon un pourcentage des PV max de la cible.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
# winrate                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             0.501607
# Name: 0, dtype: object
# =========================================
# elo                 TOUT
# server              TOUT
# patch               16.3
# label                  1
# name               Briar
# role                 jun
# role_pickrate      91.1%
# tier                  S+
# winrate            52.8%
# winrate_evol       +1.5%
# pickrate            6.7%
# games            599 576
# Name: 0, dtype: object
# =========================================
# champion                                                                                                          Nami
# role                                                                                                               sup
# role_play_ratio                                                                                                  99.8%
# tier                                                                                                                S+
# rank                                                                                                            2 / 39
# winrate                                                                                                         52.3 %
# pickrate                                                                                                        10.4 %
# banrate                                                                                                          2.2 %
# nb_games_analyzed                                                                                            2491832.0
# url                            https://dpm.lol/champions/Nami/build?lane=utility&tier=all&platform=all&timeframe=15.24
# collect_coherente                                                                                                 True
# matchup_adc_1_name                                                                                               Corki
# matchup_adc_1_winrate                                                                                           56.34%
# matchup_adc_1_games                                                                                            16110.0
# matchup_adc_1_lane_quality                                                                                         NaN
# matchup_adc_2_name                                                                                             Kalista
# matchup_adc_2_winrate                                                                                           55.53%
# matchup_adc_2_games                                                                                            16231.0
# matchup_adc_2_lane_quality                                                                                         NaN
# matchup_jun_1_name                                                                                                 NaN
# matchup_jun_1_winrate                                                                                              NaN
# matchup_jun_1_games                                                                                                NaN
# matchup_jun_1_lane_quality                                                                                         NaN
# matchup_jun_2_name                                                                                                 NaN
# matchup_jun_2_winrate                                                                                              NaN
# matchup_jun_2_games                                                                                                NaN
# matchup_jun_2_lane_quality                                                                                         NaN
# matchup_mid_1_name                                                                                                 NaN
# matchup_mid_1_winrate                                                                                              NaN
# matchup_mid_1_games                                                                                                NaN
# matchup_mid_1_lane_quality                                                                                         NaN
# matchup_mid_2_name                                                                                                 NaN
# matchup_mid_2_winrate                                                                                              NaN
# matchup_mid_2_games                                                                                                NaN
# matchup_mid_2_lane_quality                                                                                         NaN
# matchup_sup_1_name                                                                                                 NaN
# matchup_sup_1_winrate                                                                                              NaN
# matchup_sup_1_games                                                                                                NaN
# matchup_sup_1_lane_quality                                                                                         NaN
# matchup_sup_2_name                                                                                                 NaN
# matchup_sup_2_winrate                                                                                              NaN
# matchup_sup_2_games                                                                                                NaN
# matchup_sup_2_lane_quality                                                                                         NaN
# matchup_top_1_name                                                                                                 NaN
# matchup_top_1_winrate                                                                                              NaN
# matchup_top_1_games                                                                                                NaN
# matchup_top_1_lane_quality                                                                                         NaN
# matchup_top_2_name                                                                                                 NaN
# matchup_top_2_winrate                                                                                              NaN
# matchup_top_2_games                                                                                                NaN
# matchup_top_2_lane_quality                                                                                         NaN
# Name: 0, dtype: object
# =========================================
# champion                                                                                                          Nami
# role                                                                                                               sup
# role_play_ratio                                                                                                  99.8%
# tier                                                                                                                S+
# rank                                                                                                            2 / 39
# winrate                                                                                                         52.3 %
# pickrate                                                                                                        10.4 %
# banrate                                                                                                          2.2 %
# nb_games_analyzed                                                                                              2491832
# url                            https://dpm.lol/champions/Nami/build?lane=utility&tier=all&platform=all&timeframe=15.24
# collect_coherente                                                                                                 True
# synergy_adc_1_name                                                                                               Swain
# synergy_adc_1_winrate                                                                                           57.70%
# synergy_adc_1_games                                                                                            16008.0
# synergy_adc_1_lane_quality                                                                                         NaN
# synergy_adc_2_name                                                                                               Brand
# synergy_adc_2_winrate                                                                                           57.16%
# synergy_adc_2_games                                                                                            19397.0
# synergy_adc_2_lane_quality                                                                                         NaN
# synergy_jun_1_name                                                                                                 NaN
# synergy_jun_1_winrate                                                                                              NaN
# synergy_jun_1_games                                                                                                NaN
# synergy_jun_1_lane_quality                                                                                         NaN
# synergy_mid_1_name                                                                                                 NaN
# synergy_mid_1_winrate                                                                                              NaN
# synergy_mid_1_games                                                                                                NaN
# synergy_mid_1_lane_quality                                                                                         NaN
# synergy_mid_2_name                                                                                                 NaN
# synergy_mid_2_winrate                                                                                              NaN
# synergy_mid_2_games                                                                                                NaN
# synergy_mid_2_lane_quality                                                                                         NaN
# synergy_sup_1_name                                                                                                 NaN
# synergy_sup_1_winrate                                                                                              NaN
# synergy_sup_1_games                                                                                                NaN
# synergy_sup_1_lane_quality                                                                                         NaN
# synergy_sup_2_name                                                                                                 NaN
# synergy_sup_2_winrate                                                                                              NaN
# synergy_sup_2_games                                                                                                NaN
# synergy_sup_2_lane_quality                                                                                         NaN
# synergy_top_1_name                                                                                                 NaN
# synergy_top_1_winrate                                                                                              NaN
# synergy_top_1_games                                                                                                NaN
# synergy_top_1_lane_quality                                                                                         NaN
# synergy_top_2_name                                                                                                 NaN
# synergy_top_2_winrate                                                                                              NaN
# synergy_top_2_games                                                                                                NaN
# synergy_top_2_lane_quality                                                                                         NaN
# Name: 0, dtype: object

In [7]:
df_games.columns

Index(['match_id', 'serveur', 'patch', 'elo', 'blue_side_win',
       'blue_top_champion', 'blue_jungle_champion', 'blue_mid_champion',
       'blue_adc_champion', 'blue_support_champion', 'blue_top_puuid',
       'blue_jungle_puuid', 'blue_mid_puuid', 'blue_adc_puuid',
       'blue_support_puuid', 'red_top_champion', 'red_jungle_champion',
       'red_mid_champion', 'red_adc_champion', 'red_support_champion',
       'red_top_puuid', 'red_jungle_puuid', 'red_mid_puuid', 'red_adc_puuid',
       'red_support_puuid', 'blue_ban_1', 'blue_ban_2', 'blue_ban_3',
       'blue_ban_4', 'blue_ban_5', 'red_ban_1', 'red_ban_2', 'red_ban_3',
       'red_ban_4', 'red_ban_5'],
      dtype='object')

In [ ]:
################################ cleanning games

In [8]:
df_games.drop(columns=["blue_top_puuid", "red_top_puuid", "blue_jungle_puuid", "red_jungle_puuid", "blue_mid_puuid", "red_mid_puuid", "blue_adc_puuid", "red_adc_puuid", "blue_support_puuid", "red_support_puuid", "blue_ban_1", "red_ban_1", "blue_ban_2", "red_ban_2", "blue_ban_3", "red_ban_3", "blue_ban_4", "red_ban_4", "blue_ban_5", "red_ban_5"], inplace=True)

In [10]:
df_games.head()

,match_id,serveur,patch,elo,blue_side_win,blue_top_champion,blue_jungle_champion,blue_mid_champion,blue_adc_champion,blue_support_champion,red_top_champion,red_jungle_champion,red_mid_champion,red_adc_champion,red_support_champion
0,EUW1_7517331727,euw1,15.17.708.5788,HIGH_ELO,False,Sett,Talon,Diana,Jinx,Rell,Yasuo,FiddleSticks,Cassiopeia,Aphelios,Bard
1,EUW1_7509322616,euw1,15.17.706.7412,HIGH_ELO,False,Mordekaiser,Qiyana,Yasuo,Corki,Nami,Jax,Hecarim,Syndra,Senna,Bard
2,EUW1_7509243675,euw1,15.17.706.7412,HIGH_ELO,False,Smolder,Kindred,Galio,Jinx,Milio,Quinn,Kayn,Xerath,MissFortune,Rakan
3,EUW1_7509193063,euw1,15.17.706.7412,HIGH_ELO,False,Warwick,Nidalee,Akali,Yunara,Rakan,Chogath,RekSai,Xerath,Kaisa,Sona
4,EUW1_7508909082,euw1,15.17.706.7412,HIGH_ELO,False,Aurora,XinZhao,Twitch,Yunara,Rakan,Jayce,Sett,Akali,Lucian,Milio

In [ ]:
##################################### cleanning champs

In [11]:
# df_copie_champs = df_champs.copy()

# df_champs= df_copie_champs.copy()

spells = ["q", "w", "e", "r"]

spell_cols = [
    f"spell_{s}_{k}"
    for s in spells
    for k in [
        "id","name","description","tooltip","leveltip","maxrank",
        "cooldown","cooldownBurn","cost","costBurn","datavalues",
        "effect","effectBurn","vars","costType","maxammo",
        "range","rangeBurn","image","resource"
    ]
]

cols_to_remove = ["skins","lore","blurb","allytips","enemytips",
                  "passive_name","passive_description","passive_image",
                  "winrate"] + spell_cols

df_champs.drop(columns=["id", "key", "skins_count", "title", "partype"], inplace=True)
df_champs.drop(columns=cols_to_remove, inplace=True)
df_champs.iloc[[0]]

,patch,name,tags,info_attack,info_defense,info_magic,info_difficulty,stats_hp,stats_hpperlevel,stats_mp,stats_mpperlevel,stats_movespeed,stats_armor,stats_armorperlevel,stats_spellblock,stats_spellblockperlevel,stats_attackrange,stats_hpregen,stats_hpregenperlevel,stats_mpregen,stats_mpregenperlevel,stats_crit,stats_critperlevel,stats_attackdamage,stats_attackdamageperlevel,stats_attackspeedperlevel,stats_attackspeed
0,15.1.1,Aatrox,"[""Fighter""]",8,4,3,4,650,114,0,0.0,345,38,4.8,32,2.05,175,3.0,0.5,0.0,0.0,0,0,60,5.0,2.5,0.651

In [ ]:
############################ fonction helper pour cleanner les noms des champions

In [12]:
import re
import unicodedata

def normalize_champion_name(name):
    if pd.isna(name):
        return name
    
    # passer en string
    name = str(name)
    
    # enlever accents
    name = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode("utf-8")
    
    # lower case
    name = name.lower()
    
    # enlever tout sauf lettres et chiffres
    name = re.sub(r"[^a-z0-9]", "", name)
    
    return name

In [13]:
def normalize_champs_names(df_champs):

    df_champs = df_champs.copy()

    df_champs["name"] = df_champs["name"].apply(normalize_champion_name)

    return df_champs

In [14]:
def normalize_games_champions(df_games, champion_cols):

    df_games = df_games.copy()

    for col in champion_cols:
        df_games[col] = df_games[col].apply(normalize_champion_name)

    return df_games

In [15]:
champion_cols = [
    "blue_top_champion",
    "blue_jungle_champion",
    "blue_mid_champion",
    "blue_adc_champion",
    "blue_support_champion",
    "red_top_champion",
    "red_jungle_champion",
    "red_mid_champion",
    "red_adc_champion",
    "red_support_champion",
]

df_games = normalize_games_champions(df_games, champion_cols)
df_champs = normalize_champs_names(df_champs)

In [16]:
champion_fix = {
    "masteryi": "maitreyi",
    "monkeyking": "wukong",
    "nunu": "nunuetwillump",
    "renata": "renataglasc"
}
champion_cols = [c for c in df_games.columns if c.endswith("_champion")]

for col in champion_cols:
    df_games[col] = df_games[col].replace(champion_fix)

In [40]:
########################## aggrege champs et games

In [17]:
print(sorted([v for v in df_games["blue_top_champion"].unique() if pd.notna(v)]))
print("NaN présent :", df_games["blue_top_champion"].isna().any())

['aatrox', 'ahri', 'akali', 'akshan', 'alistar', 'ambessa', 'amumu', 'anivia', 'annie', 'aphelios', 'ashe', 'aurelionsol', 'aurora', 'azir', 'bard', 'belveth', 'blitzcrank', 'brand', 'braum', 'briar', 'caitlyn', 'camille', 'cassiopeia', 'chogath', 'corki', 'darius', 'diana', 'draven', 'drmundo', 'ekko', 'elise', 'evelynn', 'ezreal', 'fiddlesticks', 'fiora', 'fizz', 'galio', 'gangplank', 'garen', 'gnar', 'gragas', 'graves', 'gwen', 'hecarim', 'heimerdinger', 'hwei', 'illaoi', 'irelia', 'ivern', 'janna', 'jarvaniv', 'jax', 'jayce', 'jhin', 'jinx', 'kaisa', 'kalista', 'karma', 'karthus', 'kassadin', 'katarina', 'kayle', 'kayn', 'kennen', 'khazix', 'kindred', 'kled', 'kogmaw', 'ksante', 'leblanc', 'leesin', 'leona', 'lillia', 'lissandra', 'lucian', 'lulu', 'lux', 'maitreyi', 'malphite', 'malzahar', 'maokai', 'mel', 'milio', 'missfortune', 'mordekaiser', 'morgana', 'naafiri', 'nami', 'nasus', 'nautilus', 'neeko', 'nidalee', 'nilah', 'nocturne', 'nunuetwillump', 'olaf', 'orianna', 'ornn', 'pantheon', 'poppy', 'pyke', 'qiyana', 'quinn', 'rakan', 'rammus', 'reksai', 'rell', 'renekton', 'rengar', 'riven', 'rumble', 'ryze', 'samira', 'sejuani', 'senna', 'seraphine', 'sett', 'shaco', 'shen', 'shyvana', 'singed', 'sion', 'sivir', 'skarner', 'smolder', 'sona', 'soraka', 'swain', 'sylas', 'syndra', 'tahmkench', 'taliyah', 'talon', 'taric', 'teemo', 'thresh', 'tristana', 'trundle', 'tryndamere', 'twistedfate', 'twitch', 'udyr', 'urgot', 'varus', 'vayne', 'veigar', 'velkoz', 'vex', 'vi', 'viego', 'viktor', 'vladimir', 'volibear', 'warwick', 'wukong', 'xayah', 'xerath', 'xinzhao', 'yasuo', 'yone', 'yorick', 'yunara', 'yuumi', 'zaahen', 'zac', 'zed', 'zeri', 'ziggs', 'zilean', 'zoe', 'zyra']
NaN présent : True

In [18]:
sorted(df_champs["name"].unique())

['aatrox',
 'ahri',
 'akali',
 'akshan',
 'alistar',
 'ambessa',
 'amumu',
 'anivia',
 'annie',
 'aphelios',
 'ashe',
 'aurelionsol',
 'aurora',
 'azir',
 'bard',
 'belveth',
 'blitzcrank',
 'brand',
 'braum',
 'briar',
 'caitlyn',
 'camille',
 'cassiopeia',
 'chogath',
 'corki',
 'darius',
 'diana',
 'draven',
 'drmundo',
 'ekko',
 'elise',
 'evelynn',
 'ezreal',
 'fiddlesticks',
 'fiora',
 'fizz',
 'galio',
 'gangplank',
 'garen',
 'gnar',
 'gragas',
 'graves',
 'gwen',
 'hecarim',
 'heimerdinger',
 'hwei',
 'illaoi',
 'irelia',
 'ivern',
 'janna',
 'jarvaniv',
 'jax',
 'jayce',
 'jhin',
 'jinx',
 'kaisa',
 'kalista',
 'karma',
 'karthus',
 'kassadin',
 'katarina',
 'kayle',
 'kayn',
 'kennen',
 'khazix',
 'kindred',
 'kled',
 'kogmaw',
 'ksante',
 'leblanc',
 'leesin',
 'leona',
 'lillia',
 'lissandra',
 'lucian',
 'lulu',
 'lux',
 'maitreyi',
 'malphite',
 'malzahar',
 'maokai',
 'mel',
 'milio',
 'missfortune',
 'mordekaiser',
 'morgana',
 'naafiri',
 'nami',
 'nasus',
 'nautilus',
 'neeko',
 'nidalee',
 'nilah',
 'nocturne',
 'nunuetwillump',
 'olaf',
 'orianna',
 'ornn',
 'pantheon',
 'poppy',
 'pyke',
 'qiyana',
 'quinn',
 'rakan',
 'rammus',
 'reksai',
 'rell',
 'renataglasc',
 'renekton',
 'rengar',
 'riven',
 'rumble',
 'ryze',
 'samira',
 'sejuani',
 'senna',
 'seraphine',
 'sett',
 'shaco',
 'shen',
 'shyvana',
 'singed',
 'sion',
 'sivir',
 'skarner',
 'smolder',
 'sona',
 'soraka',
 'swain',
 'sylas',
 'syndra',
 'tahmkench',
 'taliyah',
 'talon',
 'taric',
 'teemo',
 'thresh',
 'tristana',
 'trundle',
 'tryndamere',
 'twistedfate',
 'twitch',
 'udyr',
 'urgot',
 'varus',
 'vayne',
 'veigar',
 'velkoz',
 'vex',
 'vi',
 'viego',
 'viktor',
 'vladimir',
 'volibear',
 'warwick',
 'wukong',
 'xayah',
 'xerath',
 'xinzhao',
 'yasuo',
 'yone',
 'yorick',
 'yunara',
 'yuumi',
 'zaahen',
 'zac',
 'zed',
 'zeri',
 'ziggs',
 'zilean',
 'zoe',
 'zyra']

In [19]:
# aggrege games et champions : 

import pandas as pd

# --- normaliser les patches ---
df_games = df_games.copy()
df_champion = df_champs.copy()

df_games["patch_short"] = df_games["patch"].str.extract(r"(\d+\.\d+)")
df_champion["patch_short"] = df_champion["patch"].str.extract(r"(\d+\.\d+)")

# colonnes champion dans games
champion_cols = [
    "blue_top_champion",
    "blue_jungle_champion",
    "blue_mid_champion",
    "blue_adc_champion",
    "blue_support_champion",
    "red_top_champion",
    "red_jungle_champion",
    "red_mid_champion",
    "red_adc_champion",
    "red_support_champion",
]

# stats champion (tout sauf patch / name)
champ_stats = df_champion.columns.difference(["patch", "patch_short", "name"])

df_result = df_games.copy()

for col in champion_cols:

    prefix = col.replace("_champion", "")

    temp = df_champion.rename(columns={"name": col})

    temp = temp[["patch_short", col] + list(champ_stats)]

    temp = temp.rename(
        columns={c: f"{prefix}_{c}" for c in champ_stats}
    )

    df_result = df_result.merge(
        temp,
        how="left",
        on=["patch_short", col],
    )

# optionnel : supprimer patch_short
df_result = df_result.drop(columns="patch_short")

In [20]:
# df_result.head()
df_result["elo"].unique()

array(['HIGH_ELO', 'UNKNOWN', 'CHALLENGER', 'GRANDMASTER', 'MASTER',
       'DIAMOND'], dtype=object)

In [21]:
import pandas as pd
from ast import literal_eval  # si les listes sont stockées en string

# sélectionner toutes les colonnes se terminant par "_tags"
tag_cols = [c for c in df_result.columns if c.endswith("_tags")]

# dictionnaire pour stocker toutes les valeurs uniques
unique_tags = {}

for col in tag_cols:
    # si les valeurs sont des string de liste, convertir en vraie liste
    df_result[col] = df_result[col].apply(lambda x: literal_eval(x) if isinstance(x, str) else x)
    
    # explode et récupérer uniques
    unique_tags[col] = df_result[col].explode().unique()

# afficher le résultat
for col, tags in unique_tags.items():
    print(f"{col}: {tags}")

blue_top_tags: ['Fighter' 'Tank' 'Mage' 'Marksman' 'Assassin' 'Support' nan]
blue_jungle_tags: ['Assassin' 'Marksman' 'Mage' 'Fighter' 'Tank' 'Support' nan]
blue_mid_tags: ['Fighter' 'Assassin' 'Tank' 'Mage' 'Marksman' 'Support' nan]
blue_adc_tags: ['Marksman' 'Mage' 'Support' 'Assassin' 'Fighter' 'Tank' nan]
blue_support_tags: ['Tank' 'Support' 'Mage' 'Fighter' 'Assassin' 'Marksman' nan]
red_top_tags: ['Fighter' 'Assassin' 'Marksman' 'Tank' 'Mage' 'Support' nan]
red_jungle_tags: ['Mage' 'Support' 'Fighter' 'Tank' 'Assassin' 'Marksman' nan]
red_mid_tags: ['Mage' 'Support' 'Assassin' 'Fighter' 'Tank' 'Marksman' nan]
red_adc_tags: ['Marksman' 'Support' 'Mage' 'Assassin' 'Fighter' 'Tank' nan]
red_support_tags: ['Support' 'Mage' 'Assassin' 'Tank' 'Marksman' 'Fighter' nan]

In [22]:
import pandas as pd
from ast import literal_eval

tag_cols = [c for c in df_result.columns if c.endswith("_tags")]

for col in tag_cols:

    df_result[col] = df_result[col].apply(
        lambda x: literal_eval(x) if isinstance(x, str) else x
    )

    exploded = df_result[col].explode()

    unique_tags = exploded.unique()
    nan_count = exploded.isna().sum()

    print(f"{col}: {unique_tags}")
    print(f"NaN count: {nan_count}\n")

blue_top_tags: ['Fighter' 'Tank' 'Mage' 'Marksman' 'Assassin' 'Support' nan]
NaN count: 121

blue_jungle_tags: ['Assassin' 'Marksman' 'Mage' 'Fighter' 'Tank' 'Support' nan]
NaN count: 93

blue_mid_tags: ['Fighter' 'Assassin' 'Tank' 'Mage' 'Marksman' 'Support' nan]
NaN count: 97

blue_adc_tags: ['Marksman' 'Mage' 'Support' 'Assassin' 'Fighter' 'Tank' nan]
NaN count: 118

blue_support_tags: ['Tank' 'Support' 'Mage' 'Fighter' 'Assassin' 'Marksman' nan]
NaN count: 117

red_top_tags: ['Fighter' 'Assassin' 'Marksman' 'Tank' 'Mage' 'Support' nan]
NaN count: 119

red_jungle_tags: ['Mage' 'Support' 'Fighter' 'Tank' 'Assassin' 'Marksman' nan]
NaN count: 86

red_mid_tags: ['Mage' 'Support' 'Assassin' 'Fighter' 'Tank' 'Marksman' nan]
NaN count: 107

red_adc_tags: ['Marksman' 'Support' 'Mage' 'Assassin' 'Fighter' 'Tank' nan]
NaN count: 120

red_support_tags: ['Support' 'Mage' 'Assassin' 'Tank' 'Marksman' 'Fighter' nan]
NaN count: 103

In [23]:
df_result.shape

(280996, 265)

In [24]:
df_result[df_result["blue_support_tags"].isna()].shape

(117, 265)

In [25]:
# total de NaN dans toutes les colonnes champion
total_nan = df_games[champion_cols].isna().sum().sum()

# nombre de lignes avec au moins un NaN
rows_with_nan = df_games[champion_cols].isna().any(axis=1).sum()

print("Total NaN dans les colonnes champions :", total_nan)
print("Nombre de lignes avec au moins un NaN :", rows_with_nan)
print(df_games[champion_cols].isna().sum())

Total NaN dans les colonnes champions : 1081
Nombre de lignes avec au moins un NaN : 1063
blue_top_champion        121
blue_jungle_champion      93
blue_mid_champion         97
blue_adc_champion        118
blue_support_champion    117
red_top_champion         119
red_jungle_champion       86
red_mid_champion         107
red_adc_champion         120
red_support_champion     103
dtype: int64

In [26]:
df_result[df_result["blue_support_tags"].isna()]["blue_support_champion"].unique()

array([nan], dtype=object)

In [ ]:
###########################################################################################################################
####### ON INCLUT LES WINRATES ############################################################

In [27]:
df_result.head()

,match_id,serveur,patch,elo,blue_side_win,blue_top_champion,blue_jungle_champion,blue_mid_champion,blue_adc_champion,blue_support_champion,red_top_champion,red_jungle_champion,red_mid_champion,red_adc_champion,red_support_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags
0,EUW1_7517331727,euw1,15.17.708.5788,HIGH_ELO,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"[Fighter, Tank]",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,[Assassin],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"[Fighter, Assassin]",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,[Marksman],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"[Tank, Support]",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"[Fighter, Assassin]",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"[Mage, Support]",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,[Mage],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,[Marksman],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"[Support, Mage]"
1,EUW1_7509322616,euw1,15.17.706.7412,HIGH_ELO,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"[Fighter, Mage]",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,[Assassin],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"[Fighter, Assassin]",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"[Marksman, Mage]",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"[Support, Mage]",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,[Fighter],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"[Fighter, Tank]",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,[Mage],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"[Support, Marksman]",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"[Support, Mage]"
2,EUW1_7509243675,euw1,15.17.706.7412,HIGH_ELO,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"[Marksman, Mage]",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,[Marksman],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"[Tank, Mage]",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"[Support, Mage]",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"[Marksman, Assassin]",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"[Fighter, Assassin]",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"[Mage, Support]",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"[Marksman, Mage]",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,[Support]
3,EUW1_7509193063,euw1,15.17.706.7412,HIGH_ELO,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"[Fighter, Tank]",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"[Assassin, Mage]",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,[Assassin],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,[Support],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"[Tank, Mage]",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"[Fighter, Tank]",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"[Mage, Support]",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"[Marksman, Mage]",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"[Support, Mage]"
4,EUW1_7508909082,euw1,15.17.706.7412,HIGH_ELO,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio,3.0,4.0,5.0,8.0,23.0,4.5,53.0,3.00,550.0,0.668,2.00,0.0,0.0,607.0,110.0,6.00,0.55,335.0,475.0,30.0,8.00,0.8,32.0,1.30,"[Mage, Assassin]",8.0,6.0,2.0,3.0,35.0,4.4,63.0,3.00,175.0,0.645,3.50,0.0,0.0,620.0,106.0,8.0,0.70,345.0,274.0,55.0,7.25,0.45,32.0,2.05,"[Fighter, Tank]",9.0,2.0,6.0,3.0,27.0,4.2,59.0,3.1,550.0,0.679,3.38,0.0,0.0,630.0,104.0,3.75,0.60,330.0,300.0,40.0,7.25,0.7,30.0,1.30,"[Marksman, Assassin]",9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,[Support],8.0,4.0,7.0,3.0,22.0,5.0,59.0,4.25,125.0,0.658,3.00,0.0,0.0,590.0,109.0,6.0,0.60,335.0,375.0,45.0,6.0,0.80,30.0,1.30,"[Fighter, Marksman]",8.0,5.0,2.0,1.0,33.0,4.70,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.0,0.50,340.0,0.0,0.0,0.0,0.00,28.0,2.05,"[Fighter, Tank]",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.0,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,[Assassin],8.0,5.0,6.0,3.0,28.0,4.2,60.0,2.9,500.0,0.638,3.3,0.0,0.0,641.0,100.0,3.75,0.65,335.0,320.0,43.0,7.0,0.8,30.0,1.3,"[Marksman, Assassin]",2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.0,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.40,30.0,1.30,"[Support, Mage]"

In [ ]:
# attends déjà on va reformater winrate matchup et synergy. ensuite,

on va concatenner winrates simple de TOUTTOUT15.24 
puis on va associer df_result avec df_winrates simple, 
puis on va ssocier df_result avec df_winrates_matchup

il faudra choisir les bons patchs, elos et serveurs. il faudra aussi nettoyer les noms pour bien faire matcher.

In [28]:
df_simple_wr.head()

,elo,server,patch,label,name,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,TOUT,TOUT,16.3,1,Briar,jun,91.1%,S+,52.8%,+1.5%,6.7%,599 576
1,TOUT,TOUT,16.3,2,Miss Fortune,adc,97.0%,S+,51.7%,-0.0%,15.5%,1 386 160
2,TOUT,TOUT,16.3,3,Malzahar,mid,92.2%,S+,52.3%,+0.0%,8.1%,724 180
3,TOUT,TOUT,16.3,4,Swain,adc,18.6%,S+,54.6%,-0.1%,1.7%,154 988
4,TOUT,TOUT,16.3,5,Jinx,adc,99.5%,S+,51.6%,-0.2%,16.6%,1 485 175

In [29]:
matchups_df.head()

,champion,role,role_play_ratio,tier,rank,winrate,pickrate,banrate,nb_games_analyzed,url,collect_coherente,matchup_adc_1_name,matchup_adc_1_winrate,matchup_adc_1_games,matchup_adc_1_lane_quality,matchup_adc_2_name,matchup_adc_2_winrate,matchup_adc_2_games,matchup_adc_2_lane_quality,matchup_adc_3_name,matchup_adc_3_winrate,matchup_adc_3_games,matchup_adc_3_lane_quality,matchup_adc_4_name,matchup_adc_4_winrate,matchup_adc_4_games,matchup_adc_4_lane_quality,matchup_adc_5_name,matchup_adc_5_winrate,matchup_adc_5_games,matchup_adc_5_lane_quality,matchup_adc_6_name,matchup_adc_6_winrate,matchup_adc_6_games,matchup_adc_6_lane_quality,matchup_adc_7_name,matchup_adc_7_winrate,matchup_adc_7_games,matchup_adc_7_lane_quality,matchup_adc_8_name,matchup_adc_8_winrate,matchup_adc_8_games,matchup_adc_8_lane_quality,matchup_adc_9_name,matchup_adc_9_winrate,matchup_adc_9_games,matchup_adc_9_lane_quality,matchup_adc_10_name,matchup_adc_10_winrate,matchup_adc_10_games,matchup_adc_10_lane_quality,matchup_adc_11_name,matchup_adc_11_winrate,matchup_adc_11_games,matchup_adc_11_lane_quality,matchup_adc_12_name,matchup_adc_12_winrate,matchup_adc_12_games,matchup_adc_12_lane_quality,matchup_adc_13_name,matchup_adc_13_winrate,matchup_adc_13_games,matchup_adc_13_lane_quality,matchup_adc_14_name,matchup_adc_14_winrate,matchup_adc_14_games,matchup_adc_14_lane_quality,matchup_adc_15_name,matchup_adc_15_winrate,matchup_adc_15_games,matchup_adc_15_lane_quality,matchup_adc_16_name,matchup_adc_16_winrate,matchup_adc_16_games,matchup_adc_16_lane_quality,matchup_adc_17_name,matchup_adc_17_winrate,matchup_adc_17_games,matchup_adc_17_lane_quality,matchup_adc_18_name,matchup_adc_18_winrate,matchup_adc_18_games,matchup_adc_18_lane_quality,matchup_adc_19_name,matchup_adc_19_winrate,matchup_adc_19_games,matchup_adc_19_lane_quality,matchup_adc_20_name,matchup_adc_20_winrate,matchup_adc_20_games,matchup_adc_20_lane_quality,matchup_adc_21_name,matchup_adc_21_winrate,matchup_adc_21_games,matchup_adc_21_lane_quality,matchup_adc_22_name,matchup_adc_22_winrate,matchup_adc_22_games,matchup_adc_22_lane_quality,matchup_adc_23_name,matchup_adc_23_winrate,matchup_adc_23_games,matchup_adc_23_lane_quality,matchup_adc_24_name,matchup_adc_24_winrate,matchup_adc_24_games,matchup_adc_24_lane_quality,matchup_adc_25_name,matchup_adc_25_winrate,matchup_adc_25_games,matchup_adc_25_lane_quality,matchup_adc_26_name,matchup_adc_26_winrate,matchup_adc_26_games,matchup_adc_26_lane_quality,matchup_adc_27_name,matchup_adc_27_winrate,matchup_adc_27_games,matchup_adc_27_lane_quality,matchup_adc_28_name,matchup_adc_28_winrate,matchup_adc_28_games,matchup_adc_28_lane_quality,matchup_adc_29_name,matchup_adc_29_winrate,matchup_adc_29_games,matchup_adc_29_lane_quality,matchup_adc_30_name,matchup_adc_30_winrate,matchup_adc_30_games,matchup_adc_30_lane_quality,matchup_jun_1_name,matchup_jun_1_winrate,matchup_jun_1_games,matchup_jun_1_lane_quality,matchup_jun_2_name,matchup_jun_2_winrate,matchup_jun_2_games,matchup_jun_2_lane_quality,matchup_jun_3_name,matchup_jun_3_winrate,matchup_jun_3_games,matchup_jun_3_lane_quality,matchup_jun_4_name,matchup_jun_4_winrate,matchup_jun_4_games,matchup_jun_4_lane_quality,matchup_jun_5_name,matchup_jun_5_winrate,matchup_jun_5_games,matchup_jun_5_lane_quality,matchup_jun_6_name,matchup_jun_6_winrate,matchup_jun_6_games,matchup_jun_6_lane_quality,matchup_jun_7_name,matchup_jun_7_winrate,matchup_jun_7_games,matchup_jun_7_lane_quality,matchup_jun_8_name,matchup_jun_8_winrate,matchup_jun_8_games,matchup_jun_8_lane_quality,matchup_jun_9_name,matchup_jun_9_winrate,matchup_jun_9_games,matchup_jun_9_lane_quality,matchup_jun_10_name,matchup_jun_10_winrate,matchup_jun_10_games,matchup_jun_10_lane_quality,matchup_jun_11_name,matchup_jun_11_winrate,matchup_jun_11_games,matchup_jun_11_lane_quality,matchup_jun_12_name,matchup_jun_12_winrate,matchup_jun_12_games,matchup_jun_12_lane_quality,matchup_jun_13_name,matchup_jun_13_winrate,matchup_jun_13_games,matchup_jun_13_lane_quality,matchup_jun_14_name,matchup_jun_14_winrate,matchup_jun_14_games,matchup_jun_14_lane_quality,matchup_jun_15_name,matchup_jun_15_winrate,matchup_jun_15_games,matchup_jun_15_lane_quality,matchup_jun_16_name,matchup_jun_16_winrate,matchup_jun_16_games,matchup_jun_16_lane_quality,matchup_jun_17_name,matchup_jun_17_winrate,matchup_jun_17_games,matchup_jun_17_lane_quality,matchup_jun_18_name,matchup_jun_18_winrate,matchup_jun_18_games,matchup_jun_18_lane_quality,matchup_jun_19_name,matchup_jun_19_winrate,matchup_jun_19_games,matchup_jun_19_lane_quality,matchup_jun_20_name,matchup_jun_20_winrate,matchup_jun_20_games,matchup_jun_20_lane_quality,matchup_jun_21_name,matchup_jun_21_winrate,matchup_jun_21_games,matchup_jun_21_lane_quality,matchup_jun_22_name,matchup_jun_22_winrate,matchup_jun_22_games,matchup_jun_22_lane_quality,matchup_jun_23_name,matchup_jun_23_winrate,matchup_jun_23_games,matchup_jun_23_lane_quality,matchup_jun_24_name,matchup_jun_24_winrate,matchup_jun_24_games,matchup_jun_24_lane_quality,matchup_jun_25_name,matchup_jun_25_winrate,matchup_jun_25_games,matchup_jun_25_lane_quality,matchup_jun_26_name,matchup_jun_26_winrate,matchup_jun_26_games,matchup_jun_26_lane_quality,matchup_jun_27_name,matchup_jun_27_winrate,matchup_jun_27_games,matchup_jun_27_lane_quality,matchup_jun_28_name,matchup_jun_28_winrate,matchup_jun_28_games,matchup_jun_28_lane_quality,matchup_jun_29_name,matchup_jun_29_winrate,matchup_jun_29_games,matchup_jun_29_lane_quality,matchup_jun_30_name,matchup_jun_30_winrate,matchup_jun_30_games,matchup_jun_30_lane_quality,matchup_jun_31_name,matchup_jun_31_winrate,matchup_jun_31_games,matchup_jun_31_lane_quality,matchup_jun_32_name,matchup_jun_32_winrate,matchup_jun_32_games,matchup_jun_32_lane_quality,matchup_jun_33_name,matchup_jun_33_winrate,matchup_jun_33_games,matchup_jun_33_lane_quality,matchup_jun_34_name,matchup_jun_34_winrate,matchup_jun_34_games,matchup_jun_34_lane_quality,matchup_jun_35_name,matchup_jun_35_winrate,matchup_jun_35_games,matchup_jun_35_lane_quality,matchup_jun_36_name,matchup_jun_36_winrate,matchup_jun_36_games,matchup_jun_36_lane_quality,matchup_jun_37_name,matchup_jun_37_winrate,matchup_jun_37_games,matchup_jun_37_lane_quality,matchup_jun_38_name,matchup_jun_38_winrate,matchup_jun_38_games,matchup_jun_38_lane_quality,matchup_jun_39_name,matchup_jun_39_winrate,matchup_jun_39_games,matchup_jun_39_lane_quality,matchup_jun_40_name,matchup_jun_40_winrate,matchup_jun_40_games,matchup_jun_40_lane_quality,matchup_jun_41_name,matchup_jun_41_winrate,matchup_jun_41_games,matchup_jun_41_lane_quality,matchup_jun_42_name,matchup_jun_42_winrate,matchup_jun_42_games,matchup_jun_42_lane_quality,matchup_jun_43_name,matchup_jun_43_winrate,matchup_jun_43_games,matchup_jun_43_lane_quality,matchup_jun_44_name,matchup_jun_44_winrate,matchup_jun_44_games,matchup_jun_44_lane_quality,matchup_jun_45_name,matchup_jun_45_winrate,matchup_jun_45_games,matchup_jun_45_lane_quality,matchup_jun_46_name,matchup_jun_46_winrate,matchup_jun_46_games,matchup_jun_46_lane_quality,matchup_jun_47_name,matchup_jun_47_winrate,matchup_jun_47_games,matchup_jun_47_lane_quality,matchup_jun_48_name,matchup_jun_48_winrate,matchup_jun_48_games,matchup_jun_48_lane_quality,matchup_jun_49_name,matchup_jun_49_winrate,matchup_jun_49_games,matchup_jun_49_lane_quality,matchup_jun_50_name,matchup_jun_50_winrate,matchup_jun_50_games,matchup_jun_50_lane_quality,matchup_jun_51_name,matchup_jun_51_winrate,matchup_jun_51_games,matchup_jun_51_lane_quality,matchup_jun_52_name,matchup_jun_52_winrate,matchup_jun_52_games,matchup_jun_52_lane_quality,matchup_jun_53_name,matchup_jun_53_winrate,matchup_jun_53_games,matchup_jun_53_lane_quality,matchup_jun_54_name,matchup_jun_54_winrate,matchup_jun_54_games,matchup_jun_54_lane_quality,matchup_jun_55_name,matchup_jun_55_winrate,matchup_jun_55_games,matchup_jun_55_lane_quality,matchup_jun_56_name,matchup_jun_56_winrate,matchup_jun_56_games,matchup_jun_56_lane_quality,matchup_jun_57_name,matchup_jun_57_winrate,matchup_jun_57_games,matchup_jun_57_lane_quality,matchup_jun_58_name,matchup_jun_58_winrate,matchup_jun_58_games,matchup_jun_58_lane_quality,matchup_mid_1_name,matchup_mid_1_winrate,matchup_mid_1_games,matchup_mid_1_lane_quality,matchup_mid_2_name,matchup_mid_2_winrate,matchup_mid_2_games,matchup_mid_2_lane_quality,matchup_mid_3_name,matchup_mid_3_winrate,matchup_mid_3_games,matchup_mid_3_lane_quality,matchup_mid_4_name,matchup_mid_4_winrate,matchup_mid_4_games,matchup_mid_4_lane_quality,matchup_mid_5_name,matchup_mid_5_winrate,matchup_mid_5_games,matchup_mid_5_lane_quality,matchup_mid_6_name,matchup_mid_6_winrate,matchup_mid_6_games,matchup_mid_6_lane_quality,matchup_mid_7_name,matchup_mid_7_winrate,matchup_mid_7_games,matchup_mid_7_lane_quality,matchup_mid_8_name,matchup_mid_8_winrate,matchup_mid_8_games,matchup_mid_8_lane_quality,matchup_mid_9_name,matchup_mid_9_winrate,matchup_mid_9_games,matchup_mid_9_lane_quality,matchup_mid_10_name,matchup_mid_10_winrate,matchup_mid_10_games,matchup_mid_10_lane_quality,matchup_mid_11_name,matchup_mid_11_winrate,matchup_mid_11_games,matchup_mid_11_lane_quality,matchup_mid_12_name,matchup_mid_12_winrate,matchup_mid_12_games,matchup_mid_12_lane_quality,matchup_mid_13_name,matchup_mid_13_winrate,matchup_mid_13_games,matchup_mid_13_lane_quality,matchup_mid_14_name,matchup_mid_14_winrate,matchup_mid_14_games,matchup_mid_14_lane_quality,matchup_mid_15_name,matchup_mid_15_winrate,matchup_mid_15_games,matchup_mid_15_lane_quality,matchup_mid_16_name,matchup_mid_16_winrate,matchup_mid_16_games,matchup_mid_16_lane_quality,matchup_mid_17_name,matchup_mid_17_winrate,matchup_mid_17_games,matchup_mid_17_lane_quality,matchup_mid_18_name,matchup_mid_18_winrate,matchup_mid_18_games,matchup_mid_18_lane_quality,matchup_mid_19_name,matchup_mid_19_winrate,matchup_mid_19_games,matchup_mid_19_lane_quality,matchup_mid_20_name,matchup_mid_20_winrate,matchup_mid_20_games,matchup_mid_20_lane_quality,matchup_mid_21_name,matchup_mid_21_winrate,matchup_mid_21_games,matchup_mid_21_lane_quality,matchup_mid_22_name,matchup_mid_22_winrate,matchup_mid_22_games,matchup_mid_22_lane_quality,matchup_mid_23_name,matchup_mid_23_winrate,matchup_mid_23_games,matchup_mid_23_lane_quality,matchup_mid_24_name,matchup_mid_24_winrate,matchup_mid_24_games,matchup_mid_24_lane_quality,matchup_mid_25_name,matchup_mid_25_winrate,matchup_mid_25_games,matchup_mid_25_lane_quality,matchup_mid_26_name,matchup_mid_26_winrate,matchup_mid_26_games,matchup_mid_26_lane_quality,matchup_mid_27_name,matchup_mid_27_winrate,matchup_mid_27_games,matchup_mid_27_lane_quality,matchup_mid_28_name,matchup_mid_28_winrate,matchup_mid_28_games,matchup_mid_28_lane_quality,matchup_mid_29_name,matchup_mid_29_winrate,matchup_mid_29_games,matchup_mid_29_lane_quality,matchup_mid_30_name,matchup_mid_30_winrate,matchup_mid_30_games,matchup_mid_30_lane_quality,matchup_mid_31_name,matchup_mid_31_winrate,matchup_mid_31_games,matchup_mid_31_lane_quality,matchup_mid_32_name,matchup_mid_32_winrate,matchup_mid_32_games,matchup_mid_32_lane_quality,matchup_mid_33_name,matchup_mid_33_winrate,matchup_mid_33_games,matchup_mid_33_lane_quality,matchup_mid_34_name,matchup_mid_34_winrate,matchup_mid_34_games,matchup_mid_34_lane_quality,matchup_mid_35_name,matchup_mid_35_winrate,matchup_mid_35_games,matchup_mid_35_lane_quality,matchup_mid_36_name,matchup_mid_36_winrate,matchup_mid_36_games,matchup_mid_36_lane_quality,matchup_mid_37_name,matchup_mid_37_winrate,matchup_mid_37_games,matchup_mid_37_lane_quality,matchup_mid_38_name,matchup_mid_38_winrate,matchup_mid_38_games,matchup_mid_38_lane_quality,matchup_mid_39_name,matchup_mid_39_winrate,matchup_mid_39_games,matchup_mid_39_lane_quality,matchup_mid_40_name,matchup_mid_40_winrate,matchup_mid_40_games,matchup_mid_40_lane_quality,matchup_mid_41_name,matchup_mid_41_winrate,matchup_mid_41_games,matchup_mid_41_lane_quality,matchup_mid_42_name,matchup_mid_42_winrate,matchup_mid_42_games,matchup_mid_42_lane_quality,matchup_mid_43_name,matchup_mid_43_winrate,matchup_mid_43_games,matchup_mid_43_lane_quality,matchup_mid_44_name,matchup_mid_44_winrate,matchup_mid_44_games,matchup_mid_44_lane_quality,matchup_mid_45_name,matchup_mid_45_winrate,matchup_mid_45_games,matchup_mid_45_lane_quality,matchup_mid_46_name,matchup_mid_46_winrate,matchup_mid_46_games,matchup_mid_46_lane_quality,matchup_mid_47_name,matchup_mid_47_winrate,matchup_mid_47_games,matchup_mid_47_lane_quality,matchup_mid_48_name,matchup_mid_48_winrate,matchup_mid_48_games,matchup_mid_48_lane_quality,matchup_mid_49_name,matchup_mid_49_winrate,matchup_mid_49_games,matchup_mid_49_lane_quality,matchup_mid_50_name,matchup_mid_50_winrate,matchup_mid_50_games,matchup_mid_50_lane_quality,matchup_mid_51_name,matchup_mid_51_winrate,matchup_mid_51_games,matchup_mid_51_lane_quality,matchup_mid_52_name,matchup_mid_52_winrate,matchup_mid_52_games,matchup_mid_52_lane_quality,matchup_mid_53_name,matchup_mid_53_winrate,matchup_mid_53_games,matchup_mid_53_lane_quality,matchup_mid_54_name,matchup_mid_54_winrate,matchup_mid_54_games,matchup_mid_54_lane_quality,matchup_mid_55_name,matchup_mid_55_winrate,matchup_mid_55_games,matchup_mid_55_lane_quality,matchup_mid_56_name,matchup_mid_56_winrate,matchup_mid_56_games,matchup_mid_56_lane_quality,matchup_mid_57_name,matchup_mid_57_winrate,matchup_mid_57_games,matchup_mid_57_lane_quality,matchup_mid_58_name,matchup_mid_58_winrate,matchup_mid_58_games,matchup_mid_58_lane_quality,matchup_mid_59_name,matchup_mid_59_winrate,matchup_mid_59_games,matchup_mid_59_lane_quality,matchup_mid_60_name,matchup_mid_60_winrate,matchup_mid_60_games,matchup_mid_60_lane_quality,matchup_sup_1_name,matchup_sup_1_winrate,matchup_sup_1_games,matchup_sup_1_lane_quality,matchup_sup_2_name,matchup_sup_2_winrate,matchup_sup_2_games,matchup_sup_2_lane_quality,matchup_sup_3_name,matchup_sup_3_winrate,matchup_sup_3_games,matchup_sup_3_lane_quality,matchup_sup_4_name,matchup_sup_4_winrate,matchup_sup_4_games,matchup_sup_4_lane_quality,matchup_sup_5_name,matchup_sup_5_winrate,matchup_sup_5_games,matchup_sup_5_lane_quality,matchup_sup_6_name,matchup_sup_6_winrate,matchup_sup_6_games,matchup_sup_6_lane_quality,matchup_sup_7_name,matchup_sup_7_winrate,matchup_sup_7_games,matchup_sup_7_lane_quality,matchup_sup_8_name,matchup_sup_8_winrate,matchup_sup_8_games,matchup_sup_8_lane_quality,matchup_sup_9_name,matchup_sup_9_winrate,matchup_sup_9_games,matchup_sup_9_lane_quality,matchup_sup_10_name,matchup_sup_10_winrate,matchup_sup_10_games,matchup_sup_10_lane_quality,matchup_sup_11_name,matchup_sup_11_winrate,matchup_sup_11_games,matchup_sup_11_lane_quality,matchup_sup_12_name,matchup_sup_12_winrate,matchup_sup_12_games,matchup_sup_12_lane_quality,matchup_sup_13_name,matchup_sup_13_winrate,matchup_sup_13_games,matchup_sup_13_lane_quality,matchup_sup_14_name,matchup_sup_14_winrate,matchup_sup_14_games,matchup_sup_14_lane_quality,matchup_sup_15_name,matchup_sup_15_winrate,matchup_sup_15_games,matchup_sup_15_lane_quality,matchup_sup_16_name,matchup_sup_16_winrate,matchup_sup_16_games,matchup_sup_16_lane_quality,matchup_sup_17_name,matchup_sup_17_winrate,matchup_sup_17_games,matchup_sup_17_lane_quality,matchup_sup_18_name,matchup_sup_18_winrate,matchup_sup_18_games,matchup_sup_18_lane_quality,matchup_sup_19_name,matchup_sup_19_winrate,matchup_sup_19_games,matchup_sup_19_lane_quality,matchup_sup_20_name,matchup_sup_20_winrate,matchup_sup_20_games,matchup_sup_20_lane_quality,matchup_sup_21_name,matchup_sup_21_winrate,matchup_sup_21_games,matchup_sup_21_lane_quality,matchup_sup_22_name,matchup_sup_22_winrate,matchup_sup_22_games,matchup_sup_22_lane_quality,matchup_sup_23_name,matchup_sup_23_winrate,matchup_sup_23_games,matchup_sup_23_lane_quality,matchup_sup_24_name,matchup_sup_24_winrate,matchup_sup_24_games,matchup_sup_24_lane_quality,matchup_sup_25_name,matchup_sup_25_winrate,matchup_sup_25_games,matchup_sup_25_lane_quality,matchup_sup_26_name,matchup_sup_26_winrate,matchup_sup_26_games,matchup_sup_26_lane_quality,matchup_sup_27_name,matchup_sup_27_winrate,matchup_sup_27_games,matchup_sup_27_lane_quality,matchup_sup_28_name,matchup_sup_28_winrate,matchup_sup_28_games,matchup_sup_28_lane_quality,matchup_sup_29_name,matchup_sup_29_winrate,matchup_sup_29_games,matchup_sup_29_lane_quality,matchup_sup_30_name,matchup_sup_30_winrate,matchup_sup_30_games,matchup_sup_30_lane_quality,matchup_sup_31_name,matchup_sup_31_winrate,matchup_sup_31_games,matchup_sup_31_lane_quality,matchup_sup_32_name,matchup_sup_32_winrate,matchup_sup_32_games,matchup_sup_32_lane_quality,matchup_sup_33_name,matchup_sup_33_winrate,matchup_sup_33_games,matchup_sup_33_lane_quality,matchup_sup_34_name,matchup_sup_34_winrate,matchup_sup_34_games,matchup_sup_34_lane_quality,matchup_sup_35_name,matchup_sup_35_winrate,matchup_sup_35_games,matchup_sup_35_lane_quality,matchup_sup_36_name,matchup_sup_36_winrate,matchup_sup_36_games,matchup_sup_36_lane_quality,matchup_sup_37_name,matchup_sup_37_winrate,matchup_sup_37_games,matchup_sup_37_lane_quality,matchup_sup_38_name,matchup_sup_38_winrate,matchup_sup_38_games,matchup_sup_38_lane_quality,matchup_sup_39_name,matchup_sup_39_winrate,matchup_sup_39_games,matchup_sup_39_lane_quality,matchup_sup_40_name,matchup_sup_40_winrate,matchup_sup_40_games,matchup_sup_40_lane_quality,matchup_sup_41_name,matchup_sup_41_winrate,matchup_sup_41_games,matchup_sup_41_lane_quality,matchup_sup_42_name,matchup_sup_42_winrate,matchup_sup_42_games,matchup_sup_42_lane_quality,matchup_sup_43_name,matchup_sup_43_winrate,matchup_sup_43_games,matchup_sup_43_lane_quality,matchup_sup_44_name,matchup_sup_44_winrate,matchup_sup_44_games,matchup_sup_44_lane_quality,matchup_sup_45_name,matchup_sup_45_winrate,matchup_sup_45_games,matchup_sup_45_lane_quality,matchup_sup_46_name,matchup_sup_46_winrate,matchup_sup_46_games,matchup_sup_46_lane_quality,matchup_sup_47_name,matchup_sup_47_winrate,matchup_sup_47_games,matchup_sup_47_lane_quality,matchup_sup_48_name,matchup_sup_48_winrate,matchup_sup_48_games,matchup_sup_48_lane_quality,matchup_sup_49_name,matchup_sup_49_winrate,matchup_sup_49_games,matchup_sup_49_lane_quality,matchup_sup_50_name,matchup_sup_50_winrate,matchup_sup_50_games,matchup_sup_50_lane_quality,matchup_top_1_name,matchup_top_1_winrate,matchup_top_1_games,matchup_top_1_lane_quality,matchup_top_2_name,matchup_top_2_winrate,matchup_top_2_games,matchup_top_2_lane_quality,matchup_top_3_name,matchup_top_3_winrate,matchup_top_3_games,matchup_top_3_lane_quality,matchup_top_4_name,matchup_top_4_winrate,matchup_top_4_games,matchup_top_4_lane_quality,matchup_top_5_name,matchup_top_5_winrate,matchup_top_5_games,matchup_top_5_lane_quality,matchup_top_6_name,matchup_top_6_winrate,matchup_top_6_games,matchup_top_6_lane_quality,matchup_top_7_name,matchup_top_7_winrate,matchup_top_7_games,matchup_top_7_lane_quality,matchup_top_8_name,matchup_top_8_winrate,matchup_top_8_games,matchup_top_8_lane_quality,matchup_top_9_name,matchup_top_9_winrate,matchup_top_9_games,matchup_top_9_lane_quality,matchup_top_10_name,matchup_top_10_winrate,matchup_top_10_games,matchup_top_10_lane_quality,matchup_top_11_name,matchup_top_11_winrate,matchup_top_11_games,matchup_top_11_lane_quality,matchup_top_12_name,matchup_top_12_winrate,matchup_top_12_games,matchup_top_12_lane_quality,matchup_top_13_name,matchup_top_13_winrate,matchup_top_13_games,matchup_top_13_lane_quality,matchup_top_14_name,matchup_top_14_winrate,matchup_top_14_games,matchup_top_14_lane_quality,matchup_top_15_name,matchup_top_15_winrate,matchup_top_15_games,matchup_top_15_lane_quality,matchup_top_16_name,matchup_top_16_winrate,matchup_top_16_games,matchup_top_16_lane_quality,matchup_top_17_name,matchup_top_17_winrate,matchup_top_17_games,matchup_top_17_lane_quality,matchup_top_18_name,matchup_top_18_winrate,matchup_top_18_games,matchup_top_18_lane_quality,matchup_top_19_name,matchup_top_19_winrate,matchup_top_19_games,matchup_top_19_lane_quality,matchup_top_20_name,matchup_top_20_winrate,matchup_top_20_games,matchup_top_20_lane_quality,matchup_top_21_nam

In [30]:
matchups_df.shape

(1090, 1035)

In [31]:
synergies_df.head()

,champion,role,role_play_ratio,tier,rank,winrate,pickrate,banrate,nb_games_analyzed,url,collect_coherente,synergy_adc_1_name,synergy_adc_1_winrate,synergy_adc_1_games,synergy_adc_1_lane_quality,synergy_adc_2_name,synergy_adc_2_winrate,synergy_adc_2_games,synergy_adc_2_lane_quality,synergy_adc_3_name,synergy_adc_3_winrate,synergy_adc_3_games,synergy_adc_3_lane_quality,synergy_adc_4_name,synergy_adc_4_winrate,synergy_adc_4_games,synergy_adc_4_lane_quality,synergy_adc_5_name,synergy_adc_5_winrate,synergy_adc_5_games,synergy_adc_5_lane_quality,synergy_adc_6_name,synergy_adc_6_winrate,synergy_adc_6_games,synergy_adc_6_lane_quality,synergy_adc_7_name,synergy_adc_7_winrate,synergy_adc_7_games,synergy_adc_7_lane_quality,synergy_adc_8_name,synergy_adc_8_winrate,synergy_adc_8_games,synergy_adc_8_lane_quality,synergy_adc_9_name,synergy_adc_9_winrate,synergy_adc_9_games,synergy_adc_9_lane_quality,synergy_adc_10_name,synergy_adc_10_winrate,synergy_adc_10_games,synergy_adc_10_lane_quality,synergy_adc_11_name,synergy_adc_11_winrate,synergy_adc_11_games,synergy_adc_11_lane_quality,synergy_adc_12_name,synergy_adc_12_winrate,synergy_adc_12_games,synergy_adc_12_lane_quality,synergy_adc_13_name,synergy_adc_13_winrate,synergy_adc_13_games,synergy_adc_13_lane_quality,synergy_adc_14_name,synergy_adc_14_winrate,synergy_adc_14_games,synergy_adc_14_lane_quality,synergy_adc_15_name,synergy_adc_15_winrate,synergy_adc_15_games,synergy_adc_15_lane_quality,synergy_adc_16_name,synergy_adc_16_winrate,synergy_adc_16_games,synergy_adc_16_lane_quality,synergy_adc_17_name,synergy_adc_17_winrate,synergy_adc_17_games,synergy_adc_17_lane_quality,synergy_adc_18_name,synergy_adc_18_winrate,synergy_adc_18_games,synergy_adc_18_lane_quality,synergy_adc_19_name,synergy_adc_19_winrate,synergy_adc_19_games,synergy_adc_19_lane_quality,synergy_adc_20_name,synergy_adc_20_winrate,synergy_adc_20_games,synergy_adc_20_lane_quality,synergy_adc_21_name,synergy_adc_21_winrate,synergy_adc_21_games,synergy_adc_21_lane_quality,synergy_adc_22_name,synergy_adc_22_winrate,synergy_adc_22_games,synergy_adc_22_lane_quality,synergy_adc_23_name,synergy_adc_23_winrate,synergy_adc_23_games,synergy_adc_23_lane_quality,synergy_adc_24_name,synergy_adc_24_winrate,synergy_adc_24_games,synergy_adc_24_lane_quality,synergy_adc_25_name,synergy_adc_25_winrate,synergy_adc_25_games,synergy_adc_25_lane_quality,synergy_adc_26_name,synergy_adc_26_winrate,synergy_adc_26_games,synergy_adc_26_lane_quality,synergy_adc_27_name,synergy_adc_27_winrate,synergy_adc_27_games,synergy_adc_27_lane_quality,synergy_adc_28_name,synergy_adc_28_winrate,synergy_adc_28_games,synergy_adc_28_lane_quality,synergy_adc_29_name,synergy_adc_29_winrate,synergy_adc_29_games,synergy_adc_29_lane_quality,synergy_adc_30_name,synergy_adc_30_winrate,synergy_adc_30_games,synergy_adc_30_lane_quality,synergy_adc_31_name,synergy_adc_31_winrate,synergy_adc_31_games,synergy_adc_31_lane_quality,synergy_adc_32_name,synergy_adc_32_winrate,synergy_adc_32_games,synergy_adc_32_lane_quality,synergy_adc_33_name,synergy_adc_33_winrate,synergy_adc_33_games,synergy_adc_33_lane_quality,synergy_adc_34_name,synergy_adc_34_winrate,synergy_adc_34_games,synergy_adc_34_lane_quality,synergy_adc_35_name,synergy_adc_35_winrate,synergy_adc_35_games,synergy_adc_35_lane_quality,synergy_adc_36_name,synergy_adc_36_winrate,synergy_adc_36_games,synergy_adc_36_lane_quality,synergy_jun_1_name,synergy_jun_1_winrate,synergy_jun_1_games,synergy_jun_1_lane_quality,synergy_jun_2_name,synergy_jun_2_winrate,synergy_jun_2_games,synergy_jun_2_lane_quality,synergy_jun_3_name,synergy_jun_3_winrate,synergy_jun_3_games,synergy_jun_3_lane_quality,synergy_jun_4_name,synergy_jun_4_winrate,synergy_jun_4_games,synergy_jun_4_lane_quality,synergy_jun_5_name,synergy_jun_5_winrate,synergy_jun_5_games,synergy_jun_5_lane_quality,synergy_jun_6_name,synergy_jun_6_winrate,synergy_jun_6_games,synergy_jun_6_lane_quality,synergy_jun_7_name,synergy_jun_7_winrate,synergy_jun_7_games,synergy_jun_7_lane_quality,synergy_jun_8_name,synergy_jun_8_winrate,synergy_jun_8_games,synergy_jun_8_lane_quality,synergy_jun_9_name,synergy_jun_9_winrate,synergy_jun_9_games,synergy_jun_9_lane_quality,synergy_jun_10_name,synergy_jun_10_winrate,synergy_jun_10_games,synergy_jun_10_lane_quality,synergy_jun_11_name,synergy_jun_11_winrate,synergy_jun_11_games,synergy_jun_11_lane_quality,synergy_jun_12_name,synergy_jun_12_winrate,synergy_jun_12_games,synergy_jun_12_lane_quality,synergy_jun_13_name,synergy_jun_13_winrate,synergy_jun_13_games,synergy_jun_13_lane_quality,synergy_jun_14_name,synergy_jun_14_winrate,synergy_jun_14_games,synergy_jun_14_lane_quality,synergy_jun_15_name,synergy_jun_15_winrate,synergy_jun_15_games,synergy_jun_15_lane_quality,synergy_jun_16_name,synergy_jun_16_winrate,synergy_jun_16_games,synergy_jun_16_lane_quality,synergy_jun_17_name,synergy_jun_17_winrate,synergy_jun_17_games,synergy_jun_17_lane_quality,synergy_jun_18_name,synergy_jun_18_winrate,synergy_jun_18_games,synergy_jun_18_lane_quality,synergy_jun_19_name,synergy_jun_19_winrate,synergy_jun_19_games,synergy_jun_19_lane_quality,synergy_jun_20_name,synergy_jun_20_winrate,synergy_jun_20_games,synergy_jun_20_lane_quality,synergy_jun_21_name,synergy_jun_21_winrate,synergy_jun_21_games,synergy_jun_21_lane_quality,synergy_jun_22_name,synergy_jun_22_winrate,synergy_jun_22_games,synergy_jun_22_lane_quality,synergy_jun_23_name,synergy_jun_23_winrate,synergy_jun_23_games,synergy_jun_23_lane_quality,synergy_jun_24_name,synergy_jun_24_winrate,synergy_jun_24_games,synergy_jun_24_lane_quality,synergy_jun_25_name,synergy_jun_25_winrate,synergy_jun_25_games,synergy_jun_25_lane_quality,synergy_jun_26_name,synergy_jun_26_winrate,synergy_jun_26_games,synergy_jun_26_lane_quality,synergy_jun_27_name,synergy_jun_27_winrate,synergy_jun_27_games,synergy_jun_27_lane_quality,synergy_jun_28_name,synergy_jun_28_winrate,synergy_jun_28_games,synergy_jun_28_lane_quality,synergy_jun_29_name,synergy_jun_29_winrate,synergy_jun_29_games,synergy_jun_29_lane_quality,synergy_jun_30_name,synergy_jun_30_winrate,synergy_jun_30_games,synergy_jun_30_lane_quality,synergy_jun_31_name,synergy_jun_31_winrate,synergy_jun_31_games,synergy_jun_31_lane_quality,synergy_jun_32_name,synergy_jun_32_winrate,synergy_jun_32_games,synergy_jun_32_lane_quality,synergy_jun_33_name,synergy_jun_33_winrate,synergy_jun_33_games,synergy_jun_33_lane_quality,synergy_jun_34_name,synergy_jun_34_winrate,synergy_jun_34_games,synergy_jun_34_lane_quality,synergy_jun_35_name,synergy_jun_35_winrate,synergy_jun_35_games,synergy_jun_35_lane_quality,synergy_jun_36_name,synergy_jun_36_winrate,synergy_jun_36_games,synergy_jun_36_lane_quality,synergy_jun_37_name,synergy_jun_37_winrate,synergy_jun_37_games,synergy_jun_37_lane_quality,synergy_jun_38_name,synergy_jun_38_winrate,synergy_jun_38_games,synergy_jun_38_lane_quality,synergy_jun_39_name,synergy_jun_39_winrate,synergy_jun_39_games,synergy_jun_39_lane_quality,synergy_jun_40_name,synergy_jun_40_winrate,synergy_jun_40_games,synergy_jun_40_lane_quality,synergy_jun_41_name,synergy_jun_41_winrate,synergy_jun_41_games,synergy_jun_41_lane_quality,synergy_jun_42_name,synergy_jun_42_winrate,synergy_jun_42_games,synergy_jun_42_lane_quality,synergy_jun_43_name,synergy_jun_43_winrate,synergy_jun_43_games,synergy_jun_43_lane_quality,synergy_jun_44_name,synergy_jun_44_winrate,synergy_jun_44_games,synergy_jun_44_lane_quality,synergy_jun_45_name,synergy_jun_45_winrate,synergy_jun_45_games,synergy_jun_45_lane_quality,synergy_jun_46_name,synergy_jun_46_winrate,synergy_jun_46_games,synergy_jun_46_lane_quality,synergy_jun_47_name,synergy_jun_47_winrate,synergy_jun_47_games,synergy_jun_47_lane_quality,synergy_jun_48_name,synergy_jun_48_winrate,synergy_jun_48_games,synergy_jun_48_lane_quality,synergy_jun_49_name,synergy_jun_49_winrate,synergy_jun_49_games,synergy_jun_49_lane_quality,synergy_jun_50_name,synergy_jun_50_winrate,synergy_jun_50_games,synergy_jun_50_lane_quality,synergy_jun_51_name,synergy_jun_51_winrate,synergy_jun_51_games,synergy_jun_51_lane_quality,synergy_jun_52_name,synergy_jun_52_winrate,synergy_jun_52_games,synergy_jun_52_lane_quality,synergy_jun_53_name,synergy_jun_53_winrate,synergy_jun_53_games,synergy_jun_53_lane_quality,synergy_jun_54_name,synergy_jun_54_winrate,synergy_jun_54_games,synergy_jun_54_lane_quality,synergy_jun_55_name,synergy_jun_55_winrate,synergy_jun_55_games,synergy_jun_55_lane_quality,synergy_jun_56_name,synergy_jun_56_winrate,synergy_jun_56_games,synergy_jun_56_lane_quality,synergy_jun_57_name,synergy_jun_57_winrate,synergy_jun_57_games,synergy_jun_57_lane_quality,synergy_jun_58_name,synergy_jun_58_winrate,synergy_jun_58_games,synergy_jun_58_lane_quality,synergy_jun_59_name,synergy_jun_59_winrate,synergy_jun_59_games,synergy_jun_59_lane_quality,synergy_jun_60_name,synergy_jun_60_winrate,synergy_jun_60_games,synergy_jun_60_lane_quality,synergy_jun_61_name,synergy_jun_61_winrate,synergy_jun_61_games,synergy_jun_61_lane_quality,synergy_jun_62_name,synergy_jun_62_winrate,synergy_jun_62_games,synergy_jun_62_lane_quality,synergy_mid_1_name,synergy_mid_1_winrate,synergy_mid_1_games,synergy_mid_1_lane_quality,synergy_mid_2_name,synergy_mid_2_winrate,synergy_mid_2_games,synergy_mid_2_lane_quality,synergy_mid_3_name,synergy_mid_3_winrate,synergy_mid_3_games,synergy_mid_3_lane_quality,synergy_mid_4_name,synergy_mid_4_winrate,synergy_mid_4_games,synergy_mid_4_lane_quality,synergy_mid_5_name,synergy_mid_5_winrate,synergy_mid_5_games,synergy_mid_5_lane_quality,synergy_mid_6_name,synergy_mid_6_winrate,synergy_mid_6_games,synergy_mid_6_lane_quality,synergy_mid_7_name,synergy_mid_7_winrate,synergy_mid_7_games,synergy_mid_7_lane_quality,synergy_mid_8_name,synergy_mid_8_winrate,synergy_mid_8_games,synergy_mid_8_lane_quality,synergy_mid_9_name,synergy_mid_9_winrate,synergy_mid_9_games,synergy_mid_9_lane_quality,synergy_mid_10_name,synergy_mid_10_winrate,synergy_mid_10_games,synergy_mid_10_lane_quality,synergy_mid_11_name,synergy_mid_11_winrate,synergy_mid_11_games,synergy_mid_11_lane_quality,synergy_mid_12_name,synergy_mid_12_winrate,synergy_mid_12_games,synergy_mid_12_lane_quality,synergy_mid_13_name,synergy_mid_13_winrate,synergy_mid_13_games,synergy_mid_13_lane_quality,synergy_mid_14_name,synergy_mid_14_winrate,synergy_mid_14_games,synergy_mid_14_lane_quality,synergy_mid_15_name,synergy_mid_15_winrate,synergy_mid_15_games,synergy_mid_15_lane_quality,synergy_mid_16_name,synergy_mid_16_winrate,synergy_mid_16_games,synergy_mid_16_lane_quality,synergy_mid_17_name,synergy_mid_17_winrate,synergy_mid_17_games,synergy_mid_17_lane_quality,synergy_mid_18_name,synergy_mid_18_winrate,synergy_mid_18_games,synergy_mid_18_lane_quality,synergy_mid_19_name,synergy_mid_19_winrate,synergy_mid_19_games,synergy_mid_19_lane_quality,synergy_mid_20_name,synergy_mid_20_winrate,synergy_mid_20_games,synergy_mid_20_lane_quality,synergy_mid_21_name,synergy_mid_21_winrate,synergy_mid_21_games,synergy_mid_21_lane_quality,synergy_mid_22_name,synergy_mid_22_winrate,synergy_mid_22_games,synergy_mid_22_lane_quality,synergy_mid_23_name,synergy_mid_23_winrate,synergy_mid_23_games,synergy_mid_23_lane_quality,synergy_mid_24_name,synergy_mid_24_winrate,synergy_mid_24_games,synergy_mid_24_lane_quality,synergy_mid_25_name,synergy_mid_25_winrate,synergy_mid_25_games,synergy_mid_25_lane_quality,synergy_mid_26_name,synergy_mid_26_winrate,synergy_mid_26_games,synergy_mid_26_lane_quality,synergy_mid_27_name,synergy_mid_27_winrate,synergy_mid_27_games,synergy_mid_27_lane_quality,synergy_mid_28_name,synergy_mid_28_winrate,synergy_mid_28_games,synergy_mid_28_lane_quality,synergy_mid_29_name,synergy_mid_29_winrate,synergy_mid_29_games,synergy_mid_29_lane_quality,synergy_mid_30_name,synergy_mid_30_winrate,synergy_mid_30_games,synergy_mid_30_lane_quality,synergy_mid_31_name,synergy_mid_31_winrate,synergy_mid_31_games,synergy_mid_31_lane_quality,synergy_mid_32_name,synergy_mid_32_winrate,synergy_mid_32_games,synergy_mid_32_lane_quality,synergy_mid_33_name,synergy_mid_33_winrate,synergy_mid_33_games,synergy_mid_33_lane_quality,synergy_mid_34_name,synergy_mid_34_winrate,synergy_mid_34_games,synergy_mid_34_lane_quality,synergy_mid_35_name,synergy_mid_35_winrate,synergy_mid_35_games,synergy_mid_35_lane_quality,synergy_mid_36_name,synergy_mid_36_winrate,synergy_mid_36_games,synergy_mid_36_lane_quality,synergy_mid_37_name,synergy_mid_37_winrate,synergy_mid_37_games,synergy_mid_37_lane_quality,synergy_mid_38_name,synergy_mid_38_winrate,synergy_mid_38_games,synergy_mid_38_lane_quality,synergy_mid_39_name,synergy_mid_39_winrate,synergy_mid_39_games,synergy_mid_39_lane_quality,synergy_mid_40_name,synergy_mid_40_winrate,synergy_mid_40_games,synergy_mid_40_lane_quality,synergy_mid_41_name,synergy_mid_41_winrate,synergy_mid_41_games,synergy_mid_41_lane_quality,synergy_mid_42_name,synergy_mid_42_winrate,synergy_mid_42_games,synergy_mid_42_lane_quality,synergy_mid_43_name,synergy_mid_43_winrate,synergy_mid_43_games,synergy_mid_43_lane_quality,synergy_mid_44_name,synergy_mid_44_winrate,synergy_mid_44_games,synergy_mid_44_lane_quality,synergy_mid_45_name,synergy_mid_45_winrate,synergy_mid_45_games,synergy_mid_45_lane_quality,synergy_mid_46_name,synergy_mid_46_winrate,synergy_mid_46_games,synergy_mid_46_lane_quality,synergy_mid_47_name,synergy_mid_47_winrate,synergy_mid_47_games,synergy_mid_47_lane_quality,synergy_mid_48_name,synergy_mid_48_winrate,synergy_mid_48_games,synergy_mid_48_lane_quality,synergy_mid_49_name,synergy_mid_49_winrate,synergy_mid_49_games,synergy_mid_49_lane_quality,synergy_mid_50_name,synergy_mid_50_winrate,synergy_mid_50_games,synergy_mid_50_lane_quality,synergy_mid_51_name,synergy_mid_51_winrate,synergy_mid_51_games,synergy_mid_51_lane_quality,synergy_mid_52_name,synergy_mid_52_winrate,synergy_mid_52_games,synergy_mid_52_lane_quality,synergy_mid_53_name,synergy_mid_53_winrate,synergy_mid_53_games,synergy_mid_53_lane_quality,synergy_mid_54_name,synergy_mid_54_winrate,synergy_mid_54_games,synergy_mid_54_lane_quality,synergy_mid_55_name,synergy_mid_55_winrate,synergy_mid_55_games,synergy_mid_55_lane_quality,synergy_mid_56_name,synergy_mid_56_winrate,synergy_mid_56_games,synergy_mid_56_lane_quality,synergy_mid_57_name,synergy_mid_57_winrate,synergy_mid_57_games,synergy_mid_57_lane_quality,synergy_mid_58_name,synergy_mid_58_winrate,synergy_mid_58_games,synergy_mid_58_lane_quality,synergy_mid_59_name,synergy_mid_59_winrate,synergy_mid_59_games,synergy_mid_59_lane_quality,synergy_mid_60_name,synergy_mid_60_winrate,synergy_mid_60_games,synergy_mid_60_lane_quality,synergy_mid_61_name,synergy_mid_61_winrate,synergy_mid_61_games,synergy_mid_61_lane_quality,synergy_mid_62_name,synergy_mid_62_winrate,synergy_mid_62_games,synergy_mid_62_lane_quality,synergy_mid_63_name,synergy_mid_63_winrate,synergy_mid_63_games,synergy_mid_63_lane_quality,synergy_mid_64_name,synergy_mid_64_winrate,synergy_mid_64_games,synergy_mid_64_lane_quality,synergy_mid_65_name,synergy_mid_65_winrate,synergy_mid_65_games,synergy_mid_65_lane_quality,synergy_mid_66_name,synergy_mid_66_winrate,synergy_mid_66_games,synergy_mid_66_lane_quality,synergy_mid_67_name,synergy_mid_67_winrate,synergy_mid_67_games,synergy_mid_67_lane_quality,synergy_mid_68_name,synergy_mid_68_winrate,synergy_mid_68_games,synergy_mid_68_lane_quality,synergy_sup_1_name,synergy_sup_1_winrate,synergy_sup_1_games,synergy_sup_1_lane_quality,synergy_sup_2_name,synergy_sup_2_winrate,synergy_sup_2_games,synergy_sup_2_lane_quality,synergy_sup_3_name,synergy_sup_3_winrate,synergy_sup_3_games,synergy_sup_3_lane_quality,synergy_sup_4_name,synergy_sup_4_winrate,synergy_sup_4_games,synergy_sup_4_lane_quality,synergy_sup_5_name,synergy_sup_5_winrate,synergy_sup_5_games,synergy_sup_5_lane_quality,synergy_sup_6_name,synergy_sup_6_winrate,synergy_sup_6_games,synergy_sup_6_lane_quality,synergy_sup_7_name,synergy_sup_7_winrate,synergy_sup_7_games,synergy_sup_7_lane_quality,synergy_sup_8_name,synergy_sup_8_winrate,synergy_sup_8_games,synergy_sup_8_lane_quality,synergy_sup_9_name,synergy_sup_9_winrate,synergy_sup_9_games,synergy_sup_9_lane_quality,synergy_sup_10_name,synergy_sup_10_winrate,synergy_sup_10_games,synergy_sup_10_lane_quality,synergy_sup_11_name,synergy_sup_11_winrate,synergy_sup_11_games,synergy_sup_11_lane_quality,synergy_sup_12_name,synergy_sup_12_winrate,synergy_sup_12_games,synergy_sup_12_lane_quality,synergy_sup_13_name,synergy_sup_13_winrate,synergy_sup_13_games,synergy_sup_13_lane_quality,synergy_sup_14_name,synergy_sup_14_winrate,synergy_sup_14_games,synergy_sup_14_lane_quality,synergy_sup_15_name,synergy_sup_15_winrate,synergy_sup_15_games,synergy_sup_15_lane_quality,synergy_sup_16_name,synergy_sup_16_winrate,synergy_sup_16_games,synergy_sup_16_lane_quality,synergy_sup_17_name,synergy_sup_17_winrate,synergy_sup_17_games,synergy_sup_17_lane_quality,synergy_sup_18_name,synergy_sup_18_winrate,synergy_sup_18_games,synergy_sup_18_lane_quality,synergy_sup_19_name,synergy_sup_19_winrate,synergy_sup_19_games,synergy_sup_19_lane_quality,synergy_sup_20_name,synergy_sup_20_winrate,synergy_sup_20_games,synergy_sup_20_lane_quality,synergy_sup_21_name,synergy_sup_21_winrate,synergy_sup_21_games,synergy_sup_21_lane_quality,synergy_sup_22_name,synergy_sup_22_winrate,synergy_sup_22_games,synergy_sup_22_lane_quality,synergy_sup_23_name,synergy_sup_23_winrate,synergy_sup_23_games,synergy_sup_23_lane_quality,synergy_sup_24_name,synergy_sup_24_winrate,synergy_sup_24_games,synergy_sup_24_lane_quality,synergy_sup_25_name,synergy_sup_25_winrate,synergy_sup_25_games,synergy_sup_25_lane_quality,synergy_sup_26_name,synergy_sup_26_winrate,synergy_sup_26_games,synergy_sup_26_lane_quality,synergy_sup_27_name,synergy_sup_27_winrate,synergy_sup_27_games,synergy_sup_27_lane_quality,synergy_sup_28_name,synergy_sup_28_winrate,synergy_sup_28_games,synergy_sup_28_lane_quality,synergy_sup_29_name,synergy_sup_29_winrate,synergy_sup_29_games,synergy_sup_29_lane_quality,synergy_sup_30_name,synergy_sup_30_winrate,synergy_sup_30_games,synergy_sup_30_lane_quality,synergy_sup_31_name,synergy_sup_31_winrate,synergy_sup_31_games,synergy_sup_31_lane_quality,synergy_sup_32_name,synergy_sup_32_winrate,synergy_sup_32_games,synergy_sup_32_lane_quality,synergy_sup_33_name,synergy_sup_33_winrate,synergy_sup_33_games,synergy_sup_33_lane_quality,synergy_sup_34_name,synergy_sup_34_winrate,synergy_sup_34_games,synergy_sup_34_lane_quality,synergy_sup_35_name,synergy_sup_35_winrate,synergy_sup_35_games,synergy_sup_35_lane_quality,synergy_sup_36_name,synergy_sup_36_winrate,synergy_sup_36_games,synergy_sup_36_lane_quality,synergy_sup_37_name,synergy_sup_37_winrate,synergy_sup_37_games,synergy_sup_37_lane_quality,synergy_sup_38_name,synergy_sup_38_winrate,synergy_sup_38_games,synergy_sup_38_lane_quality,synergy_sup_39_name,synergy_sup_39_winrate,synergy_sup_39_games,synergy_sup_39_lane_quality,synergy_sup_40_name,synergy_sup_40_winrate,synergy_sup_40_games,synergy_sup_40_lane_quality,synergy_sup_41_name,synergy_sup_41_winrate,synergy_sup_41_games,synergy_sup_41_lane_quality,synergy_sup_42_name,synergy_sup_42_winrate,synergy_sup_42_games,synergy_sup_42_lane_quality,synergy_sup_43_name,synergy_sup_43_winrate,synergy_sup_43_games,synergy_sup_43_lane_quality,synergy_sup_44_name,synergy_sup_44_winrate,synergy_sup_44_games,synergy_sup_44_lane_quality,synergy_sup_45_name,synergy_sup_45_winrate,synergy_sup_45_games,synergy_sup_45_lane_quality,synergy_sup_46_name,synergy_sup_46_winrate,synergy_sup_46_games,synergy_sup_46_lane_quality,synergy_sup_47_name,synergy_sup_47_winrate,synergy_sup_47_games,synergy_sup_47_lane_quality,synergy_sup_48_name,synergy_sup_48_winrate,synergy_sup_48_games,synergy_sup_48_lane_quality,synergy_sup_49_name,synergy_sup_49_winrate,synergy_sup_49_games,synergy_sup_49_lane_quality,synergy_sup_50_name,synergy_sup_50_winrate,synergy_sup_50_games,synergy_sup_50_lane_quality,synergy_sup_51_name,synergy_sup_51_winrate,synergy_sup_51_games,synergy_sup_51_lane_quality,synergy_sup_52_name,synergy_sup_52_winrate,synergy_sup_52_games,synergy_su

In [89]:
############################### resructuration de matchups_df

In [ ]:
# champion                                                                                                          Nami
# role                                                                                                               sup
# role_play_ratio                                                                                                  99.8%
# tier                                                                                                                S+
# rank                                                                                                            2 / 39
# winrate                                                                                                         52.3 %
# pickrate                                                                                                        10.4 %
# banrate                                                                                                          2.2 %
# nb_games_analyzed                                                                                            2491832.0

In [32]:
import pandas as pd

def reformat_matchups(matchups_df):
    result_rows = []

    # les lanes de matchups
    lanes = ["adc", "jun", "mid", "sup", "top"]

    for _, row in matchups_df.iterrows():
        champion = row["champion"]
        role = row["role"]

        for lane in lanes:
            # récupérer toutes les colonnes correspondant à cette lane
            lane_cols = [col for col in matchups_df.columns if col.startswith(f"matchup_{lane}_")]
            n_matchups = len(lane_cols) // 4  # chaque matchup a 4 colonnes

            for i in range(1, n_matchups + 1):
                name_col = f"matchup_{lane}_{i}_name"
                winrate_col = f"matchup_{lane}_{i}_winrate"
                games_col = f"matchup_{lane}_{i}_games"
                lane_quality_col = f"matchup_{lane}_{i}_lane_quality"

                if pd.notna(row.get(name_col)):
                    result_rows.append({
                        "champion": champion,
                        "role": role,
                        "role_matchup": lane,
                        "matchup_name": row.get(name_col),
                        "matchup_winrate": row.get(winrate_col),
                        "matchup_games": row.get(games_col),
                        "matchup_lane_quality": row.get(lane_quality_col),
                        "role_play_ratio": row["role_play_ratio"],
                        "tier": row["tier"],
                        "winrate": row["winrate"],
                        "pickrate": row["pickrate"],
                        "banrate": row["banrate"],
                        "nb_games_analyzed": row["nb_games_analyzed"]
                    })

    df_long = pd.DataFrame(result_rows)
    return df_long

In [33]:
df_matchups_long = reformat_matchups(matchups_df)
df_matchups_long.head()

,champion,role,role_matchup,matchup_name,matchup_winrate,matchup_games,matchup_lane_quality,role_play_ratio,tier,winrate,pickrate,banrate,nb_games_analyzed
0,Nami,sup,adc,Corki,56.34%,16110.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832.0
1,Nami,sup,adc,Kalista,55.53%,16231.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832.0
2,Nami,sup,adc,Varus,55.37%,44692.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832.0
3,Nami,sup,adc,Yunara,55.03%,80587.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832.0
4,Nami,sup,adc,Ezreal,54.82%,115928.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832.0

In [34]:
df_matchups_long.shape

(52156, 13)

In [101]:
# matchups_df[matchups_df["champion"] == "Aatrox"]

In [100]:
# df_matchups_long[df_matchups_long["champion"] == "Aatrox"]

In [35]:
import pandas as pd

def reformat_synergies(synergies_df):
    result_rows = []

    # les lanes de synergies
    lanes = ["adc", "jun", "mid", "sup", "top"]

    for _, row in synergies_df.iterrows():
        champion = row["champion"]
        role = row["role"]

        for lane in lanes:
            # récupérer toutes les colonnes correspondant à cette lane
            lane_cols = [col for col in synergies_df.columns if col.startswith(f"synergy_{lane}_")]
            n_synergies = len(lane_cols) // 4  # chaque synergy a 4 colonnes

            for i in range(1, n_synergies + 1):
                name_col = f"synergy_{lane}_{i}_name"
                winrate_col = f"synergy_{lane}_{i}_winrate"
                games_col = f"synergy_{lane}_{i}_games"
                lane_quality_col = f"synergy_{lane}_{i}_lane_quality"

                if pd.notna(row.get(name_col)):
                    result_rows.append({
                        "champion": champion,
                        "role": role,
                        "role_synergy": lane,
                        "synergy_name": row.get(name_col),
                        "synergy_winrate": row.get(winrate_col),
                        "synergy_games": row.get(games_col),
                        "synergy_lane_quality": row.get(lane_quality_col),
                        "role_play_ratio": row["role_play_ratio"],
                        "tier": row["tier"],
                        "winrate": row["winrate"],
                        "pickrate": row["pickrate"],
                        "banrate": row["banrate"],
                        "nb_games_analyzed": row["nb_games_analyzed"]
                    })

    df_long = pd.DataFrame(result_rows)
    return df_long

In [36]:
df_synergies_long = reformat_synergies(synergies_df)
df_synergies_long.head()

,champion,role,role_synergy,synergy_name,synergy_winrate,synergy_games,synergy_lane_quality,role_play_ratio,tier,winrate,pickrate,banrate,nb_games_analyzed
0,Nami,sup,adc,Swain,57.70%,16008.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832
1,Nami,sup,adc,Brand,57.16%,19397.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832
2,Nami,sup,adc,Veigar,56.16%,6063.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832
3,Nami,sup,adc,Yasuo,55.67%,15984.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832
4,Nami,sup,adc,Smolder,54.92%,152845.0,NaN,99.8%,S+,52.3 %,10.4 %,2.2 %,2491832

In [33]:
df_synergies_long.shape

(42854, 13)

In [37]:
df_synergies_long.champion.unique()

array(['Nami', 'Dr.Mundo', 'Viego', 'Jax', 'Kled', 'Anivia', 'Vladimir',
       'Pyke', 'Heimerdinger', 'Lillia', 'Seraphine', 'Ekko', 'Irelia',
       'Aatrox', 'Zilean', 'Aurelion Sol', 'Maokai', 'Wukong', 'Kassadin',
       'Leblanc', 'Trundle', 'Bard', "Cho'Gath", 'Poppy', 'Vayne', 'Ornn',
       'Akali', 'Xin Zhao', 'Yasuo', 'Yone', 'Zaahen', 'Elise', 'Olaf',
       'Shyvana', 'Renekton', 'Fiddlesticks', 'LeeSin', 'Graves', 'Mel',
       "Kha'Zix", 'Fiora', 'Shen', 'Malphite', 'Tahm Kench', 'Galio',
       'Mordekaiser', 'Warwick', 'Volibear', 'Hwei', 'Lissandra', 'Jayce',
       'Quinn', 'Cassiopeia', 'Zac', 'Nunu', 'Zed', 'Ziggs', 'Ivern',
       'Renata', 'Kennen', 'Evelynn', 'Udyr', 'Pantheon', 'Sejuani',
       'Ambessa', 'Talon', 'Naafiri', 'Rell', 'Senna', 'Riven',
       "Bel'Veth", 'Annie', 'Gwen', 'Rakan', 'Akshan', 'Tryndamere',
       'Twisted Fate', 'Orianna', 'Ryze', 'Aurora', 'Alistar', 'Gnar',
       'Zoe', 'Yuumi', 'Vi', 'Kindred', 'Morgana', 'Teemo', 'Lux',
       'Amumu', "Rek'Sai", 'Hecarim', 'Smolder', 'Neeko', 'Qiyana',
       'Karthus', 'Rumble', 'Camille', 'Gangplank', 'Gragas', 'Taliyah',
       'Rengar', 'Nidalee', 'Ashe', "K'Sante", 'Azir', 'Garen', 'Sett',
       'Yorick', 'Leona', 'Diana', 'Swain', 'Master Yi', 'Fizz', 'Brand',
       'Zyra', 'Ahri', 'Veigar', 'Kayn', 'Briar', 'Malzahar', 'Milio',
       'Rammus', 'Kayle', 'Soraka', 'Nautilus', 'Shaco', 'Xerath',
       'Singed', 'Urgot', 'Viktor', 'Taric', 'Thresh', 'Darius', 'Illaoi',
       'Sona', 'Sylas', 'Katarina', 'Sion', 'Janna', 'Nocturne', 'Syndra',
       "Vel'Koz", 'Lulu', 'Braum', 'Nasus', 'Blitzcrank', 'Jarvan IV',
       'Karma', 'Vex', 'Twitch', 'Sivir', 'Ezreal', 'Draven', 'Lucian',
       'Xayah', 'Zeri', 'Yunara', 'Varus', 'Kalista', 'Corki', 'Jinx',
       'Caitlyn', 'Jhin', 'Miss Fortune', 'Nilah', 'Samira', "Kai'Sa",
       "Kog'Maw", 'Tristana', 'Aphelios'], dtype=object)

In [38]:
import pandas as pd

# Ajouter la colonne 'type' à chaque df
df_matchups_long['type'] = 'matchup'
df_synergies_long['type'] = 'synergy'

# Pour que les colonnes correspondent, renommer les colonnes pour être identiques
df_matchups_renamed = df_matchups_long.rename(columns={
    'role_matchup': 'role_interaction',
    'matchup_name': 'interaction_name',
    'matchup_winrate': 'interaction_winrate',
    'matchup_games': 'interaction_games',
    'matchup_lane_quality': 'interaction_lane_quality'
})

df_synergies_renamed = df_synergies_long.rename(columns={
    'role_synergy': 'role_interaction',
    'synergy_name': 'interaction_name',
    'synergy_winrate': 'interaction_winrate',
    'synergy_games': 'interaction_games',
    'synergy_lane_quality': 'interaction_lane_quality'
})

# Concaténer les deux df
df_synergy_matchup_long = pd.concat([df_matchups_renamed, df_synergies_renamed], ignore_index=True)

# Optionnel : trier par champion, role et type
df_synergy_matchup_long = df_synergy_matchup_long.sort_values(by=['champion', 'role', 'type']).reset_index(drop=True)

print(df_synergy_matchup_long.head(10))

  champion role role_interaction interaction_name interaction_winrate  \
0   Aatrox  jun              adc            Varus              52.74%
1   Aatrox  jun              adc            Corki              52.64%
2   Aatrox  jun              adc           Yunara              51.39%
3   Aatrox  jun              adc           Ezreal              51.03%
4   Aatrox  jun              adc          Kalista              50.90%
5   Aatrox  jun              adc           Draven              50.62%
6   Aatrox  jun              adc              Mel              50.42%
7   Aatrox  jun              adc             Zeri              50.32%
8   Aatrox  jun              adc            Kaisa              50.31%
9   Aatrox  jun              adc           Lucian              50.05%

   interaction_games interaction_lane_quality role_play_ratio tier winrate  \
0            17535.0                      NaN           37.1%  NaN  49.0 %
1             5579.0                      NaN           37.1%  NaN  49.0 %
2            33097.0                      NaN           37.1%  NaN  49.0 %
3            50551.0                      NaN           37.1%  NaN  49.0 %
4             6544.0                      NaN           37.1%  NaN  49.0 %
5            15535.0                      NaN           37.1%  NaN  49.0 %
6             4843.0                      NaN           37.1%  NaN  49.0 %
7            13029.0                      NaN           37.1%  NaN  49.0 %
8            73758.0                      NaN           37.1%  NaN  49.0 %
9            36753.0                      NaN           37.1%  NaN  49.0 %

  pickrate banrate  nb_games_analyzed     type
0    3.4 %  10.7 %                NaN  matchup
1    3.4 %  10.7 %                NaN  matchup
2    3.4 %  10.7 %                NaN  matchup
3    3.4 %  10.7 %                NaN  matchup
4    3.4 %  10.7 %                NaN  matchup
5    3.4 %  10.7 %                NaN  matchup
6    3.4 %  10.7 %                NaN  matchup
7    3.4 %  10.7 %                NaN  matchup
8    3.4 %  10.7 %                NaN  matchup
9    3.4 %  10.7 %                NaN  matchup

In [36]:
df_synergy_matchup_long.shape

(95010, 14)

In [39]:
df_result[df_result["blue_support_tags"].isna()]["blue_support_champion"].unique()

array([nan], dtype=object)

In [40]:
import re

def normalize_champion_name(name: str) -> str:
    if pd.isna(name):
        return name

    # minuscules
    name = name.lower()

    # supprimer apostrophes, points, espaces, tirets
    name = re.sub(r"[ '\.\-]", "", name)

    # mapping des exceptions Riot
    exceptions = {
        "masteryi": "maitreyi",
        "nunu": "nunuetwillump",
        "renata": "renataglasc"
    }

    return exceptions.get(name, name)

In [41]:
df_synergy_matchup_long["champion"] = df_synergy_matchup_long["champion"].apply(normalize_champion_name)
df_synergy_matchup_long["interaction_name"] = df_synergy_matchup_long["interaction_name"].apply(normalize_champion_name)

In [42]:
df_synergy_matchup_long.head()

,champion,role,role_interaction,interaction_name,interaction_winrate,interaction_games,interaction_lane_quality,role_play_ratio,tier,winrate,pickrate,banrate,nb_games_analyzed,type
0,aatrox,jun,adc,varus,52.74%,17535.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup
1,aatrox,jun,adc,corki,52.64%,5579.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup
2,aatrox,jun,adc,yunara,51.39%,33097.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup
3,aatrox,jun,adc,ezreal,51.03%,50551.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup
4,aatrox,jun,adc,kalista,50.90%,6544.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup

In [ ]:
################################### on a cleanné les winrates matchups. maintenant, ajoutons la donnée de simple winrate apres l'avoir nettoyée.

In [ ]:
# attends déjà on va reformater winrate matchup et synergy. ensuite,

on va concatenner winrates simple de TOUTTOUT15.24 
puis on va associer df_result avec df_winrates simple sur le bon patch, elos et serveurs,
puis on va ssocier df_result avec df_winrates_matchup

il faudra choisir les bons patchs, elos et serveurs. il faudra aussi nettoyer les noms pour bien faire matcher.

In [43]:
df_simple_wr.head()

,elo,server,patch,label,name,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,TOUT,TOUT,16.3,1,briar,jun,91.1%,S+,52.8%,+1.5%,6.7%,599 576
1,TOUT,TOUT,16.3,2,missfortune,adc,97.0%,S+,51.7%,-0.0%,15.5%,1 386 160
2,TOUT,TOUT,16.3,3,malzahar,mid,92.2%,S+,52.3%,+0.0%,8.1%,724 180
3,TOUT,TOUT,16.3,4,swain,adc,18.6%,S+,54.6%,-0.1%,1.7%,154 988
4,TOUT,TOUT,16.3,5,jinx,adc,99.5%,S+,51.6%,-0.2%,16.6%,1 485 175

In [43]:
df_simple_wr["name"] = df_simple_wr["name"].apply(normalize_champion_name)

In [44]:
def build_extended_synergy_df(df_synergy_matchup_long, df_simple_wr):

    df_simple = df_simple_wr.copy()

    # nettoyage
    for col in ["elo", "server", "patch", "name", "role"]:
        df_simple[col] = df_simple[col].astype(str).str.strip().str.lower()

    df_synergy = df_synergy_matchup_long.copy()
    for col in ["champion", "role"]:
        df_synergy[col] = df_synergy[col].astype(str).str.strip().str.lower()

    # filtrage
    df_simple = df_simple[
        (df_simple["elo"] == "tout") &
        (df_simple["server"] == "tout") &
        (df_simple["patch"] == "15.24")
    ]

    # merge sur champion + role
    df_extended = df_synergy.merge(
        df_simple,
        left_on=["champion", "role"],
        right_on=["name", "role"],
        how="left",
        suffixes=("", "_simple_wr")
    )

    return df_extended

In [45]:
df_synergy_matchup_long_extended = build_extended_synergy_df(
    df_synergy_matchup_long,
    df_simple_wr
)

In [46]:
df_synergy_matchup_long_extended.head()

,champion,role,role_interaction,interaction_name,interaction_winrate,interaction_games,interaction_lane_quality,role_play_ratio,tier,winrate,pickrate,banrate,nb_games_analyzed,type,elo,server,patch,label,name,role_pickrate,tier_simple_wr,winrate_simple_wr,winrate_evol,pickrate_simple_wr,games
0,aatrox,jun,adc,varus,52.74%,17535.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup,tout,tout,15.24,123.0,aatrox,37.1%,C,49.0%,-0.0%,3.4%,816 833
1,aatrox,jun,adc,corki,52.64%,5579.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup,tout,tout,15.24,123.0,aatrox,37.1%,C,49.0%,-0.0%,3.4%,816 833
2,aatrox,jun,adc,yunara,51.39%,33097.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup,tout,tout,15.24,123.0,aatrox,37.1%,C,49.0%,-0.0%,3.4%,816 833
3,aatrox,jun,adc,ezreal,51.03%,50551.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup,tout,tout,15.24,123.0,aatrox,37.1%,C,49.0%,-0.0%,3.4%,816 833
4,aatrox,jun,adc,kalista,50.90%,6544.0,NaN,37.1%,NaN,49.0 %,3.4 %,10.7 %,NaN,matchup,tout,tout,15.24,123.0,aatrox,37.1%,C,49.0%,-0.0%,3.4%,816 833

In [ ]:
# attends déjà on va reformater winrate matchup et synergy. ensuite,

# on va concatenner winrates simple de TOUTTOUT15.24 
puis on va associer df_result avec df_winrates simple sur le bon patch, elos et serveurs,
puis on va ssocier df_result avec df_winrates_matchup

il faudra choisir les bons patchs, elos et serveurs. il faudra aussi nettoyer les noms pour bien faire matcher.

In [ ]:
# on a concatené wr simple et wr matchup. on va maintenant associer df result avec df_synergy_matchup_long_extended puis avec df_simple_wr en prenant le elo, server, patch qui correspond

In [47]:
df_result.head()

,match_id,serveur,patch,elo,blue_side_win,blue_top_champion,blue_jungle_champion,blue_mid_champion,blue_adc_champion,blue_support_champion,red_top_champion,red_jungle_champion,red_mid_champion,red_adc_champion,red_support_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags
0,EUW1_7517331727,euw1,15.17.708.5788,HIGH_ELO,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"[Fighter, Tank]",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,[Assassin],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"[Fighter, Assassin]",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,[Marksman],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"[Tank, Support]",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"[Fighter, Assassin]",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"[Mage, Support]",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,[Mage],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,[Marksman],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"[Support, Mage]"
1,EUW1_7509322616,euw1,15.17.706.7412,HIGH_ELO,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"[Fighter, Mage]",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,[Assassin],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"[Fighter, Assassin]",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"[Marksman, Mage]",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"[Support, Mage]",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,[Fighter],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"[Fighter, Tank]",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,[Mage],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"[Support, Marksman]",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"[Support, Mage]"
2,EUW1_7509243675,euw1,15.17.706.7412,HIGH_ELO,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"[Marksman, Mage]",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,[Marksman],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"[Tank, Mage]",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"[Support, Mage]",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"[Marksman, Assassin]",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"[Fighter, Assassin]",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"[Mage, Support]",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"[Marksman, Mage]",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,[Support]
3,EUW1_7509193063,euw1,15.17.706.7412,HIGH_ELO,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"[Fighter, Tank]",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"[Assassin, Mage]",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,[Assassin],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,[Support],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"[Tank, Mage]",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"[Fighter, Tank]",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"[Mage, Support]",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"[Marksman, Mage]",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"[Support, Mage]"
4,EUW1_7508909082,euw1,15.17.706.7412,HIGH_ELO,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio,3.0,4.0,5.0,8.0,23.0,4.5,53.0,3.00,550.0,0.668,2.00,0.0,0.0,607.0,110.0,6.00,0.55,335.0,475.0,30.0,8.00,0.8,32.0,1.30,"[Mage, Assassin]",8.0,6.0,2.0,3.0,35.0,4.4,63.0,3.00,175.0,0.645,3.50,0.0,0.0,620.0,106.0,8.0,0.70,345.0,274.0,55.0,7.25,0.45,32.0,2.05,"[Fighter, Tank]",9.0,2.0,6.0,3.0,27.0,4.2,59.0,3.1,550.0,0.679,3.38,0.0,0.0,630.0,104.0,3.75,0.60,330.0,300.0,40.0,7.25,0.7,30.0,1.30,"[Marksman, Assassin]",9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,[Marksman],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,[Support],8.0,4.0,7.0,3.0,22.0,5.0,59.0,4.25,125.0,0.658,3.00,0.0,0.0,590.0,109.0,6.0,0.60,335.0,375.0,45.0,6.0,0.80,30.0,1.30,"[Fighter, Marksman]",8.0,5.0,2.0,1.0,33.0,4.70,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.0,0.50,340.0,0.0,0.0,0.0,0.00,28.0,2.05,"[Fighter, Tank]",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.0,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,[Assassin],8.0,5.0,6.0,3.0,28.0,4.2,60.0,2.9,500.0,0.638,3.3,0.0,0.0,641.0,100.0,3.75,0.65,335.0,320.0,43.0,7.0,0.8,30.0,1.3,"[Marksman, Assassin]",2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.0,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.40,30.0,1.30,"[Support, Mage]"

In [48]:
df_result.iloc[0:5, :15]

,match_id,serveur,patch,elo,blue_side_win,blue_top_champion,blue_jungle_champion,blue_mid_champion,blue_adc_champion,blue_support_champion,red_top_champion,red_jungle_champion,red_mid_champion,red_adc_champion,red_support_champion
0,EUW1_7517331727,euw1,15.17.708.5788,HIGH_ELO,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard
1,EUW1_7509322616,euw1,15.17.706.7412,HIGH_ELO,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard
2,EUW1_7509243675,euw1,15.17.706.7412,HIGH_ELO,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan
3,EUW1_7509193063,euw1,15.17.706.7412,HIGH_ELO,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona
4,EUW1_7508909082,euw1,15.17.706.7412,HIGH_ELO,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio

In [49]:
print(df_result["serveur"].unique())
print(df_result["patch"].unique())
print(df_result["elo"].unique())

['euw1' 'kr' 'eun1']
['15.17.708.5788' '15.17.706.7412' '15.16.706.7476' '15.17.708.2856'
 '15.15.701.6241' '15.15.699.7589' '15.14.697.2104' '15.16.704.6097'
 '15.16.704.3186' '15.18.710.2811' '15.21.721.8442' '15.22.723.8534'
 '15.20.719.545' '15.19.715.1836' '15.19.714.7225' '15.21.721.4012'
 '15.20.717.2831' '15.22.723.1955' '15.21.720.925' '15.13.693.4876'
 '15.13.692.4165' '15.13.691.9951' '15.12.688.6522' '15.19.713.5912'
 '15.11.685.5259' '15.10.680.4378' '15.23.728.3286' '15.22.724.5161'
 '15.23.726.9074' '15.14.695.3589' '15.21.721.583' '15.16.702.7993'
 '15.11.684.1658' '15.9.678.1456' '15.8.675.10' '15.7.669.24'
 '15.3.656.4086' '15.3.654.407' '15.16.704.1925' '15.7.672.4034'
 '15.6.668.2516' '15.9.678.398' '15.8.674.8619' '15.6.667.3303'
 '15.24.730.505' '15.9.677.4704' '15.7.670.3172' '15.17.707.9808'
 '15.24.730.7955' '15.5.662.6652' '15.5.661.4445' '15.4.657.5386'
 '15.6.664.9480' '15.13.693.1306' '15.2.652.1536' '15.8.673.8244'
 '15.1.649.4112' '15.6.666.5757' '15.24.731.2566' '15.24.731.5210'
 '15.24.732.64' '15.24.733.5841' '15.24.733.6673' '15.24.734.7485']
['HIGH_ELO' 'UNKNOWN' 'CHALLENGER' 'GRANDMASTER' 'MASTER' 'DIAMOND']

In [51]:
df_simple_wr.head()

,elo,server,patch,label,name,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,TOUT,TOUT,16.3,1,briar,jun,91.1%,S+,52.8%,+1.5%,6.7%,599 576
1,TOUT,TOUT,16.3,2,missfortune,adc,97.0%,S+,51.7%,-0.0%,15.5%,1 386 160
2,TOUT,TOUT,16.3,3,malzahar,mid,92.2%,S+,52.3%,+0.0%,8.1%,724 180
3,TOUT,TOUT,16.3,4,swain,adc,18.6%,S+,54.6%,-0.1%,1.7%,154 988
4,TOUT,TOUT,16.3,5,jinx,adc,99.5%,S+,51.6%,-0.2%,16.6%,1 485 175

In [50]:
print(df_simple_wr["server"].unique())
print(df_simple_wr["patch"].unique())
print(df_simple_wr["elo"].unique())

['TOUT' nan 'KR' 'EUW' 'VN']
[16.3  15.24]
['TOUT' 'Bronze' 'Grandmaster' 'Challenger']

In [51]:
def normalize_columns_and_values(df_result, df_simple_wr):
    import pandas as pd

    # --- Normaliser les noms de colonnes ---
    df_result = df_result.rename(columns={
        "serveur": "server",
        "blue_top_champion": "blue_top_champion",
        "blue_jungle_champion": "blue_jun_champion",
        "blue_mid_champion": "blue_mid_champion",
        "blue_adc_champion": "blue_adc_champion",
        "blue_support_champion": "blue_sup_champion",
        "red_top_champion": "red_top_champion",
        "red_jungle_champion": "red_jun_champion",
        "red_mid_champion": "red_mid_champion",
        "red_adc_champion": "red_adc_champion",
        "red_support_champion": "red_sup_champion",
    })

    df_simple_wr = df_simple_wr.rename(columns={
        "server": "server",
        "name": "champion"
    })

    # --- Normaliser les valeurs textuelles (en minuscules et sans espaces) ---
    for df in [df_result, df_simple_wr]:
        for col in df.columns:
            if df[col].dtype == "object":
                df[col] = df[col].astype(str).str.lower().str.strip()

    # --- Uniformiser quelques valeurs spécifiques pour le merge ---
    # Serveur
    df_result["server"] = df_result["server"].replace({
        "euw1": "euw",
        "eun1": "eune",
        "kr": "kr"
    })

    # Elo
    # df_result["elo"] = df_result["elo"].replace({
    #     "high_elo": "tout",
    #     "unknown": "tout"
    # })

    # Patch
    df_result["patch"] = df_result["patch"].str[:5]  # par exemple '15.17'
    df_result["patch"] = df_result["patch"].str.rstrip('.')

    return df_result, df_simple_wr

In [52]:
# Normalisation des colonnes et valeurs
df_result_norm, df_simple_wr_norm = normalize_columns_and_values(df_result, df_simple_wr)

In [53]:
print(df_result_norm["server"].unique())
print(df_result_norm["patch"].unique())
print(df_result_norm["elo"].unique())

print(df_simple_wr_norm["server"].unique())
print(df_simple_wr_norm["patch"].unique())
print(df_simple_wr_norm["elo"].unique())

['euw' 'kr' 'eune']
['15.17' '15.16' '15.15' '15.14' '15.18' '15.21' '15.22' '15.20' '15.19'
 '15.13' '15.12' '15.11' '15.10' '15.23' '15.9' '15.8' '15.7' '15.3'
 '15.6' '15.24' '15.5' '15.4' '15.2' '15.1']
['high_elo' 'unknown' 'challenger' 'grandmaster' 'master' 'diamond']
['tout' 'nan' 'kr' 'euw' 'vn']
[16.3  15.24]
['tout' 'bronze' 'grandmaster' 'challenger']

In [54]:
df_result_norm.head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']"
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']"
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support']
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']"
4,euw1_7508909082,euw,15.17,high_elo,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio,3.0,4.0,5.0,8.0,23.0,4.5,53.0,3.00,550.0,0.668,2.00,0.0,0.0,607.0,110.0,6.00,0.55,335.0,475.0,30.0,8.00,0.8,32.0,1.30,"['mage', 'assassin']",8.0,6.0,2.0,3.0,35.0,4.4,63.0,3.00,175.0,0.645,3.50,0.0,0.0,620.0,106.0,8.0,0.70,345.0,274.0,55.0,7.25,0.45,32.0,2.05,"['fighter', 'tank']",9.0,2.0,6.0,3.0,27.0,4.2,59.0,3.1,550.0,0.679,3.38,0.0,0.0,630.0,104.0,3.75,0.60,330.0,300.0,40.0,7.25,0.7,30.0,1.30,"['marksman', 'assassin']",9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],8.0,4.0,7.0,3.0,22.0,5.0,59.0,4.25,125.0,0.658,3.00,0.0,0.0,590.0,109.0,6.0,0.60,335.0,375.0,45.0,6.0,0.80,30.0,1.30,"['fighter', 'marksman']",8.0,5.0,2.0,1.0,33.0,4.70,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.0,0.50,340.0,0.0,0.0,0.0,0.00,28.0,2.05,"['fighter', 'tank']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.0,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],8.0,5.0,6.0,3.0,28.0,4.2,60.0,2.9,500.0,0.638,3.3,0.0,0.0,641.0,100.0,3.75,0.65,335.0,320.0,43.0,7.0,0.8,30.0,1.3,"['marksman', 'assassin']",2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.0,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.40,30.0,1.30,"['support', 'mage']"

In [55]:
df_simple_wr_norm.head()

,elo,server,patch,label,champion,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,tout,tout,16.3,1,briar,jun,91.1%,s+,52.8%,+1.5%,6.7%,599 576
1,tout,tout,16.3,2,missfortune,adc,97.0%,s+,51.7%,-0.0%,15.5%,1 386 160
2,tout,tout,16.3,3,malzahar,mid,92.2%,s+,52.3%,+0.0%,8.1%,724 180
3,tout,tout,16.3,4,swain,adc,18.6%,s+,54.6%,-0.1%,1.7%,154 988
4,tout,tout,16.3,5,jinx,adc,99.5%,s+,51.6%,-0.2%,16.6%,1 485 175

In [ ]:
# def find_best_simple_wr_row(result_row, df_simple_wr_norm):
#     import pandas as pd
#     import numpy as np

#     server = result_row["server"]
#     patch = str(result_row["patch"])
#     elo = result_row["elo"]
#     champion = result_row["blue_top_champion"]

#     print("\n----------------------")
#     print("Recherche pour :", server, patch, elo, champion)

#     # garder seulement le champion
#     candidates = df_simple_wr_norm[df_simple_wr_norm["champion"] == champion].copy()

#     if candidates.empty:
#         print("❌ aucun champion correspondant")
#         return None

#     # ---------- SERVER SCORE ----------
#     candidates["server_score"] = 0
#     candidates.loc[candidates["server"] == server, "server_score"] = 3
#     candidates.loc[candidates["server"] == "tout", "server_score"] = 1

#     # ---------- ELO SCORE ----------
#     candidates["elo_score"] = 0
#     candidates.loc[candidates["elo"] == elo, "elo_score"] = 3
#     candidates.loc[candidates["elo"] == "tout", "elo_score"] = 1

#     # ---------- PATCH SCORE ----------
#     patch_float = float(patch)

#     candidates["patch_score"] = 0

#     # exact
#     candidates.loc[candidates["patch"].astype(str) == patch, "patch_score"] = 4

#     # même 15.17
#     patch_minor = ".".join(patch.split(".")[:2])
#     mask_minor = candidates["patch"].astype(str).str.startswith(patch_minor)
#     candidates.loc[(candidates["patch_score"] == 0) & mask_minor, "patch_score"] = 3

#     # même 15
#     patch_major = patch.split(".")[0]
#     mask_major = candidates["patch"].astype(str).str.startswith(patch_major)
#     candidates.loc[(candidates["patch_score"] == 0) & mask_major, "patch_score"] = 2

#     # patch distance
#     candidates["patch_distance"] = (
#         candidates["patch"].astype(float) - patch_float
#     ).abs()

#     candidates.loc[candidates["patch_score"] == 0, "patch_score"] = 1

#     # ---------- SCORE TOTAL ----------
#     candidates["score"] = (
#         candidates["server_score"]
#         + candidates["elo_score"]
#         + candidates["patch_score"]
#     )

#     # tri : meilleur score puis patch le plus proche
#     candidates = candidates.sort_values(
#         by=["score", "patch_distance"],
#         ascending=[False, True]
#     )

#     best_row = candidates.iloc[0]

#     print("✅ ligne choisie :")
#     print("server :", best_row["server"])
#     print("patch :", best_row["patch"])
#     print("elo :", best_row["elo"])
#     print("score :", best_row["score"])

#     return best_row

In [57]:
# row = df_result_norm.iloc[1]

# best_row = find_best_simple_wr_row(row, df_simple_wr_norm)
# print(best_row)

# # for index, row in best_row.iterrows():
# #     print("=======================")
# #     print(f"Row {index}:")
# #     print(row)

In [58]:
df_result_norm.iloc[0:1, :]

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.0,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.0,0.5,340.0,0.0,0.0,0.0,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.1,125.0,0.625,2.9,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.6,0.8,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.0,0.0,0.0,640.0,109.0,6.5,0.85,345.0,375.0,25.0,8.0,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.5,325.0,260.0,50.0,6.7,1.0,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.0,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.0,0.7,28.0,1.8,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.5,0.0,0.0,590.0,110.0,6.5,0.9,345.0,100.0,0.0,0.0,0.0,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.7,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.6,335.0,500.0,28.0,8.0,0.8,30.0,1.3,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.5,0.0,0.0,630.0,104.0,5.5,0.5,328.0,400.0,40.0,8.0,0.8,32.0,1.3,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.0,0.45,30.0,1.3,"['support', 'mage']"

In [ ]:
on arrive à retrouver la ligne de df_simple_wr pour 1 champion. maintenant on va retrouver les 10 lignes pour les 10 champions.

et ensuite, on va faire ca pour toutes les lignes du df

In [ ]:
# def build_champion_index(df_simple_wr_norm):
#     champion_index = {
#         champ: df.reset_index(drop=True)
#         for champ, df in df_simple_wr_norm.groupby("champion")
#     }
#     return champion_index

In [ ]:
# champion_index = build_champion_index(df_simple_wr_norm)

In [ ]:
PROBLEME DANS LE CODE QUI SUIT : EST-CE QUON RAMMENE UN WR SIMPLE MEME QUAND LE CHAMPION NEN A PAS (IL FAUT AJOUTER LA CONDITION BON ROLE)

In [ ]:
# def find_best_row_fast(server, patch, elo, champion, champion_index):

#     import numpy as np

#     if champion not in champion_index:
#         return None

#     candidates = champion_index[champion]

#     patch = str(patch)
#     patch_float = float(patch)

#     # SERVER SCORE
#     server_score = np.where(candidates["server"] == server, 3,
#                     np.where(candidates["server"] == "tout", 1, 0))

#     # ELO SCORE
#     elo_score = np.where(candidates["elo"] == elo, 3,
#                  np.where(candidates["elo"] == "tout", 1, 0))

#     # PATCH SCORE
#     patch_str = candidates["patch"].astype(str)

#     patch_score = np.zeros(len(candidates))

#     exact_mask = patch_str == patch
#     patch_score[exact_mask] = 4

#     minor = ".".join(patch.split(".")[:2])
#     minor_mask = patch_str.str.startswith(minor)
#     patch_score[(patch_score == 0) & minor_mask] = 3

#     major = patch.split(".")[0]
#     major_mask = patch_str.str.startswith(major)
#     patch_score[(patch_score == 0) & major_mask] = 2

#     patch_score[patch_score == 0] = 1

#     patch_distance = np.abs(candidates["patch"].astype(float) - patch_float)

#     total_score = server_score + elo_score + patch_score

#     best_idx = np.lexsort((patch_distance, -total_score))[0]

#     return candidates.iloc[best_idx]

In [ ]:
# def get_best_rows_for_game(row, champion_index):

#     server = row["server"]
#     patch = row["patch"]
#     elo = row["elo"]

#     champs = [
#         "blue_top_champion",
#         "blue_jun_champion",
#         "blue_mid_champion",
#         "blue_adc_champion",
#         "blue_sup_champion",
#         "red_top_champion",
#         "red_jun_champion",
#         "red_mid_champion",
#         "red_adc_champion",
#         "red_sup_champion",
#     ]

#     results = {}

#     for col in champs:

#         champ = row[col]

#         best = find_best_row_fast(server, patch, elo, champ, champion_index)

#         results[col] = best

#     return results

In [ ]:
# row = df_result_norm.iloc[0]

# best_rows = get_best_rows_for_game(row, champion_index)

In [66]:
# best_rows

In [ ]:
============================================================================================================================

In [ ]:
############### maintenant, pour tout le df_result_norm, on va ajouter les 10 lignes de df_simple_wr_norm correspondantes à chaque champion
# mais la methode n'est pas optimisée et prend genre 17h à s'éxecuter sur tout le dataframe.

In [ ]:
# def build_enhanced_dataframe(df_result_norm, champion_index):

#     import pandas as pd

#     df_result_norm = df_result_norm.copy()

#     champion_cols = [
#         "blue_top_champion",
#         "blue_jun_champion",
#         "blue_mid_champion",
#         "blue_adc_champion",
#         "blue_sup_champion",
#         "red_top_champion",
#         "red_jun_champion",
#         "red_mid_champion",
#         "red_adc_champion",
#         "red_sup_champion",
#     ]

#     enhanced_rows = []

#     for _, row in df_result_norm.iterrows():

#         best_rows = get_best_rows_for_game(row, champion_index)

#         new_data = {}

#         for champ_col, best_row in best_rows.items():

#             if best_row is None:
#                 continue

#             prefix = champ_col.replace("_champion", "")

#             for col, val in best_row.items():

#                 if col in ["champion"]:
#                     continue

#                 new_col = f"{prefix}_{col}"

#                 new_data[new_col] = val

#         enhanced_rows.append(new_data)

#     df_extra = pd.DataFrame(enhanced_rows)

#     df_enhanced = pd.concat(
#         [df_result_norm.reset_index(drop=True), df_extra],
#         axis=1
#     )

#     return df_enhanced

In [ ]:
# champion_index = build_champion_index(df_simple_wr_norm)

In [67]:
# df_enhanced = build_enhanced_dataframe(df_result_norm.iloc[:,:], champion_index)

In [ ]:
# df_enhanced.head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags,blue_top_elo,blue_top_server,blue_top_patch,blue_top_label,blue_top_role,blue_top_role_pickrate,blue_top_tier,blue_top_winrate,blue_top_winrate_evol,blue_top_pickrate,blue_top_games,blue_jun_elo,blue_jun_server,blue_jun_patch,blue_jun_label,blue_jun_role,blue_jun_role_pickrate,blue_jun_tier,blue_jun_winrate,blue_jun_winrate_evol,blue_jun_pickrate,blue_jun_games,blue_mid_elo,blue_mid_server,blue_mid_patch,blue_mid_label,blue_mid_role,blue_mid_role_pickrate,blue_mid_tier,blue_mid_winrate,blue_mid_winrate_evol,blue_mid_pickrate,blue_mid_games,blue_adc_elo,blue_adc_server,blue_adc_patch,blue_adc_label,blue_adc_role,blue_adc_role_pickrate,blue_adc_tier,blue_adc_winrate,blue_adc_winrate_evol,blue_adc_pickrate,blue_adc_games,blue_sup_elo,blue_sup_server,blue_sup_patch,blue_sup_label,blue_sup_role,blue_sup_role_pickrate,blue_sup_tier,blue_sup_winrate,blue_sup_winrate_evol,blue_sup_pickrate,blue_sup_games,red_top_elo,red_top_server,red_top_patch,red_top_label,red_top_role,red_top_role_pickrate,red_top_tier,red_top_winrate,red_top_winrate_evol,red_top_pickrate,red_top_games,red_jun_elo,red_jun_server,red_jun_patch,red_jun_label,red_jun_role,red_jun_role_pickrate,red_jun_tier,red_jun_winrate,red_jun_winrate_evol,red_jun_pickrate,red_jun_games,red_mid_elo,red_mid_server,red_mid_patch,red_mid_label,red_mid_role,red_mid_role_pickrate,red_mid_tier,red_mid_winrate,red_mid_winrate_evol,red_mid_pickrate,red_mid_games,red_adc_elo,red_adc_server,red_adc_patch,red_adc_label,red_adc_role,red_adc_role_pickrate,red_adc_tier,red_adc_winrate,red_adc_winrate_evol,red_adc_pickrate,red_adc_games,red_sup_elo,red_sup_server,red_sup_patch,red_sup_label,red_sup_role,red_sup_role_pickrate,red_sup_tier,red_sup_winrate,red_sup_winrate_evol,red_sup_pickrate,red_sup_games
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",tout,euw,15.24,18,top,91.0%,s,52.1%,+0.1%,7.8%,550 219,tout,euw,15.24,145,jun,66.5%,d,49.3%,+0.2%,3.6%,250 800,tout,euw,15.24,17,jun,59.9%,s,51.0%,-1.4%,8.5%,596 627,tout,euw,15.24,29,adc,99.1%,a,50.4%,-0.1%,13.2%,926 671,tout,euw,15.24,170,sup,99.0%,d,49.3%,-0.0%,2.8%,197 059,tout,euw,15.24,37,mid,69.3%,a,50.1%,-0.6%,8.2%,578 608,tout,euw,15.24,125,jun,71.7%,c,50.4%,+0.1%,2.8%,199 830,tout,euw,15.24,128,mid,69.2%,c,50.5%,+0.1%,1.9%,135 885,tout,euw,15.24,103,adc,97.9%,c,50.0%,-0.2%,5.6%,390 800,tout,euw,15.24,88,sup,98.2%,c,50.3%,+0.5%,5.5%,390 527
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",tout,euw,15.24,24,top,89.0%,s,50.9%,+0.6%,7.6%,535 221,tout,euw,15.24,196,mid,41.6%,d,47.9%,-0.1%,2.0%,143 285,tout,euw,15.24,37,mid,69.3%,a,50.1%,-0.6%,8.2%,578 608,tout,euw,15.24,215,adc,76.7%,d,46.8%,-0.4%,1.2%,85 174,tout,euw,15.24,9,sup,99.8%,s+,52.2%,+0.1%,11.8%,830 890,tout,euw,15.24,12,jun,51.6%,s,51.8%,-0.3%,6.6%,464 917,tout,euw,15.24,174,jun,99.1%,d,49.2%,+1.2%,2.4%,168 423,tout,euw,15.24,50,mid,93.8%,a,50.8%,-0.1%,6.6%,466 357,tout,euw,15.24,161,sup,87.8%,d,49.2%,+0.2%,4.3%,304 029,tout,euw,15.24,88,sup,98.2%,c,50.3%,+0.5%,5.5%,390 527
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support'],tout,euw,15.24,19,adc,82.4%,s,51.3%,-0.2%,10.2%,721 465,tout,euw,15.24,197,jun,96.9%,d,48.0%,+0.6%,2.6%,182 657,tout,euw,15.24,138,mid,79.3%,d,49.9%,-0.3%,3.3%,231 877,tout,euw,15.24,29,adc,99.1%,a,50.4%,-0.1%,13.2%,926 671,tout,euw,15.24,7,sup,99.6%,s+,52.5%,-0.2%,8.2%,577 543,tout,euw,15.24,149,top,74.3%,d,49.9%,-0.1%,2.0%,143 656,tout,euw,15.24,55,jun,93.4%,b,50.1%,+0.9%,7.9%,554 875,tout,euw,15.24,59,mid,51.2%,b,51.3%,-0.1%,4.2%,294 187,tout,euw,15.24,1,adc,97.3%,s+,52.5%,-0.1%,25.4%,1 788 527,tout,euw,15.24,180,sup,98.4%,d,48.9%,+0.2%,3.2%,226 732
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']",tout,euw,15.24,16,jun,82.0%,s,51.9%,+0.1%,6.5%,456 214,tout,euw,15.24,219,jun,77.5%,d,45.4%,+0.2%,1.5%,108 444,tout,euw,15.24,72,mid,84.0%,c,49.1%,+0.5%,6.9%,483 002,tout,euw,15.24,194,adc,98.4%,d,46.9%,-0.1%,6.1%,427 211,tout,euw,15.24,180,sup,98.4%,d,48.9%,+0.2%,3.2%,226 732,tout,euw,15.24,110,top,64.4%,c,50.1%,+0.6%,4.4%,310 162,tout,euw,15.24,195,jun,82.1%,d,48.8%,+0.3%,1.1%,76 336,tout,euw,15.24,59,mid,51.2%,b,51.3%,-0.1%,4.2%,294 187,tout,euw,15.24,79,adc,97.0%,c,48.7%,+0.5%,14.0%,985 376,tout,euw,15.24,81,sup,98.8%,c,51.8%,-0.5%,2.8%,195 095
4,euw1_7508909082,euw,15.17,high_elo,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio,3.0,4.0,5.0,8.0,23.0,4.5,53.0,3.00,550.0,0.668,2.00,0.0,0.0,607.0,110.0,6.00,0.55,335.0,475.0,30.0,8.00,0.8,32.0,1.30,"['mage', 'assassin']",8.0,6.0,2.0,3.0,35.0,4.4,63.0,3.00,175.0,0.645,3.50,0.0,0.0,620.0,106.0,8.0,0.70,345.0,274.0,55.0,7.25,0.45,32.0,2.05,"['fighter', 'tank']",9.0,2.0,6.0,3.0,27.0,4.2,59.0,3.1,550.0,0.679,3.38,0.0,0.0,630.0,104.0,3.75,0.60,330.0,300.0,40.0,7.25,0.7,30.0,1.30,"['marksman', 'assassin']",9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],8.0,4.0,7.0,3.0,22.0,5.0,59.0,4.25,125.0,0.658,3.00,0.0,0.0,590.0,109.0,6.0,0.60,335.0,375.0,45.0,6.0,0.80,30.0,1.30,"['fighter', 'marksman']",8.0,5.0,2.0,1.0,33.0,4.70,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.0,0.50,340.0,0.0,0.0,0.0,0.00,28.0,2.05,"['fighter', 'tank']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.0,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],8.0,5.0,6.0,3.0,28.0,4.2,60.0,2.9,500.0,0.638,3.3,0.0,0.0,641.0,100.0,3.75,0.65,335.0,320.0,43.0,7.0,0.8,30.0,1.3,"['marksman', 'assassin']",2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.0,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.40,30.0,1.30,"['support', 'mage']",tout,euw,15.24,182,mid,79.6%,d,48.8%,-0.0%,2.3%,161 702,tout,euw,15.24,154,jun,89.7%,d,49.8%,+2.3%,2.7%,191 877,tout,euw,15.24,86,adc,80.9%,c,49.9%,+0.1%,4.8%,341 243,tout,euw,15.24,194,adc,98.4%,d,46.9%,-0.1%,6.1%,427 211,tout,euw,15.24,180,sup,98.4%,d,48.9%,+0.2%,3.2%,226 732,tout,euw,15.24,200,jun,41.0%,d,48.4%,-0.6%,1.2%,81 614,tout,euw,15.24,18,top,91.0%,s,52.1%,+0.1%,7.8%,550 219,tout,euw,15.24,72,mid,84.0%,c,49.1%,+0.5%,6.9%,483 002,tout,euw,15.24,173,adc,96.1%,d,48.2%,-0.1%,6.1%,432 795,tout,euw,15.24,7,sup,99.6%,s+,52.5%,-0.2%,8.2%,577 543

In [ ]:
============================================================================================================================

In [ ]:
############################ maintenant, de facon optimisée mais attention, le group by n'est pas fait avec le role donc ca nous ramene des winrates d'autres roles.

In [ ]:
import pandas as pd

def build_champion_index_vector(df_simple_wr_norm):
    """
    Retourne un DataFrame de tous les champions concaténés
    avec un MultiIndex: champion
    """
    df_simple_wr_norm_copy = df_simple_wr_norm.copy()
    df_simple_wr_norm_copy["patch_float"] = df_simple_wr_norm_copy["patch"].astype(float)
    df_simple_wr_norm_copy.set_index("champion", inplace=True)
    return df_simple_wr_norm_copy

In [83]:
def stack_champions(df_result_norm):
    champ_cols = [
        "blue_top_champion","blue_jun_champion","blue_mid_champion",
        "blue_adc_champion","blue_sup_champion",
        "red_top_champion","red_jun_champion","red_mid_champion",
        "red_adc_champion","red_sup_champion"
    ]

    df_stacked = df_result_norm.melt(
        id_vars=["match_id","server","patch","elo","blue_side_win"],
        value_vars=champ_cols,
        var_name="role",
        value_name="champion"
    )

    df_stacked["patch_float"] = df_stacked["patch"].astype(float)

    return df_stacked

In [134]:
def score_candidates(df_stacked, df_simple_wr_norm_indexed):
    import numpy as np

    # Merge stacked avec simple_wr pour tous les champions
    df_merged = df_stacked.merge(
        df_simple_wr_norm_indexed.reset_index(),
        how="left",
        on=["champion", "role"],
        suffixes=("", "_wr")
    )

    # Scoring vectoriel
    server_score = np.where(df_merged["server_wr"] == df_merged["server"], 3,
                    np.where(df_merged["server_wr"] == "tout", 1, 0))

    elo_score = np.where(df_merged["elo_wr"] == df_merged["elo"], 3,
                 np.where(df_merged["elo_wr"] == "tout", 1, 0))

    patch_score = np.zeros(len(df_merged))

    patch = df_merged["patch_float"]
    patch_wr = df_merged["patch_float_wr"]

    # exact
    patch_score[patch == patch_wr] = 4

    # même 15.17
    patch_minor = patch.astype(str).str[:4]
    patch_wr_minor = patch_wr.astype(str).str[:4]
    mask_minor = (patch_score == 0) & (patch_minor == patch_wr_minor)
    patch_score[mask_minor] = 3

    # même 15
    patch_major = patch.astype(str).str[:2]
    patch_wr_major = patch_wr.astype(str).str[:2]
    mask_major = (patch_score == 0) & (patch_major == patch_wr_major)
    patch_score[mask_major] = 2

    # patch restant
    patch_score[patch_score == 0] = 1

    df_merged["score"] = server_score + elo_score + patch_score
    df_merged["patch_distance"] = (patch - patch_wr).abs()

    return df_merged

In [85]:
def select_best_per_role(df_scored):
    # trouver l'index du meilleur score par match_id + role
    idx = df_scored.groupby(["match_id","role"]) \
                   .apply(lambda x: x.sort_values(["score","patch_distance"], ascending=[False,True]).index[0])

    df_best = df_scored.loc[idx.values].reset_index(drop=True)

    return df_best

In [86]:
def build_df_enhanced(df_result_norm, df_simple_wr_norm):
    # 1️⃣ index vectorisé
    df_indexed = build_champion_index_vector(df_simple_wr_norm)

    # 2️⃣ stack champions
    df_stacked = stack_champions(df_result_norm)

    # 3️⃣ scoring vectoriel
    df_scored = score_candidates(df_stacked, df_indexed)

    # 4️⃣ select best
    df_best = select_best_per_role(df_scored)

    # 5️⃣ pivot pour retrouver les colonnes par role
    extra_cols = [c for c in df_best.columns if c not in ["match_id","role","champion",
                                                          "server","patch","elo","blue_side_win"]]

    df_pivot = df_best.pivot(index="match_id", columns="role", values=extra_cols)
    # flatten multiindex
    df_pivot.columns = [f"{role}_{col}" for col, role in df_pivot.columns]

    # 6️⃣ concat avec df_result_norm
    df_enhanced = df_result_norm.set_index("match_id").join(df_pivot).reset_index()

    return df_enhanced

In [ ]:
===============================================

In [133]:
print(df_stacked["role"].unique())
print(df_simple_wr_norm["role"].unique())

NameError: name 'df_stacked' is not defined

In [103]:
print(df_simple_wr_norm.columns)

Index(['elo', 'server', 'patch', 'label', 'champion', 'role', 'role_pickrate',
       'tier', 'winrate', 'winrate_evol', 'pickrate', 'games'],
      dtype='object')

In [121]:
df_simple_wr_norm.head()

,elo,server,patch,label,champion,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,tout,tout,16.3,1,briar,jun,91.1%,s+,52.8%,+1.5%,6.7%,599 576
1,tout,tout,16.3,2,missfortune,adc,97.0%,s+,51.7%,-0.0%,15.5%,1 386 160
2,tout,tout,16.3,3,malzahar,mid,92.2%,s+,52.3%,+0.0%,8.1%,724 180
3,tout,tout,16.3,4,swain,adc,18.6%,s+,54.6%,-0.1%,1.7%,154 988
4,tout,tout,16.3,5,jinx,adc,99.5%,s+,51.6%,-0.2%,16.6%,1 485 175

In [104]:
print(df_result_norm.columns)

Index(['match_id', 'server', 'patch', 'elo', 'blue_side_win',
       'blue_top_champion', 'blue_jun_champion', 'blue_mid_champion',
       'blue_adc_champion', 'blue_sup_champion',
       ...
       'red_support_stats_hpregen', 'red_support_stats_hpregenperlevel',
       'red_support_stats_movespeed', 'red_support_stats_mp',
       'red_support_stats_mpperlevel', 'red_support_stats_mpregen',
       'red_support_stats_mpregenperlevel', 'red_support_stats_spellblock',
       'red_support_stats_spellblockperlevel', 'red_support_tags'],
      dtype='object', length=265)

In [122]:
df_result_norm.iloc[:5, list(range(0,15)) + list(range(265,(df_result_norm).shape[1]))]

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona
4,euw1_7508909082,euw,15.17,high_elo,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio

In [ ]:
#mauvais group by : on préfère ramener un winrate de mauvaise lane ici.
# import pandas as pd

# def build_champion_index_vector(df_simple_wr_norm):
#     """
#     Retourne un DataFrame de tous les champions concaténés
#     avec un MultiIndex: champion
#     """
#     df_simple_wr_norm_copy = df_simple_wr_norm.copy()
#     df_simple_wr_norm_copy["patch_float"] = df_simple_wr_norm_copy["patch"].astype(float)
#     df_simple_wr_norm_copy.set_index("champion", inplace=True)
#     return df_simple_wr_norm_copy





# def stack_champions(df_result_norm):
#     champ_cols = [
#         "blue_top_champion","blue_jun_champion","blue_mid_champion",
#         "blue_adc_champion","blue_sup_champion",
#         "red_top_champion","red_jun_champion","red_mid_champion",
#         "red_adc_champion","red_sup_champion"
#     ]

#     df_stacked = df_result_norm.melt(
#         id_vars=["match_id","server","patch","elo","blue_side_win"],
#         value_vars=champ_cols,
#         var_name="role",
#         value_name="champion"
#     )

#     df_stacked["patch_float"] = df_stacked["patch"].astype(float)

#     return df_stacked




# def score_candidates(df_stacked, df_simple_wr_norm_indexed):
#     import numpy as np

#     # Merge stacked avec simple_wr pour tous les champions
#     df_merged = df_stacked.merge(
#         df_simple_wr_norm_indexed.reset_index(),
#         how="left",
#         on="champion",
#         suffixes=("", "_wr")
#     )

#     # Scoring vectoriel
#     server_score = np.where(df_merged["server_wr"] == df_merged["server"], 3,
#                     np.where(df_merged["server_wr"] == "tout", 1, 0))

#     elo_score = np.where(df_merged["elo_wr"] == df_merged["elo"], 3,
#                  np.where(df_merged["elo_wr"] == "tout", 1, 0))

#     patch_score = np.zeros(len(df_merged))

#     patch = df_merged["patch_float"]
#     patch_wr = df_merged["patch_float_wr"]

#     # exact
#     patch_score[patch == patch_wr] = 4

#     # même 15.17
#     patch_minor = patch.astype(str).str[:4]
#     patch_wr_minor = patch_wr.astype(str).str[:4]
#     mask_minor = (patch_score == 0) & (patch_minor == patch_wr_minor)
#     patch_score[mask_minor] = 3

#     # même 15
#     patch_major = patch.astype(str).str[:2]
#     patch_wr_major = patch_wr.astype(str).str[:2]
#     mask_major = (patch_score == 0) & (patch_major == patch_wr_major)
#     patch_score[mask_major] = 2

#     # patch restant
#     patch_score[patch_score == 0] = 1

#     df_merged["score"] = server_score + elo_score + patch_score
#     df_merged["patch_distance"] = (patch - patch_wr).abs()

#     return df_merged


# def select_best_per_role(df_scored):
#     # trouver l'index du meilleur score par match_id + role
#     idx = df_scored.groupby(["match_id","role"]) \
#                    .apply(lambda x: x.sort_values(["score","patch_distance"], ascending=[False,True]).index[0])

#     df_best = df_scored.loc[idx.values].reset_index(drop=True)

#     return df_best



# def build_df_enhanced(df_result_norm, df_simple_wr_norm):
#     # 1️⃣ index vectorisé
#     df_indexed = build_champion_index_vector(df_simple_wr_norm)

#     # 2️⃣ stack champions
#     df_stacked = stack_champions(df_result_norm)

#     # 3️⃣ scoring vectoriel
#     df_scored = score_candidates(df_stacked, df_indexed)

#     # 4️⃣ select best
#     df_best = select_best_per_role(df_scored)

#     # 5️⃣ pivot pour retrouver les colonnes par role
#     extra_cols = [c for c in df_best.columns if c not in ["match_id","role","champion",
#                                                           "server","patch","elo","blue_side_win"]]

#     df_pivot = df_best.pivot(index="match_id", columns="role", values=extra_cols)
#     # flatten multiindex
#     df_pivot.columns = [f"{role}_{col}" for col, role in df_pivot.columns]

#     # 6️⃣ concat avec df_result_norm
#     df_enhanced = df_result_norm.set_index("match_id").join(df_pivot).reset_index()

#     return df_enhanced

In [ ]:
# ICI C'est la bonne methode optimisée en temps mais pas en memoire donc à executer par parties. 
# et peut-etre faudrait-il empecher de ramener bronz en wr si le elo de la game est trop élevé.
import pandas as pd

def build_champion_index_vector(df_simple_wr_norm):
    """
    Prépare le dataframe WR avec patch_float
    et index champion + role
    """
    df = df_simple_wr_norm.copy()

    df["patch_float"] = df["patch"].astype(float)

    # l'index permet de faire la jointure plus rapidement mais le nombre de lignes pendant la jointure explose quand meme.
    # essayer join plutot que merge mais il faut d'abord setter en tant qu'index role et champion dnas les 2 df car join marche sur les index

    df.set_index(["champion","role"], inplace=True)

    return df

def stack_champions(df_result_norm):

    champ_cols = [
        "blue_top_champion","blue_jun_champion","blue_mid_champion",
        "blue_adc_champion","blue_sup_champion",
        "red_top_champion","red_jun_champion","red_mid_champion",
        "red_adc_champion","red_sup_champion"
    ]

    df_stacked = df_result_norm.melt(
        id_vars=["match_id","server","patch","elo","blue_side_win"],
        value_vars=champ_cols,
        var_name="champion_col",
        value_name="champion"
    )

    # extraire team et role
    split = df_stacked["champion_col"].str.split("_", expand=True)

    df_stacked["team"] = split[0]
    df_stacked["role"] = split[1]

    df_stacked["patch_float"] = df_stacked["patch"].astype(float)

    return df_stacked


def score_candidates(df_stacked, df_simple_wr_norm_indexed):

    import numpy as np

    df_wr = df_simple_wr_norm_indexed.reset_index()

    df_merged = df_stacked.merge(
        df_wr,
        how="left",
        on=["champion","role"],
        suffixes=("", "_wr")
    )

    # server score
    server_score = np.where(
        df_merged["server_wr"] == df_merged["server"], 3,
        np.where(df_merged["server_wr"] == "tout", 1, 0)
    )

    # elo score
    elo_score = np.where(
        df_merged["elo_wr"] == df_merged["elo"], 3,
        np.where(df_merged["elo_wr"] == "tout", 1, 0)
    )

    # patch score
    patch = df_merged["patch_float"]
    patch_wr = df_merged["patch_float_wr"]

    patch_score = np.zeros(len(df_merged))

    # exact
    patch_score[patch == patch_wr] = 4

    # même mineur
    patch_minor = patch.astype(str).str[:4]
    patch_wr_minor = patch_wr.astype(str).str[:4]

    mask_minor = (patch_score == 0) & (patch_minor == patch_wr_minor)
    patch_score[mask_minor] = 3

    # même majeur
    patch_major = patch.astype(str).str[:2]
    patch_wr_major = patch_wr.astype(str).str[:2]

    mask_major = (patch_score == 0) & (patch_major == patch_wr_major)
    patch_score[mask_major] = 2

    patch_score[patch_score == 0] = 1

    df_merged["score"] = server_score + elo_score + patch_score
    df_merged["patch_distance"] = (patch - patch_wr).abs()

    return df_merged


def select_best_per_role(df_scored):

    idx = df_scored.groupby(["match_id","team","role"]) \
        .apply(lambda x: x.sort_values(
            ["score","patch_distance"],
            ascending=[False,True]
        ).index[0])

    df_best = df_scored.loc[idx.values].reset_index(drop=True)

    return df_best


def build_df_enhanced(df_result_norm, df_simple_wr_norm):

    # 1 index WR
    df_indexed = build_champion_index_vector(df_simple_wr_norm)

    # 2 stack
    df_stacked = stack_champions(df_result_norm)

    # 3 scoring
    df_scored = score_candidates(df_stacked, df_indexed)

    # 4 best candidate
    df_best = select_best_per_role(df_scored)

    # colonnes à ajouter
    extra_cols = [
        c for c in df_best.columns
        # if c not in [
        #     "match_id","champion","team","role",
        #     "server","patch","elo","blue_side_win",
        #     "champion_col"
        # ]
        if c not in [
            "match_id",
            "champion",
            "team",
            "role",
            "server","patch","elo","blue_side_win",
            "champion_col"
        ]
    ]

    # clé pivot
    df_best["team_role"] = df_best["team"] + "_" + df_best["role"]

    df_pivot = df_best.pivot(
        index="match_id",
        columns="team_role",
        values=extra_cols
    )

    # flatten colonnes
    df_pivot.columns = [
        f"{team_role}_{col}"
        for col, team_role in df_pivot.columns
    ]

    df_enhanced = (
        df_result_norm
        .set_index("match_id")
        .join(df_pivot)
        .reset_index()
    )

    return df_enhanced

In [124]:
===============================================

SyntaxError: invalid syntax (3758341841.py, line 1)

In [150]:
dfs_enhanced_bis = []
dfs_enhanced_bis.append(build_df_enhanced(df_result_norm.iloc[0:1000], df_simple_wr_norm))

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\3488179251.py:101: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","team","role"]) \

In [151]:
dfs_enhanced_bis[0].head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags,blue_adc_role,blue_jun_role,blue_mid_role,blue_sup_role,blue_top_role,red_adc_role,red_jun_role,red_mid_role,red_sup_role,red_top_role,blue_adc_patch_float,blue_jun_patch_float,blue_mid_patch_float,blue_sup_patch_float,blue_top_patch_float,red_adc_patch_float,red_jun_patch_float,red_mid_patch_float,red_sup_patch_float,red_top_patch_float,blue_adc_elo_wr,blue_jun_elo_wr,blue_mid_elo_wr,blue_sup_elo_wr,blue_top_elo_wr,red_adc_elo_wr,red_jun_elo_wr,red_mid_elo_wr,red_sup_elo_wr,red_top_elo_wr,blue_adc_server_wr,blue_jun_server_wr,blue_mid_server_wr,blue_sup_server_wr,blue_top_server_wr,red_adc_server_wr,red_jun_server_wr,red_mid_server_wr,red_sup_server_wr,red_top_server_wr,blue_adc_patch_wr,blue_jun_patch_wr,blue_mid_patch_wr,blue_sup_patch_wr,blue_top_patch_wr,red_adc_patch_wr,red_jun_patch_wr,red_mid_patch_wr,red_sup_patch_wr,red_top_patch_wr,blue_adc_label,blue_jun_label,blue_mid_label,blue_sup_label,blue_top_label,red_adc_label,red_jun_label,red_mid_label,red_sup_label,red_top_label,blue_adc_role_pickrate,blue_jun_role_pickrate,blue_mid_role_pickrate,blue_sup_role_pickrate,blue_top_role_pickrate,red_adc_role_pickrate,red_jun_role_pickrate,red_mid_role_pickrate,red_sup_role_pickrate,red_top_role_pickrate,blue_adc_tier,blue_jun_tier,blue_mid_tier,blue_sup_tier,blue_top_tier,red_adc_tier,red_jun_tier,red_mid_tier,red_sup_tier,red_top_tier,blue_adc_winrate,blue_jun_winrate,blue_mid_winrate,blue_sup_winrate,blue_top_winrate,red_adc_winrate,red_jun_winrate,red_mid_winrate,red_sup_winrate,red_top_winrate,blue_adc_winrate_evol,blue_jun_winrate_evol,blue_mid_winrate_evol,blue_sup_winrate_evol,blue_top_winrate_evol,red_adc_winrate_evol,red_jun_winrate_evol,red_mid_winrate_evol,red_sup_winrate_evol,red_top_winrate_evol,blue_adc_pickrate,blue_jun_pickrate,blue_mid_pickrate,blue_sup_pickrate,blue_top_pickrate,red_adc_pickrate,red_jun_pickrate,red_mid_pickrate,red_sup_pickrate,red_top_pickrate,blue_adc_games,blue_jun_games,blue_mid_games,blue_sup_games,blue_top_games,red_adc_games,red_jun_games,red_mid_games,red_sup_games,red_top_games,blue_adc_patch_float_wr,blue_jun_patch_float_wr,blue_mid_patch_float_wr,blue_sup_patch_float_wr,blue_top_patch_float_wr,red_adc_patch_float_wr,red_jun_patch_float_wr,red_mid_patch_float_wr,red_sup_patch_float_wr,red_top_patch_float_wr,blue_adc_score,blue_jun_score,blue_mid_score,blue_sup_score,blue_top_score,red_adc_score,red_jun_score,red_mid_score,red_sup_score,red_top_score,blue_adc_patch_distance,blue_jun_patch_distance,blue_mid_patch_distance,blue_sup_patch_distance,blue_top_patch_distance,red_adc_patch_distance,red_jun_patch_distance,red_mid_patch_distance,red_sup_patch_distance,red_top_patch_distance
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,145.0,30.0,170.0,18.0,103.0,125.0,128.0,88.0,131.0,99.1%,66.5%,38.6%,99.0%,91.0%,97.9%,71.7%,69.2%,98.2%,21.5%,a,d,a,d,s,c,c,c,c,c,50.4%,49.3%,51.4%,49.3%,52.1%,50.0%,50.4%,50.5%,50.3%,48.8%,-0.1%,+0.2%,-0.1%,-0.0%,+0.1%,-0.2%,+0.1%,+0.1%,+0.5%,-0.5%,13.2%,3.6%,5.0%,2.8%,7.8%,5.6%,2.8%,1.9%,5.5%,2.7%,926 671,250 800,354 648,197 059,550 219,390 800,199 830,135 885,390 527,188 094,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,nan,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,16.3,15.24,15.24,15.24,15.24,215.0,217.0,37.0,9.0,24.0,144.0,174.0,50.0,88.0,83.0,76.7%,55.1%,69.3%,99.8%,89.0%,12.6%,99.1%,93.8%,98.2%,46.4%,d,d,a,s+,s,d,d,a,c,c,46.8%,45.3%,50.1%,52.2%,50.9%,50.2%,49.2%,50.8%,50.3%,49.3%,-0.4%,-0.3%,-0.6%,+0.1%,+0.6%,-0.6%,+1.2%,-0.1%,+0.5%,-0.3%,1.2%,2.6%,8.2%,11.8%,7.6%,1.4%,2.4%,6.6%,5.5%,5.1%,85 174,183 545,578 608,830 890,535 221,15 410,168 423,466 357,390 527,359 722,15.24,15.24,15.24,15.24,15.24,16.3,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,2.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,1.13,0.07,0.07,0.07,0.07
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support'],adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,bronze,tout,tout,tout,tout,tout,euw,euw,euw,euw,vn,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,197.0,138.0,7.0,82.0,1.0,55.0,59.0,180.0,149.0,99.1%,96.9%,79.3%,99.6%,6.3%,97.3%,93.4%,51.2%,98.4%,74.3%,a,d,d,s+,c,s+,b,b,d,d,50.4%,48.0%,49.9%,52.5%,50.5%,52.5%,50.1%,51.3%,48.9%,49.9%,-0.1%,+0.6%,-0.3%,-0.2%,-4.7%,-0.1%,+0.9%,-0.1%,+0.2%,-0.1%,13.2%,2.6%,3.3%,8.2%,2.7%,25.4%,7.9%,4.2%,3.2%,2.0%,926 671,182 657,231 877,577 543,1 704,1 788 527,554 875,294 187,226 732,143 656,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,2.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']",adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,194.0,219.0,72.0,180.0,43.0,79.0,195.0,59.0,81.0,110.0,98.4%,77.5%,84.0%,98.4%,17.1%,97.0%,82.1%,51.2%,98.8%,64.4%,d,d,c,d,a,c,d,b,c,c,46.9%,45.4%,49.1%,48.9%,52.1%,48.7%,48.8%,51.3%,51.8%,50.1%,-0.1%,+0.2%,+0.5%,+0.2%,+0.9%,+0.5%,+0.3%,-0.1%,-0.5%,+0.6%,6.1%,1.5%,6.9%,3.2%,1.7%,14.0%,1.1%,4.2%,2.8%,4.4%,427 211,108 444,483 002,226 732,116 552,985 376,76 336,294 187,195 095,310 162,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07

In [167]:
dfs_enhanced_bis[0].iloc[:10, list(range(0,15)) + list(range(265,(dfs_enhanced_bis[0]).shape[1]))]

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_adc_role,blue_jun_role,blue_mid_role,blue_sup_role,blue_top_role,red_adc_role,red_jun_role,red_mid_role,red_sup_role,red_top_role,blue_adc_patch_float,blue_jun_patch_float,blue_mid_patch_float,blue_sup_patch_float,blue_top_patch_float,red_adc_patch_float,red_jun_patch_float,red_mid_patch_float,red_sup_patch_float,red_top_patch_float,blue_adc_elo_wr,blue_jun_elo_wr,blue_mid_elo_wr,blue_sup_elo_wr,blue_top_elo_wr,red_adc_elo_wr,red_jun_elo_wr,red_mid_elo_wr,red_sup_elo_wr,red_top_elo_wr,blue_adc_server_wr,blue_jun_server_wr,blue_mid_server_wr,blue_sup_server_wr,blue_top_server_wr,red_adc_server_wr,red_jun_server_wr,red_mid_server_wr,red_sup_server_wr,red_top_server_wr,blue_adc_patch_wr,blue_jun_patch_wr,blue_mid_patch_wr,blue_sup_patch_wr,blue_top_patch_wr,red_adc_patch_wr,red_jun_patch_wr,red_mid_patch_wr,red_sup_patch_wr,red_top_patch_wr,blue_adc_label,blue_jun_label,blue_mid_label,blue_sup_label,blue_top_label,red_adc_label,red_jun_label,red_mid_label,red_sup_label,red_top_label,blue_adc_role_pickrate,blue_jun_role_pickrate,blue_mid_role_pickrate,blue_sup_role_pickrate,blue_top_role_pickrate,red_adc_role_pickrate,red_jun_role_pickrate,red_mid_role_pickrate,red_sup_role_pickrate,red_top_role_pickrate,blue_adc_tier,blue_jun_tier,blue_mid_tier,blue_sup_tier,blue_top_tier,red_adc_tier,red_jun_tier,red_mid_tier,red_sup_tier,red_top_tier,blue_adc_winrate,blue_jun_winrate,blue_mid_winrate,blue_sup_winrate,blue_top_winrate,red_adc_winrate,red_jun_winrate,red_mid_winrate,red_sup_winrate,red_top_winrate,blue_adc_winrate_evol,blue_jun_winrate_evol,blue_mid_winrate_evol,blue_sup_winrate_evol,blue_top_winrate_evol,red_adc_winrate_evol,red_jun_winrate_evol,red_mid_winrate_evol,red_sup_winrate_evol,red_top_winrate_evol,blue_adc_pickrate,blue_jun_pickrate,blue_mid_pickrate,blue_sup_pickrate,blue_top_pickrate,red_adc_pickrate,red_jun_pickrate,red_mid_pickrate,red_sup_pickrate,red_top_pickrate,blue_adc_games,blue_jun_games,blue_mid_games,blue_sup_games,blue_top_games,red_adc_games,red_jun_games,red_mid_games,red_sup_games,red_top_games,blue_adc_patch_float_wr,blue_jun_patch_float_wr,blue_mid_patch_float_wr,blue_sup_patch_float_wr,blue_top_patch_float_wr,red_adc_patch_float_wr,red_jun_patch_float_wr,red_mid_patch_float_wr,red_sup_patch_float_wr,red_top_patch_float_wr,blue_adc_score,blue_jun_score,blue_mid_score,blue_sup_score,blue_top_score,red_adc_score,red_jun_score,red_mid_score,red_sup_score,red_top_score,blue_adc_patch_distance,blue_jun_patch_distance,blue_mid_patch_distance,blue_sup_patch_distance,blue_top_patch_distance,red_adc_patch_distance,red_jun_patch_distance,red_mid_patch_distance,red_sup_patch_distance,red_top_patch_distance
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,145.0,30.0,170.0,18.0,103.0,125.0,128.0,88.0,131.0,99.1%,66.5%,38.6%,99.0%,91.0%,97.9%,71.7%,69.2%,98.2%,21.5%,a,d,a,d,s,c,c,c,c,c,50.4%,49.3%,51.4%,49.3%,52.1%,50.0%,50.4%,50.5%,50.3%,48.8%,-0.1%,+0.2%,-0.1%,-0.0%,+0.1%,-0.2%,+0.1%,+0.1%,+0.5%,-0.5%,13.2%,3.6%,5.0%,2.8%,7.8%,5.6%,2.8%,1.9%,5.5%,2.7%,926 671,250 800,354 648,197 059,550 219,390 800,199 830,135 885,390 527,188 094,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,nan,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,16.3,15.24,15.24,15.24,15.24,215.0,217.0,37.0,9.0,24.0,144.0,174.0,50.0,88.0,83.0,76.7%,55.1%,69.3%,99.8%,89.0%,12.6%,99.1%,93.8%,98.2%,46.4%,d,d,a,s+,s,d,d,a,c,c,46.8%,45.3%,50.1%,52.2%,50.9%,50.2%,49.2%,50.8%,50.3%,49.3%,-0.4%,-0.3%,-0.6%,+0.1%,+0.6%,-0.6%,+1.2%,-0.1%,+0.5%,-0.3%,1.2%,2.6%,8.2%,11.8%,7.6%,1.4%,2.4%,6.6%,5.5%,5.1%,85 174,183 545,578 608,830 890,535 221,15 410,168 423,466 357,390 527,359 722,15.24,15.24,15.24,15.24,15.24,16.3,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,2.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,1.13,0.07,0.07,0.07,0.07
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,bronze,tout,tout,tout,tout,tout,euw,euw,euw,euw,vn,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,197.0,138.0,7.0,82.0,1.0,55.0,59.0,180.0,149.0,99.1%,96.9%,79.3%,99.6%,6.3%,97.3%,93.4%,51.2%,98.4%,74.3%,a,d,d,s+,c,s+,b,b,d,d,50.4%,48.0%,49.9%,52.5%,50.5%,52.5%,50.1%,51.3%,48.9%,49.9%,-0.1%,+0.6%,-0.3%,-0.2%,-4.7%,-0.1%,+0.9%,-0.1%,+0.2%,-0.1%,13.2%,2.6%,3.3%,8.2%,2.7%,25.4%,7.9%,4.2%,3.2%,2.0%,926 671,182 657,231 877,577 543,1 704,1 788 527,554 875,294 187,226 732,143 656,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,2.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,194.0,219.0,72.0,180.0,43.0,79.0,195.0,59.0,81.0,110.0,98.4%,77.5%,84.0%,98.4%,17.1%,97.0%,82.1%,51.2%,98.8%,64.4%,d,d,c,d,a,c,d,b,c,c,46.9%,45.4%,49.1%,48.9%,52.1%,48.7%,48.8%,51.3%,51.8%,50.1%,-0.1%,+0.2%,+0.5%,+0.2%,+0.9%,+0.5%,+0.3%,-0.1%,-0.5%,+0.6%,6.1%,1.5%,6.9%,3.2%,1.7%,14.0%,1.1%,4.2%,2.8%,4.4%,427 211,108 444,483 002,226 732,116 552,985 376,76 336,294 187,195 095,310 162,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
4,euw1_7508909082,euw,15.17,high_elo,False,aurora,xinzhao,twitch,yunara,rakan,jayce,sett,akali,lucian,milio,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,NaN,tout,grandmaster,tout,NaN,tout,tout,tout,euw,euw,NaN,euw,euw,euw,NaN,euw,euw,euw,15.24,15.24,NaN,15.24,15.24,15.24,NaN,15.24,15.24,15.24,194.0,154.0,NaN,180.0,89.0,173.0,NaN,72.0,7.0,214.0,98.4%,89.7%,NaN,98.4%,30.2%,96.1%,NaN,84.0%,99.6%,45.4%,d,d,NaN,d,b,d,NaN,c,s+,d,46.9%,49.8%,NaN,48.9%,52.0%,48.2%,NaN,49.1%,52.5%,46.8%,-0.1%,+2.3%,NaN,+0.2%,-4.3%,-0.1%,NaN,+0.5%,-0.2%,-0.5%,6.1%,2.7%,NaN,3.2%,2.2%,6.1%,NaN,6.9%,8.2%,1.7%,427 211,191 877,NaN,226 732,248,432 795,NaN,483 002,577 543,117 285,15.24,15.24,NaN,15.24,15.24,15.24,NaN,15.24,15.24,15.24,6.0,6.0,1.0,6.0,5.0,6.0,1.0,6.0,6.0,6.0,0.07,0.07,NaN,0.07,0.07,0.07,NaN,0.07,0.07,0.07
5,euw1_7508869243,euw,15.17,high_elo,True,heimerdinger,trundle,yasuo,xerath,maokai,aurora,hecarim,malzahar,ashe,nidalee,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,NaN,tout,tout,tout,tout,tout,tout,tout,challenger,grandmaster,NaN,euw,euw,euw,euw,euw,euw,euw,tout,euw,NaN,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,NaN,111.0,37.0,106.0,97.0,44.0,174.0,3.0,12.0,89.0,NaN,65.3%,69.3%,78.2%,63.2%,88.8%,99.1%,90.0%,16.6%,30.2%,NaN,c,a,c,c,a,d,s+,s+,b,NaN,50.8%,50.1%,51.3%,50.8%,49.9%,49.2%,52.0%,56.0%,52.0%,NaN,+2.0%,-0.6%,+1.8%,+1.3%,+0.2%,+1.2%,+0.1%,-6.1%,-4.3%,NaN,2.3%,8.2%,1.8%,2.0%,11.0%,2.4%,8.8%,1.1%,2.2%,NaN,161 332,578 608,129 711,139 510,772 806,168 423,618 121,336,248,NaN,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,1.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,3.0,5.0,NaN,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
6,euw1_7508851515,euw,15.17,high_elo,False,skarner,talon,fizz,smolder,rakan,darius,nidalee,katarina,yunara,taric,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,NaN,tout,tout,tout,tout,tout,euw,euw,euw,euw,NaN,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,NaN,15.24,15.24,15.24,15.24,15.24,19.0,145.0,25.0,180.0,NaN,194.0,219.0,76.0,64.0,56.0,82.4%,66.5%,89.4%,98.4%,NaN,98.4%,77.5%,96.2%,93.2%,92.1%,s,d,s,d,NaN,d,d,c,b,b,51.3%,49.3%,51.3%,48.9%,NaN,46.9%,45.4%,49.0%,52.5%,49.0%,-0.2%,+0.2%,+0.3%,+0.2%,NaN,-0.1%,+0.2%,+0.3%,-0.3%,+0.3%,10.2%,3.6%,6.1%,3.2%,NaN,6.1%,1.5%,7.5%,1.7%,8.6%,721 465,250 800,428 026,226 732,NaN,427 211,108 444,526 506,117 057,608 141,15.24,15.24,15.24,15.24,NaN,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,1.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,NaN,0.07,0.07,0.07,0.07,0.07
7,euw1_7507963628,euw,15.16,high_elo,False,urgot,shaco,syndra,corki,pantheon,aurora,qiyana,yasuo,samira,sylas,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,tout,tout,tout,tout,tout,tout,tout,tout,tout,grandmaster,euw,euw,euw,euw,euw,euw,euw,euw,kr,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,215.0,67.0,50.0,165.0,49.0,75.0,217.0,37.0,127.0,89.0,76.7%,74.2%,93.8%,45.7%,94.3%,98.3%,55.1%,69.3%,5.6%,30.2%,d,b,a,d,a,c,d,a,c,b,46.8%,49.7%,50.8%,49.0%,52.3%,49.8%,45.3%,50.1%,49.5%,52.0%,-0.4%,-0.0%,-0.1%,+0.1%,-0.1%,+0.1%,-0.3%,-0.6%,-0.6%,-4.3%,1.2%,5.4%,6.6%,3.6%,3.6%,5.5%,2.6%,8.2%,1.8%,2.2%,85 174,381 853,466 357,255 321,252 031,388 831,183 545,578 608,40 442,248,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,3.0,5.0,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08,0.08
8,euw1_7506939511,euw,15.16,high_elo,True,illaoi,volibear,syndra,ezreal,neeko,poppy,gwen,wukong,jhin,xerath,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,15.16,tout,tout,tout,tout,tout,tout,grandmaster,NaN,tout,tout,euw,euw,euw,euw,euw,euw,euw,NaN,euw,kr,15.24,15.24,15.24,15.24,15.24,15.24,15.24,NaN,15.24,15.24,163.0,52.0,50.0,203.0,57.0,32.0,8.0,NaN,117.0,42.0,95.1%,51.9%,93.8%,78.7%,95.8%,97.3%,26.3%,NaN,46.0%,22.7%,d,a,a,d,b,a,s+,NaN,c,a,47.8%,51.7%,50.8%,47.5%,51.2%,50.4%,57.2%,NaN,50.1%,52.1%,+1.6%,-2.4%,-0.1%,-0.1%,-0.3%,+0.1%,+1.2%,NaN,+0.4%,+0.6%,7.9%,4.1%,6.6%,3.1%,3.1%,14.6%,1.2%,NaN,2.7%,1.6%,556 429,290 182,466 357,220 904,219 171,1 030 317,138,NaN,188 821,35 351,15.24,15.24,15.24,15.24,15.24,15.24,15.24,NaN,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,5.0,1.0,6.0,3.0,0.08,0.08,0.08,0.08,0.08,0.08,0.08,NaN,0.08,0.08
9,euw1_7512192924,euw,15.17,high_elo,True,leesin,hecarim,kassadin,draven,rell,gangplank,diana,jhin,yunara,galio,adc,jun,mid,sup,top,adc,jun,mid,sup,top,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,NaN,tout,tout,NaN,bronze,tout,euw,euw,euw,euw,NaN,euw,euw,NaN,vn,euw,15.24,15.24,15.24,15.24,NaN,15.24,15.24,NaN,15.24,15.24,112.0,174.0,108.0,170.0,NaN,194.0,17.0,NaN,163.0,210.0,95.2%,99.1%,96.9%,99.0%,NaN,98.4%,59.9%,NaN,17.8%,86.3%,c,d,c,d,NaN,d,s,NaN,d,d,48.7%,49.2%,50.9%,49.3%,NaN,46.9%,51.0%,NaN,48.5%,47.3%,+1.3%,+1.2%,-0.4%,-0.0%,NaN,-0.1%,-1.4%,NaN,-5.2%,-0.3%,4.2%,2.4%,2.5%,2.8%,NaN,6.1%,8.5%,NaN,1.3%,2.4%,294 971,168 423,177 486,197 059,NaN,427 211,596 627,NaN,831,170 818,15.24,15.24,15.24,15.24,NaN,15.24,15.24,NaN,15.24,15.24,6.0,6.0,6.0,6.0,1.0,6.0,6.0,1.0,2.0,6.0,0.07,0.07,0.07,0.07,NaN,0.07,0.07,NaN,0.07,0.07

In [157]:
# verifier en regardant si les bons wr existent ou pas et si ceux qui sont remontés ont bien ces valeurs

df_simple_wr_norm.head()

,elo,server,patch,label,champion,role,role_pickrate,tier,winrate,winrate_evol,pickrate,games
0,tout,tout,16.3,1,briar,jun,91.1%,s+,52.8%,+1.5%,6.7%,599 576
1,tout,tout,16.3,2,missfortune,adc,97.0%,s+,51.7%,-0.0%,15.5%,1 386 160
2,tout,tout,16.3,3,malzahar,mid,92.2%,s+,52.3%,+0.0%,8.1%,724 180
3,tout,tout,16.3,4,swain,adc,18.6%,s+,54.6%,-0.1%,1.7%,154 988
4,tout,tout,16.3,5,jinx,adc,99.5%,s+,51.6%,-0.2%,16.6%,1 485 175

In [166]:
print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "aurora"].shape)
print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "aurora"].head(24))

print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "smolder"].shape)
print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "smolder"].head(39))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].shape)
# print(df_simple_wr_norm[df_simple_wr_norm["champion"] == "sett"].head(24))

(40, 12)
              elo server  patch  label champion role role_pickrate tier  \
180          tout   tout  16.30    181   aurora  mid         80.5%    d
399          tout   tout  15.24    188   aurora  mid         79.6%    d
618          tout    nan  16.30    188   aurora  mid         80.5%    d
827          tout    nan  15.24    177   aurora  mid         79.6%    d
1047         tout     kr  16.30    173   aurora  mid         80.5%    d
1264         tout     kr  15.24    189   aurora  mid         79.6%    d
1455         tout    euw  16.30    177   aurora  mid         80.5%    d
1675         tout    euw  15.24    182   aurora  mid         79.6%    d
1890       bronze   tout  16.30    176   aurora  mid         81.8%    d
2042  grandmaster   tout  16.30    119   aurora  mid         65.1%    c
2052  grandmaster   tout  16.30    129   aurora  top         32.7%    c
2236  grandmaster   tout  15.24    105   aurora  top         30.2%    c
2335  grandmaster   tout  15.24    204   aurora  mid         68.1%    d
2398  grandmaster     kr  16.30     48   aurora  top         32.7%    a
2406  grandmaster     kr  16.30     56   aurora  mid         65.1%    a
2550  grandmaster     kr  15.24     57   aurora  top         30.2%    a
2656  grandmaster     kr  15.24    163   aurora  mid         68.1%    d
2840  grandmaster    euw  16.30    151   aurora  top         32.7%    d
2862  grandmaster    euw  16.30    173   aurora  mid         65.1%    d
2956  grandmaster    euw  15.24     89   aurora  top         30.2%    b
3030  grandmaster    euw  15.24    163   aurora  mid         68.1%    d
3129   challenger   tout  16.30     47   aurora  mid         61.1%    a
3163   challenger   tout  16.30     81   aurora  top         38.4%    b
3465   challenger   tout  15.24    173   aurora  top         34.6%    d

     winrate winrate_evol pickrate    games
180    48.7%        +0.1%     2.4%  212 922
399    48.8%        +0.1%     2.2%  535 563
618    48.7%        +0.8%     2.5%   27 460
827    49.0%        +0.8%     2.4%   68 106
1047   49.0%        +0.0%     3.4%   23 959
1264   48.8%        +0.0%     2.4%   54 007
1455   48.8%        -0.0%     2.4%   69 767
1675   48.8%        -0.0%     2.3%  161 702
1890   47.6%        -0.6%     2.2%   17 628
2042   50.4%        +1.2%     3.7%    1 565
2052   50.7%        -1.3%     1.9%      785
2236   51.7%        -1.3%     1.5%    1 313
2335   47.3%        +1.2%     3.4%    2 964
2398   52.9%        +2.6%     3.7%      208
2406   51.3%        +7.3%     7.3%      413
2550   53.4%        +2.6%     2.4%      313
2656   46.6%        +7.3%     4.8%      637
2840   47.6%        -4.3%     2.5%      164
2862   43.1%        -9.1%     3.6%      232
2956   52.0%        -4.3%     2.2%      248
3030   47.8%        -9.1%     3.8%      429
3129   52.5%        +7.4%     5.0%      902
3163   51.7%        +1.9%     3.1%      567
3465   48.7%        +1.9%     2.0%      575
(39, 12)
              elo server  patch  label champion role role_pickrate tier  \
20           tout   tout  16.30     21  smolder  adc         86.4%    s
226          tout   tout  15.24     15  smolder  adc         82.4%    s
410          tout   tout  15.24    199  smolder  mid         11.3%    d
459          tout    nan  16.30     29  smolder  adc         86.4%    a
675          tout    nan  15.24     25  smolder  adc         82.4%    s
843          tout    nan  15.24    193  smolder  mid         11.3%    d
1024         tout     kr  16.30    150  smolder  adc         86.4%    d
1130         tout     kr  15.24     55  smolder  adc         82.4%    b
1278         tout     kr  15.24    203  smolder  mid         11.3%    d
1306         tout    euw  16.30     28  smolder  adc         86.4%    a
1512         tout    euw  15.24     19  smolder  adc         82.4%    s
1692         tout    euw  15.24    199  smolder  mid         11.3%    d
1771       bronze   tout  16.30     57  smolder  adc         86.4%    a
2112  grandmaster   tout  16.30    189  smolder  adc         81.4%    d
2280  grandmaster   tout  15.24    149  smolder  adc         82.3%    d
2336  grandmaster   tout  15.24    205  smolder  mid         13.6%    d
2603  grandmaster     kr  15.24    110  smolder  adc         82.3%    c
2778  grandmaster    euw  16.30     89  smolder  adc         81.4%    c
2979  grandmaster    euw  15.24    112  smolder  adc         82.3%    c
3051  grandmaster    euw  15.24    184  smolder  mid         13.6%    d
3248   challenger   tout  16.30    166  smolder  adc         78.5%    d
3481   challenger   tout  15.24    189  smolder  adc         79.6%    d
3484   challenger   tout  15.24    192  smolder  mid         16.1%    d
3691   challenger     kr  15.24    103  smolder  adc         79.6%    d
3938   challenger    euw  15.24    117  smolder  adc         79.6%    d
3985       bronze   tout  15.24     41  smolder  adc         82.2%    a
4106       bronze   tout  15.24    162  smolder  mid         10.9%    d
4177       bronze     vn  16.30     19  smolder  adc         86.4%   s+
4240       bronze     vn  16.30     82  smolder  mid          8.7%    b
4296       bronze     vn  16.30    138  smolder  top          4.4%    d
4364       bronze     vn  15.24      6  smolder  adc         82.2%   s+
4435       bronze     vn  15.24     77  smolder  mid         10.9%    b
4440       bronze     vn  15.24     82  smolder  top          6.3%    c
4679       bronze     kr  16.30    121  smolder  adc         86.4%    c
4826       bronze     kr  15.24     73  smolder  adc         82.2%    b
4937       bronze     kr  15.24    184  smolder  top          6.3%    d
5016       bronze    euw  16.30     63  smolder  adc         86.4%    a
5196       bronze    euw  15.24     38  smolder  adc         82.2%    a
5312       bronze    euw  15.24    154  smolder  mid         10.9%    d

     winrate winrate_evol pickrate      games
20     51.4%        -0.1%     9.1%    818 242
226    51.5%        -0.1%     9.6%  2 310 043
410    48.2%        -0.5%     1.3%    318 308
459    50.9%        -0.1%     9.4%    104 611
675    51.0%        -0.1%    10.0%    282 863
843    48.2%        -0.2%     1.3%     35 478
1024   50.2%        -0.8%     3.4%     23 889
1130   51.2%        -0.8%     6.4%    146 142
1278   46.3%        -0.3%     1.0%     23 651
1306   50.9%        -0.2%     9.6%    275 021
1512   51.3%        -0.2%    10.2%    721 465
1692   47.8%        +0.5%     1.3%     94 703
1771   51.0%        -1.0%     7.4%     58 859
2112   47.3%        -0.3%     5.3%      2 260
2280   48.6%        -0.3%     7.1%      6 156
2336   47.8%        -1.0%     1.2%      1 016
2603   50.6%       -10.8%     4.1%        538
2778   51.4%        +6.6%     3.3%        212
2979   50.1%        +6.6%     5.5%        629
3051   47.7%        +7.4%     1.1%        128
3248   48.1%        +0.1%     4.1%        747
3481   46.9%        +0.1%     6.2%      1 831
3484   48.2%        +4.3%     1.3%        371
3691   48.7%       -12.1%     3.3%        187
3938   42.2%        +2.7%     4.6%        173
3985   51.6%        -1.0%     7.8%    208 964
4106   48.9%        +0.7%     1.0%     27 827
4177   53.0%        -0.6%    12.6%      1 403
4240   50.9%        +0.5%     3.5%        391
4296   48.6%        -4.7%     1.6%        181
4364   52.4%        -0.6%    14.8%      9 377
4435   50.2%        +0.5%     4.8%      3 067
4440   50.5%        -4.7%     2.7%      1 704
4679   50.0%        -2.1%     4.1%      1 357
4826   51.1%        -2.1%     6.3%     10 715
4937   47.7%        -4.8%     1.1%      1 812
5016   50.6%        -1.4%     7.8%     23 410
5196   51.5%        -1.4%     8.5%     81 248
5312   49.1%        +1.1%     1.1%     10 402

In [154]:
for r in ["top","jun","mid","adc","sup"]:
    print(
        r,
        (dfs_enhanced_bis[0][f"red_{r}_role"] == r).mean()
    )

top 1.0
jun 1.0
mid 1.0
adc 1.0
sup 1.0

In [65]:
dfs_enhanced = []
for i in range(5):
# for i in range(30):
    dfs_enhanced.append(build_df_enhanced(df_result_norm.iloc[i*1000:(i+1)*1000], df_simple_wr_norm))
    print(f"Batch {i} done")

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

Batch 0 done

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

Batch 1 done

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

Batch 2 done

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

Batch 3 done
Batch 4 done

C:\Users\samue\AppData\Local\Temp\ipykernel_81728\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

In [69]:
dfs_enhanced[0].head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags,blue_adc_champion_patch_float,blue_jun_champion_patch_float,blue_mid_champion_patch_float,blue_sup_champion_patch_float,blue_top_champion_patch_float,red_adc_champion_patch_float,red_jun_champion_patch_float,red_mid_champion_patch_float,red_sup_champion_patch_float,red_top_champion_patch_float,blue_adc_champion_elo_wr,blue_jun_champion_elo_wr,blue_mid_champion_elo_wr,blue_sup_champion_elo_wr,blue_top_champion_elo_wr,red_adc_champion_elo_wr,red_jun_champion_elo_wr,red_mid_champion_elo_wr,red_sup_champion_elo_wr,red_top_champion_elo_wr,blue_adc_champion_server_wr,blue_jun_champion_server_wr,blue_mid_champion_server_wr,blue_sup_champion_server_wr,blue_top_champion_server_wr,red_adc_champion_server_wr,red_jun_champion_server_wr,red_mid_champion_server_wr,red_sup_champion_server_wr,red_top_champion_server_wr,blue_adc_champion_patch_wr,blue_jun_champion_patch_wr,blue_mid_champion_patch_wr,blue_sup_champion_patch_wr,blue_top_champion_patch_wr,red_adc_champion_patch_wr,red_jun_champion_patch_wr,red_mid_champion_patch_wr,red_sup_champion_patch_wr,red_top_champion_patch_wr,blue_adc_champion_label,blue_jun_champion_label,blue_mid_champion_label,blue_sup_champion_label,blue_top_champion_label,red_adc_champion_label,red_jun_champion_label,red_mid_champion_label,red_sup_champion_label,red_top_champion_label,blue_adc_champion_role_wr,blue_jun_champion_role_wr,blue_mid_champion_role_wr,blue_sup_champion_role_wr,blue_top_champion_role_wr,red_adc_champion_role_wr,red_jun_champion_role_wr,red_mid_champion_role_wr,red_sup_champion_role_wr,red_top_champion_role_wr,blue_adc_champion_role_pickrate,blue_jun_champion_role_pickrate,blue_mid_champion_role_pickrate,blue_sup_champion_role_pickrate,blue_top_champion_role_pickrate,red_adc_champion_role_pickrate,red_jun_champion_role_pickrate,red_mid_champion_role_pickrate,red_sup_champion_role_pickrate,red_top_champion_role_pickrate,blue_adc_champion_tier,blue_jun_champion_tier,blue_mid_champion_tier,blue_sup_champion_tier,blue_top_champion_tier,red_adc_champion_tier,red_jun_champion_tier,red_mid_champion_tier,red_sup_champion_tier,red_top_champion_tier,blue_adc_champion_winrate,blue_jun_champion_winrate,blue_mid_champion_winrate,blue_sup_champion_winrate,blue_top_champion_winrate,red_adc_champion_winrate,red_jun_champion_winrate,red_mid_champion_winrate,red_sup_champion_winrate,red_top_champion_winrate,blue_adc_champion_winrate_evol,blue_jun_champion_winrate_evol,blue_mid_champion_winrate_evol,blue_sup_champion_winrate_evol,blue_top_champion_winrate_evol,red_adc_champion_winrate_evol,red_jun_champion_winrate_evol,red_mid_champion_winrate_evol,red_sup_champion_winrate_evol,red_top_champion_winrate_evol,blue_adc_champion_pickrate,blue_jun_champion_pickrate,blue_mid_champion_pickrate,blue_sup_champion_pickrate,blue_top_champion_pickrate,red_adc_champion_pickrate,red_jun_champion_pickrate,red_mid_champion_pickrate,red_sup_champion_pickrate,red_top_champion_pickrate,blue_adc_champion_games,blue_jun_champion_games,blue_mid_champion_games,blue_sup_champion_games,blue_top_champion_games,red_adc_champion_games,red_jun_champion_games,red_mid_champion_games,red_sup_champion_games,red_top_champion_games,blue_adc_champion_patch_float_wr,blue_jun_champion_patch_float_wr,blue_mid_champion_patch_float_wr,blue_sup_champion_patch_float_wr,blue_top_champion_patch_float_wr,red_adc_champion_patch_float_wr,red_jun_champion_patch_float_wr,red_mid_champion_patch_float_wr,red_sup_champion_patch_float_wr,red_top_champion_patch_float_wr,blue_adc_champion_score,blue_jun_champion_score,blue_mid_champion_score,blue_sup_champion_score,blue_top_champion_score,red_adc_champion_score,red_jun_champion_score,red_mid_champion_score,red_sup_champion_score,red_top_champion_score,blue_adc_champion_patch_distance,blue_jun_champion_patch_distance,blue_mid_champion_patch_distance,blue_sup_champion_patch_distance,blue_top_champion_patch_distance,red_adc_champion_patch_distance,red_jun_champion_patch_distance,red_mid_champion_patch_distance,red_sup_champion_patch_distance,red_top_champion_patch_distance
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,145.0,17.0,170.0,18.0,103.0,125.0,128.0,88.0,37.0,adc,jun,jun,sup,top,adc,jun,mid,sup,mid,99.1%,66.5%,59.9%,99.0%,91.0%,97.9%,71.7%,69.2%,98.2%,69.3%,a,d,s,d,s,c,c,c,c,a,50.4%,49.3%,51.0%,49.3%,52.1%,50.0%,50.4%,50.5%,50.3%,50.1%,-0.1%,+0.2%,-1.4%,-0.0%,+0.1%,-0.2%,+0.1%,+0.1%,+0.5%,-0.6%,13.2%,3.6%,8.5%,2.8%,7.8%,5.6%,2.8%,1.9%,5.5%,8.2%,926 671,250 800,596 627,197 059,550 219,390 800,199 830,135 885,390 527,578 608,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,215.0,196.0,37.0,9.0,24.0,161.0,174.0,50.0,88.0,12.0,adc,mid,mid,sup,top,sup,jun,mid,sup,jun,76.7%,41.6%,69.3%,99.8%,89.0%,87.8%,99.1%,93.8%,98.2%,51.6%,d,d,a,s+,s,d,d,a,c,s,46.8%,47.9%,50.1%,52.2%,50.9%,49.2%,49.2%,50.8%,50.3%,51.8%,-0.4%,-0.1%,-0.6%,+0.1%,+0.6%,+0.2%,+1.2%,-0.1%,+0.5%,-0.3%,1.2%,2.0%,8.2%,11.8%,7.6%,4.3%,2.4%,6.6%,5.5%,6.6%,85 174,143 285,578 608,830 890,535 221,304 029,168 423,466 357,390 527,464 917,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support'],15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,197.0,138.0,7.0,19.0,1.0,55.0,59.0,180.0,149.0,adc,jun,mid,sup,adc,adc,jun,mid,sup,top,99.1%,96.9%,79.3%,99.6%,82.4%,97.3%,93.4%,51.2%,98.4%,74.3%,a,d,d,s+,s,s+,b,b,d,d,50.4%,48.0%,49.9%,52.5%,51.3%,52.5%,50.1%,51.3%,48.9%,49.9%,-0.1%,+0.6%,-0.3%,-0.2%,-0.2%,-0.1%,+0.9%,-0.1%,+0.2%,-0.1%,13.2%,2.6%,3.3%,8.2%,10.2%,25.4%,7.9%,4.2%,3.2%,2.0%,926 671,182 657,231 877,577 543,721 465,1 788 527,554 875,294 187,226 732,143 656,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,194.0,219.0,72.0,180.0,16.0,79.0,195.0,59.0,81.0,110.0,adc,jun,mid,sup,jun,adc,jun,mid,sup,top,98.4%,77.5%,84.0%,98.4%,82.0%,97.0%,82.1%,51.2%,98.8%,64.4%,d,d,c,d,s,c,d,b,c,c,46.9%,45.4%,49.1%,48.9%,51.9%,48.7%,48.8%,51.3%,51.8%,50.1%,-0.1%,+0.2%,+0.5%,+0.2%,+0.1%,+0.5%,+0.3%,-0.1%,-0.5%,+0.6%,6.1%,1.5%,6.9%,3.2%,6.5%,14.0%,1.1%,4.2%,2.8%,4.4%,427 211,108 444,483 002,226 732,456 214,985 376,76 336,294 187,195 095,310 162,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07

In [73]:
df_simple_wr_norm["patch"].unique()

array([16.3 , 15.24])

In [125]:
dfs_enhanced = []
for i in range(1):
# for i in range(30):
    dfs_enhanced.append(build_df_enhanced(df_result_norm.iloc[i*100000:(i+1)*100000], df_simple_wr_norm))
    print(f"Batch {i} done")

C:\Users\samue\AppData\Local\Temp\ipykernel_80040\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

Batch 0 done

In [130]:
df_enhanced_100000.head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags,blue_adc_champion_patch_float,blue_jun_champion_patch_float,blue_mid_champion_patch_float,blue_sup_champion_patch_float,blue_top_champion_patch_float,red_adc_champion_patch_float,red_jun_champion_patch_float,red_mid_champion_patch_float,red_sup_champion_patch_float,red_top_champion_patch_float,blue_adc_champion_elo_wr,blue_jun_champion_elo_wr,blue_mid_champion_elo_wr,blue_sup_champion_elo_wr,blue_top_champion_elo_wr,red_adc_champion_elo_wr,red_jun_champion_elo_wr,red_mid_champion_elo_wr,red_sup_champion_elo_wr,red_top_champion_elo_wr,blue_adc_champion_server_wr,blue_jun_champion_server_wr,blue_mid_champion_server_wr,blue_sup_champion_server_wr,blue_top_champion_server_wr,red_adc_champion_server_wr,red_jun_champion_server_wr,red_mid_champion_server_wr,red_sup_champion_server_wr,red_top_champion_server_wr,blue_adc_champion_patch_wr,blue_jun_champion_patch_wr,blue_mid_champion_patch_wr,blue_sup_champion_patch_wr,blue_top_champion_patch_wr,red_adc_champion_patch_wr,red_jun_champion_patch_wr,red_mid_champion_patch_wr,red_sup_champion_patch_wr,red_top_champion_patch_wr,blue_adc_champion_label,blue_jun_champion_label,blue_mid_champion_label,blue_sup_champion_label,blue_top_champion_label,red_adc_champion_label,red_jun_champion_label,red_mid_champion_label,red_sup_champion_label,red_top_champion_label,blue_adc_champion_role_wr,blue_jun_champion_role_wr,blue_mid_champion_role_wr,blue_sup_champion_role_wr,blue_top_champion_role_wr,red_adc_champion_role_wr,red_jun_champion_role_wr,red_mid_champion_role_wr,red_sup_champion_role_wr,red_top_champion_role_wr,blue_adc_champion_role_pickrate,blue_jun_champion_role_pickrate,blue_mid_champion_role_pickrate,blue_sup_champion_role_pickrate,blue_top_champion_role_pickrate,red_adc_champion_role_pickrate,red_jun_champion_role_pickrate,red_mid_champion_role_pickrate,red_sup_champion_role_pickrate,red_top_champion_role_pickrate,blue_adc_champion_tier,blue_jun_champion_tier,blue_mid_champion_tier,blue_sup_champion_tier,blue_top_champion_tier,red_adc_champion_tier,red_jun_champion_tier,red_mid_champion_tier,red_sup_champion_tier,red_top_champion_tier,blue_adc_champion_winrate,blue_jun_champion_winrate,blue_mid_champion_winrate,blue_sup_champion_winrate,blue_top_champion_winrate,red_adc_champion_winrate,red_jun_champion_winrate,red_mid_champion_winrate,red_sup_champion_winrate,red_top_champion_winrate,blue_adc_champion_winrate_evol,blue_jun_champion_winrate_evol,blue_mid_champion_winrate_evol,blue_sup_champion_winrate_evol,blue_top_champion_winrate_evol,red_adc_champion_winrate_evol,red_jun_champion_winrate_evol,red_mid_champion_winrate_evol,red_sup_champion_winrate_evol,red_top_champion_winrate_evol,blue_adc_champion_pickrate,blue_jun_champion_pickrate,blue_mid_champion_pickrate,blue_sup_champion_pickrate,blue_top_champion_pickrate,red_adc_champion_pickrate,red_jun_champion_pickrate,red_mid_champion_pickrate,red_sup_champion_pickrate,red_top_champion_pickrate,blue_adc_champion_games,blue_jun_champion_games,blue_mid_champion_games,blue_sup_champion_games,blue_top_champion_games,red_adc_champion_games,red_jun_champion_games,red_mid_champion_games,red_sup_champion_games,red_top_champion_games,blue_adc_champion_patch_float_wr,blue_jun_champion_patch_float_wr,blue_mid_champion_patch_float_wr,blue_sup_champion_patch_float_wr,blue_top_champion_patch_float_wr,red_adc_champion_patch_float_wr,red_jun_champion_patch_float_wr,red_mid_champion_patch_float_wr,red_sup_champion_patch_float_wr,red_top_champion_patch_float_wr,blue_adc_champion_score,blue_jun_champion_score,blue_mid_champion_score,blue_sup_champion_score,blue_top_champion_score,red_adc_champion_score,red_jun_champion_score,red_mid_champion_score,red_sup_champion_score,red_top_champion_score,blue_adc_champion_patch_distance,blue_jun_champion_patch_distance,blue_mid_champion_patch_distance,blue_sup_champion_patch_distance,blue_top_champion_patch_distance,red_adc_champion_patch_distance,red_jun_champion_patch_distance,red_mid_champion_patch_distance,red_sup_champion_patch_distance,red_top_champion_patch_distance
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,145.0,17.0,170.0,18.0,103.0,125.0,128.0,88.0,37.0,adc,jun,jun,sup,top,adc,jun,mid,sup,mid,99.1%,66.5%,59.9%,99.0%,91.0%,97.9%,71.7%,69.2%,98.2%,69.3%,a,d,s,d,s,c,c,c,c,a,50.4%,49.3%,51.0%,49.3%,52.1%,50.0%,50.4%,50.5%,50.3%,50.1%,-0.1%,+0.2%,-1.4%,-0.0%,+0.1%,-0.2%,+0.1%,+0.1%,+0.5%,-0.6%,13.2%,3.6%,8.5%,2.8%,7.8%,5.6%,2.8%,1.9%,5.5%,8.2%,926 671,250 800,596 627,197 059,550 219,390 800,199 830,135 885,390 527,578 608,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,215.0,196.0,37.0,9.0,24.0,161.0,174.0,50.0,88.0,12.0,adc,mid,mid,sup,top,sup,jun,mid,sup,jun,76.7%,41.6%,69.3%,99.8%,89.0%,87.8%,99.1%,93.8%,98.2%,51.6%,d,d,a,s+,s,d,d,a,c,s,46.8%,47.9%,50.1%,52.2%,50.9%,49.2%,49.2%,50.8%,50.3%,51.8%,-0.4%,-0.1%,-0.6%,+0.1%,+0.6%,+0.2%,+1.2%,-0.1%,+0.5%,-0.3%,1.2%,2.0%,8.2%,11.8%,7.6%,4.3%,2.4%,6.6%,5.5%,6.6%,85 174,143 285,578 608,830 890,535 221,304 029,168 423,466 357,390 527,464 917,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support'],15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29.0,197.0,138.0,7.0,19.0,1.0,55.0,59.0,180.0,149.0,adc,jun,mid,sup,adc,adc,jun,mid,sup,top,99.1%,96.9%,79.3%,99.6%,82.4%,97.3%,93.4%,51.2%,98.4%,74.3%,a,d,d,s+,s,s+,b,b,d,d,50.4%,48.0%,49.9%,52.5%,51.3%,52.5%,50.1%,51.3%,48.9%,49.9%,-0.1%,+0.6%,-0.3%,-0.2%,-0.2%,-0.1%,+0.9%,-0.1%,+0.2%,-0.1%,13.2%,2.6%,3.3%,8.2%,10.2%,25.4%,7.9%,4.2%,3.2%,2.0%,926 671,182 657,231 877,577 543,721 465,1 788 527,554 875,294 187,226 732,143 656,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,194.0,219.0,72.0,180.0,16.0,79.0,195.0,59.0,81.0,110.0,adc,jun,mid,sup,jun,adc,jun,mid,sup,top,98.4%,77.5%,84.0%,98.4%,82.0%,97.0%,82.1%,51.2%,98.8%,64.4%,d,d,c,d,s,c,d,b,c,c,46.9%,45.4%,49.1%,48.9%,51.9%,48.7%,48.8%,51.3%,51.8%,50.1%,-0.1%,+0.2%,+0.5%,+0.2%,+0.1%,+0.5%,+0.3%,-0.1%,-0.5%,+0.6%,6.1%,1.5%,6.9%,3.2%,6.5%,14.0%,1.1%,4.2%,2.8%,4.4%,427 211,108 444,483 002,226 732,456 214,985 376,76 336,294 187,195 095,310 162,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07

In [142]:
df_enhanced_100000[(df_enhanced_100000["red_mid_champion_patch_distance"].isna()) & (df_enhanced_100000["red_mid_champion"] != "nan")].head(20)

Empty DataFrame
Columns: [match_id, server, patch, elo, blue_side_win, blue_top_champion, blue_jun_champion, blue_mid_champion, blue_adc_champion, blue_sup_champion, red_top_champion, red_jun_champion, red_mid_champion, red_adc_champion, red_sup_champion, blue_top_info_attack, blue_top_info_defense, blue_top_info_difficulty, blue_top_info_magic, blue_top_stats_armor, blue_top_stats_armorperlevel, blue_top_stats_attackdamage, blue_top_stats_attackdamageperlevel, blue_top_stats_attackrange, blue_top_stats_attackspeed, blue_top_stats_attackspeedperlevel, blue_top_stats_crit, blue_top_stats_critperlevel, blue_top_stats_hp, blue_top_stats_hpperlevel, blue_top_stats_hpregen, blue_top_stats_hpregenperlevel, blue_top_stats_movespeed, blue_top_stats_mp, blue_top_stats_mpperlevel, blue_top_stats_mpregen, blue_top_stats_mpregenperlevel, blue_top_stats_spellblock, blue_top_stats_spellblockperlevel, blue_top_tags, blue_jungle_info_attack, blue_jungle_info_defense, blue_jungle_info_difficulty, blue_jungle_info_magic, blue_jungle_stats_armor, blue_jungle_stats_armorperlevel, blue_jungle_stats_attackdamage, blue_jungle_stats_attackdamageperlevel, blue_jungle_stats_attackrange, blue_jungle_stats_attackspeed, blue_jungle_stats_attackspeedperlevel, blue_jungle_stats_crit, blue_jungle_stats_critperlevel, blue_jungle_stats_hp, blue_jungle_stats_hpperlevel, blue_jungle_stats_hpregen, blue_jungle_stats_hpregenperlevel, blue_jungle_stats_movespeed, blue_jungle_stats_mp, blue_jungle_stats_mpperlevel, blue_jungle_stats_mpregen, blue_jungle_stats_mpregenperlevel, blue_jungle_stats_spellblock, blue_jungle_stats_spellblockperlevel, blue_jungle_tags, blue_mid_info_attack, blue_mid_info_defense, blue_mid_info_difficulty, blue_mid_info_magic, blue_mid_stats_armor, blue_mid_stats_armorperlevel, blue_mid_stats_attackdamage, blue_mid_stats_attackdamageperlevel, blue_mid_stats_attackrange, blue_mid_stats_attackspeed, blue_mid_stats_attackspeedperlevel, blue_mid_stats_crit, blue_mid_stats_critperlevel, blue_mid_stats_hp, blue_mid_stats_hpperlevel, blue_mid_stats_hpregen, blue_mid_stats_hpregenperlevel, blue_mid_stats_movespeed, blue_mid_stats_mp, blue_mid_stats_mpperlevel, blue_mid_stats_mpregen, blue_mid_stats_mpregenperlevel, blue_mid_stats_spellblock, blue_mid_stats_spellblockperlevel, blue_mid_tags, blue_adc_info_attack, blue_adc_info_defense, blue_adc_info_difficulty, blue_adc_info_magic, blue_adc_stats_armor, blue_adc_stats_armorperlevel, blue_adc_stats_attackdamage, blue_adc_stats_attackdamageperlevel, blue_adc_stats_attackrange, blue_adc_stats_attackspeed, ...]
Index: []

In [ ]:
est ce qu'on trouve des wr simples meme pour les champions pour lesquels on de vrait pas ? (car il n'y a que 218 wr simples)'

In [ ]:
df_enhanced = build_df_enhanced(df_result_norm.iloc[:10000, :], df_simple_wr_norm)

C:\Users\samue\AppData\Local\Temp\ipykernel_80040\4063607101.py:3: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  idx = df_scored.groupby(["match_id","role"]) \

In [119]:
df_enhanced.head()

,match_id,server,patch,elo,blue_side_win,blue_top_champion,blue_jun_champion,blue_mid_champion,blue_adc_champion,blue_sup_champion,red_top_champion,red_jun_champion,red_mid_champion,red_adc_champion,red_sup_champion,blue_top_info_attack,blue_top_info_defense,blue_top_info_difficulty,blue_top_info_magic,blue_top_stats_armor,blue_top_stats_armorperlevel,blue_top_stats_attackdamage,blue_top_stats_attackdamageperlevel,blue_top_stats_attackrange,blue_top_stats_attackspeed,blue_top_stats_attackspeedperlevel,blue_top_stats_crit,blue_top_stats_critperlevel,blue_top_stats_hp,blue_top_stats_hpperlevel,blue_top_stats_hpregen,blue_top_stats_hpregenperlevel,blue_top_stats_movespeed,blue_top_stats_mp,blue_top_stats_mpperlevel,blue_top_stats_mpregen,blue_top_stats_mpregenperlevel,blue_top_stats_spellblock,blue_top_stats_spellblockperlevel,blue_top_tags,blue_jungle_info_attack,blue_jungle_info_defense,blue_jungle_info_difficulty,blue_jungle_info_magic,blue_jungle_stats_armor,blue_jungle_stats_armorperlevel,blue_jungle_stats_attackdamage,blue_jungle_stats_attackdamageperlevel,blue_jungle_stats_attackrange,blue_jungle_stats_attackspeed,blue_jungle_stats_attackspeedperlevel,blue_jungle_stats_crit,blue_jungle_stats_critperlevel,blue_jungle_stats_hp,blue_jungle_stats_hpperlevel,blue_jungle_stats_hpregen,blue_jungle_stats_hpregenperlevel,blue_jungle_stats_movespeed,blue_jungle_stats_mp,blue_jungle_stats_mpperlevel,blue_jungle_stats_mpregen,blue_jungle_stats_mpregenperlevel,blue_jungle_stats_spellblock,blue_jungle_stats_spellblockperlevel,blue_jungle_tags,blue_mid_info_attack,blue_mid_info_defense,blue_mid_info_difficulty,blue_mid_info_magic,blue_mid_stats_armor,blue_mid_stats_armorperlevel,blue_mid_stats_attackdamage,blue_mid_stats_attackdamageperlevel,blue_mid_stats_attackrange,blue_mid_stats_attackspeed,blue_mid_stats_attackspeedperlevel,blue_mid_stats_crit,blue_mid_stats_critperlevel,blue_mid_stats_hp,blue_mid_stats_hpperlevel,blue_mid_stats_hpregen,blue_mid_stats_hpregenperlevel,blue_mid_stats_movespeed,blue_mid_stats_mp,blue_mid_stats_mpperlevel,blue_mid_stats_mpregen,blue_mid_stats_mpregenperlevel,blue_mid_stats_spellblock,blue_mid_stats_spellblockperlevel,blue_mid_tags,blue_adc_info_attack,blue_adc_info_defense,blue_adc_info_difficulty,blue_adc_info_magic,blue_adc_stats_armor,blue_adc_stats_armorperlevel,blue_adc_stats_attackdamage,blue_adc_stats_attackdamageperlevel,blue_adc_stats_attackrange,blue_adc_stats_attackspeed,blue_adc_stats_attackspeedperlevel,blue_adc_stats_crit,blue_adc_stats_critperlevel,blue_adc_stats_hp,blue_adc_stats_hpperlevel,blue_adc_stats_hpregen,blue_adc_stats_hpregenperlevel,blue_adc_stats_movespeed,blue_adc_stats_mp,blue_adc_stats_mpperlevel,blue_adc_stats_mpregen,blue_adc_stats_mpregenperlevel,blue_adc_stats_spellblock,blue_adc_stats_spellblockperlevel,blue_adc_tags,blue_support_info_attack,blue_support_info_defense,blue_support_info_difficulty,blue_support_info_magic,blue_support_stats_armor,blue_support_stats_armorperlevel,blue_support_stats_attackdamage,blue_support_stats_attackdamageperlevel,blue_support_stats_attackrange,blue_support_stats_attackspeed,blue_support_stats_attackspeedperlevel,blue_support_stats_crit,blue_support_stats_critperlevel,blue_support_stats_hp,blue_support_stats_hpperlevel,blue_support_stats_hpregen,blue_support_stats_hpregenperlevel,blue_support_stats_movespeed,blue_support_stats_mp,blue_support_stats_mpperlevel,blue_support_stats_mpregen,blue_support_stats_mpregenperlevel,blue_support_stats_spellblock,blue_support_stats_spellblockperlevel,blue_support_tags,red_top_info_attack,red_top_info_defense,red_top_info_difficulty,red_top_info_magic,red_top_stats_armor,red_top_stats_armorperlevel,red_top_stats_attackdamage,red_top_stats_attackdamageperlevel,red_top_stats_attackrange,red_top_stats_attackspeed,red_top_stats_attackspeedperlevel,red_top_stats_crit,red_top_stats_critperlevel,red_top_stats_hp,red_top_stats_hpperlevel,red_top_stats_hpregen,red_top_stats_hpregenperlevel,red_top_stats_movespeed,red_top_stats_mp,red_top_stats_mpperlevel,red_top_stats_mpregen,red_top_stats_mpregenperlevel,red_top_stats_spellblock,red_top_stats_spellblockperlevel,red_top_tags,red_jungle_info_attack,red_jungle_info_defense,red_jungle_info_difficulty,red_jungle_info_magic,red_jungle_stats_armor,red_jungle_stats_armorperlevel,red_jungle_stats_attackdamage,red_jungle_stats_attackdamageperlevel,red_jungle_stats_attackrange,red_jungle_stats_attackspeed,red_jungle_stats_attackspeedperlevel,red_jungle_stats_crit,red_jungle_stats_critperlevel,red_jungle_stats_hp,red_jungle_stats_hpperlevel,red_jungle_stats_hpregen,red_jungle_stats_hpregenperlevel,red_jungle_stats_movespeed,red_jungle_stats_mp,red_jungle_stats_mpperlevel,red_jungle_stats_mpregen,red_jungle_stats_mpregenperlevel,red_jungle_stats_spellblock,red_jungle_stats_spellblockperlevel,red_jungle_tags,red_mid_info_attack,red_mid_info_defense,red_mid_info_difficulty,red_mid_info_magic,red_mid_stats_armor,red_mid_stats_armorperlevel,red_mid_stats_attackdamage,red_mid_stats_attackdamageperlevel,red_mid_stats_attackrange,red_mid_stats_attackspeed,red_mid_stats_attackspeedperlevel,red_mid_stats_crit,red_mid_stats_critperlevel,red_mid_stats_hp,red_mid_stats_hpperlevel,red_mid_stats_hpregen,red_mid_stats_hpregenperlevel,red_mid_stats_movespeed,red_mid_stats_mp,red_mid_stats_mpperlevel,red_mid_stats_mpregen,red_mid_stats_mpregenperlevel,red_mid_stats_spellblock,red_mid_stats_spellblockperlevel,red_mid_tags,red_adc_info_attack,red_adc_info_defense,red_adc_info_difficulty,red_adc_info_magic,red_adc_stats_armor,red_adc_stats_armorperlevel,red_adc_stats_attackdamage,red_adc_stats_attackdamageperlevel,red_adc_stats_attackrange,red_adc_stats_attackspeed,red_adc_stats_attackspeedperlevel,red_adc_stats_crit,red_adc_stats_critperlevel,red_adc_stats_hp,red_adc_stats_hpperlevel,red_adc_stats_hpregen,red_adc_stats_hpregenperlevel,red_adc_stats_movespeed,red_adc_stats_mp,red_adc_stats_mpperlevel,red_adc_stats_mpregen,red_adc_stats_mpregenperlevel,red_adc_stats_spellblock,red_adc_stats_spellblockperlevel,red_adc_tags,red_support_info_attack,red_support_info_defense,red_support_info_difficulty,red_support_info_magic,red_support_stats_armor,red_support_stats_armorperlevel,red_support_stats_attackdamage,red_support_stats_attackdamageperlevel,red_support_stats_attackrange,red_support_stats_attackspeed,red_support_stats_attackspeedperlevel,red_support_stats_crit,red_support_stats_critperlevel,red_support_stats_hp,red_support_stats_hpperlevel,red_support_stats_hpregen,red_support_stats_hpregenperlevel,red_support_stats_movespeed,red_support_stats_mp,red_support_stats_mpperlevel,red_support_stats_mpregen,red_support_stats_mpregenperlevel,red_support_stats_spellblock,red_support_stats_spellblockperlevel,red_support_tags,blue_adc_champion_patch_float,blue_jun_champion_patch_float,blue_mid_champion_patch_float,blue_sup_champion_patch_float,blue_top_champion_patch_float,red_adc_champion_patch_float,red_jun_champion_patch_float,red_mid_champion_patch_float,red_sup_champion_patch_float,red_top_champion_patch_float,blue_adc_champion_elo_wr,blue_jun_champion_elo_wr,blue_mid_champion_elo_wr,blue_sup_champion_elo_wr,blue_top_champion_elo_wr,red_adc_champion_elo_wr,red_jun_champion_elo_wr,red_mid_champion_elo_wr,red_sup_champion_elo_wr,red_top_champion_elo_wr,blue_adc_champion_server_wr,blue_jun_champion_server_wr,blue_mid_champion_server_wr,blue_sup_champion_server_wr,blue_top_champion_server_wr,red_adc_champion_server_wr,red_jun_champion_server_wr,red_mid_champion_server_wr,red_sup_champion_server_wr,red_top_champion_server_wr,blue_adc_champion_patch_wr,blue_jun_champion_patch_wr,blue_mid_champion_patch_wr,blue_sup_champion_patch_wr,blue_top_champion_patch_wr,red_adc_champion_patch_wr,red_jun_champion_patch_wr,red_mid_champion_patch_wr,red_sup_champion_patch_wr,red_top_champion_patch_wr,blue_adc_champion_label,blue_jun_champion_label,blue_mid_champion_label,blue_sup_champion_label,blue_top_champion_label,red_adc_champion_label,red_jun_champion_label,red_mid_champion_label,red_sup_champion_label,red_top_champion_label,blue_adc_champion_role_wr,blue_jun_champion_role_wr,blue_mid_champion_role_wr,blue_sup_champion_role_wr,blue_top_champion_role_wr,red_adc_champion_role_wr,red_jun_champion_role_wr,red_mid_champion_role_wr,red_sup_champion_role_wr,red_top_champion_role_wr,blue_adc_champion_role_pickrate,blue_jun_champion_role_pickrate,blue_mid_champion_role_pickrate,blue_sup_champion_role_pickrate,blue_top_champion_role_pickrate,red_adc_champion_role_pickrate,red_jun_champion_role_pickrate,red_mid_champion_role_pickrate,red_sup_champion_role_pickrate,red_top_champion_role_pickrate,blue_adc_champion_tier,blue_jun_champion_tier,blue_mid_champion_tier,blue_sup_champion_tier,blue_top_champion_tier,red_adc_champion_tier,red_jun_champion_tier,red_mid_champion_tier,red_sup_champion_tier,red_top_champion_tier,blue_adc_champion_winrate,blue_jun_champion_winrate,blue_mid_champion_winrate,blue_sup_champion_winrate,blue_top_champion_winrate,red_adc_champion_winrate,red_jun_champion_winrate,red_mid_champion_winrate,red_sup_champion_winrate,red_top_champion_winrate,blue_adc_champion_winrate_evol,blue_jun_champion_winrate_evol,blue_mid_champion_winrate_evol,blue_sup_champion_winrate_evol,blue_top_champion_winrate_evol,red_adc_champion_winrate_evol,red_jun_champion_winrate_evol,red_mid_champion_winrate_evol,red_sup_champion_winrate_evol,red_top_champion_winrate_evol,blue_adc_champion_pickrate,blue_jun_champion_pickrate,blue_mid_champion_pickrate,blue_sup_champion_pickrate,blue_top_champion_pickrate,red_adc_champion_pickrate,red_jun_champion_pickrate,red_mid_champion_pickrate,red_sup_champion_pickrate,red_top_champion_pickrate,blue_adc_champion_games,blue_jun_champion_games,blue_mid_champion_games,blue_sup_champion_games,blue_top_champion_games,red_adc_champion_games,red_jun_champion_games,red_mid_champion_games,red_sup_champion_games,red_top_champion_games,blue_adc_champion_patch_float_wr,blue_jun_champion_patch_float_wr,blue_mid_champion_patch_float_wr,blue_sup_champion_patch_float_wr,blue_top_champion_patch_float_wr,red_adc_champion_patch_float_wr,red_jun_champion_patch_float_wr,red_mid_champion_patch_float_wr,red_sup_champion_patch_float_wr,red_top_champion_patch_float_wr,blue_adc_champion_score,blue_jun_champion_score,blue_mid_champion_score,blue_sup_champion_score,blue_top_champion_score,red_adc_champion_score,red_jun_champion_score,red_mid_champion_score,red_sup_champion_score,red_top_champion_score,blue_adc_champion_patch_distance,blue_jun_champion_patch_distance,blue_mid_champion_patch_distance,blue_sup_champion_patch_distance,blue_top_champion_patch_distance,red_adc_champion_patch_distance,red_jun_champion_patch_distance,red_mid_champion_patch_distance,red_sup_champion_patch_distance,red_top_champion_patch_distance
0,euw1_7517331727,euw,15.17,high_elo,False,sett,talon,diana,jinx,rell,yasuo,fiddlesticks,cassiopeia,aphelios,bard,8.0,5.0,2.0,1.0,33.0,4.7,60.0,4.00,125.0,0.625,1.75,0.0,0.0,670.0,114.0,7.00,0.50,340.0,0.0,0.0,0.00,0.0,28.0,2.05,"['fighter', 'tank']",9.0,3.0,7.0,1.0,30.0,4.7,68.0,3.10,125.0,0.625,2.90,0.0,0.0,658.0,109.0,8.5,0.75,335.0,400.0,37.0,7.60,0.80,36.0,2.05,['assassin'],7.0,6.0,4.0,8.0,31.0,4.3,57.0,3.0,150.0,0.625,2.00,0.0,0.0,640.0,109.0,6.50,0.85,345.0,375.0,25.0,8.00,0.8,32.0,2.05,"['fighter', 'assassin']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],0.0,0.0,0.0,0.0,30.0,4.0,55.0,3.0,175.0,0.625,2.00,0.0,0.0,620.0,104.0,7.5,0.85,315.0,320.0,40.0,7.00,0.7,28.0,1.80,"['tank', 'support']",8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.50,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.5,0.90,345.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'assassin']",2.0,3.0,9.0,9.0,34.0,4.70,55.0,2.65,480.0,0.625,2.11,0.0,0.0,650.0,106.0,5.5,0.60,335.0,500.0,28.0,8.0,0.80,30.0,1.30,"['mage', 'support']",2.0,3.0,10.0,9.0,18.0,4.7,53.0,3.0,550.0,0.647,1.50,0.0,0.0,630.0,104.0,5.5,0.50,328.0,400.0,40.0,8.00,0.8,32.0,1.30,['mage'],6.0,2.0,10.0,1.0,26.0,4.2,55.0,2.3,550.0,0.665,2.1,0.0,0.0,600.0,102.0,3.25,0.55,325.0,348.0,42.0,6.5,0.4,30.0,1.3,['marksman'],4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29,145,17,170,18,103,125,128,88,37,adc,jun,jun,sup,top,adc,jun,mid,sup,mid,99.1%,66.5%,59.9%,99.0%,91.0%,97.9%,71.7%,69.2%,98.2%,69.3%,a,d,s,d,s,c,c,c,c,a,50.4%,49.3%,51.0%,49.3%,52.1%,50.0%,50.4%,50.5%,50.3%,50.1%,-0.1%,+0.2%,-1.4%,-0.0%,+0.1%,-0.2%,+0.1%,+0.1%,+0.5%,-0.6%,13.2%,3.6%,8.5%,2.8%,7.8%,5.6%,2.8%,1.9%,5.5%,8.2%,926 671,250 800,596 627,197 059,550 219,390 800,199 830,135 885,390 527,578 608,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
1,euw1_7509322616,euw,15.17,high_elo,False,mordekaiser,qiyana,yasuo,corki,nami,jax,hecarim,syndra,senna,bard,4.0,6.0,4.0,7.0,37.0,4.2,61.0,4.00,175.0,0.625,1.00,0.0,0.0,645.0,104.0,5.00,0.75,335.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'mage']",0.0,2.0,8.0,4.0,31.0,4.7,66.0,3.10,150.0,0.688,2.10,0.0,0.0,590.0,124.0,8.0,0.90,335.0,375.0,60.0,8.00,0.70,32.0,2.05,['assassin'],8.0,4.0,10.0,4.0,32.0,4.6,60.0,2.5,175.0,0.697,3.50,0.0,0.0,590.0,110.0,6.50,0.90,345.0,100.0,0.0,0.00,0.0,32.0,2.05,"['fighter', 'assassin']",8.0,3.0,6.0,6.0,27.0,4.5,52.0,2.00,550.0,0.644,2.8,0.0,0.0,610.0,100.0,5.50,0.55,325.0,350.0,40.0,7.4,0.70,30.0,1.3,"['marksman', 'mage']",4.0,3.0,5.0,7.0,29.0,5.2,54.0,3.1,550.0,0.644,2.61,0.0,0.0,560.0,88.0,5.5,0.55,335.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",7.0,5.0,5.0,7.0,36.0,4.2,68.0,4.25,125.0,0.638,3.40,0.0,0.0,665.0,103.0,8.5,0.55,350.0,339.0,52.0,8.2,0.70,32.0,2.05,['fighter'],8.0,6.0,6.0,4.0,32.0,5.45,66.0,3.70,175.0,0.670,2.50,0.0,0.0,625.0,106.0,7.0,0.75,345.0,280.0,40.0,7.0,0.80,32.0,2.05,"['fighter', 'tank']",2.0,3.0,8.0,9.0,25.0,4.6,54.0,2.9,550.0,0.658,2.00,0.0,0.0,563.0,104.0,6.5,0.60,330.0,480.0,40.0,8.00,0.8,30.0,1.30,['mage'],7.0,2.0,7.0,6.0,25.0,4.0,50.0,0.0,600.0,0.625,3.0,0.0,0.0,530.0,89.0,3.50,0.55,330.0,350.0,45.0,11.5,0.7,30.0,1.3,"['support', 'marksman']",4.0,4.0,9.0,5.0,34.0,5.0,52.0,3.0,500.0,0.658,2.0,0.0,0.0,630.0,103.0,5.5,0.55,335.0,350.0,50.0,6.00,0.45,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,215,196,37,9,24,161,174,50,88,12,adc,mid,mid,sup,top,sup,jun,mid,sup,jun,76.7%,41.6%,69.3%,99.8%,89.0%,87.8%,99.1%,93.8%,98.2%,51.6%,d,d,a,s+,s,d,d,a,c,s,46.8%,47.9%,50.1%,52.2%,50.9%,49.2%,49.2%,50.8%,50.3%,51.8%,-0.4%,-0.1%,-0.6%,+0.1%,+0.6%,+0.2%,+1.2%,-0.1%,+0.5%,-0.3%,1.2%,2.0%,8.2%,11.8%,7.6%,4.3%,2.4%,6.6%,5.5%,6.6%,85 174,143 285,578 608,830 890,535 221,304 029,168 423,466 357,390 527,464 917,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
2,euw1_7509243675,euw,15.17,high_elo,False,smolder,kindred,galio,jinx,milio,quinn,kayn,xerath,missfortune,rakan,8.0,2.0,6.0,5.0,24.0,4.7,60.0,2.30,550.0,0.638,4.00,0.0,0.0,575.0,100.0,3.75,0.60,330.0,300.0,40.0,8.50,0.7,30.0,1.30,"['marksman', 'mage']",8.0,2.0,4.0,2.0,29.0,4.7,65.0,3.25,500.0,0.625,3.50,0.0,0.0,595.0,104.0,7.0,0.55,325.0,300.0,35.0,7.00,0.40,30.0,1.30,['marksman'],1.0,10.0,5.0,6.0,24.0,4.7,59.0,3.5,150.0,0.625,1.50,0.0,0.0,600.0,126.0,8.00,0.80,340.0,410.0,40.0,9.50,0.7,32.0,2.05,"['tank', 'mage']",9.0,2.0,6.0,4.0,26.0,4.7,59.0,3.25,525.0,0.625,1.4,0.0,0.0,630.0,105.0,3.75,0.50,325.0,260.0,50.0,6.7,1.00,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,26.0,4.6,48.0,3.2,525.0,0.625,3.00,0.0,0.0,560.0,88.0,5.0,0.50,330.0,365.0,43.0,11.50,0.4,30.0,1.30,"['support', 'mage']",9.0,4.0,5.0,2.0,28.0,4.7,59.0,2.70,525.0,0.668,3.10,0.0,0.0,565.0,107.0,5.5,0.55,330.0,269.0,35.0,7.0,0.40,30.0,1.30,"['marksman', 'assassin']",10.0,6.0,8.0,1.0,38.0,4.50,68.0,3.30,175.0,0.669,2.70,0.0,0.0,655.0,103.0,8.0,0.75,340.0,410.0,50.0,11.5,0.95,32.0,2.05,"['fighter', 'assassin']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,2.0,1.0,5.0,25.0,4.0,55.0,2.4,550.0,0.656,3.0,0.0,0.0,640.0,103.0,3.75,0.65,325.0,300.0,40.0,8.0,0.8,30.0,1.3,"['marksman', 'mage']",2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.0,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.50,32.0,2.05,['support'],15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,29,197,138,7,19,1,55,59,180,149,adc,jun,mid,sup,adc,adc,jun,mid,sup,top,99.1%,96.9%,79.3%,99.6%,82.4%,97.3%,93.4%,51.2%,98.4%,74.3%,a,d,d,s+,s,s+,b,b,d,d,50.4%,48.0%,49.9%,52.5%,51.3%,52.5%,50.1%,51.3%,48.9%,49.9%,-0.1%,+0.6%,-0.3%,-0.2%,-0.2%,-0.1%,+0.9%,-0.1%,+0.2%,-0.1%,13.2%,2.6%,3.3%,8.2%,10.2%,25.4%,7.9%,4.2%,3.2%,2.0%,926 671,182 657,231 877,577 543,721 465,1 788 527,554 875,294 187,226 732,143 656,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07
3,euw1_7509193063,euw,15.17,high_elo,False,warwick,nidalee,akali,yunara,rakan,chogath,reksai,xerath,kaisa,sona,9.0,5.0,3.0,3.0,33.0,4.4,65.0,2.75,125.0,0.638,2.30,0.0,0.0,620.0,99.0,4.00,0.75,335.0,280.0,35.0,7.45,0.6,32.0,2.05,"['fighter', 'tank']",5.0,4.0,8.0,7.0,32.0,5.0,58.0,3.50,525.0,0.638,3.22,0.0,0.0,610.0,109.0,6.0,0.60,335.0,295.0,45.0,6.00,0.80,30.0,1.45,"['assassin', 'mage']",5.0,3.0,7.0,8.0,23.0,4.7,62.0,3.3,125.0,0.625,3.20,0.0,0.0,600.0,119.0,9.00,0.90,345.0,200.0,0.0,50.00,0.0,37.0,2.05,['assassin'],9.0,2.0,4.0,0.0,25.0,4.4,56.0,2.50,575.0,0.650,2.0,0.0,0.0,600.0,110.0,4.00,0.55,325.0,275.0,45.0,7.5,0.75,30.0,1.3,['marksman'],2.0,4.0,5.0,8.0,30.0,4.9,62.0,3.5,300.0,0.635,3.00,0.0,0.0,610.0,99.0,5.0,0.50,335.0,315.0,50.0,8.75,0.5,32.0,2.05,['support'],3.0,7.0,5.0,7.0,38.0,4.5,69.0,4.20,125.0,0.658,1.44,0.0,0.0,644.0,94.0,9.0,0.85,345.0,270.0,60.0,7.2,0.45,32.0,2.05,"['tank', 'mage']",8.0,5.0,3.0,2.0,35.0,4.50,62.0,3.00,175.0,0.667,2.00,0.0,0.0,600.0,99.0,2.5,0.50,340.0,100.0,0.0,0.0,0.00,32.0,2.05,"['fighter', 'tank']",1.0,3.0,8.0,10.0,22.0,4.7,55.0,3.0,525.0,0.658,1.36,0.0,0.0,596.0,106.0,5.5,0.55,340.0,400.0,22.0,6.85,0.8,30.0,1.30,"['mage', 'support']",8.0,5.0,6.0,3.0,27.0,4.2,59.0,2.6,525.0,0.644,1.8,0.0,0.0,640.0,102.0,4.00,0.55,335.0,345.0,40.0,8.2,0.7,30.0,1.3,"['marksman', 'mage']",5.0,2.0,4.0,8.0,26.0,4.2,49.0,3.0,550.0,0.644,2.3,0.0,0.0,550.0,91.0,5.5,0.55,325.0,340.0,45.0,11.50,0.40,30.0,1.30,"['support', 'mage']",15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,15.17,tout,tout,tout,tout,tout,tout,tout,tout,tout,tout,euw,euw,euw,euw,euw,euw,euw,euw,euw,euw,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,194,219,72,180,16,79,195,59,81,110,adc,jun,mid,sup,jun,adc,jun,mid,sup,top,98.4%,77.5%,84.0%,98.4%,82.0%,97.0%,82.1%,51.2%,98.8%,64.4%,d,d,c,d,s,c,d,b,c,c,46.9%,45.4%,49.1%,48.9%,51.9%,48.7%,48.8%,51.3%,51.8%,50.1%,-0.1%,+0.2%,+0.5%,+0.2%,+0.1%,+0.5%,+0.3%,-0.1%,-0.5%,+0.6%,6.1%,1.5%,6.9%,3.2%,6.5%,14.0%,1.1%,4.2%,2.8%,4.4%,427 211,108 444,483 002,226 732,456 214,985 376,76 336,294 187,195 095,310 162,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,15.24,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,6.0,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07

In [ ]:
============================================================================================================================

In [107]:
################### optimisé en memoire
def build_df_enhanced_low_mem(df_result_norm, df_simple_wr_norm):
    import pandas as pd
    import numpy as np

    champion_index = {champ: g for champ, g in df_simple_wr_norm.groupby("champion")}

    df_result_norm = df_result_norm.copy()
    roles = [
        "blue_top", "blue_jun", "blue_mid", "blue_adc", "blue_sup",
        "red_top", "red_jun", "red_mid", "red_adc", "red_sup"
    ]

    for role in roles:

        champ_col = f"{role}_champion"
        champions = df_result_norm[champ_col].values

        merged_rows = []

        for i, champ in enumerate(champions):

            if champ not in champion_index:
                merged_rows.append({})
                continue

            df_cand = champion_index[champ].copy()
            row = df_result_norm.iloc[i]

            # Vectorial scoring sur ce petit df
            server_score = np.where(df_cand["server"] == row["server"], 3,
                            np.where(df_cand["server"] == "tout", 1, 0))
            elo_score = np.where(df_cand["elo"] == row["elo"], 3,
                         np.where(df_cand["elo"] == "tout", 1, 0))
            patch_score = np.zeros(len(df_cand))
            patch_float = float(row["patch"])
            patch_cand_float = df_cand["patch"].astype(float)
            patch_score[patch_cand_float == patch_float] = 4
            patch_minor = ".".join(str(row["patch"]).split(".")[:2])
            mask_minor = df_cand["patch"].astype(str).str.startswith(patch_minor)
            patch_score[(patch_score == 0) & mask_minor] = 3
            patch_major = str(row["patch"]).split(".")[0]
            mask_major = df_cand["patch"].astype(str).str.startswith(patch_major)
            patch_score[(patch_score == 0) & mask_major] = 2
            patch_score[patch_score == 0] = 1

            total_score = server_score + elo_score + patch_score
            best_idx = np.argmax(total_score)
            best_row = df_cand.iloc[best_idx]

            # ajouter les colonnes avec prefix role
            new_data = {f"{role}_{c}": best_row[c] for c in df_cand.columns if c != "champion"}
            merged_rows.append(new_data)

        df_extra = pd.DataFrame(merged_rows)
        df_result_norm = pd.concat([df_result_norm.reset_index(drop=True), df_extra], axis=1)

    return df_result_norm

In [108]:
df_enhanced = build_df_enhanced_low_mem(df_result_norm, df_simple_wr_norm)

KeyboardInterrupt:

In [ ]:
============================================================================================================================

In [69]:
def add_blue_top_features(df_result_norm, df_simple_wr_norm):
    import pandas as pd

    # --- sécuriser les types ---
    for col in ["server", "patch", "elo"]:
        df_result_norm[col] = df_result_norm[col].astype(str)
        df_simple_wr_norm[col] = df_simple_wr_norm[col].astype(str)

    df_result_norm["blue_top_champion"] = df_result_norm["blue_top_champion"].astype(str)
    df_simple_wr_norm["champion"] = df_simple_wr_norm["champion"].astype(str)

    # --- merge vectorisé ---
    df_merged = df_result_norm.merge(
        df_simple_wr_norm,
        how="left",
        left_on=["server", "patch", "elo", "blue_top_champion"],
        right_on=["server", "patch", "elo", "champion"],
        suffixes=("", "_simple")
    )

    # --- debug ---
    exact_mask = df_merged["champion"].notna()

    for _, row in df_merged[exact_mask].iterrows():
        print("exact match :", row["server"], row["patch"], row["elo"], row["blue_top_champion"])

    for _, row in df_merged[~exact_mask].iterrows():
        print("pas d'exact match :", row["server"], row["patch"], row["elo"], row["blue_top_champion"])

    # --- colonnes à ajouter ---
    cols_to_add = [
        c for c in df_simple_wr_norm.columns
        if c not in ["server", "patch", "elo", "champion"]
    ]

    rename_dict = {c: f"blue_top_{c}" for c in cols_to_add}

    df_merged = df_merged.rename(columns=rename_dict)

    new_cols = list(rename_dict.values())

    df_final = pd.concat(
        [df_result_norm.reset_index(drop=True),
         df_merged[new_cols].reset_index(drop=True)],
        axis=1
    )

    return df_final

In [70]:
df_games_champs_simple_wr = add_blue_top_features(df_result_norm[:10], df_simple_wr_norm)

C:\Users\samue\AppData\Local\Temp\ipykernel_80040\1597507506.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result_norm[col] = df_result_norm[col].astype(str)
C:\Users\samue\AppData\Local\Temp\ipykernel_80040\1597507506.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result_norm[col] = df_result_norm[col].astype(str)
C:\Users\samue\AppData\Local\Temp\ipykernel_80040\1597507506.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result_norm[col] = df_result_norm[col].astype(str)
C:\Users\samue\AppData\Local\Temp\ipykernel_80040\1597507506.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_result_norm["blue_top_champion"] = df_result_norm["blue_top_champion"].astype(str)

pas d'exact match : euw 15.17 tout sett
pas d'exact match : euw 15.17 tout mordekaiser
pas d'exact match : euw 15.17 tout smolder
pas d'exact match : euw 15.17 tout warwick
pas d'exact match : euw 15.17 tout aurora
pas d'exact match : euw 15.17 tout heimerdinger
pas d'exact match : euw 15.17 tout skarner
pas d'exact match : euw 15.16 tout urgot
pas d'exact match : euw 15.16 tout illaoi
pas d'exact match : euw 15.17 tout leesin

In [ ]:
je crois que ta methode a un probleme : missing s'affiche pour tous les matchs...
quand le elo de la games est "high elo", tu dois quand meme me ramener quelque chose detoutes facons... je crois qu'il y a aussi un probleme aves les roles. pour rappel : 
df_simple_wr.head()

elo	server	patch	label	name	role	role_pickrate	tier	winrate	winrate_evol	pickrate	games
0	TOUT	TOUT	16.3	1	briar	jun	91.1%	S+	52.8%	+1.5%	6.7%	599 576
1	TOUT	TOUT	16.3	2	missfortune	adc	97.0%	S+	51.7%	-0.0%	15.5%	1 386 160
2	TOUT	TOUT	16.3	3	malzahar	mid	92.2%	S+	52.3%	+0.0%	8.1%	724 180
3	TOUT	TOUT	16.3	4	swain	adc	18.6%	S+	54.6%	-0.1%	1.7%	154 988
4	TOUT	TOUT	16.3	5	jinx	adc	99.5%	S+	51.6%	-0.2%	16.6%	1 485 175