In [1]:
import requests

API_KEY = "RGAPI-fd1df5a4-0ba9-46c3-ae19-0a83dfcd771b"  # ⚠️ ne pas commit ça
REGION = "euw1"              # euw1, na1, kr, etc.

HEADERS = {
    "X-Riot-Token": API_KEY
}

In [5]:
leagues = [
    {"name": "LEC", "region": "europe", "queue": 420, "players": ["player1EUW", "player2EUW"]},
    {"name": "LCS", "region": "americas", "queue": 420, "players": ["player1NA", "player2NA"]},
    {"name": "LCK", "region": "asia", "queue": 420, "players": ["player1KR", "player2KR"]}
]

In [2]:
def get_puuid(game_name, tag_line, region):
    url = f"https://{region}.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{game_name}/{tag_line}"
    r = requests.get(url, headers=HEADERS)
    r.raise_for_status()
    return r.json()["puuid"]

In [3]:
def get_last_matches(puuid, region="europe", count=10):
    url = f"https://{region}.api.riotgames.com/lol/match/v5/matches/by-puuid/{puuid}/ids"
    params = {"start": 0, "count": count}
    r = requests.get(url, headers=HEADERS, params=params)
    r.raise_for_status()
    return r.json()

In [6]:
all_matches = []

for league in leagues:
    league_name = league["name"]
    region = league["region"]
    
    print(f"=== {league_name} ===")
    
    for player in league["players"]:
        # Si tu as le Riot ID sous format "gameName#tagLine", split :
        game_name, tag_line = player.split("#")
        puuid = get_puuid(game_name, tag_line, region)
        
        matches = get_last_matches(puuid, region, count=10)  # change le count ici
        for match_id in matches:
            all_matches.append({
                "league": league_name,
                "player": player,
                "match_id": match_id
            })

# Convertir en DataFrame
df = pd.DataFrame(all_matches)
df.head()

=== LEC ===

ValueError: not enough values to unpack (expected 2, got 1)

In [8]:
!pip install beautifulsoup4 lxml

Collecting beautifulsoup4
  Downloading beautifulsoup4-4.14.3-py3-none-any.whl (107 kB)
     -------------------------------------- 107.7/107.7 KB 3.1 MB/s eta 0:00:00
Collecting lxml
  Downloading lxml-6.0.2-cp39-cp39-win_amd64.whl (4.0 MB)
     ---------------------------------------- 4.0/4.0 MB 18.4 MB/s eta 0:00:00
Collecting soupsieve>=1.6.1
  Downloading soupsieve-2.8.1-py3-none-any.whl (36 kB)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\samue\documents\datascientest-lol-draft_analyzer\venv\lib\site-packages (from beautifulsoup4) (4.15.0)
Installing collected packages: soupsieve, lxml, beautifulsoup4
Successfully installed beautifulsoup4-4.14.3 lxml-6.0.2 soupsieve-2.8.1

WARNING: You are using pip version 22.0.4; however, version 25.3 is available.
You should consider upgrading via the 'C:\Users\samue\Documents\datascientest-lol-draft_analyzer\venv\Scripts\python.exe -m pip install --upgrade pip' command.

In [7]:
# recup les rosters

import requests

url = "https://lolesports.com/schedule?leagues=lec,lcs,lck,lpl"
r = requests.get(url)
# tu récupères le HTML → parser avec BeautifulSoup
from bs4 import BeautifulSoup
soup = BeautifulSoup(r.text, "html.parser")

# chercher les rosters → tag CSS ou JSON dans le HTML

ModuleNotFoundError: No module named 'bs4'

In [12]:
from bs4 import BeautifulSoup
import requests

url = "https://lolesports.com/schedule?leagues=lec"
r = requests.get(url)

soup = BeautifulSoup(r.text, "lxml")  # ou "html.parser"
print(soup.prettify()[:10000])  # afficher les 1000 premiers caractères du HTML

<!DOCTYPE html>
<html class="__variable_bf98f5 __variable_e4a612" lang="fr-FR">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link as="font" crossorigin="" href="/_next/static/media/579e0f95cacfae57-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/dedada5e2588d0aa-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/e88c72b592450e05-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/f1f0c35b32161446-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/fcb100c7607696fd-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/0c330b400fbfca12-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/4fb4b4b016bdd4ad-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/78dae3993a240aec-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/964c460f529c81b2-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/9ec276a6be1c1181-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="font" crossorigin="" href="/_next/static/media/def172b5dc2d7e26-s.p.woff2" rel="preload" type="font/woff2"/>
  <link as="image" imagesizes="(max-width: 639px) 256px,(max-width: 767px) 256px,(max-width: 1023px) 256px,(max-width: 1279px) 256px,(max-width: 1535px) 256px,(min-width: 1536px) 256px" imagesrcset="https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 16w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 32w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 48w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 64w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 96w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 128w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 256w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 384w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 640w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 750w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 828w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 1080w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 1200w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 1920w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 2048w, https://cmsassets.rgpub.io/sanity/images/dsfx7636/esports/ebb15a64be8b4703f7fac000f2efc5329a148da2-136x32.svg?accountingTag=lol_esports 3840w" rel="preload"/>
  <link data-precedence="next" href="/_next/static/css/e3a03f556eeb07fd.css" rel="stylesheet"/>
  <link data-precedence="next" href="/_next/static/css/4e61a2836bddd84b.css" rel="stylesheet"/>
  <link data-precedence="next" href="/_next/static/css/35e666c5cd818573.css" rel="stylesheet"/>
  <link as="script" fetchpriority="low" href="/_next/static/chunks/webpack-4b7e3936bf7fd888.js" rel="preload"/>
  <script async="" src="/_next/static/chunks/f5e865f6-bd43dabc9df6efef.js">
  </script>
  <script async="" src="/_next/static/chunks/4451-e6a1f425e3def04a.js">
  </script>
  <script async="" src="/_next/static/chunks/main-app-6f500f8a1f0d66fd.js">
  </script>
  <script async="" src="/_next/static/chunks/4202-a8bbdf0ec4ba7598.js">
  </script>
  <script async="" src="/_next/static/chunks/app/global-error-3d4f6a14a9151f63.js">
  </script>
  <script async="" src="/_next/static/chunks/aaea2bcf-7eb96b626eb25602.js">
  </script>
  <script async="" src="/_next/static/chunks/7739-846c8179b86b5ca8.js">
  </script>
  <script async="" src="/_next/static/chunks/2783-98136e77a927c05a.js">
  </script>
  <script async="" src="/_next/static/chunks/6886-fd736f5ddaa27317.js">
  </script>
  <script async="" src="/_next/static/chunks/5578-f1c1496c3b3ac551.js">
  </script>
  <script async="" src="/_next/static/chunks/1260-4d2ebd2df0d537b7.js">
  </script>
  <script async="" src="/_next/static/chunks/9562-2776eb4a79d0dd5d.js">
  </script>
  <script async="" src="/_next/static/chunks/7980-1f50e8ccea3708a3.js">
  </script>
  <script async="" src="/_next/static/chunks/4420-b5d3ec9cb111a9d9.js">
  </script>
  <script async="" src="/_next/static/chunks/app/%5Blocale%5D/layout-2d5237a884a0ec7f.js">
  </script>
  <script async="" src="/_next/static/chunks/6766-415e18ca2f57cf11.js">
  </script>
  <script async="" src="/_next/static/chunks/6874-b7cb13c1909bc74c.js">
  </script>
  <script async="" src="/_next/static/chunks/7685-16e92d5b65f93ce6.js">
  </script>
  <script async="" src="/_next/static/chunks/6566-c48deb789254d289.js">
  </script>
  <script async="" src="/_next/static/chunks/7804-6e8ee9d07764f61f.js">
  </script>
  <script async="" src="/_next/static/chunks/2626-7e8758559f90689b.js">
  </script>
  <script async="" src="/_next/static/chunks/3411-0da1f92e0913ef95.js">
  </script>
  <script async="" src="/_next/static/chunks/1631-46fa2666bea45fc0.js">
  </script>
  <script async="" src="/_next/static/chunks/7481-429c5fa7b677fd74.js">
  </script>
  <script async="" src="/_next/static/chunks/7878-4757011c11ccab7f.js">
  </script>
  <script async="" src="/_next/static/chunks/564-0478d4a53331a7b6.js">
  </script>
  <script async="" src="/_next/static/chunks/app/%5Blocale%5D/lolesports/leagues/%5Bleagues%5D/page-8c7293a3963b4018.js">
  </script>
  <script async="" src="/_next/static/chunks/5659-232f3d0da8df2d99.js">
  </script>
  <script async="" src="/_next/static/chunks/5727-33ddbd7cf18325e2.js">
  </script>
  <script async="" src="/_next/static/chunks/5244-98e3723ff648709b.js">
  </script>
  <script async="" src="/_next/static/chunks/6722-99cfa2b6d59e214c.js">
  </script>
  <script async="" src="/_next/static/chunks/3753-c5d66c4172608605.js">
  </script>
  <script async="" src="/_next/static/chunks/53-aaf678c63d0e1c1a.js">
  </script>
  <script async="" src="/_next/static/chunks/245-7d8eecab8a2b6a8f.js">
  </script>
  <script async="" src="/_next/static/chunks/4310-8afd313d1dd816d3.js">
  </script>
  <script async="" src="/_next/static/chunks/6536-9ea81845f5eb997a.js">
  </script>
  <script async="" src="/_next/static/chunks/2384-adf572cdcec7e738.js">
  </script>
  <script async="" src="/_next/static/chunks/3455-c4db01d782bf252d.js">
  </script>
  <script async="" src="/_next/static/chunks/app/%5Blocale%5D/lolesports/leagues/%5Bleagues%5D/layout-ff47f0426f249429.js">
  </script>
  <script async="" src="/_next/static/chunks/6391-8337aeaeb38f4ac9.js">
  </script>
  <script async="" src="/_next/static/chunks/9552-bd0d52025ab5384d.js">
  </script>
  <script async="" src="/_next/static/chunks/7955-cd46488e23eab1d8.js">
  </script>
  <script async="" src="/_next/static/chunks/3436-7a9b46a2b224e563.js">
  </script>
  <script async="" src="/_next/static/chunks/6217-363b38ea3d0c6020.js">
  </script>
  <script async="" src="/_next/static/chunks/9788-055c0d219e6f2cf1.js">
  </script>
  <script async="" src="/_next/static/chunks/app/%5Blocale%5D/lolesports/layout-6ffbb9a53a26826c.js">
  </script>
  <link as="script" href="https://cmp.osano.com/16BZ95S4qp9Kl2gUA/da3676fa-a107-4042-89d6-d35e83e22544/osano.js" rel="preload"/>
  <link as="script" href="https://www.googletagmanager.com/gtm.js?id=GTM-MBFKBN" rel="preload"/>
  <link as="script" href="https://cdn.rgpub.io/public/live/riotbar/latest/lolesports.fr_FR.js" rel="preload"/>
  <meta content="" name="next-size-adjust"/>
  <meta content="#000000" name="theme-color"/>
  <title>
   LoL Esports | PLANNING
  </title>
  <meta content="The best place to watch LoL Esports and earn rewards!" name="description"/>
  <meta content="LoL Esports" name="application-name"/>
  <link href="/manifest.json" rel="manifest"/>
  <meta content="giabiihe129qbd3mvcocnl10keykmh" name="facebook-domain-verification"/>
  <meta content="yes" name="mobile-web-app-capable"/>
  <meta content="LoL Esports" name="apple-mobile-web-app-title"/>
  <meta content="black" name="apple-mobile-web-app-status-bar-style"/>
  <link href="/fr-FR/lolesports/icon.png?3edd2103008e7e7d" rel="icon" sizes="48x48" type="image/png"/>
  <link href="/fr-FR/lolesports/apple-icon.png?ed83e4812648ed65" rel="apple-touch-icon" sizes="180x180" type="image/png"/>
  <script>
   document.querySelectorAll('body link[rel="icon"], body link[rel="apple-touch-icon"]').forEach(el => document.head.appendChild(el))
  </script>
  <script nomodule="" src="/_next/static/chunks/polyfills-42372ed130431b0a.js">
  </script>
  <script>
   (window[Symbol.for("ApolloSSRDataTransport")] ??= []).push({"rehydrate":{"«R14mdrlrlnb»":{"data":{"__typename":"Query","le

In [1]:
# essai avec le csv de https://oracleselixir.com/tools/downloads
import pandas as pd
df = pd.read_csv("2025_pro_games.csv")
df.head()

C:\Users\samue\AppData\Local\Temp\ipykernel_8784\1856620446.py:3: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("2025_pro_games.csv")

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,200.0,224.0,-1.0,17.0,1.0,1.0,2.0,2.0,4.0,2.0
1,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,157.0,-2363.0,-1444.0,-18.0,0.0,1.0,2.0,1.0,7.0,0.0
2,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,241.0,-1552.0,-2465.0,-41.0,1.0,0.0,2.0,1.0,5.0,1.0
3,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,257.0,-2613.0,-1156.0,-6.0,1.0,1.0,2.0,6.0,2.0,0.0
4,LOLTMNT03_179647,complete,NaN,LFL2,2025,Winter,0,2025-01-11 11:11:24,1,15.01,...,20.0,-662.0,-734.0,18.0,0.0,2.0,2.0,0.0,8.0,0.0

In [2]:
df["league"].unique()

array(['LFL2', 'LPL', 'LCKC', 'LVP SL', 'LCK', 'NLC', 'LCP', 'LEC', 'HLL',
       'PRM', 'LFL', 'LIT', 'TCL', 'HW', 'LJL', 'LTA S', 'LTA N', 'RL',
       'NEXO', 'CD', 'EBL', 'PCS', 'ROL', 'LPLOL', 'AL', 'LTA', 'VCS',
       'FST', 'EM', 'LRS', 'LRN', 'NACL', 'LAS', 'HC', 'PRMP', 'HM', 'CT',
       'Asia Master', 'MSI', 'EWC', 'WLDs', 'ASI', 'IC', 'KeSPA', 'DCup'],
      dtype=object)

In [3]:
df[df["league"] == "LEC"].head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
1344,LOLTMNT06_96344,complete,NaN,LEC,2025,Winter,0,2025-01-18 17:09:08,1,15.01,...,229.0,150.0,-93.0,19.0,1.0,1.0,0.0,0.0,0.0,1.0
1345,LOLTMNT06_96344,complete,NaN,LEC,2025,Winter,0,2025-01-18 17:09:08,1,15.01,...,161.0,1128.0,2084.0,27.0,0.0,2.0,0.0,0.0,0.0,0.0
1346,LOLTMNT06_96344,complete,NaN,LEC,2025,Winter,0,2025-01-18 17:09:08,1,15.01,...,224.0,689.0,-268.0,13.0,1.0,0.0,0.0,0.0,0.0,0.0
1347,LOLTMNT06_96344,complete,NaN,LEC,2025,Winter,0,2025-01-18 17:09:08,1,15.01,...,270.0,531.0,579.0,-14.0,0.0,1.0,0.0,0.0,0.0,0.0
1348,LOLTMNT06_96344,complete,NaN,LEC,2025,Winter,0,2025-01-18 17:09:08,1,15.01,...,27.0,177.0,-447.0,8.0,0.0,1.0,0.0,0.0,0.0,1.0

In [7]:
for col in df.columns:
    print(col)

gameid
datacompleteness
url
league
year
split
playoffs
date
game
patch
participantid
side
position
playername
playerid
teamname
teamid
champion
ban1
ban2
ban3
ban4
ban5
pick1
pick2
pick3
pick4
pick5
gamelength
result
kills
deaths
assists
teamkills
teamdeaths
doublekills
triplekills
quadrakills
pentakills
firstblood
firstbloodkill
firstbloodassist
firstbloodvictim
team kpm
ckpm
firstdragon
dragons
opp_dragons
elementaldrakes
opp_elementaldrakes
infernals
mountains
clouds
oceans
chemtechs
hextechs
dragons (type unknown)
elders
opp_elders
firstherald
heralds
opp_heralds
void_grubs
opp_void_grubs
firstbaron
barons
opp_barons
atakhans
opp_atakhans
firsttower
towers
opp_towers
firstmidtower
firsttothreetowers
turretplates
opp_turretplates
inhibitors
opp_inhibitors
damagetochampions
dpm
damageshare
damagetakenperminute
damagemitigatedperminute
damagetotowers
wardsplaced
wpm
wardskilled
wcpm
controlwardsbought
visionscore
vspm
totalgold
earnedgold
earned gpm
earnedgoldshare
goldspent
gspd
gpr
total cs
minionkills
monsterkills
monsterkillsownjungle
monsterkillsenemyjungle
cspm
goldat10
xpat10
csat10
opp_goldat10
opp_xpat10
opp_csat10
golddiffat10
xpdiffat10
csdiffat10
killsat10
assistsat10
deathsat10
opp_killsat10
opp_assistsat10
opp_deathsat10
goldat15
xpat15
csat15
opp_goldat15
opp_xpat15
opp_csat15
golddiffat15
xpdiffat15
csdiffat15
killsat15
assistsat15
deathsat15
opp_killsat15
opp_assistsat15
opp_deathsat15
goldat20
xpat20
csat20
opp_goldat20
opp_xpat20
opp_csat20
golddiffat20
xpdiffat20
csdiffat20
killsat20
assistsat20
deathsat20
opp_killsat20
opp_assistsat20
opp_deathsat20
goldat25
xpat25
csat25
opp_goldat25
opp_xpat25
opp_csat25
golddiffat25
xpdiffat25
csdiffat25
killsat25
assistsat25
deathsat25
opp_killsat25
opp_assistsat25
opp_deathsat25

In [12]:
print(df[df["league"] == "LEC"].iloc[0].to_string())

gameid                                                LOLTMNT06_96344
datacompleteness                                             complete
url                                                               NaN
league                                                            LEC
year                                                             2025
split                                                          Winter
playoffs                                                            0
date                                              2025-01-18 17:09:08
game                                                                1
patch                                                           15.01
participantid                                                       1
side                                                             Blue
position                                                          top
playername                                                    Carlsen
playerid                    oe:player:5fa6eac8bedeed60a83f154d9538ee1
teamname                                                Team Heretics
teamid                        oe:team:1285e1c04d54de96502f12da4d49458
champion                                                      K'Sante
ban1                                                          Kalista
ban2                                                             Azir
ban3                                                           Aurora
ban4                                                     Renata Glasc
ban5                                                           Wukong
pick1                                                             NaN
pick2                                                             NaN
pick3                                                             NaN
pick4                                                             NaN
pick5                                                             NaN
gamelength                                                       2323
result                                                              0
kills                                                               2
deaths                                                              3
assists                                                             1
teamkills                                                           3
teamdeaths                                                         11
doublekills                                                       0.0
triplekills                                                       0.0
quadrakills                                                       0.0
pentakills                                                        0.0
firstblood                                                        1.0
firstbloodkill                                                    1.0
firstbloodassist                                                  0.0
firstbloodvictim                                                  0.0
team kpm                                                       0.0775
ckpm                                                           0.3616
firstdragon                                                       NaN
dragons                                                           NaN
opp_dragons                                                       NaN
elementaldrakes                                                   NaN
opp_elementaldrakes                                               NaN
infernals                                                         NaN
mountains                                                         NaN
clouds                                                            NaN
oceans                                                            NaN
chemtechs                                                         NaN
hextechs                                                          NaN
dragons (type unknown)                                            NaN
elders                                                            NaN
opp_elders                                                        NaN
firstherald                                                       NaN
heralds                                                           NaN
opp_heralds                                                       NaN
void_grubs                                                        NaN
opp_void_grubs                                                    NaN
firstbaron                                                        NaN
barons                                                            0.0
opp_barons                                                        0.0
atakhans                                                          NaN
opp_atakhans                                                      NaN
firsttower                                                        NaN
towers                                                            NaN
opp_towers                                                        NaN
firstmidtower                                                     NaN
firsttothreetowers                                                NaN
turretplates                                                      NaN
opp_turretplates                                                  NaN
inhibitors                                                        0.0
opp_inhibitors                                                    0.0
damagetochampions                                               11006
dpm                                                          284.2703
damageshare                                                   0.14523
damagetakenperminute                                        1054.3263
damagemitigatedperminute                                    1495.4025
damagetotowers                                                  278.0
wardsplaced                                                        17
wpm                                                            0.4391
wardskilled                                                         4
wcpm                                                           0.1033
controlwardsbought                                                  9
visionscore                                                        30
vspm                                                           0.7749
totalgold                                                       12726
earnedgold                                                       7711
earned gpm                                                   199.1649
earnedgoldshare                                              0.210487
goldspent                                                       12275
gspd                                                              NaN
gpr                                                               NaN
total cs                                                        302.0
minionkills                                                     302.0
monsterkills                                                        0
monsterkillsownjungle                                             NaN
monsterkillsenemyjungle                                           NaN
cspm                                                           7.8003
goldat10                                                       3792.0
xpat10                                                         5191.0
csat10                                                           95.0
opp_goldat10                                                   3068.0
opp_xpat10                                                     4681.0
opp_csat10                                                       78.0
golddiffat10                                                    724.0
xpdiffat10                                                      510.0
csdiffat10                                                       17.0
killsat10                                                         1.0
assistsat10                                                       0.0
deathsat10                                                        0.0
opp_killsat10                                                     0.0
opp_assistsat10                                                   0.0
opp_deathsat10                                                    1.0
goldat15                                                       5412.0
xpat15                                                         7863.0
csat15                                                          148.0
opp_goldat15                                                   5050.0
opp_xpat15                                                     7787.0
opp_csat15                                                      139.0
golddiffat15                                                    362.0
xpdiffat15                                                       76.0
csdiffat15                                                        9.0
killsat15                                                         1.0
assistsat15                                                       0.0
deathsat15                                                        0.0
opp_killsat15                                                     0.0
opp_assistsat15                                                   0.0
opp_deathsat15                                                    1.0
goldat20                                                       7323.0
xpat20                                                        10562.0
csat20                                                          200.0
opp_goldat20                                                   7376.0
opp_xpat20                                                    11011.0
opp_csat20                                                      188.0
golddiffat20                                                    -53.0
xpdiffat20                                                     -449.0
csdiffat20                                                       12.0
killsat20                                                         1.0
assistsat20                                                       0.0
deathsat20                                                        0.0
opp_killsat20                                                     0.0
opp_assistsat20                                                   0.0
opp_deathsat20                                                    1.0
goldat25                                                       9091.0
xpat25                                                        13138.0
csat25                                                          248.0
opp_goldat25                                                   8941.0
opp_xpat25                                                    13231.0
opp_csat25                                                      229.0
golddiffat25                                                    150.0
xpdiffat25                                                      -93.0
csdiffat25                                                       19.0
killsat25                                                         1.0
assistsat25                                                       1.0
deathsat25                                                        0.0
opp_killsat25                                                     0.0
opp_assistsat25                                                   0.0
opp_deathsat25                                                    1.0

In [17]:
print(df[(df["teamname"] == "Team Heretics") & (df["date"] == "2025-01-18 17:09:08")].to_string())

               gameid datacompleteness  url league  year   split  playoffs                 date  game  patch  participantid  side position playername                                   playerid       teamname                                   teamid champion     ban1  ban2    ban3          ban4    ban5   pick1    pick2    pick3 pick4 pick5  gamelength  result  kills  deaths  assists  teamkills  teamdeaths  doublekills  triplekills  quadrakills  pentakills  firstblood  firstbloodkill  firstbloodassist  firstbloodvictim  team kpm    ckpm  firstdragon  dragons  opp_dragons  elementaldrakes  opp_elementaldrakes  infernals  mountains  clouds  oceans  chemtechs  hextechs  dragons (type unknown)  elders  opp_elders  firstherald  heralds  opp_heralds  void_grubs  opp_void_grubs  firstbaron  barons  opp_barons  atakhans  opp_atakhans  firsttower  towers  opp_towers  firstmidtower  firsttothreetowers  turretplates  opp_turretplates  inhibitors  opp_inhibitors  damagetochampions        dpm  damageshare  damagetakenperminute  damagemitigatedperminute  damagetotowers  wardsplaced     wpm  wardskilled    wcpm  controlwardsbought  visionscore    vspm  totalgold  earnedgold  earned gpm  earnedgoldshare  goldspent     gspd   gpr  total cs  minionkills  monsterkills  monsterkillsownjungle  monsterkillsenemyjungle     cspm  goldat10   xpat10  csat10  opp_goldat10  opp_xpat10  opp_csat10  golddiffat10  xpdiffat10  csdiffat10  killsat10  assistsat10  deathsat10  opp_killsat10  opp_assistsat10  opp_deathsat10  goldat15   xpat15  csat15  opp_goldat15  opp_xpat15  opp_csat15  golddiffat15  xpdiffat15  csdiffat15  killsat15  assistsat15  deathsat15  opp_killsat15  opp_assistsat15  opp_deathsat15  goldat20   xpat20  csat20  opp_goldat20  opp_xpat20  opp_csat20  golddiffat20  xpdiffat20  csdiffat20  killsat20  assistsat20  deathsat20  opp_killsat20  opp_assistsat20  opp_deathsat20  goldat25   xpat25  csat25  opp_goldat25  opp_xpat25  opp_csat25  golddiffat25  xpdiffat25  csdiffat25  killsat25  assistsat25  deathsat25  opp_killsat25  opp_assistsat25  opp_deathsat25
1344  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              1  Blue      top    Carlsen  oe:player:5fa6eac8bedeed60a83f154d9538ee1  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  K'Sante  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN   NaN   NaN        2323       0      2       3        1          3          11          0.0          0.0          0.0         0.0         1.0             1.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              11006   284.2703     0.145230             1054.3263                 1495.4025           278.0           17  0.4391            4  0.1033                   9           30  0.7749      12726        7711    199.1649         0.210487      12275      NaN   NaN     302.0        302.0             0                    NaN                      NaN   7.8003    3792.0   5191.0    95.0        3068.0      4681.0        78.0         724.0       510.0        17.0        1.0          0.0         0.0            0.0              0.0             1.0    5412.0   7863.0   148.0        5050.0      7787.0       139.0         362.0        76.0         9.0        1.0          0.0         0.0            0.0              0.0             1.0    7323.0  10562.0   200.0        7376.0     11011.0       188.0         -53.0      -449.0        12.0        1.0          0.0         0.0            0.0              0.0             1.0    9091.0  13138.0   248.0        8941.0     13231.0       229.0         150.0       -93.0        19.0        1.0          1.0         0.0            0.0              0.0             1.0
1345  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              2  Blue      jng       Sheo  oe:player:404079b4e478ea2a8b57904c640311b  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  Sejuani  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN   NaN   NaN        2323       0      0       1        2          3          11          0.0          0.0          0.0         0.0         1.0             0.0               1.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0               8151   210.5295     0.107557              898.1920                 1484.2445           380.0           14  0.3616            8  0.2066                  13           52  1.3431      11882        6867    177.3655         0.187450      11600      NaN   NaN     243.0         22.0           221                    NaN                      NaN   6.2764    3279.0   3708.0    69.0        3118.0      3700.0        70.0         161.0         8.0        -1.0        0.0          1.0         0.0            0.0              0.0             0.0    5012.0   5913.0   109.0        4690.0      6016.0       114.0         322.0      -103.0        -5.0        0.0          1.0         0.0            0.0              0.0             0.0    6824.0   8883.0   154.0        6083.0      7750.0       142.0         741.0      1133.0        12.0        0.0          1.0         0.0            0.0              0.0             0.0    8358.0  11068.0   188.0        7230.0      8984.0       161.0        1128.0      2084.0        27.0        0.0          2.0         0.0            0.0              0.0             0.0
1346  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              3  Blue      mid    Kamiloo  oe:player:728ce343a6718cfdd5d223c971cc2fd  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458   Viktor  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN   NaN   NaN        2323       0      1       3        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              29458   760.8610     0.388715              399.7503                  357.3655          4544.0           22  0.5682           10  0.2583                  11           62  1.6014      13628        8613    222.4623         0.235107      13825      NaN   NaN     320.0        320.0             0                    NaN                      NaN   8.2652    3127.0   4475.0    79.0        3160.0      4604.0        85.0         -33.0      -129.0        -6.0        0.0          0.0         0.0            0.0              0.0             0.0    5020.0   7353.0   141.0        4877.0      7437.0       137.0         143.0       -84.0         4.0        0.0          0.0         0.0            0.0              0.0             0.0    7035.0   9939.0   190.0        6895.0     10461.0       188.0         140.0      -522.0         2.0        0.0          0.0         0.0            0.0              0.0             0.0    9051.0  12275.0   237.0        8362.0     12543.0       224.0         689.0      -268.0        13.0        1.0          0.0         0.0            0.0              0.0             0.0
1347  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              4  Blue      bot    Flakked  oe:player:717bb4d71a2dab54e7020b1a8fde420  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Zeri  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN   NaN   NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0              23762   613.7409     0.313553              448.8506                  243.2028          1821.0           18  0.4649           21  0.5424                   5           68  1.7563      15603       10588    273.4740         0.289015      14725      NaN   NaN     398.0        368.0            30                    NaN                      NaN  10.2798    3296.0   3771.0    86.0        3462.0      3656.0        96.0        -166.0       115.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    5560.0   6299.0   139.0        5234.0      6185.0       149.0         326.0       114.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    7708.0   8813.0   199.0        7383.0      8992.0       214.0         325.0      -179.0       -15.0        0.0          0.0         0.0            0.0              0.0             0.0    9832.0  11883.0   256.0        9301.0     11304.0       270.0         531.0       579.0       -14.0        0.0          1.0         0.0            0.0              0.0             0.0
1348  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              5  Blue      sup      Stend  oe:player:41672e17bc1f86dc5d93955c031d2a9  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Rell  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN   NaN   NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0               3406    87.9724     0.044944              425.3207                  571.5885             0.0           75  1.9372           16  0.4133                  17          140  3.6160       7870        2855     73.7409         0.077941       7625      NaN   NaN      38.0         38.0             0                    NaN                      NaN   0.9815    2121.0   2231.0    13.0        2058.0      2456.0        15.0          63.0      -225.0        -2.0        0.0          0.0         0.0            0.0              0.0             0.0    3138.0   3321.0    22.0        3062.0      3211.0        19.0          76.0       110.0         3.0        0.0          0.0         0.0            0.0              0.0             0.0    4217.0   4374.0    30.0        4108.0      4347.0        23.0         109.0        27.0         7.0        0.0          0.0         0.0            0.0              0.0             0.0    5207.0   4604.0    35.0        5030.0      5051.0        27.0         177.0      -447.0         8.0        0.0          1.0         0.0            0.0              0.0             1.0
1354  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01            100  Blue     team        NaN                                        NaN  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458      NaN  Kalista  Azir  Aurora  Renata Glasc  Wukong  Viktor  Sejuani  K'Sante  Zeri  Rell        2323       0      3      11        6          3          11          0.0          0.0          0.0         0.0         1.0             NaN               NaN               NaN    0.0775  0.3616          0.0      2.0          4.0              2.0                  4.0        0.0        0.0     2.0     0.0        0.0       0.0                     NaN     0.0         0.0          1.0      1.0          0.0         6.0             0.0         0.0     0.0         2.0       0.0           1.0         0.0     4.0        11.0            1.0                 1.0           1.0               3.0         0.0             3.0              75783  1957.3741          NaN             3226.4399                 4151.8037          7023.0          146  3.7710           59  1.5239                  55          352  9.0917      61709       36636    946.2591              NaN      60050 -0.08796  0.19       NaN       1050.0           251                    NaN                      NaN  33.6031   15615.0  19376.0   342.0       14866.0     19097.0       344.0         749.0       279.0        -2.0        1.0          1.0         0.0            0.0              0.0             1.0   24142.0  30749.0   559.0       22913.0     30636.0       558.0        1229.0       113.0         1.0        1.0          1.0         0.0            0.0              0.0             1.0   33107.0  42571.0   773.0       31845.0     42561.0       755.0        1262.0        10.0        18.0        1.0          1.0         0.0            0.0              0.0             1.0   41539.0  52968.0   964.0       38864.0     51113.0       911.0        2675.0      1855.0        53.0        2.0          5.0         0.0            0.0              0.0             2.0

In [18]:
print(df[df["date"] == "2025-01-18 17:09:08"].to_string())

               gameid datacompleteness  url league  year   split  playoffs                 date  game  patch  participantid  side position playername                                   playerid       teamname                                   teamid champion     ban1  ban2    ban3          ban4    ban5   pick1    pick2    pick3  pick4    pick5  gamelength  result  kills  deaths  assists  teamkills  teamdeaths  doublekills  triplekills  quadrakills  pentakills  firstblood  firstbloodkill  firstbloodassist  firstbloodvictim  team kpm    ckpm  firstdragon  dragons  opp_dragons  elementaldrakes  opp_elementaldrakes  infernals  mountains  clouds  oceans  chemtechs  hextechs  dragons (type unknown)  elders  opp_elders  firstherald  heralds  opp_heralds  void_grubs  opp_void_grubs  firstbaron  barons  opp_barons  atakhans  opp_atakhans  firsttower  towers  opp_towers  firstmidtower  firsttothreetowers  turretplates  opp_turretplates  inhibitors  opp_inhibitors  damagetochampions        dpm  damageshare  damagetakenperminute  damagemitigatedperminute  damagetotowers  wardsplaced     wpm  wardskilled    wcpm  controlwardsbought  visionscore    vspm  totalgold  earnedgold  earned gpm  earnedgoldshare  goldspent     gspd   gpr  total cs  minionkills  monsterkills  monsterkillsownjungle  monsterkillsenemyjungle     cspm  goldat10   xpat10  csat10  opp_goldat10  opp_xpat10  opp_csat10  golddiffat10  xpdiffat10  csdiffat10  killsat10  assistsat10  deathsat10  opp_killsat10  opp_assistsat10  opp_deathsat10  goldat15   xpat15  csat15  opp_goldat15  opp_xpat15  opp_csat15  golddiffat15  xpdiffat15  csdiffat15  killsat15  assistsat15  deathsat15  opp_killsat15  opp_assistsat15  opp_deathsat15  goldat20   xpat20  csat20  opp_goldat20  opp_xpat20  opp_csat20  golddiffat20  xpdiffat20  csdiffat20  killsat20  assistsat20  deathsat20  opp_killsat20  opp_assistsat20  opp_deathsat20  goldat25   xpat25  csat25  opp_goldat25  opp_xpat25  opp_csat25  golddiffat25  xpdiffat25  csdiffat25  killsat25  assistsat25  deathsat25  opp_killsat25  opp_assistsat25  opp_deathsat25
1344  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              1  Blue      top    Carlsen  oe:player:5fa6eac8bedeed60a83f154d9538ee1  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  K'Sante  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      2       3        1          3          11          0.0          0.0          0.0         0.0         1.0             1.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              11006   284.2703     0.145230             1054.3263                 1495.4025           278.0           17  0.4391            4  0.1033                   9           30  0.7749      12726        7711    199.1649         0.210487      12275      NaN   NaN     302.0        302.0             0                    NaN                      NaN   7.8003    3792.0   5191.0    95.0        3068.0      4681.0        78.0         724.0       510.0        17.0        1.0          0.0         0.0            0.0              0.0             1.0    5412.0   7863.0   148.0        5050.0      7787.0       139.0         362.0        76.0         9.0        1.0          0.0         0.0            0.0              0.0             1.0    7323.0  10562.0   200.0        7376.0     11011.0       188.0         -53.0      -449.0        12.0        1.0          0.0         0.0            0.0              0.0             1.0    9091.0  13138.0   248.0        8941.0     13231.0       229.0         150.0       -93.0        19.0        1.0          1.0         0.0            0.0              0.0             1.0
1345  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              2  Blue      jng       Sheo  oe:player:404079b4e478ea2a8b57904c640311b  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  Sejuani  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       1        2          3          11          0.0          0.0          0.0         0.0         1.0             0.0               1.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0               8151   210.5295     0.107557              898.1920                 1484.2445           380.0           14  0.3616            8  0.2066                  13           52  1.3431      11882        6867    177.3655         0.187450      11600      NaN   NaN     243.0         22.0           221                    NaN                      NaN   6.2764    3279.0   3708.0    69.0        3118.0      3700.0        70.0         161.0         8.0        -1.0        0.0          1.0         0.0            0.0              0.0             0.0    5012.0   5913.0   109.0        4690.0      6016.0       114.0         322.0      -103.0        -5.0        0.0          1.0         0.0            0.0              0.0             0.0    6824.0   8883.0   154.0        6083.0      7750.0       142.0         741.0      1133.0        12.0        0.0          1.0         0.0            0.0              0.0             0.0    8358.0  11068.0   188.0        7230.0      8984.0       161.0        1128.0      2084.0        27.0        0.0          2.0         0.0            0.0              0.0             0.0
1346  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              3  Blue      mid    Kamiloo  oe:player:728ce343a6718cfdd5d223c971cc2fd  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458   Viktor  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      1       3        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              29458   760.8610     0.388715              399.7503                  357.3655          4544.0           22  0.5682           10  0.2583                  11           62  1.6014      13628        8613    222.4623         0.235107      13825      NaN   NaN     320.0        320.0             0                    NaN                      NaN   8.2652    3127.0   4475.0    79.0        3160.0      4604.0        85.0         -33.0      -129.0        -6.0        0.0          0.0         0.0            0.0              0.0             0.0    5020.0   7353.0   141.0        4877.0      7437.0       137.0         143.0       -84.0         4.0        0.0          0.0         0.0            0.0              0.0             0.0    7035.0   9939.0   190.0        6895.0     10461.0       188.0         140.0      -522.0         2.0        0.0          0.0         0.0            0.0              0.0             0.0    9051.0  12275.0   237.0        8362.0     12543.0       224.0         689.0      -268.0        13.0        1.0          0.0         0.0            0.0              0.0             0.0
1347  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              4  Blue      bot    Flakked  oe:player:717bb4d71a2dab54e7020b1a8fde420  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Zeri  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0              23762   613.7409     0.313553              448.8506                  243.2028          1821.0           18  0.4649           21  0.5424                   5           68  1.7563      15603       10588    273.4740         0.289015      14725      NaN   NaN     398.0        368.0            30                    NaN                      NaN  10.2798    3296.0   3771.0    86.0        3462.0      3656.0        96.0        -166.0       115.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    5560.0   6299.0   139.0        5234.0      6185.0       149.0         326.0       114.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    7708.0   8813.0   199.0        7383.0      8992.0       214.0         325.0      -179.0       -15.0        0.0          0.0         0.0            0.0              0.0             0.0    9832.0  11883.0   256.0        9301.0     11304.0       270.0         531.0       579.0       -14.0        0.0          1.0         0.0            0.0              0.0             0.0
1348  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              5  Blue      sup      Stend  oe:player:41672e17bc1f86dc5d93955c031d2a9  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Rell  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0               3406    87.9724     0.044944              425.3207                  571.5885             0.0           75  1.9372           16  0.4133                  17          140  3.6160       7870        2855     73.7409         0.077941       7625      NaN   NaN      38.0         38.0             0                    NaN                      NaN   0.9815    2121.0   2231.0    13.0        2058.0      2456.0        15.0          63.0      -225.0        -2.0        0.0          0.0         0.0            0.0              0.0             0.0    3138.0   3321.0    22.0        3062.0      3211.0        19.0          76.0       110.0         3.0        0.0          0.0         0.0            0.0              0.0             0.0    4217.0   4374.0    30.0        4108.0      4347.0        23.0         109.0        27.0         7.0        0.0          0.0         0.0            0.0              0.0             0.0    5207.0   4604.0    35.0        5030.0      5051.0        27.0         177.0      -447.0         8.0        0.0          1.0         0.0            0.0              0.0             1.0
1349  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              6   Red      top       Adam  oe:player:6a9abcfebed9c636ca90560b7f49855          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243    Garen  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      2       1        5         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               1.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              15847   409.3069     0.174550             1039.3457                 1818.8291         14044.0           11  0.2841           15  0.3874                   4           45  1.1623      17157       12142    313.6117         0.252866      16000      NaN   NaN     348.0        344.0             4                    NaN                      NaN   8.9884    3068.0   4681.0    78.0        3792.0      5191.0        95.0        -724.0      -510.0       -17.0        0.0          0.0         1.0            1.0              0.0             0.0    5050.0   7787.0   139.0        5412.0      7863.0       148.0        -362.0       -76.0        -9.0        0.0          0.0         1.0            1.0              0.0             0.0    7376.0  11011.0   188.0        7323.0     10562.0       200.0          53.0       449.0       -12.0        0.0          0.0         1.0            1.0              0.0             0.0    8941.0  13231.0   229.0        9091.0     13138.0       248.0        -150.0        93.0       -19.0        0.0          0.0         1.0            1.0              1.0             0.0
1350  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              7   Red      jng    Malrang  oe:player:b06f165ee2371a61d3be74d413e1e21          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243   Maokai  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      2       0        6         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     1.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         1.0             0.0              17439   450.4262     0.192085              920.0947                  792.7594             0.0           10  0.2583           17  0.4391                   7           61  1.5755      12565        7550    195.0065         0.157238      10625      NaN   NaN     206.0         20.0           186                    NaN                      NaN   5.3207    3118.0   3700.0    70.0        3279.0      3708.0        69.0        -161.0        -8.0         1.0        0.0          0.0         0.0            0.0              1.0             0.0    4690.0   6016.0   114.0        5012.0      5913.0       109.0        -322.0       103.0         5.0        0.0          0.0         0.0            0.0              1.0             0.0    6083.0   7750.0   142.0        6824.0      8883.0       154.0        -741.0     -1133.0       -12.0        0.0          0.0         0.0            0.0              1.0             0.0    7230.0   8984.0   161.0        8358.0     11068.0       188.0       -1128.0     -2084.0       -27.0        0.0          0.0         0.0            0.0              2.0             0.0
1351  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              8   Red      mid    Larssen  oe:player:d3f8c554a302aebd5d2bae668ae197e          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243  Orianna  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      1       0       10         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              23290   601.5497     0.256532              405.0194                  323.8140          4331.0           14  0.3616            6  0.1550                   3           33  0.8523      14865        9850    254.4124         0.205135      13975      NaN   NaN     297.0        285.0            12                    NaN                      NaN   7.6711    3160.0   4604.0    85.0        3127.0      4475.0        79.0          33.0       129.0         6.0        0.0          0.0         0.0            0.0              0.0             0.0    4877.0   7437.0   137.0        5020.0      7353.0       141.0        -143.0        84.0        -4.0        0.0          0.0         0.0            0.0              0.0             0.0    6895.0  10461.0   188.0        7035.0      9939.0       190.0        -140.0       522.0        -2.0        0.0          0.0         0.0            0.0              0.0             0.0    8362.0  12543.0   224.0        9051.0     12275.0       237.0        -689.0       268.0       -13.0        0.0          0.0         0.0            1.0              0.0             0.0

In [24]:
len(df["teamname"].unique())

447

In [20]:
len(df)/12

10051.833333333334

In [21]:
print(df["patch"].unique())

[15.01 15.02 15.03 15.04 15.05 15.06 15.07 15.08 15.09 15.1  15.11 15.12
 15.13 15.14 15.15 15.16 15.17 15.18 15.19 15.2  15.21 15.22 15.23 15.24]

In [ ]:
# on essaye de faire tenir une game par ligne

In [22]:
import pandas as pd

# Copie de sécurité
df0 = df.copy()

# Colonnes d'identification d'une game
GAME_KEYS = [
    "gameid", "league", "year", "split", "playoffs",
    "date", "game", "patch"
]

# =========================
# 1️⃣ Séparer joueurs / teams
# =========================
df_players = df0[df0["participantid"].between(1, 10)]
df_teams = df0[df0["participantid"].isin([100, 200])]

# =========================
# 2️⃣ Pivot joueurs → 1 ligne par game
# =========================
player_cols = [c for c in df_players.columns if c not in GAME_KEYS + ["participantid"]]

players_wide = (
    df_players
    .set_index(GAME_KEYS + ["participantid"])[player_cols]
    .unstack("participantid")
)

# Aplatir les colonnes (ex: kills_p1, kills_p2, ...)
players_wide.columns = [
    f"{col}_p{pid}" for col, pid in players_wide.columns
]

players_wide = players_wide.reset_index()

# =========================
# 3️⃣ Pivot teams (Blue / Red)
# =========================
team_cols = [c for c in df_teams.columns if c not in GAME_KEYS + ["participantid"]]

teams_wide = (
    df_teams
    .set_index(GAME_KEYS + ["participantid"])[team_cols]
    .unstack("participantid")
)

teams_wide.columns = [
    f"{col}_{'blue' if pid == 100 else 'red'}"
    for col, pid in teams_wide.columns
]

teams_wide = teams_wide.reset_index()

# =========================
# 4️⃣ Fusion finale
# =========================
df_games = (
    players_wide
    .merge(teams_wide, on=GAME_KEYS, how="left")
)

df_games.head()

,gameid,league,year,split,playoffs,date,game,patch,datacompleteness_p1,datacompleteness_p2,...,assistsat25_blue,assistsat25_red,deathsat25_blue,deathsat25_red,opp_killsat25_blue,opp_killsat25_red,opp_assistsat25_blue,opp_assistsat25_red,opp_deathsat25_blue,opp_deathsat25_red
0,11715-11715_game_1,LPL,2025,Split 1,0,2025-01-12 09:24:17,1,15.01,partial,partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,11715-11715_game_2,LPL,2025,Split 1,0,2025-01-12 10:26:00,2,15.01,partial,partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11715-11715_game_3,LPL,2025,Split 1,0,2025-01-12 11:21:40,3,15.01,partial,partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11716-11716_game_1,LPL,2025,Split 1,0,2025-01-13 09:35:11,1,15.01,partial,partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11716-11716_game_2,LPL,2025,Split 1,0,2025-01-13 10:36:48,2,15.01,partial,partial,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
df_games["split"].unique()

array(['Split 1', 'Split 2 Placements', 'Split 2', 'Split 3', nan,
       'Winter', 'Forge', 'Cup', 'Kickoff', 'Spring', 'Rounds 1-2',
       'Storm', 'Champ 1', 'Ignite', 'Summer', 'Rounds 3-5', 'Champ 2',
       'Finals', 'Final Four', 'Flash In'], dtype=object)

In [26]:
df_games.shape

(10053, 1868)

In [28]:
print(df_games["side_p1"].unique())

['Blue' nan]

In [35]:
print(df_games[df_games["side_p1"].isna()].to_string())

                gameid league  year split  playoffs                 date  game  patch datacompleteness_p1 datacompleteness_p2 datacompleteness_p3 datacompleteness_p4 datacompleteness_p5 datacompleteness_p6 datacompleteness_p7 datacompleteness_p8 datacompleteness_p9 datacompleteness_p10 url_p1 url_p2 url_p3 url_p4 url_p5 url_p6 url_p7 url_p8 url_p9 url_p10 side_p1 side_p2 side_p3 side_p4 side_p5 side_p6 side_p7 side_p8 side_p9 side_p10 position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10 playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10 teamname_p1        teamname_p2  teamname_p3        teamname_p4        teamname_p5 teamname_p6 teamname_p7 teamname_p8 teamname_p9 teamname_p10 teamid_p1                                teamid_p2                                teamid_p3                                teamid_p4                                teamid_p5                                teamid_p6                                teamid_p7                                teamid_p8                                teamid_p9                               teamid_p10 champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8   champion_p9 champion_p10 ban1_p1 ban1_p2 ban1_p3 ban1_p4 ban1_p5 ban1_p6 ban1_p7 ban1_p8 ban1_p9 ban1_p10 ban2_p1 ban2_p2 ban2_p3 ban2_p4 ban2_p5 ban2_p6 ban2_p7 ban2_p8 ban2_p9 ban2_p10 ban3_p1 ban3_p2 ban3_p3 ban3_p4 ban3_p5 ban3_p6 ban3_p7 ban3_p8 ban3_p9 ban3_p10 ban4_p1 ban4_p2 ban4_p3 ban4_p4 ban4_p5 ban4_p6 ban4_p7 ban4_p8 ban4_p9 ban4_p10 ban5_p1 ban5_p2 ban5_p3 ban5_p4 ban5_p5 ban5_p6 ban5_p7 ban5_p8 ban5_p9 ban5_p10 pick1_p1 pick1_p2 pick1_p3 pick1_p4 pick1_p5 pick1_p6 pick1_p7 pick1_p8 pick1_p9 pick1_p10 pick2_p1 pick2_p2 pick2_p3 pick2_p4 pick2_p5 pick2_p6 pick2_p7 pick2_p8 pick2_p9 pick2_p10 pick3_p1 pick3_p2 pick3_p3 pick3_p4 pick3_p5 pick3_p6 pick3_p7 pick3_p8 pick3_p9 pick3_p10 pick4_p1 pick4_p2 pick4_p3 pick4_p4 pick4_p5 pick4_p6 pick4_p7 pick4_p8 pick4_p9 pick4_p10 pick5_p1 pick5_p2 pick5_p3 pick5_p4 pick5_p5 pick5_p6 pick5_p7 pick5_p8 pick5_p9 pick5_p10  gamelength_p1  gamelength_p2  gamelength_p3  gamelength_p4  gamelength_p5  gamelength_p6  gamelength_p7  gamelength_p8  gamelength_p9  gamelength_p10  result_p1  result_p2  result_p3  result_p4  result_p5  result_p6  result_p7  result_p8  result_p9  result_p10  kills_p1  kills_p2  kills_p3  kills_p4  kills_p5  kills_p6  kills_p7  kills_p8  kills_p9  kills_p10  deaths_p1  deaths_p2  deaths_p3  deaths_p4  deaths_p5  deaths_p6  deaths_p7  deaths_p8  deaths_p9  deaths_p10  assists_p1  assists_p2  assists_p3  assists_p4  assists_p5  assists_p6  assists_p7  assists_p8  assists_p9  assists_p10  teamkills_p1  teamkills_p2  teamkills_p3  teamkills_p4  teamkills_p5  teamkills_p6  teamkills_p7  teamkills_p8  teamkills_p9  teamkills_p10  teamdeaths_p1  teamdeaths_p2  teamdeaths_p3  teamdeaths_p4  teamdeaths_p5  teamdeaths_p6  teamdeaths_p7  teamdeaths_p8  teamdeaths_p9  teamdeaths_p10  doublekills_p1  doublekills_p2  doublekills_p3  doublekills_p4  doublekills_p5  doublekills_p6  doublekills_p7  doublekills_p8  doublekills_p9  doublekills_p10  triplekills_p1  triplekills_p2  triplekills_p3  triplekills_p4  triplekills_p5  triplekills_p6  triplekills_p7  triplekills_p8  triplekills_p9  triplekills_p10  quadrakills_p1  quadrakills_p2  quadrakills_p3  quadrakills_p4  quadrakills_p5  quadrakills_p6  quadrakills_p7  quadrakills_p8  quadrakills_p9  quadrakills_p10  pentakills_p1  pentakills_p2  pentakills_p3  pentakills_p4  pentakills_p5  pentakills_p6  pentakills_p7  pentakills_p8  pentakills_p9  pentakills_p10  firstblood_p1  firstblood_p2  firstblood_p3  firstblood_p4  firstblood_p5  firstblood_p6  firstblood_p7  firstblood_p8  firstblood_p9  firstblood_p10  firstbloodkill_p1  firstbloodkill_p2  firstbloodkill_p3  firstbloodkill_p4  firstbloodkill_p5  firstbloodkill_p6  firstbloodkill_p7  firstbloodkill_p8  firstbloodkill_p9  firstbloodkill_p10  firstbloodassist_p1  firstbloodassist_p2  firstbloodassist_p3  firstbloodassist_p4  firstbloodassist_p5  firstbloodassist_p6  firstbloodassist_p7  firstbloodassist_p8  firstbloodassist_p9  firstbloodassist_p10  firstbloodvictim_p1  firstbloodvictim_p2  firstbloodvictim_p3  firstbloodvictim_p4  firstbloodvictim_p5  firstbloodvictim_p6  firstbloodvictim_p7  firstbloodvictim_p8  firstbloodvictim_p9  firstbloodvictim_p10  team kpm_p1  team kpm_p2  team kpm_p3  team kpm_p4  team kpm_p5  team kpm_p6  team kpm_p7  team kpm_p8  team kpm_p9  team kpm_p10  ckpm_p1  ckpm_p2  ckpm_p3  ckpm_p4  ckpm_p5  ckpm_p6  ckpm_p7  ckpm_p8  ckpm_p9  ckpm_p10  firstdragon_p1  firstdragon_p2  firstdragon_p3  firstdragon_p4  firstdragon_p5  firstdragon_p6  firstdragon_p7  firstdragon_p8  firstdragon_p9  firstdragon_p10  dragons_p1  dragons_p2  dragons_p3  dragons_p4  dragons_p5  dragons_p6  dragons_p7  dragons_p8  dragons_p9  dragons_p10  opp_dragons_p1  opp_dragons_p2  opp_dragons_p3  opp_dragons_p4  opp_dragons_p5  opp_dragons_p6  opp_dragons_p7  opp_dragons_p8  opp_dragons_p9  opp_dragons_p10  elementaldrakes_p1  elementaldrakes_p2  elementaldrakes_p3  elementaldrakes_p4  elementaldrakes_p5  elementaldrakes_p6  elementaldrakes_p7  elementaldrakes_p8  elementaldrakes_p9  elementaldrakes_p10  opp_elementaldrakes_p1  opp_elementaldrakes_p2  opp_elementaldrakes_p3  opp_elementaldrakes_p4  opp_elementaldrakes_p5  opp_elementaldrakes_p6  opp_elementaldrakes_p7  opp_elementaldrakes_p8  opp_elementaldrakes_p9  opp_elementaldrakes_p10  infernals_p1  infernals_p2  infernals_p3  infernals_p4  infernals_p5  infernals_p6  infernals_p7  infernals_p8  infernals_p9  infernals_p10  mountains_p1  mountains_p2  mountains_p3  mountains_p4  mountains_p5  mountains_p6  mountains_p7  mountains_p8  mountains_p9  mountains_p10  clouds_p1  clouds_p2  clouds_p3  clouds_p4  clouds_p5  clouds_p6  clouds_p7  clouds_p8  clouds_p9  clouds_p10  oceans_p1  oceans_p2  oceans_p3  oceans_p4  oceans_p5  oceans_p6  oceans_p7  oceans_p8  oceans_p9  oceans_p10  chemtechs_p1  chemtechs_p2  chemtechs_p3  chemtechs_p4  chemtechs_p5  chemtechs_p6  chemtechs_p7  chemtechs_p8  chemtechs_p9  chemtechs_p10  hextechs_p1  hextechs_p2  hextechs_p3  hextechs_p4  hextechs_p5  hextechs_p6  hextechs_p7  hextechs_p8  hextechs_p9  hextechs_p10  dragons (type unknown)_p1  dragons (type unknown)_p2  dragons (type unknown)_p3  dragons (type unknown)_p4  dragons (type unknown)_p5  dragons (type unknown)_p6  dragons (type unknown)_p7  dragons (type unknown)_p8  dragons (type unknown)_p9  dragons (type unknown)_p10  elders_p1  elders_p2  elders_p3  elders_p4  elders_p5  elders_p6  elders_p7  elders_p8  elders_p9  elders_p10  opp_elders_p1  opp_elders_p2  opp_elders_p3  opp_elders_p4  opp_elders_p5  opp_elders_p6  opp_elders_p7  opp_elders_p8  opp_elders_p9  opp_elders_p10  firstherald_p1  firstherald_p2  firstherald_p3  firstherald_p4  firstherald_p5  firstherald_p6  firstherald_p7  firstherald_p8  firstherald_p9  firstherald_p10  heralds_p1  heralds_p2  heralds_p3  heralds_p4  heralds_p5  heralds_p6  heralds_p7  heralds_p8  heralds_p9  heralds_p10  opp_heralds_p1  opp_heralds_p2  opp_heralds_p3  opp_heralds_p4  opp_heralds_p5  opp_heralds_p6  opp_heralds_p7  opp_heralds_p8  opp_heralds_p9  opp_heralds_p10  void_grubs_p1  void_grubs_p2  void_grubs_p3  void_grubs_p4  void_grubs_p5  void_grubs_p6  void_grubs_p7  void_grubs_p8  void_grubs_p9  void_grubs_p10  opp_void_grubs_p1  opp_void_grubs_p2  opp_void_grubs_p3  opp_void_grubs_p4  opp_void_grubs_p5  opp_void_grubs_p6  opp_void_grubs_p7  opp_void_grubs_p8  opp_void_grubs_p9  opp_void_grubs_p10  firstbaron_p1  firstbaron_p2  firstbaron_p3  firstbaron_p4  firstbaron_p5  firstbaron_p6  firstbaron_p7  firstbaron_p8  firstbaron_p9  firstbaron_p10  barons_p1  barons_p2  barons_p3  barons_p4  barons_p5  barons_p6  barons_p7  barons_p8  barons_p9  barons_p10  opp_barons_p1  opp_barons_p2  opp_barons_p3  opp_barons_p4  opp_barons_p5  opp_barons_p6  opp_barons_p7  opp_barons_p8  opp_barons_p9  opp_barons_p10  atakhans_p1  atakhans_p2  atakhans_p3  atakhans_p4  atakhans_p5  atakhans_p6  atakhans_p7  atakhans_p8  atakhans_p9  atakhans_p10  opp_atakhans_p1  opp_atakhans_p2  opp_atakhans_p3  opp_atakhans_p4  opp_atakhans_p5  opp_atakhans_p6  opp_atakhans_p7  opp_atakhans_p8  opp_atakhans_p9  opp_atakhans_p10  firsttower_p1  firsttower_p2  firsttower_p3  firsttower_p4  firsttower_p5  firsttower_p6  firsttower_p7  firsttower_p8  firsttower_p9  firsttower_p10  towers_p1  towers_p2  towers_p3  towers_p4  towers_p5  towers_p6  towers_p7  towers_p8  towers_p9  towers_p10  opp_towers_p1  opp_towers_p2  opp_towers_p3  opp_towers_p4  opp_towers_p5  opp_towers_p6  opp_towers_p7  opp_towers_p8  opp_towers_p9  opp_towers_p10  firstmidtower_p1  firstmidtower_p2  firstmidtower_p3  firstmidtower_p4  firstmidtower_p5  firstmidtower_p6  firstmidtower_p7  firstmidtower_p8  firstmidtower_p9  firstmidtower_p10  firsttothreetowers_p1  firsttothreetowers_p2  firsttothreetowers_p3  firsttothreetowers_p4  firsttothreetowers_p5  firsttothreetowers_p6  firsttothreetowers_p7  firsttothreetowers_p8  firsttothreetowers_p9  firsttothreetowers_p10  turretplates_p1  turretplates_p2  turretplates_p3  turretplates_p4  turretplates_p5  turretplates_p6  turretplates_p7  turretplates_p8  turretplates_p9  turretplates_p10  opp_turretplates_p1  opp_turretplates_p2  opp_turretplates_p3  opp_turretplates_p4  opp_turretplates_p5  opp_turretplates_p6  opp_turretplates_p7  opp_turretplates_p8  opp_turretplates_p9  opp_turretplates_p10  inhibitors_p1  inhibitors_p2  inhibitors_p3  inhibitors_p4  inhibitors_p5  inhibitors_p6  inhibitors_p7  inhibitors_p8  inhibitors_p9  inhibitors_p10  opp_inhibitors_p1  opp_inhibitors_p2  opp_inhibitors_p3  opp_inhibitors_p4  opp_inhibitors_p5  opp_inhibitors_p6  opp_inhibitors_p7  opp_inhibitors_p8  opp_inhibitors_p9  opp_inhibitors_p10  damagetochampions_p1  damagetochampions_p2  damagetochampions_p3  damagetochampions_p4  damagetochampions_p5  damagetochampions_p6  damagetochampions_p7  damagetochampions_p8  damagetochampions_p9  damagetochampions_p10  dpm_p1    dpm_p2    dpm_p3    dpm_p4    dpm_p5    dpm_p6    dpm_p7    dpm_p8    dpm_p9   dpm_p10  damageshare_p1  damageshare_p2  damageshare_p3  damageshare_p4  damageshare_p5  damageshare_p6  damageshare_p7  damageshare_p8  damageshare_p9  damageshare_p10  damagetakenperminute_p1  damagetakenperminute_p2  damagetakenperminute_p3  damagetakenperminute_p4  damagetakenperminute_p5  damagetakenperminute_p6  damagetakenperminute_p7  damagetakenperminute_p8  damagetakenperminute_p9  damagetakenperminute_p10  damagemitigatedperminute_p1  damagemitigatedperminute_p2  damagemitigatedperminute_p3  damagemitigatedperminute_p4  damagemitigatedperminute_p5  damagemitigatedperminute_p6  damagemitigatedperminute_p7  damagemitigatedperminute_p8  damagemitigatedperminute_p9  damagemitigatedperminute_p10  damagetotowers_p1  damagetotowers_p2  damagetotowers_p3  damagetotowers_p4  damagetotowers_p5  damagetotowers_p6  damagetotowers_p7  damagetotowers_p8  damagetotowers_p9  damagetotowers_p10  wardsplaced_p1  wardsplaced_p2  wardsplaced_p3  wardsplaced_p4  wardsplaced_p5  wardsplaced_p6  wardsplaced_p7  wardsplaced_p8  wardsplaced_p9  wardsplaced_p10  wpm_p1  wpm_p2  wpm_p3  wpm_p4  wpm_p5  wpm_p6  wpm_p7  wpm_p8  wpm_p9  wpm_p10  wardskilled_p1  wardskilled_p2  wardskilled_p3  wardskilled_p4  wardskilled_p5  wardskilled_p6  wardskilled_p7  wardskilled_p8  wardskilled_p9  wardskilled_p10  wcpm_p1  wcpm_p2  wcpm_p3  wcpm_p4  wcpm_p5  wcpm_p6  wcpm_p7  wcpm_p8  wcpm_p9  wcpm_p10  controlwardsbought_p1  controlwardsbought_p2  controlwardsbought_p3  controlwardsbought_p4  controlwardsbought_p5  controlwardsbought_p6  controlwardsbought_p7  controlwardsbought_p8  controlwardsbought_p9  controlwardsbought_p10  visionscore_p1  visionscore_p2  visionscore_p3  visionscore_p4  visionscore_p5  visionscore_p6  visionscore_p7  visionscore_p8  visionscore_p9  visionscore_p10  vspm_p1  vspm_p2  vspm_p3  vspm_p4  vspm_p5  vspm_p6  vspm_p7  vspm_p8  vspm_p9  vspm_p10  totalgold_p1  totalgold_p2  totalgold_p3  totalgold_p4  totalgold_p5  totalgold_p6  totalgold_p7  totalgold_p8  totalgold_p9  totalgold_p10  earnedgold_p1  earnedgold_p2  earnedgold_p3  earnedgold_p4  earnedgold_p5  earnedgold_p6  earnedgold_p7  earnedgold_p8  earnedgold_p9  earnedgold_p10  earned gpm_p1  earned gpm_p2  earned gpm_p3  earned gpm_p4  earned gpm_p5  earned gpm_p6  earned gpm_p7  earned gpm_p8  earned gpm_p9  earned gpm_p10  earnedgoldshare_p1  earnedgoldshare_p2  earnedgoldshare_p3  earnedgoldshare_p4  earnedgoldshare_p5  earnedgoldshare_p6  earnedgoldshare_p7  earnedgoldshare_p8  earnedgoldshare_p9  earnedgoldshare_p10  goldspent_p1  goldspent_p2  goldspent_p3  goldspent_p4  goldspent_p5  goldspent_p6  goldspent_p7  goldspent_p8  goldspent_p9  goldspent_p10  gspd_p1  gspd_p2  gspd_p3  gspd_p4  gspd_p5  gspd_p6  gspd_p7  gspd_p8  gspd_p9  gspd_p10  gpr_p1  gpr_p2  gpr_p3  gpr_p4  gpr_p5  gpr_p6  gpr_p7  gpr_p8  gpr_p9  gpr_p10  total cs_p1  total cs_p2  total cs_p3  total cs_p4  total cs_p5  total cs_p6  total cs_p7  total cs_p8  total cs_p9  total cs_p10  minionkills_p1  minionkills_p2  minionkills_p3  minionkills_p4  minionkills_p5  minionkills_p6  minionkills_p7  minionkills_p8  minionkills_p9  minionkills_p10  monsterkills_p1  monsterkills_p2  monsterkills_p3  monsterkills_p4  monsterkills_p5  monsterkills_p6  monsterkills_p7  monsterkills_p8  monsterkills_p9  monsterkills_p10  monsterkillsownjungle_p1  monsterkillsownjungle_p2  monsterkillsownjungle_p3  monsterkillsownjungle_p4  monsterkillsownjungle_p5  monsterkillsownjungle_p6  monsterkillsownjungle_p7  monsterkillsownjungle_p8  monsterkillsownjungle_p9  monsterkillsownjungle_p10  monsterkillsenemyjungle_p1  monsterkillsenemyjungle_p2  monsterkillsenemyjungle_p3  monsterkillsenemyjungle_p4  monsterkillsenemyjungle_p5  monsterkillsenemyjungle_p6  monsterkillsenemyjungle_p7  monsterkillsenemyjungle_p8  monsterkillsenemyjungle_p9  monsterkillsenemyjungle_p10  cspm_p1  cspm_p2  cspm_p3  cspm_p4  cspm_p5  cspm_p6  cspm_p7  cspm_p8  cspm_p9  cspm_p10  goldat10_p1  goldat10_p2  goldat10_p3  goldat10_p4  goldat10_p5  goldat10_p6  goldat10_p7  goldat10_p8  goldat10_p9  goldat10_p10  xpat10_p1  xpat10_p2  xpat10_p3  xpat10_p4  xpat10_p5  xpat10_p6  xpat10_p7  xpat10_p8  xpat10_p9  xpat10_p10  csat10_p1  csat10_p2  csat10_p3  csat10_p4  csat10_p5  csat10_p6  csat10_p7  csat10_p8  csat10_p9  csat10_p10  opp_goldat10_p1  opp_goldat10_p2  opp_goldat10_p3  opp_goldat10_p4  opp_goldat10_p5  opp_goldat10_p6  opp_goldat10_p7  opp_goldat10_p8  opp_goldat10_p9  opp_goldat10_p10  opp_xpat10_p1  opp_xpat10_p2  opp_xpat10_p3  opp_xpat10_p4  opp_xpat10_p5  opp_xpat10_p6  opp_xpat10_p7  opp_xpat10_p8  opp_xpat10_p9  opp_xpat10_p10  opp_csat10_p1  opp_csat10_p2  opp_csat10_p3  opp_csat10_p4  opp_csat10_p5  opp_csat10_p6  opp_csat10_p7  opp_csat10_p8  opp_csat10_p9  opp_csat10_p10  golddiffat10_p1  golddiffat10_p2  golddiffat10_p3  golddiffat10_p4  golddiffat10_p5  golddiffat10_p6  golddiffat10_p7  golddiffat10_p8  golddiffat10_p9  golddiffat10_p10  xpdiffat10_p1  xpdiffat10_p2  xpdiffat10_p3  xpdiffat10_p4  xpdiffat10_p5  xpdiffat10_p6  xpdiffat10_p7  xpdiffat10_p8  xpdiffat10_p9  xpdiffat10_p10  csdiffat10_p1  csdiffat10_p2  csdiffat10_p3  csdiffat10_p4  csdiffat10_p5  csdiffat10_p6  csdiffat10_p7  csdiffat10_p8  csdiffat10_p9  csdiffat10_p10  killsat10_p1  killsat10_p2  killsat10_p3  killsat10_p4  killsat10_p5  killsat10_p6  killsat10_p7  killsat10_p8  killsat10_p9  killsat10_p10  assistsat10_p1  assistsat10_p2  assistsat10_p3  assistsat10_p4  assistsat10_p5  assistsat10_p6  assistsat10_p7  assistsat10_p8  assistsat10_p9  assistsat10_p10  deathsat10_p1  deathsat10_p2  deathsat10_p3  deathsat10_p4  deathsat10_p5  deathsat10_p6  deathsat10_p7  deathsat10_p8  deathsat10_p9  deathsat10_p10  opp_killsat10_p1  opp_killsat10_p2  opp_killsat10_p3  opp_killsat10_p4  opp_killsat10_p5  opp_killsat10_p6  opp_killsat10_p7  opp_killsat10_p8  opp_killsat10_p9  opp_killsat10_p10  opp_assistsat10_p1  opp_assistsat10_p2  opp_assistsat10_p3  opp_assistsat10_p4  opp_assistsat10_p5  opp_assistsat10_p6  opp_assistsat10_p7  opp_assistsat10_p8  opp_assistsat10_p9  opp_assistsat10_p10  opp_deathsat10_p1  opp_deathsat10_p2  opp_deathsat10_p3  opp_deathsat10_p4  opp_deathsat10_p5  opp_deathsat10_p6  opp_deathsat10_p7  opp_deathsat10_p8  opp_deathsat10_p9  opp_deathsat10_p10  goldat15_p1  goldat15_p2  goldat15_p3  goldat15_p4  goldat15_p5  goldat15_p6  goldat15_p7  goldat15_p8  goldat15_p9  goldat15_p10  xpat15_p1  xpat15_p2  xpat15_p3  xpat15_p4  xpat15_p5  xpat15_p6  xpat15_p7  xpat15_p8  xpat15_p9  xpat15_p10  csat15_p1  csat15_p2  csat15_p3  csat15_p4  csat15_p5  csat15_p6  csat15_p7  csat15_p8  csat15_p9  csat15_p10  opp_goldat15_p1  opp_goldat15_p2  opp_goldat15_p3  opp_goldat15_p4  opp_goldat15_p5  opp_goldat15_p6  opp_goldat15_p7  opp_goldat15_p8  opp_goldat15_p9  opp_goldat15_p10  opp_xpat15_p1  opp_xpat15_p2  opp_xpat15_p3  opp_xpat15_p4  opp_xpat15_p5  opp_xpat15_p6  opp_xpat15_p7  opp_xpat15_p8  opp_xpat15_p9  opp_xpat15_p10  opp_csat15_p1  opp_csat15_p2  opp_csat15_p3  opp_csat15_p4  opp_csat15_p5  opp_csat15_p6  opp_csat15_p7  opp_csat15_p8  opp_csat15_p9  opp_csat15_p10  golddiffat15_p1  golddiffat15_p2  golddiffat15_p3  golddiffat15_p4  golddiffat15_p5  golddiffat15_p6  golddiffat15_p7  golddiffat15_p8  golddiffat15_p9  golddiffat15_p10  xpdiffat15_p1  xpdiffat15_p2  xpdiffat15_p3  xpdiffat15_p4  xpdiffat15_p5  xpdiffat15_p6  xpdiffat15_p7  xpdiffat15_p8  xpdiffat15_p9  xpdiffat15_p10  csdiffat15_p1  csdiffat15_p2  csdiffat15_p3  csdiffat15_p4  csdiffat15_p5  csdiffat15_p6  csdiffat15_p7  csdiffat15_p8  csdiffat15_p9  csdiffat15_p10  killsat15_p1  killsat15_p2  killsat15_p3  killsat15_p4  killsat15_p5  killsat15_p6  killsat15_p7  killsat15_p8  killsat15_p9  killsat15_p10  assistsat15_p1  assistsat15_p2  assistsat15_p3  assistsat15_p4  assistsat15_p5  assistsat15_p6  assistsat15_p7  assistsat15_p8  assistsat15_p9  assistsat15_p10  deathsat15_p1  deathsat15_p2  deathsat15_p3  deathsat15_p4  deathsat15_p5  deathsat15_p6  deathsat15_p7  deathsat15_p8  deathsat15_p9  deathsat15_p10  opp_killsat15_p1  opp_killsat15_p2  opp_killsat15_p3  opp_killsat15_p4  opp_killsat15_p5  opp_killsat15_p6  opp_killsat15_p7  opp_killsat15_p8  opp_killsat15_p9  opp_killsat15_p10  opp_assistsat15_p1  opp_assistsat15_p2  opp_assistsat15_p3  opp_assistsat15_p4  opp_assistsat15_p5  opp_assistsat15_p6  opp_assistsat15_p7  opp_assistsat15_p8  opp_assistsat15_p9  opp_assistsat15_p10  opp_deathsat15_p1  opp_deathsat15_p2  opp_deathsat15_p3  opp_deathsat15_p4  opp_deathsat15_p5  opp_deathsat15_p6  opp_deathsat15_p7  opp_deathsat15_p8  opp_deathsat15_p9  opp_deathsat15_p10  goldat20_p1  goldat20_p2  goldat20_p3  goldat20_p4  goldat20_p5  goldat20_p6  goldat20_p7  goldat20_p8  goldat20_p9  goldat20_p10  xpat20_p1  xpat20_p2  xpat20_p3  xpat20_p4  xpat20_p5  xpat20_p6  xpat20_p7  xpat20_p8  xpat20_p9  xpat20_p10  csat20_p1  csat20_p2  csat20_p3  csat20_p4  csat20_p5  csat20_p6  csat20_p7  csat20_p8  csat20_p9  csat20_p10  opp_goldat20_p1  opp_goldat20_p2  opp_goldat20_p3  opp_goldat20_p4  opp_goldat20_p5  opp_goldat20_p6  opp_goldat20_p7  opp_goldat20_p8  opp_goldat20_p9  opp_goldat20_p10  opp_xpat20_p1  opp_xpat20_p2  opp_xpat20_p3  opp_xpat20_p4  opp_xpat20_p5  opp_xpat20_p6  opp_xpat20_p7  opp_xpat20_p8  opp_xpat20_p9  opp_xpat20_p10  opp_csat20_p1  opp_csat20_p2  opp_csat20_p3  opp_csat20_p4  opp_csat20_p5  o

In [32]:
print(df_games["position_p1"].unique())

['top' 'mid' 'bot' nan]

In [38]:
print(df[df["date"] == "2025-01-18 17:09:08"].to_string())

               gameid datacompleteness  url league  year   split  playoffs                 date  game  patch  participantid  side position playername                                   playerid       teamname                                   teamid champion     ban1  ban2    ban3          ban4    ban5   pick1    pick2    pick3  pick4    pick5  gamelength  result  kills  deaths  assists  teamkills  teamdeaths  doublekills  triplekills  quadrakills  pentakills  firstblood  firstbloodkill  firstbloodassist  firstbloodvictim  team kpm    ckpm  firstdragon  dragons  opp_dragons  elementaldrakes  opp_elementaldrakes  infernals  mountains  clouds  oceans  chemtechs  hextechs  dragons (type unknown)  elders  opp_elders  firstherald  heralds  opp_heralds  void_grubs  opp_void_grubs  firstbaron  barons  opp_barons  atakhans  opp_atakhans  firsttower  towers  opp_towers  firstmidtower  firsttothreetowers  turretplates  opp_turretplates  inhibitors  opp_inhibitors  damagetochampions        dpm  damageshare  damagetakenperminute  damagemitigatedperminute  damagetotowers  wardsplaced     wpm  wardskilled    wcpm  controlwardsbought  visionscore    vspm  totalgold  earnedgold  earned gpm  earnedgoldshare  goldspent     gspd   gpr  total cs  minionkills  monsterkills  monsterkillsownjungle  monsterkillsenemyjungle     cspm  goldat10   xpat10  csat10  opp_goldat10  opp_xpat10  opp_csat10  golddiffat10  xpdiffat10  csdiffat10  killsat10  assistsat10  deathsat10  opp_killsat10  opp_assistsat10  opp_deathsat10  goldat15   xpat15  csat15  opp_goldat15  opp_xpat15  opp_csat15  golddiffat15  xpdiffat15  csdiffat15  killsat15  assistsat15  deathsat15  opp_killsat15  opp_assistsat15  opp_deathsat15  goldat20   xpat20  csat20  opp_goldat20  opp_xpat20  opp_csat20  golddiffat20  xpdiffat20  csdiffat20  killsat20  assistsat20  deathsat20  opp_killsat20  opp_assistsat20  opp_deathsat20  goldat25   xpat25  csat25  opp_goldat25  opp_xpat25  opp_csat25  golddiffat25  xpdiffat25  csdiffat25  killsat25  assistsat25  deathsat25  opp_killsat25  opp_assistsat25  opp_deathsat25
1344  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              1  Blue      top    Carlsen  oe:player:5fa6eac8bedeed60a83f154d9538ee1  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  K'Sante  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      2       3        1          3          11          0.0          0.0          0.0         0.0         1.0             1.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              11006   284.2703     0.145230             1054.3263                 1495.4025           278.0           17  0.4391            4  0.1033                   9           30  0.7749      12726        7711    199.1649         0.210487      12275      NaN   NaN     302.0        302.0             0                    NaN                      NaN   7.8003    3792.0   5191.0    95.0        3068.0      4681.0        78.0         724.0       510.0        17.0        1.0          0.0         0.0            0.0              0.0             1.0    5412.0   7863.0   148.0        5050.0      7787.0       139.0         362.0        76.0         9.0        1.0          0.0         0.0            0.0              0.0             1.0    7323.0  10562.0   200.0        7376.0     11011.0       188.0         -53.0      -449.0        12.0        1.0          0.0         0.0            0.0              0.0             1.0    9091.0  13138.0   248.0        8941.0     13231.0       229.0         150.0       -93.0        19.0        1.0          1.0         0.0            0.0              0.0             1.0
1345  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              2  Blue      jng       Sheo  oe:player:404079b4e478ea2a8b57904c640311b  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458  Sejuani  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       1        2          3          11          0.0          0.0          0.0         0.0         1.0             0.0               1.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0               8151   210.5295     0.107557              898.1920                 1484.2445           380.0           14  0.3616            8  0.2066                  13           52  1.3431      11882        6867    177.3655         0.187450      11600      NaN   NaN     243.0         22.0           221                    NaN                      NaN   6.2764    3279.0   3708.0    69.0        3118.0      3700.0        70.0         161.0         8.0        -1.0        0.0          1.0         0.0            0.0              0.0             0.0    5012.0   5913.0   109.0        4690.0      6016.0       114.0         322.0      -103.0        -5.0        0.0          1.0         0.0            0.0              0.0             0.0    6824.0   8883.0   154.0        6083.0      7750.0       142.0         741.0      1133.0        12.0        0.0          1.0         0.0            0.0              0.0             0.0    8358.0  11068.0   188.0        7230.0      8984.0       161.0        1128.0      2084.0        27.0        0.0          2.0         0.0            0.0              0.0             0.0
1346  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              3  Blue      mid    Kamiloo  oe:player:728ce343a6718cfdd5d223c971cc2fd  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458   Viktor  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      1       3        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              29458   760.8610     0.388715              399.7503                  357.3655          4544.0           22  0.5682           10  0.2583                  11           62  1.6014      13628        8613    222.4623         0.235107      13825      NaN   NaN     320.0        320.0             0                    NaN                      NaN   8.2652    3127.0   4475.0    79.0        3160.0      4604.0        85.0         -33.0      -129.0        -6.0        0.0          0.0         0.0            0.0              0.0             0.0    5020.0   7353.0   141.0        4877.0      7437.0       137.0         143.0       -84.0         4.0        0.0          0.0         0.0            0.0              0.0             0.0    7035.0   9939.0   190.0        6895.0     10461.0       188.0         140.0      -522.0         2.0        0.0          0.0         0.0            0.0              0.0             0.0    9051.0  12275.0   237.0        8362.0     12543.0       224.0         689.0      -268.0        13.0        1.0          0.0         0.0            0.0              0.0             0.0
1347  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              4  Blue      bot    Flakked  oe:player:717bb4d71a2dab54e7020b1a8fde420  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Zeri  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         1.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             1.0              23762   613.7409     0.313553              448.8506                  243.2028          1821.0           18  0.4649           21  0.5424                   5           68  1.7563      15603       10588    273.4740         0.289015      14725      NaN   NaN     398.0        368.0            30                    NaN                      NaN  10.2798    3296.0   3771.0    86.0        3462.0      3656.0        96.0        -166.0       115.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    5560.0   6299.0   139.0        5234.0      6185.0       149.0         326.0       114.0       -10.0        0.0          0.0         0.0            0.0              0.0             0.0    7708.0   8813.0   199.0        7383.0      8992.0       214.0         325.0      -179.0       -15.0        0.0          0.0         0.0            0.0              0.0             0.0    9832.0  11883.0   256.0        9301.0     11304.0       270.0         531.0       579.0       -14.0        0.0          1.0         0.0            0.0              0.0             0.0
1348  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              5  Blue      sup      Stend  oe:player:41672e17bc1f86dc5d93955c031d2a9  Team Heretics  oe:team:1285e1c04d54de96502f12da4d49458     Rell  Kalista  Azir  Aurora  Renata Glasc  Wukong     NaN      NaN      NaN    NaN      NaN        2323       0      0       2        1          3          11          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.0775  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0               3406    87.9724     0.044944              425.3207                  571.5885             0.0           75  1.9372           16  0.4133                  17          140  3.6160       7870        2855     73.7409         0.077941       7625      NaN   NaN      38.0         38.0             0                    NaN                      NaN   0.9815    2121.0   2231.0    13.0        2058.0      2456.0        15.0          63.0      -225.0        -2.0        0.0          0.0         0.0            0.0              0.0             0.0    3138.0   3321.0    22.0        3062.0      3211.0        19.0          76.0       110.0         3.0        0.0          0.0         0.0            0.0              0.0             0.0    4217.0   4374.0    30.0        4108.0      4347.0        23.0         109.0        27.0         7.0        0.0          0.0         0.0            0.0              0.0             0.0    5207.0   4604.0    35.0        5030.0      5051.0        27.0         177.0      -447.0         8.0        0.0          1.0         0.0            0.0              0.0             1.0
1349  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              6   Red      top       Adam  oe:player:6a9abcfebed9c636ca90560b7f49855          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243    Garen  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      2       1        5         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               1.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              15847   409.3069     0.174550             1039.3457                 1818.8291         14044.0           11  0.2841           15  0.3874                   4           45  1.1623      17157       12142    313.6117         0.252866      16000      NaN   NaN     348.0        344.0             4                    NaN                      NaN   8.9884    3068.0   4681.0    78.0        3792.0      5191.0        95.0        -724.0      -510.0       -17.0        0.0          0.0         1.0            1.0              0.0             0.0    5050.0   7787.0   139.0        5412.0      7863.0       148.0        -362.0       -76.0        -9.0        0.0          0.0         1.0            1.0              0.0             0.0    7376.0  11011.0   188.0        7323.0     10562.0       200.0          53.0       449.0       -12.0        0.0          0.0         1.0            1.0              0.0             0.0    8941.0  13231.0   229.0        9091.0     13138.0       248.0        -150.0        93.0       -19.0        0.0          0.0         1.0            1.0              1.0             0.0
1350  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              7   Red      jng    Malrang  oe:player:b06f165ee2371a61d3be74d413e1e21          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243   Maokai  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      2       0        6         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     1.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         1.0             0.0              17439   450.4262     0.192085              920.0947                  792.7594             0.0           10  0.2583           17  0.4391                   7           61  1.5755      12565        7550    195.0065         0.157238      10625      NaN   NaN     206.0         20.0           186                    NaN                      NaN   5.3207    3118.0   3700.0    70.0        3279.0      3708.0        69.0        -161.0        -8.0         1.0        0.0          0.0         0.0            0.0              1.0             0.0    4690.0   6016.0   114.0        5012.0      5913.0       109.0        -322.0       103.0         5.0        0.0          0.0         0.0            0.0              1.0             0.0    6083.0   7750.0   142.0        6824.0      8883.0       154.0        -741.0     -1133.0       -12.0        0.0          0.0         0.0            0.0              1.0             0.0    7230.0   8984.0   161.0        8358.0     11068.0       188.0       -1128.0     -2084.0       -27.0        0.0          0.0         0.0            0.0              2.0             0.0
1351  LOLTMNT06_96344         complete  NaN    LEC  2025  Winter         0  2025-01-18 17:09:08     1  15.01              8   Red      mid    Larssen  oe:player:d3f8c554a302aebd5d2bae668ae197e          Rogue  oe:team:cd62e47544f14f1d239afa659b9d243  Orianna  Skarner    Vi   Corki          Ashe  Ezreal     NaN      NaN      NaN    NaN      NaN        2323       1      1       0       10         11           3          0.0          0.0          0.0         0.0         0.0             0.0               0.0               0.0    0.2841  0.3616          NaN      NaN          NaN              NaN                  NaN        NaN        NaN     NaN     NaN        NaN       NaN                     NaN     NaN         NaN          NaN      NaN          NaN         NaN             NaN         NaN     0.0         0.0       NaN           NaN         NaN     NaN         NaN            NaN                 NaN           NaN               NaN         0.0             0.0              23290   601.5497     0.256532              405.0194                  323.8140          4331.0           14  0.3616            6  0.1550                   3           33  0.8523      14865        9850    254.4124         0.205135      13975      NaN   NaN     297.0        285.0            12                    NaN                      NaN   7.6711    3160.0   4604.0    85.0        3127.0      4475.0        79.0          33.0       129.0         6.0        0.0          0.0         0.0            0.0              0.0             0.0    4877.0   7437.0   137.0        5020.0      7353.0       141.0        -143.0        84.0        -4.0        0.0          0.0         0.0            0.0              0.0             0.0    6895.0  10461.0   188.0        7035.0      9939.0       190.0        -140.0       522.0        -2.0        0.0          0.0         0.0            0.0              0.0             0.0    8362.0  12543.0   224.0        9051.0     12275.0       237.0        -689.0       268.0       -13.0        0.0          0.0         0.0            1.0              0.0             0.0

In [ ]:
print(df_games[df_games["date"] == "2025-01-18 17:09:08"].to_string())

                gameid league  year   split  playoffs                 date  game  patch datacompleteness_p1 datacompleteness_p2 datacompleteness_p3 datacompleteness_p4 datacompleteness_p5 datacompleteness_p6 datacompleteness_p7 datacompleteness_p8 datacompleteness_p9 datacompleteness_p10 url_p1 url_p2 url_p3 url_p4 url_p5 url_p6 url_p7 url_p8 url_p9 url_p10 side_p1 side_p2 side_p3 side_p4 side_p5 side_p6 side_p7 side_p8 side_p9 side_p10 position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10                                playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10    teamname_p1    teamname_p2    teamname_p3    teamname_p4    teamname_p5 teamname_p6 teamname_p7 teamname_p8 teamname_p9 teamname_p10                                teamid_p1                                teamid_p2                                teamid_p3                                teamid_p4                                teamid_p5                                teamid_p6                                teamid_p7                                teamid_p8                                teamid_p9                               teamid_p10 champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8 champion_p9 champion_p10  ban1_p1  ban1_p2  ban1_p3  ban1_p4  ban1_p5  ban1_p6  ban1_p7  ban1_p8  ban1_p9 ban1_p10 ban2_p1 ban2_p2 ban2_p3 ban2_p4 ban2_p5 ban2_p6 ban2_p7 ban2_p8 ban2_p9 ban2_p10 ban3_p1 ban3_p2 ban3_p3 ban3_p4 ban3_p5 ban3_p6 ban3_p7 ban3_p8 ban3_p9 ban3_p10       ban4_p1       ban4_p2       ban4_p3       ban4_p4       ban4_p5 ban4_p6 ban4_p7 ban4_p8 ban4_p9 ban4_p10 ban5_p1 ban5_p2 ban5_p3 ban5_p4 ban5_p5 ban5_p6 ban5_p7 ban5_p8 ban5_p9 ban5_p10 pick1_p1 pick1_p2 pick1_p3 pick1_p4 pick1_p5 pick1_p6 pick1_p7 pick1_p8 pick1_p9 pick1_p10 pick2_p1 pick2_p2 pick2_p3 pick2_p4 pick2_p5 pick2_p6 pick2_p7 pick2_p8 pick2_p9 pick2_p10 pick3_p1 pick3_p2 pick3_p3 pick3_p4 pick3_p5 pick3_p6 pick3_p7 pick3_p8 pick3_p9 pick3_p10 pick4_p1 pick4_p2 pick4_p3 pick4_p4 pick4_p5 pick4_p6 pick4_p7 pick4_p8 pick4_p9 pick4_p10 pick5_p1 pick5_p2 pick5_p3 pick5_p4 pick5_p5 pick5_p6 pick5_p7 pick5_p8 pick5_p9 pick5_p10  gamelength_p1  gamelength_p2  gamelength_p3  gamelength_p4  gamelength_p5  gamelength_p6  gamelength_p7  gamelength_p8  gamelength_p9  gamelength_p10  result_p1  result_p2  result_p3  result_p4  result_p5  result_p6  result_p7  result_p8  result_p9  result_p10  kills_p1  kills_p2  kills_p3  kills_p4  kills_p5  kills_p6  kills_p7  kills_p8  kills_p9  kills_p10  deaths_p1  deaths_p2  deaths_p3  deaths_p4  deaths_p5  deaths_p6  deaths_p7  deaths_p8  deaths_p9  deaths_p10  assists_p1  assists_p2  assists_p3  assists_p4  assists_p5  assists_p6  assists_p7  assists_p8  assists_p9  assists_p10  teamkills_p1  teamkills_p2  teamkills_p3  teamkills_p4  teamkills_p5  teamkills_p6  teamkills_p7  teamkills_p8  teamkills_p9  teamkills_p10  teamdeaths_p1  teamdeaths_p2  teamdeaths_p3  teamdeaths_p4  teamdeaths_p5  teamdeaths_p6  teamdeaths_p7  teamdeaths_p8  teamdeaths_p9  teamdeaths_p10  doublekills_p1  doublekills_p2  doublekills_p3  doublekills_p4  doublekills_p5  doublekills_p6  doublekills_p7  doublekills_p8  doublekills_p9  doublekills_p10  triplekills_p1  triplekills_p2  triplekills_p3  triplekills_p4  triplekills_p5  triplekills_p6  triplekills_p7  triplekills_p8  triplekills_p9  triplekills_p10  quadrakills_p1  quadrakills_p2  quadrakills_p3  quadrakills_p4  quadrakills_p5  quadrakills_p6  quadrakills_p7  quadrakills_p8  quadrakills_p9  quadrakills_p10  pentakills_p1  pentakills_p2  pentakills_p3  pentakills_p4  pentakills_p5  pentakills_p6  pentakills_p7  pentakills_p8  pentakills_p9  pentakills_p10  firstblood_p1  firstblood_p2  firstblood_p3  firstblood_p4  firstblood_p5  firstblood_p6  firstblood_p7  firstblood_p8  firstblood_p9  firstblood_p10  firstbloodkill_p1  firstbloodkill_p2  firstbloodkill_p3  firstbloodkill_p4  firstbloodkill_p5  firstbloodkill_p6  firstbloodkill_p7  firstbloodkill_p8  firstbloodkill_p9  firstbloodkill_p10  firstbloodassist_p1  firstbloodassist_p2  firstbloodassist_p3  firstbloodassist_p4  firstbloodassist_p5  firstbloodassist_p6  firstbloodassist_p7  firstbloodassist_p8  firstbloodassist_p9  firstbloodassist_p10  firstbloodvictim_p1  firstbloodvictim_p2  firstbloodvictim_p3  firstbloodvictim_p4  firstbloodvictim_p5  firstbloodvictim_p6  firstbloodvictim_p7  firstbloodvictim_p8  firstbloodvictim_p9  firstbloodvictim_p10  team kpm_p1  team kpm_p2  team kpm_p3  team kpm_p4  team kpm_p5  team kpm_p6  team kpm_p7  team kpm_p8  team kpm_p9  team kpm_p10  ckpm_p1  ckpm_p2  ckpm_p3  ckpm_p4  ckpm_p5  ckpm_p6  ckpm_p7  ckpm_p8  ckpm_p9  ckpm_p10  firstdragon_p1  firstdragon_p2  firstdragon_p3  firstdragon_p4  firstdragon_p5  firstdragon_p6  firstdragon_p7  firstdragon_p8  firstdragon_p9  firstdragon_p10  dragons_p1  dragons_p2  dragons_p3  dragons_p4  dragons_p5  dragons_p6  dragons_p7  dragons_p8  dragons_p9  dragons_p10  opp_dragons_p1  opp_dragons_p2  opp_dragons_p3  opp_dragons_p4  opp_dragons_p5  opp_dragons_p6  opp_dragons_p7  opp_dragons_p8  opp_dragons_p9  opp_dragons_p10  elementaldrakes_p1  elementaldrakes_p2  elementaldrakes_p3  elementaldrakes_p4  elementaldrakes_p5  elementaldrakes_p6  elementaldrakes_p7  elementaldrakes_p8  elementaldrakes_p9  elementaldrakes_p10  opp_elementaldrakes_p1  opp_elementaldrakes_p2  opp_elementaldrakes_p3  opp_elementaldrakes_p4  opp_elementaldrakes_p5  opp_elementaldrakes_p6  opp_elementaldrakes_p7  opp_elementaldrakes_p8  opp_elementaldrakes_p9  opp_elementaldrakes_p10  infernals_p1  infernals_p2  infernals_p3  infernals_p4  infernals_p5  infernals_p6  infernals_p7  infernals_p8  infernals_p9  infernals_p10  mountains_p1  mountains_p2  mountains_p3  mountains_p4  mountains_p5  mountains_p6  mountains_p7  mountains_p8  mountains_p9  mountains_p10  clouds_p1  clouds_p2  clouds_p3  clouds_p4  clouds_p5  clouds_p6  clouds_p7  clouds_p8  clouds_p9  clouds_p10  oceans_p1  oceans_p2  oceans_p3  oceans_p4  oceans_p5  oceans_p6  oceans_p7  oceans_p8  oceans_p9  oceans_p10  chemtechs_p1  chemtechs_p2  chemtechs_p3  chemtechs_p4  chemtechs_p5  chemtechs_p6  chemtechs_p7  chemtechs_p8  chemtechs_p9  chemtechs_p10  hextechs_p1  hextechs_p2  hextechs_p3  hextechs_p4  hextechs_p5  hextechs_p6  hextechs_p7  hextechs_p8  hextechs_p9  hextechs_p10  dragons (type unknown)_p1  dragons (type unknown)_p2  dragons (type unknown)_p3  dragons (type unknown)_p4  dragons (type unknown)_p5  dragons (type unknown)_p6  dragons (type unknown)_p7  dragons (type unknown)_p8  dragons (type unknown)_p9  dragons (type unknown)_p10  elders_p1  elders_p2  elders_p3  elders_p4  elders_p5  elders_p6  elders_p7  elders_p8  elders_p9  elders_p10  opp_elders_p1  opp_elders_p2  opp_elders_p3  opp_elders_p4  opp_elders_p5  opp_elders_p6  opp_elders_p7  opp_elders_p8  opp_elders_p9  opp_elders_p10  firstherald_p1  firstherald_p2  firstherald_p3  firstherald_p4  firstherald_p5  firstherald_p6  firstherald_p7  firstherald_p8  firstherald_p9  firstherald_p10  heralds_p1  heralds_p2  heralds_p3  heralds_p4  heralds_p5  heralds_p6  heralds_p7  heralds_p8  heralds_p9  heralds_p10  opp_heralds_p1  opp_heralds_p2  opp_heralds_p3  opp_heralds_p4  opp_heralds_p5  opp_heralds_p6  opp_heralds_p7  opp_heralds_p8  opp_heralds_p9  opp_heralds_p10  void_grubs_p1  void_grubs_p2  void_grubs_p3  void_grubs_p4  void_grubs_p5  void_grubs_p6  void_grubs_p7  void_grubs_p8  void_grubs_p9  void_grubs_p10  opp_void_grubs_p1  opp_void_grubs_p2  opp_void_grubs_p3  opp_void_grubs_p4  opp_void_grubs_p5  opp_void_grubs_p6  opp_void_grubs_p7  opp_void_grubs_p8  opp_void_grubs_p9  opp_void_grubs_p10  firstbaron_p1  firstbaron_p2  firstbaron_p3  firstbaron_p4  firstbaron_p5  firstbaron_p6  firstbaron_p7  firstbaron_p8  firstbaron_p9  firstbaron_p10  barons_p1  barons_p2  barons_p3  barons_p4  barons_p5  barons_p6  barons_p7  barons_p8  barons_p9  barons_p10  opp_barons_p1  opp_barons_p2  opp_barons_p3  opp_barons_p4  opp_barons_p5  opp_barons_p6  opp_barons_p7  opp_barons_p8  opp_barons_p9  opp_barons_p10  atakhans_p1  atakhans_p2  atakhans_p3  atakhans_p4  atakhans_p5  atakhans_p6  atakhans_p7  atakhans_p8  atakhans_p9  atakhans_p10  opp_atakhans_p1  opp_atakhans_p2  opp_atakhans_p3  opp_atakhans_p4  opp_atakhans_p5  opp_atakhans_p6  opp_atakhans_p7  opp_atakhans_p8  opp_atakhans_p9  opp_atakhans_p10  firsttower_p1  firsttower_p2  firsttower_p3  firsttower_p4  firsttower_p5  firsttower_p6  firsttower_p7  firsttower_p8  firsttower_p9  firsttower_p10  towers_p1  towers_p2  towers_p3  towers_p4  towers_p5  towers_p6  towers_p7  towers_p8  towers_p9  towers_p10  opp_towers_p1  opp_towers_p2  opp_towers_p3  opp_towers_p4  opp_towers_p5  opp_towers_p6  opp_towers_p7  opp_towers_p8  opp_towers_p9  opp_towers_p10  firstmidtower_p1  firstmidtower_p2  firstmidtower_p3  firstmidtower_p4  firstmidtower_p5  firstmidtower_p6  firstmidtower_p7  firstmidtower_p8  firstmidtower_p9  firstmidtower_p10  firsttothreetowers_p1  firsttothreetowers_p2  firsttothreetowers_p3  firsttothreetowers_p4  firsttothreetowers_p5  firsttothreetowers_p6  firsttothreetowers_p7  firsttothreetowers_p8  firsttothreetowers_p9  firsttothreetowers_p10  turretplates_p1  turretplates_p2  turretplates_p3  turretplates_p4  turretplates_p5  turretplates_p6  turretplates_p7  turretplates_p8  turretplates_p9  turretplates_p10  opp_turretplates_p1  opp_turretplates_p2  opp_turretplates_p3  opp_turretplates_p4  opp_turretplates_p5  opp_turretplates_p6  opp_turretplates_p7  opp_turretplates_p8  opp_turretplates_p9  opp_turretplates_p10  inhibitors_p1  inhibitors_p2  inhibitors_p3  inhibitors_p4  inhibitors_p5  inhibitors_p6  inhibitors_p7  inhibitors_p8  inhibitors_p9  inhibitors_p10  opp_inhibitors_p1  opp_inhibitors_p2  opp_inhibitors_p3  opp_inhibitors_p4  opp_inhibitors_p5  opp_inhibitors_p6  opp_inhibitors_p7  opp_inhibitors_p8  opp_inhibitors_p9  opp_inhibitors_p10  damagetochampions_p1  damagetochampions_p2  damagetochampions_p3  damagetochampions_p4  damagetochampions_p5  damagetochampions_p6  damagetochampions_p7  damagetochampions_p8  damagetochampions_p9  damagetochampions_p10    dpm_p1    dpm_p2   dpm_p3    dpm_p4   dpm_p5    dpm_p6    dpm_p7    dpm_p8    dpm_p9   dpm_p10  damageshare_p1  damageshare_p2  damageshare_p3  damageshare_p4  damageshare_p5  damageshare_p6  damageshare_p7  damageshare_p8  damageshare_p9  damageshare_p10  damagetakenperminute_p1  damagetakenperminute_p2  damagetakenperminute_p3  damagetakenperminute_p4  damagetakenperminute_p5  damagetakenperminute_p6  damagetakenperminute_p7  damagetakenperminute_p8  damagetakenperminute_p9  damagetakenperminute_p10  damagemitigatedperminute_p1  damagemitigatedperminute_p2  damagemitigatedperminute_p3  damagemitigatedperminute_p4  damagemitigatedperminute_p5  damagemitigatedperminute_p6  damagemitigatedperminute_p7  damagemitigatedperminute_p8  damagemitigatedperminute_p9  damagemitigatedperminute_p10  damagetotowers_p1  damagetotowers_p2  damagetotowers_p3  damagetotowers_p4  damagetotowers_p5  damagetotowers_p6  damagetotowers_p7  damagetotowers_p8  damagetotowers_p9  damagetotowers_p10  wardsplaced_p1  wardsplaced_p2  wardsplaced_p3  wardsplaced_p4  wardsplaced_p5  wardsplaced_p6  wardsplaced_p7  wardsplaced_p8  wardsplaced_p9  wardsplaced_p10  wpm_p1  wpm_p2  wpm_p3  wpm_p4  wpm_p5  wpm_p6  wpm_p7  wpm_p8  wpm_p9  wpm_p10  wardskilled_p1  wardskilled_p2  wardskilled_p3  wardskilled_p4  wardskilled_p5  wardskilled_p6  wardskilled_p7  wardskilled_p8  wardskilled_p9  wardskilled_p10  wcpm_p1  wcpm_p2  wcpm_p3  wcpm_p4  wcpm_p5  wcpm_p6  wcpm_p7  wcpm_p8  wcpm_p9  wcpm_p10  controlwardsbought_p1  controlwardsbought_p2  controlwardsbought_p3  controlwardsbought_p4  controlwardsbought_p5  controlwardsbought_p6  controlwardsbought_p7  controlwardsbought_p8  controlwardsbought_p9  controlwardsbought_p10  visionscore_p1  visionscore_p2  visionscore_p3  visionscore_p4  visionscore_p5  visionscore_p6  visionscore_p7  visionscore_p8  visionscore_p9  visionscore_p10  vspm_p1  vspm_p2  vspm_p3  vspm_p4  vspm_p5  vspm_p6  vspm_p7  vspm_p8  vspm_p9  vspm_p10  totalgold_p1  totalgold_p2  totalgold_p3  totalgold_p4  totalgold_p5  totalgold_p6  totalgold_p7  totalgold_p8  totalgold_p9  totalgold_p10  earnedgold_p1  earnedgold_p2  earnedgold_p3  earnedgold_p4  earnedgold_p5  earnedgold_p6  earnedgold_p7  earnedgold_p8  earnedgold_p9  earnedgold_p10  earned gpm_p1  earned gpm_p2  earned gpm_p3  earned gpm_p4  earned gpm_p5  earned gpm_p6  earned gpm_p7  earned gpm_p8  earned gpm_p9  earned gpm_p10  earnedgoldshare_p1  earnedgoldshare_p2  earnedgoldshare_p3  earnedgoldshare_p4  earnedgoldshare_p5  earnedgoldshare_p6  earnedgoldshare_p7  earnedgoldshare_p8  earnedgoldshare_p9  earnedgoldshare_p10  goldspent_p1  goldspent_p2  goldspent_p3  goldspent_p4  goldspent_p5  goldspent_p6  goldspent_p7  goldspent_p8  goldspent_p9  goldspent_p10  gspd_p1  gspd_p2  gspd_p3  gspd_p4  gspd_p5  gspd_p6  gspd_p7  gspd_p8  gspd_p9  gspd_p10  gpr_p1  gpr_p2  gpr_p3  gpr_p4  gpr_p5  gpr_p6  gpr_p7  gpr_p8  gpr_p9  gpr_p10  total cs_p1  total cs_p2  total cs_p3  total cs_p4  total cs_p5  total cs_p6  total cs_p7  total cs_p8  total cs_p9  total cs_p10  minionkills_p1  minionkills_p2  minionkills_p3  minionkills_p4  minionkills_p5  minionkills_p6  minionkills_p7  minionkills_p8  minionkills_p9  minionkills_p10  monsterkills_p1  monsterkills_p2  monsterkills_p3  monsterkills_p4  monsterkills_p5  monsterkills_p6  monsterkills_p7  monsterkills_p8  monsterkills_p9  monsterkills_p10  monsterkillsownjungle_p1  monsterkillsownjungle_p2  monsterkillsownjungle_p3  monsterkillsownjungle_p4  monsterkillsownjungle_p5  monsterkillsownjungle_p6  monsterkillsownjungle_p7  monsterkillsownjungle_p8  monsterkillsownjungle_p9  monsterkillsownjungle_p10  monsterkillsenemyjungle_p1  monsterkillsenemyjungle_p2  monsterkillsenemyjungle_p3  monsterkillsenemyjungle_p4  monsterkillsenemyjungle_p5  monsterkillsenemyjungle_p6  monsterkillsenemyjungle_p7  monsterkillsenemyjungle_p8  monsterkillsenemyjungle_p9  monsterkillsenemyjungle_p10  cspm_p1  cspm_p2  cspm_p3  cspm_p4  cspm_p5  cspm_p6  cspm_p7  cspm_p8  cspm_p9  cspm_p10  goldat10_p1  goldat10_p2  goldat10_p3  goldat10_p4  goldat10_p5  goldat10_p6  goldat10_p7  goldat10_p8  goldat10_p9  goldat10_p10  xpat10_p1  xpat10_p2  xpat10_p3  xpat10_p4  xpat10_p5  xpat10_p6  xpat10_p7  xpat10_p8  xpat10_p9  xpat10_p10  csat10_p1  csat10_p2  csat10_p3  csat10_p4  csat10_p5  csat10_p6  csat10_p7  csat10_p8  csat10_p9  csat10_p10  opp_goldat10_p1  opp_goldat10_p2  opp_goldat10_p3  opp_goldat10_p4  opp_goldat10_p5  opp_goldat10_p6  opp_goldat10_p7  opp_goldat10_p8  opp_goldat10_p9  opp_goldat10_p10  opp_xpat10_p1  opp_xpat10_p2  opp_xpat10_p3  opp_xpat10_p4  opp_xpat10_p5  opp_xpat10_p6  opp_xpat10_p7  opp_xpat10_p8  opp_xpat10_p9  opp_xpat10_p10  opp_csat10_p1  opp_csat10_p2  opp_csat10_p3  opp_csat10_p4  opp_csat10_p5  opp_csat10_p6  opp_csat10_p7  opp_csat10_p8  opp_csat10_p9  opp_csat10_p10  golddiffat10_p1  golddiffat10_p2  golddiffat10_p3  golddiffat10_p4  golddiffat10_p5  golddiffat10_p6  golddiffat10_p7  golddiffat10_p8  golddiffat10_p9  golddiffat10_p10  xpdiffat10_p1  xpdiffat10_p2  xpdiffat10_p3  xpdiffat10_p4  xpdiffat10_p5  xpdiffat10_p6  xpdiffat10_p7  xpdiffat10_p8  xpdiffat10_p9  xpdiffat10_p10  csdiffat10_p1  csdiffat10_p2  csdiffat10_p3  csdiffat10_p4  csdiffat10_p5  csdiffat10_p6  csdiffat10_p7  csdiffat10_p8  csdiffat10_p9  csdiffat10_p10  killsat10_p1  killsat10_p2  killsat10_p3  killsat10_p4  killsat10_p5  killsat10_p6  killsat10_p7  killsat10_p8  killsat10_p9  killsat10_p10  assistsat10_p1  assistsat10_p2  assistsat10_p3  assistsat10_p4  assistsat10_p5  assistsat10_p6  assistsat10_p7  assistsat10_p8  assistsat10_p9  assistsat10_p10  deathsat10_p1  deathsat10_p2  deathsat10_p3  deathsat10_p4  deathsat10_p5  deathsat10_p6  deathsat10_p7  deathsat10_p8  deathsat10_p9  deathsat10_p10  opp_killsat10_p1  opp_killsat10_p2  opp_killsat10_p3  opp_killsat10_p4  opp_killsat10_p5  opp_killsat10_p6  opp_killsat10_p7  opp_killsat10_p8  opp_killsat10_p9  opp_killsat10_p10  opp_assistsat10_p1  opp_assistsat10_p2  opp_assistsat10_p3  opp_assistsat10_p4  opp_assistsat10_p5  opp_assistsat10_p6  opp_assistsat10_p7  opp_assistsat10_p8  opp_assistsat10_p9  opp_assistsat10_p10  opp_deathsat10_p1  opp_deathsat10_p2  opp_deathsat10_p3  opp_deathsat10_p4  opp_deathsat10_p5  opp_deathsat10_p6  opp_deathsat10_p7  opp_deathsat10_p8  opp_deathsat10_p9  opp_deathsat10_p10  goldat15_p1  goldat15_p2  goldat15_p3  goldat15_p4  goldat15_p5  goldat15_p6  goldat15_p7  goldat15_p8  goldat15_p9  goldat15_p10  xpat15_p1  xpat15_p2  xpat15_p3  xpat15_p4  xpat15_p5  xpat15_p6  xpat15_p7  xpat15_p8  xpat15_p9  xpat15_p10  csat15_p1  csat15_p2  csat15_p3  csat15_p4  csat15_p5  csat15_p6  csat15_p7  csat15_p8  csat15_p9  csat15_p10  opp_goldat15_p1  opp_goldat15_p2  opp_goldat15_p3  opp_goldat15_p4  opp_goldat15_p5  opp_goldat15_p6  opp_goldat15_p7  opp_goldat15_p8  opp_goldat15_p9  opp_goldat15_p10  opp_xpat15_p1  opp_xpat15_p2  opp_xpat15_p3  opp_xpat15_p4  opp_xpat15_p5  opp_xpat15_p6  opp_xpat15_p7  opp_xpat15_p8  opp_xpat15_p9  opp_xpat15_p10  opp_csat15_p1  opp_csat15_p2  opp_csat15_p3  opp_csat15_p4  opp_csat15_p5  opp_csat15_p6  opp_csat15_p7  opp_csat15_p8  opp_csat15_p9  opp_csat15_p10  golddiffat15_p1  golddiffat15_p2  golddiffat15_p3  golddiffat15_p4  golddiffat15_p5  golddiffat15_p6  golddiffat15_p7  golddiffat15_p8  golddiffat15_p9  golddiffat15_p10  xpdiffat15_p1  xpdiffat15_p2  xpdiffat15_p3  xpdiffat15_p4  xpdiffat15_p5  xpdiffat15_p6  xpdiffat15_p7  xpdiffat15_p8  xpdiffat15_p9  xpdiffat15_p10  csdiffat15_p1  csdiffat15_p2  csdiffat15_p3  csdiffat15_p4  csdiffat15_p5  csdiffat15_p6  csdiffat15_p7  csdiffat15_p8  csdiffat15_p9  csdiffat15_p10  killsat15_p1  killsat15_p2  killsat15_p3  killsat15_p4  killsat15_p5  killsat15_p6  killsat15_p7  killsat15_p8  killsat15_p9  killsat15_p10  assistsat15_p1  assistsat15_p2  assistsat15_p3  assistsat15_p4  assistsat15_p5  assistsat15_p6  assistsat15_p7  assistsat15_p8  assistsat15_p9  assistsat15_p10  deathsat15_p1  deathsat15_p2  deathsat15_p3  deathsat15_p4  deathsat15_p5  deathsat15_p6  deathsat15_p7  deathsat15_p8  deathsat15_p9  deathsat15_p10  opp_killsat15_p1  opp_killsat15_p2  opp_killsat15_p3  opp_killsat15_p4  opp_killsat15_p5  opp_killsat15_p6  opp_killsat15_p7  opp_killsat15_p8  opp_killsat15_p9  opp_killsat15_p10  opp_assistsat15_p1  opp_assistsat15_p2  opp_assistsat15_p3  opp_assistsat15_p4  opp_assistsat15_p5  opp_assistsat15_p6  opp_assistsat15_p7  opp_assistsat15_p8  opp_assistsat15_p9  opp_assistsat15_p10  opp_deathsat15_p1  opp_deathsat15_p2  opp_deathsat15_p3  opp_deathsat15_p4  opp_deathsat15_p5  opp_deathsat15_p6  opp_deathsat15_p7  opp_deathsat15_p8  opp_deathsat15_p9  opp_deathsat15_p10  goldat20_p1  goldat20_p2  goldat20_p3  goldat20_p4  goldat20_p5  goldat20_p6  goldat20_p7  goldat20_p8  goldat20_p9  goldat20_p10  xpat20_p1  xpat20_p2  xpat20_p3  xpat20_p4  xpat20_p5  xpat20_p6  xpat20_p7  xpat20_p8  xpat20_p9  xpat20_p10  csat20_p1  csat20_p2  csat20_p3  csat20_p4  csat20_p5  csat20_p6  csat20_p7  csat20_p8  csat20_p9  csat20_p10  opp_goldat20_p1  opp_goldat20_p2  opp_goldat20_p3  opp_goldat20_p4  opp_goldat20_p5  opp_goldat20_p6  opp_goldat20_p7  opp_goldat20_p8  opp_goldat20_p9  opp_goldat20_p10  opp_xpat20_p1  opp_xpat20_p2  opp_xpat20_p3  opp_xpat20_p4  opp_xpat20_p5  opp_xpat20_p6  opp_xpat20_p7  opp_xpat20_p8  opp_xpat20_p9

In [ ]:
COLS_TO_DELETE = [
    "datacompleteness_p1", "datacompleteness_p2", "datacompleteness_p3",
    "datacompleteness_p4", "datacompleteness_p5", "datacompleteness_p6",
    "datacompleteness_p7", "datacompleteness_p8", "datacompleteness_p9",
    "datacompleteness_p10", "url_p1", "url_p2", "url_p3", "url_p4",
    "url_p5", "url_p6", "url_p7", "url_p8", "url_p9", "url_p10",
    "side_p2", "side_p3", "side_p4", "side_p5", "side_p7", "side_p8", "side_p9", "side_p10", #on garde side p1 et p6. Il faut vérifier que p1 à 5 sont toujours dans la meme équipe et que p6 à 10 sont toujours dans la meme équipe
    #vérifier que les positions sont toujours dans l'ordre aussi comme ca on peut toutes les delete, ce n'est pas le cas
    "teamname_p1", "teamname_p2", "teamname_p3", "teamname_p4",
    "teamname_p6", "teamname_p7", "teamname_p8", "teamname_p9",
    "teamid_p1", "teamid_p2", "teamid_p3", "teamid_p4",
    "teamid_p6", "teamid_p7", "teamid_p8", "teamid_p9",
    "ban1_p1", "ban1_p2", "ban1_p3", "ban1_p4", 
    "ban1_p6", "ban1_p7", "ban1_p8", "ban1_p9",
    "ban2_p1", "ban2_p2", "ban2_p3", "ban2_p4", 
    "ban2_p6", "ban2_p7", "ban2_p8", "ban2_p9",
    "ban3_p1", "ban3_p2", "ban3_p3", "ban3_p4", 
    "ban3_p6", "ban3_p7", "ban3_p8", "ban3_p9",
    "ban4_p1", "ban4_p2", "ban4_p3", "ban4_p4", 
    "ban4_p6", "ban4_p7", "ban4_p8", "ban4_p9",
    "ban5_p1", "ban5_p2", "ban5_p3", "ban5_p4", 
    "ban5_p6", "ban5_p7", "ban5_p8", "ban5_p9",
    # ---------------- on enleve tous les pickx qui correspondent aux lignes de champions mais il faut ajouter les pickx de team
    "pick1_p1", "pick1_p2", "pick1_p3", "pick1_p4", "pick1_p5",
    "pick1_p6", "pick1_p7", "pick1_p8", "pick1_p9", "pick1_p10",
    "pick2_p1", "pick2_p2", "pick2_p3", "pick2_p4", "pick2_p5",
    "pick2_p6", "pick2_p7", "pick2_p8", "pick2_p9", "pick2_p10",
    "pick3_p1", "pick3_p2", "pick3_p3", "pick3_p4", "pick3_p5",
    "pick3_p6", "pick3_p7", "pick3_p8", "pick3_p9", "pick3_p10",
    "pick4_p1", "pick4_p2", "pick4_p3", "pick4_p4", "pick4_p5",
    "pick4_p6", "pick4_p7", "pick4_p8", "pick4_p9", "pick4_p10",
    "pick5_p1", "pick5_p2", "pick5_p3", "pick5_p4", "pick5_p5",
    "pick5_p6", "pick5_p7", "pick5_p8", "pick5_p9", "pick5_p10",
    "game_length_p1", "game_length_p2", "game_length_p3", "game_length_p4",
    "game_length_p5", "game_length_p6", "game_length_p7", "game_length_p8",
    "game_length_p9",
    "result_p1", "result_p2", "result_p3", "result_p4", "result_p5",
    "result_p6", "result_p7", "result_p8", "result_p9",
    "teamkills_p1", "teamkills_p2", "teamkills_p3", "teamkills_p4",
    "teamkills_p6", "teamkills_p7", "teamkills_p8", "teamkills_p9",
    "teamdeaths_p1", "teamdeaths_p2", "teamdeaths_p3", "teamdeaths_p4",
    "teamdeaths_p6", "teamdeaths_p7", "teamdeaths_p8", "teamdeaths_p9",
    "team kpm_p1", "team kpm_p2", "team kpm_p3", "team kpm_p4",
    "team kpm_p6", "team kpm_p7", "team kpm_p8", "team kpm_p9",
    "ckpm_p1", "ckpm_p2", "ckpm_p3", "ckpm_p4",
    "ckpm_p6", "ckpm_p7", "ckpm_p8", "ckpm_p9",
    # tout ca on supprime pour les joueurs et on ne garde que par équipe firstdragon  dragons  opp_dragons  elementaldrakes  opp_elementaldrakes  infernals  mountains  clouds  oceans  chemtechs  hextechs  dragons (type unknown)  elders  opp_elders  firstherald  heralds  opp_heralds  void_grubs  opp_void_grubs  firstbaron
    # tout ca pareil : atakhans  opp_atakhans  firsttower  towers  opp_towers  firstmidtower  firsttothreetowers  turretplates  opp_turretplates
    #  on enlève tous les opp_quelquechose
    #ca on ne garde que par joueur et on enleve par equipe : damageshare
    



    

    

]

df_games_light = df_games.copy()
df_games_light.drop(columns=COLS_TO_DELETE, inplace=True)

In [42]:
df_games_very_light = df_games.copy()

In [43]:
print(df_games_very_light.head().to_string())

               gameid league  year    split  playoffs                 date  game  patch datacompleteness_p1 datacompleteness_p2 datacompleteness_p3 datacompleteness_p4 datacompleteness_p5 datacompleteness_p6 datacompleteness_p7 datacompleteness_p8 datacompleteness_p9 datacompleteness_p10                                        url_p1                                        url_p2                                        url_p3                                        url_p4                                        url_p5                                        url_p6                                        url_p7                                        url_p8                                        url_p9                                       url_p10 side_p1 side_p2 side_p3 side_p4 side_p5 side_p6 side_p7 side_p8 side_p9 side_p10 position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10                                playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10         teamname_p1         teamname_p2         teamname_p3         teamname_p4         teamname_p5         teamname_p6         teamname_p7         teamname_p8         teamname_p9        teamname_p10                                teamid_p1                                teamid_p2                                teamid_p3                                teamid_p4                                teamid_p5                                teamid_p6                                teamid_p7                                teamid_p8                                teamid_p9                               teamid_p10 champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8   champion_p9 champion_p10  ban1_p1  ban1_p2  ban1_p3  ban1_p4  ban1_p5  ban1_p6  ban1_p7  ban1_p8  ban1_p9 ban1_p10       ban2_p1       ban2_p2       ban2_p3       ban2_p4       ban2_p5  ban2_p6  ban2_p7  ban2_p8  ban2_p9 ban2_p10   ban3_p1   ban3_p2   ban3_p3   ban3_p4   ban3_p5       ban3_p6       ban3_p7       ban3_p8       ban3_p9      ban3_p10   ban4_p1   ban4_p2   ban4_p3   ban4_p4   ban4_p5       ban4_p6       ban4_p7       ban4_p8       ban4_p9      ban4_p10       ban5_p1       ban5_p2       ban5_p3       ban5_p4       ban5_p5   ban5_p6   ban5_p7   ban5_p8   ban5_p9  ban5_p10 pick1_p1 pick1_p2 pick1_p3 pick1_p4 pick1_p5 pick1_p6 pick1_p7 pick1_p8 pick1_p9 pick1_p10 pick2_p1 pick2_p2 pick2_p3 pick2_p4 pick2_p5 pick2_p6 pick2_p7 pick2_p8 pick2_p9 pick2_p10 pick3_p1 pick3_p2 pick3_p3 pick3_p4 pick3_p5 pick3_p6 pick3_p7 pick3_p8 pick3_p9 pick3_p10 pick4_p1 pick4_p2 pick4_p3 pick4_p4 pick4_p5 pick4_p6 pick4_p7 pick4_p8 pick4_p9 pick4_p10 pick5_p1 pick5_p2 pick5_p3 pick5_p4 pick5_p5 pick5_p6 pick5_p7 pick5_p8 pick5_p9 pick5_p10  gamelength_p1  gamelength_p2  gamelength_p3  gamelength_p4  gamelength_p5  gamelength_p6  gamelength_p7  gamelength_p8  gamelength_p9  gamelength_p10  result_p1  result_p2  result_p3  result_p4  result_p5  result_p6  result_p7  result_p8  result_p9  result_p10  kills_p1  kills_p2  kills_p3  kills_p4  kills_p5  kills_p6  kills_p7  kills_p8  kills_p9  kills_p10  deaths_p1  deaths_p2  deaths_p3  deaths_p4  deaths_p5  deaths_p6  deaths_p7  deaths_p8  deaths_p9  deaths_p10  assists_p1  assists_p2  assists_p3  assists_p4  assists_p5  assists_p6  assists_p7  assists_p8  assists_p9  assists_p10  teamkills_p1  teamkills_p2  teamkills_p3  teamkills_p4  teamkills_p5  teamkills_p6  teamkills_p7  teamkills_p8  teamkills_p9  teamkills_p10  teamdeaths_p1  teamdeaths_p2  teamdeaths_p3  teamdeaths_p4  teamdeaths_p5  teamdeaths_p6  teamdeaths_p7  teamdeaths_p8  teamdeaths_p9  teamdeaths_p10  doublekills_p1  doublekills_p2  doublekills_p3  doublekills_p4  doublekills_p5  doublekills_p6  doublekills_p7  doublekills_p8  doublekills_p9  doublekills_p10  triplekills_p1  triplekills_p2  triplekills_p3  triplekills_p4  triplekills_p5  triplekills_p6  triplekills_p7  triplekills_p8  triplekills_p9  triplekills_p10  quadrakills_p1  quadrakills_p2  quadrakills_p3  quadrakills_p4  quadrakills_p5  quadrakills_p6  quadrakills_p7  quadrakills_p8  quadrakills_p9  quadrakills_p10  pentakills_p1  pentakills_p2  pentakills_p3  pentakills_p4  pentakills_p5  pentakills_p6  pentakills_p7  pentakills_p8  pentakills_p9  pentakills_p10  firstblood_p1  firstblood_p2  firstblood_p3  firstblood_p4  firstblood_p5  firstblood_p6  firstblood_p7  firstblood_p8  firstblood_p9  firstblood_p10  firstbloodkill_p1  firstbloodkill_p2  firstbloodkill_p3  firstbloodkill_p4  firstbloodkill_p5  firstbloodkill_p6  firstbloodkill_p7  firstbloodkill_p8  firstbloodkill_p9  firstbloodkill_p10  firstbloodassist_p1  firstbloodassist_p2  firstbloodassist_p3  firstbloodassist_p4  firstbloodassist_p5  firstbloodassist_p6  firstbloodassist_p7  firstbloodassist_p8  firstbloodassist_p9  firstbloodassist_p10  firstbloodvictim_p1  firstbloodvictim_p2  firstbloodvictim_p3  firstbloodvictim_p4  firstbloodvictim_p5  firstbloodvictim_p6  firstbloodvictim_p7  firstbloodvictim_p8  firstbloodvictim_p9  firstbloodvictim_p10  team kpm_p1  team kpm_p2  team kpm_p3  team kpm_p4  team kpm_p5  team kpm_p6  team kpm_p7  team kpm_p8  team kpm_p9  team kpm_p10  ckpm_p1  ckpm_p2  ckpm_p3  ckpm_p4  ckpm_p5  ckpm_p6  ckpm_p7  ckpm_p8  ckpm_p9  ckpm_p10  firstdragon_p1  firstdragon_p2  firstdragon_p3  firstdragon_p4  firstdragon_p5  firstdragon_p6  firstdragon_p7  firstdragon_p8  firstdragon_p9  firstdragon_p10  dragons_p1  dragons_p2  dragons_p3  dragons_p4  dragons_p5  dragons_p6  dragons_p7  dragons_p8  dragons_p9  dragons_p10  opp_dragons_p1  opp_dragons_p2  opp_dragons_p3  opp_dragons_p4  opp_dragons_p5  opp_dragons_p6  opp_dragons_p7  opp_dragons_p8  opp_dragons_p9  opp_dragons_p10  elementaldrakes_p1  elementaldrakes_p2  elementaldrakes_p3  elementaldrakes_p4  elementaldrakes_p5  elementaldrakes_p6  elementaldrakes_p7  elementaldrakes_p8  elementaldrakes_p9  elementaldrakes_p10  opp_elementaldrakes_p1  opp_elementaldrakes_p2  opp_elementaldrakes_p3  opp_elementaldrakes_p4  opp_elementaldrakes_p5  opp_elementaldrakes_p6  opp_elementaldrakes_p7  opp_elementaldrakes_p8  opp_elementaldrakes_p9  opp_elementaldrakes_p10  infernals_p1  infernals_p2  infernals_p3  infernals_p4  infernals_p5  infernals_p6  infernals_p7  infernals_p8  infernals_p9  infernals_p10  mountains_p1  mountains_p2  mountains_p3  mountains_p4  mountains_p5  mountains_p6  mountains_p7  mountains_p8  mountains_p9  mountains_p10  clouds_p1  clouds_p2  clouds_p3  clouds_p4  clouds_p5  clouds_p6  clouds_p7  clouds_p8  clouds_p9  clouds_p10  oceans_p1  oceans_p2  oceans_p3  oceans_p4  oceans_p5  oceans_p6  oceans_p7  oceans_p8  oceans_p9  oceans_p10  chemtechs_p1  chemtechs_p2  chemtechs_p3  chemtechs_p4  chemtechs_p5  chemtechs_p6  chemtechs_p7  chemtechs_p8  chemtechs_p9  chemtechs_p10  hextechs_p1  hextechs_p2  hextechs_p3  hextechs_p4  hextechs_p5  hextechs_p6  hextechs_p7  hextechs_p8  hextechs_p9  hextechs_p10  dragons (type unknown)_p1  dragons (type unknown)_p2  dragons (type unknown)_p3  dragons (type unknown)_p4  dragons (type unknown)_p5  dragons (type unknown)_p6  dragons (type unknown)_p7  dragons (type unknown)_p8  dragons (type unknown)_p9  dragons (type unknown)_p10  elders_p1  elders_p2  elders_p3  elders_p4  elders_p5  elders_p6  elders_p7  elders_p8  elders_p9  elders_p10  opp_elders_p1  opp_elders_p2  opp_elders_p3  opp_elders_p4  opp_elders_p5  opp_elders_p6  opp_elders_p7  opp_elders_p8  opp_elders_p9  opp_elders_p10  firstherald_p1  firstherald_p2  firstherald_p3  firstherald_p4  firstherald_p5  firstherald_p6  firstherald_p7  firstherald_p8  firstherald_p9  firstherald_p10  heralds_p1  heralds_p2  heralds_p3  heralds_p4  heralds_p5  heralds_p6  heralds_p7  heralds_p8  heralds_p9  heralds_p10  opp_heralds_p1  opp_heralds_p2  opp_heralds_p3  opp_heralds_p4  opp_heralds_p5  opp_heralds_p6  opp_heralds_p7  opp_heralds_p8  opp_heralds_p9  opp_heralds_p10  void_grubs_p1  void_grubs_p2  void_grubs_p3  void_grubs_p4  void_grubs_p5  void_grubs_p6  void_grubs_p7  void_grubs_p8  void_grubs_p9  void_grubs_p10  opp_void_grubs_p1  opp_void_grubs_p2  opp_void_grubs_p3  opp_void_grubs_p4  opp_void_grubs_p5  opp_void_grubs_p6  opp_void_grubs_p7  opp_void_grubs_p8  opp_void_grubs_p9  opp_void_grubs_p10  firstbaron_p1  firstbaron_p2  firstbaron_p3  firstbaron_p4  firstbaron_p5  firstbaron_p6  firstbaron_p7  firstbaron_p8  firstbaron_p9  firstbaron_p10  barons_p1  barons_p2  barons_p3  barons_p4  barons_p5  barons_p6  barons_p7  barons_p8  barons_p9  barons_p10  opp_barons_p1  opp_barons_p2  opp_barons_p3  opp_barons_p4  opp_barons_p5  opp_barons_p6  opp_barons_p7  opp_barons_p8  opp_barons_p9  opp_barons_p10  atakhans_p1  atakhans_p2  atakhans_p3  atakhans_p4  atakhans_p5  atakhans_p6  atakhans_p7  atakhans_p8  atakhans_p9  atakhans_p10  opp_atakhans_p1  opp_atakhans_p2  opp_atakhans_p3  opp_atakhans_p4  opp_atakhans_p5  opp_atakhans_p6  opp_atakhans_p7  opp_atakhans_p8  opp_atakhans_p9  opp_atakhans_p10  firsttower_p1  firsttower_p2  firsttower_p3  firsttower_p4  firsttower_p5  firsttower_p6  firsttower_p7  firsttower_p8  firsttower_p9  firsttower_p10  towers_p1  towers_p2  towers_p3  towers_p4  towers_p5  towers_p6  towers_p7  towers_p8  towers_p9  towers_p10  opp_towers_p1  opp_towers_p2  opp_towers_p3  opp_towers_p4  opp_towers_p5  opp_towers_p6  opp_towers_p7  opp_towers_p8  opp_towers_p9  opp_towers_p10  firstmidtower_p1  firstmidtower_p2  firstmidtower_p3  firstmidtower_p4  firstmidtower_p5  firstmidtower_p6  firstmidtower_p7  firstmidtower_p8  firstmidtower_p9  firstmidtower_p10  firsttothreetowers_p1  firsttothreetowers_p2  firsttothreetowers_p3  firsttothreetowers_p4  firsttothreetowers_p5  firsttothreetowers_p6  firsttothreetowers_p7  firsttothreetowers_p8  firsttothreetowers_p9  firsttothreetowers_p10  turretplates_p1  turretplates_p2  turretplates_p3  turretplates_p4  turretplates_p5  turretplates_p6  turretplates_p7  turretplates_p8  turretplates_p9  turretplates_p10  opp_turretplates_p1  opp_turretplates_p2  opp_turretplates_p3  opp_turretplates_p4  opp_turretplates_p5  opp_turretplates_p6  opp_turretplates_p7  opp_turretplates_p8  opp_turretplates_p9  opp_turretplates_p10  inhibitors_p1  inhibitors_p2  inhibitors_p3  inhibitors_p4  inhibitors_p5  inhibitors_p6  inhibitors_p7  inhibitors_p8  inhibitors_p9  inhibitors_p10  opp_inhibitors_p1  opp_inhibitors_p2  opp_inhibitors_p3  opp_inhibitors_p4  opp_inhibitors_p5  opp_inhibitors_p6  opp_inhibitors_p7  opp_inhibitors_p8  opp_inhibitors_p9  opp_inhibitors_p10  damagetochampions_p1  damagetochampions_p2  damagetochampions_p3  damagetochampions_p4  damagetochampions_p5  damagetochampions_p6  damagetochampions_p7  damagetochampions_p8  damagetochampions_p9  damagetochampions_p10    dpm_p1    dpm_p2     dpm_p3    dpm_p4    dpm_p5    dpm_p6    dpm_p7    dpm_p8     dpm_p9   dpm_p10  damageshare_p1  damageshare_p2  damageshare_p3  damageshare_p4  damageshare_p5  damageshare_p6  damageshare_p7  damageshare_p8  damageshare_p9  damageshare_p10  damagetakenperminute_p1  damagetakenperminute_p2  damagetakenperminute_p3  damagetakenperminute_p4  damagetakenperminute_p5  damagetakenperminute_p6  damagetakenperminute_p7  damagetakenperminute_p8  damagetakenperminute_p9  damagetakenperminute_p10  damagemitigatedperminute_p1  damagemitigatedperminute_p2  damagemitigatedperminute_p3  damagemitigatedperminute_p4  damagemitigatedperminute_p5  damagemitigatedperminute_p6  damagemitigatedperminute_p7  damagemitigatedperminute_p8  damagemitigatedperminute_p9  damagemitigatedperminute_p10  damagetotowers_p1  damagetotowers_p2  damagetotowers_p3  damagetotowers_p4  damagetotowers_p5  damagetotowers_p6  damagetotowers_p7  damagetotowers_p8  damagetotowers_p9  damagetotowers_p10  wardsplaced_p1  wardsplaced_p2  wardsplaced_p3  wardsplaced_p4  wardsplaced_p5  wardsplaced_p6  wardsplaced_p7  wardsplaced_p8  wardsplaced_p9  wardsplaced_p10  wpm_p1  wpm_p2  wpm_p3  wpm_p4  wpm_p5  wpm_p6  wpm_p7  wpm_p8  wpm_p9  wpm_p10  wardskilled_p1  wardskilled_p2  wardskilled_p3  wardskilled_p4  wardskilled_p5  wardskilled_p6  wardskilled_p7  wardskilled_p8  wardskilled_p9  wardskilled_p10  wcpm_p1  wcpm_p2  wcpm_p3  wcpm_p4  wcpm_p5  wcpm_p6  wcpm_p7  wcpm_p8  wcpm_p9  wcpm_p10  controlwardsbought_p1  controlwardsbought_p2  controlwardsbought_p3  controlwardsbought_p4  controlwardsbought_p5  controlwardsbought_p6  controlwardsbought_p7  controlwardsbought_p8  controlwardsbought_p9  controlwardsbought_p10  visionscore_p1  visionscore_p2  visionscore_p3  visionscore_p4  visionscore_p5  visionscore_p6  visionscore_p7  visionscore_p8  visionscore_p9  visionscore_p10  vspm_p1  vspm_p2  vspm_p3  vspm_p4  vspm_p5  vspm_p6  vspm_p7  vspm_p8  vspm_p9  vspm_p10  totalgold_p1  totalgold_p2  totalgold_p3  totalgold_p4  totalgold_p5  totalgold_p6  totalgold_p7  totalgold_p8  totalgold_p9  totalgold_p10  earnedgold_p1  earnedgold_p2  earnedgold_p3  earnedgold_p4  earnedgold_p5  earnedgold_p6  earnedgold_p7  earnedgold_p8  earnedgold_p9  earnedgold_p10  earned gpm_p1  earned gpm_p2  earned gpm_p3  earned gpm_p4  earned gpm_p5  earned gpm_p6  earned gpm_p7  earned gpm_p8  earned gpm_p9  earned gpm_p10  earnedgoldshare_p1  earnedgoldshare_p2  earnedgoldshare_p3  earnedgoldshare_p4  earnedgoldshare_p5  earnedgoldshare_p6  earnedgoldshare_p7  earnedgoldshare_p8  earnedgoldshare_p9  earnedgoldshare_p10  goldspent_p1  goldspent_p2  goldspent_p3  goldspent_p4  goldspent_p5  goldspent_p6  goldspent_p7  goldspent_p8  goldspent_p9  goldspent_p10  gspd_p1  gspd_p2  gspd_p3  gspd_p4  gspd_p5  gspd_p6  gspd_p7  gspd_p8  gspd_p9  gspd_p10  gpr_p1  gpr_p2  gpr_p3  gpr_p4  gpr_p5  gpr_p6  gpr_p7  gpr_p8  gpr_p9  gpr_p10  total cs_p1  total cs_p2  total cs_p3  total cs_p4  total cs_p5  total cs_p6  total cs_p7  total cs_p8  total cs_p9  total cs_p10  minionkills_p1  minionkills_p2  minionkills_p3  minionkills_p4  minionkills_p5  minionkills_p6  minionkills_p7  minionkills_p8  minionkills_p9  minionkills_p10  monsterkills_p1  monsterkills_p2  monsterkills_p3  monsterkills_p4  monsterkills_p5  monsterkills_p6  monsterkills_p7  monsterkills_p8  monsterkills_p9  monsterkills_p10  monsterkillsownjungle_p1  monsterkillsownjungle_p2  monsterkillsownjungle_p3  monsterkillsownjungle_p4  monsterkillsownjungle_p5  monsterkillsownjungle_p6  monsterkillsownjungle_p7  monsterkillsownjungle_p8  monsterkillsownjungle_p9  monsterkillsownjungle_p10  monsterkillsenemyjungle_p1  monsterkillsenemyjungle_p2  monsterkillsenemyjungle_p3  monsterkillsenemyjungle_p4  monsterkillsenemyjungle_p5  monsterkillsenemyjungle_p6  monsterkillsenemyjungle_p7  monsterkillsenemyjungle_p8  monsterkillsenemyjungle_p9  monsterkillsenemyjungle_p10  cspm_p1  cspm_p2  cspm_p3  cspm_p4  cspm_p5  cspm_p6  cspm_p7  cspm_p8  cspm_p9  cspm_p10  goldat10_p1  goldat10_p2  goldat10_p3  goldat10_p4  goldat10_p5  goldat10_p6  goldat10_p7  goldat10_p8  goldat10_p9  goldat10_p10  xpat10_p1  xpat10_p2  xpat10_p3  xpat10_p4  xpat10_p5  xpat10_p6  xpat10_p7  xpat10_p8  xpat10_p9  xpat10_p10  csat10_p1  csat10_p2  csat10_p3  csat10_p4  csat10_p5  csat10_p6  csat10_p7  csat10_p8  csat10_p9  csat10_p10  opp_goldat10_p1  opp_goldat10_p2  opp_goldat10_p3  opp_goldat10_p4  opp_goldat10_p5  opp_goldat10_p6  opp_goldat10_p7  opp_goldat10_p8  opp_goldat10_p9  opp_goldat10_p10  opp_xpat10_p1  opp_xpat10_p2  opp_xpat10_p3  opp_xpat10_p4  opp_xpat10_p5  opp_xpat10_p6  opp_xpat10_p7  opp_xpat10_p8  opp_xpat10_p9  opp_xpat10_p10  opp_csat10_p1  opp_csat10_p2  opp_csat10_p3  opp_csat10_p4  opp_csat10_p5  opp_csat10_p6  opp_csat10_p7  opp_csat10_p8  opp_csat10_p9  opp_csat10_p10  golddiffat10_p1  golddiffat10_p2  golddiffat10_p3  golddiffat10_p4  golddiffat10_p5  golddiffat10_p6  golddiffat10_p7  golddiffat10_p8  golddiffat10_p9  golddiffat10_p10  xpdiffat10_p1  xpdiffat10_p2  xpdiffat10_p3  xpdiffat10_p4  xpdiffat10_p5  xpdiffat10_p6  xpdiffat10_p7  xpdiffat10_p8  xpdiffat10_p9  xpdiffat10_p10  csdiffat10_p1  csdiffat10_p2  csdiffat10_p3  csdiffat10_p4  csdiffat10_p5  csdiffat10_p6  csdiffat10_p7  csdiffat10_p8  csdiffat10_p9  csdiffat10_p10  killsat10_p1  killsat10_p2  killsat10_p3  killsat10_p4  killsat10_p5  killsat10_p6  killsat10_p7  killsat10_p8  killsat10_p9  killsat10_p10  assistsat10_p1  assistsat10_p2  assistsat10_p3  assistsat10_p4  assistsat10_p5  assistsat10_p6  assistsat10_p7  assistsat10_p8  assistsat10_p9  assistsat10_p10  deathsat10_p1  deathsat10_p2  deathsat10_p3  deathsat10_p4  deathsat10_p5  deathsat10_p6  deathsat10_p7  deathsat10_p8  deathsat10_p9  deathsat10_p10  opp_killsat10_p1  opp_killsat10_p2  opp_killsat10_p3  opp_killsat10_p4  opp_killsat10_p5  opp_killsat10_p6  opp_killsat10_p7  opp_killsat10_p8  opp_killsat10_p9  opp_killsat10_p10  opp_assistsat10_p1  opp_assistsat10_p2  opp_assistsat10_p3  opp_assistsat10_p4  opp_assistsat10_p5  opp_assistsat10_p6  opp_assistsat10_p7  opp_assistsat10_p8  opp_assistsat10_p9  opp_assistsat10_p10  opp_deathsat10_p1  opp_deathsat10_p2  opp_deathsat10_p3  opp_deathsat10_p4  opp_deathsat10_p5  opp_deathsat10_p6  opp_deathsat10_p7  opp_deathsat10_p8  opp_deathsat10_p9  opp_deathsat10_p10  goldat15_p1  goldat15_p2  goldat15_p3  goldat15_p4  goldat15_p5  goldat15_p6  goldat15_p7  goldat15_p8  goldat15_p9  goldat15_p10  xpat15_p1  xpat15_p2  xpat15_p3  xpat15_p4  xpat15_p5  xpat15_p6  xpat15_p7  xpat15_p8  xpat15_p9  xpat15_p10  csat15_p1  csat15_p2  csat15_p3  csat15_p4  csat15_p5  csat15_p6  csat15_p7  csat15_p8  csat15_p9  csat15_p10  opp_goldat15_p1  opp_goldat15_p2  opp_goldat15_p3  opp_goldat15_p4  opp_goldat15_p5  opp_goldat15_p6  opp_goldat15_p7  opp_goldat15_p8  opp_goldat15_p9  opp_goldat15_p10  opp_xpat15_p1  opp_xpat15_p2  opp_xpat15_p3  opp_xpat15_p4  opp_xpat15_p5  opp_xpat15_p6  opp_xpat15_p7  opp_xpat15_p8  opp_xpat15_p9  opp_xpat15_p10  opp_csat15_p1  opp_csat15_p2  opp_csat15_p3  opp_csat15_p4  opp_csat15_p5  opp_csat15_p6  opp_csat15_p7  opp_csat15_p8  opp_csat15_p9  opp_csat15_p10  golddiffat15_p1  golddiffat15_p2  golddiffat15_p3  golddiffat15_p4  golddiffat15_p5  golddiffat15_p6  golddiffat15_p7  golddiffat15_p8  golddiffat15_p9  golddiffat15_p10  xpdiffat15_p1  xpdiffat15_p2  xpdiffat15_p3  xpdiffat15_p4  xpdiffat15_p5  xpdiffat15_p6  xpdiffat15_p7  xpdiffat15_p8  xpdiffat15_p9  xpdiffat15_p10  csdiffat15_p1  csdiffat15_p2  csdiffat15_p3  csdiffat15_p4  csdiffat15_p5  csdiffat15_p6  csdiffat15_p7  csdiffat15_p8  csdiffat15_p9  csdiffat15_p10  killsat15_p1  killsat15_p2  killsat15_p3  killsat15_p4  killsat15_p5  killsat15_p6  killsat15_p7  killsat15_p8  killsat15_p9  killsat15_p10  assistsat15_p1  assistsat15_p2  assistsat15_p3  assistsat15_p4  assistsat15_p5  assistsat15_p6  assistsat15_p7  assistsat15_p8  assistsat15_p9  assistsat15_p10  deathsat15_p1  deathsat15_p2  deathsat15_p3  deathsat15_p4  deathsat15_p5  deathsat15_p6  deathsat15_p7  deathsat15_p8  deathsat15_p9  deathsat15_p10  opp_killsat15_p1  opp_killsat15_p2  opp_killsat15_p3  opp_killsat15_p4  opp_killsat15_p5  opp_killsat15_p6  opp_killsat15_p7  opp_killsat15_p8  opp_killsat15_p9  opp_killsat15_p10  opp_assistsat15_p1  opp_assistsat15_p2  opp_assistsat15_p3  opp_assistsat15_p4  opp_assistsat15_p5  opp_assistsat15_p6  opp_assistsat15_p7  opp_assistsat15_p8  opp_assistsat15_p9  opp_assistsat15_p10  opp_deathsat15_p1  opp_deathsat15_p2  opp_deathsat15_p3  opp_deathsat15_p4  opp_deathsat15_p5  opp_deathsat15_p6  opp_deathsat15_p7  opp_deathsat15_p8  opp_deathsat15_p9  opp_deathsat15_p10  goldat20_p1  goldat20_p2  goldat20_p3  goldat20_p4  goldat20_p5  goldat20_p6 

In [45]:
COLS_TO_DELETE = [
    "datacompleteness_p1", "datacompleteness_p2", "datacompleteness_p3",
    "datacompleteness_p4", "datacompleteness_p5", "datacompleteness_p6",
    "datacompleteness_p7", "datacompleteness_p8", "datacompleteness_p9",
    "datacompleteness_p10", "url_p1", "url_p2", "url_p3", "url_p4",
    "url_p5", "url_p6", "url_p7", "url_p8", "url_p9", "url_p10",
    "side_p2", "side_p3", "side_p4", "side_p5", "side_p7", "side_p8", "side_p9", "side_p10", #on garde side p1 et p6. Il faut vérifier que p1 à 5 sont toujours dans la meme équipe et que p6 à 10 sont toujours dans la meme équipe
    #vérifier que les positions sont toujours dans l'ordre aussi comme ca on peut toutes les delete, ce n'est pas le cas
    "teamname_p1", "teamname_p2", "teamname_p3", "teamname_p4",
    "teamname_p6", "teamname_p7", "teamname_p8", "teamname_p9",
    "teamid_p1", "teamid_p2", "teamid_p3", "teamid_p4",
    "teamid_p6", "teamid_p7", "teamid_p8", "teamid_p9",
    "ban1_p1", "ban1_p2", "ban1_p3", "ban1_p4", 
    "ban1_p6", "ban1_p7", "ban1_p8", "ban1_p9",
    "ban2_p1", "ban2_p2", "ban2_p3", "ban2_p4", 
    "ban2_p6", "ban2_p7", "ban2_p8", "ban2_p9",
    "ban3_p1", "ban3_p2", "ban3_p3", "ban3_p4", 
    "ban3_p6", "ban3_p7", "ban3_p8", "ban3_p9",
    "ban4_p1", "ban4_p2", "ban4_p3", "ban4_p4", 
    "ban4_p6", "ban4_p7", "ban4_p8", "ban4_p9",
    "ban5_p1", "ban5_p2", "ban5_p3", "ban5_p4", 
    "ban5_p6", "ban5_p7", "ban5_p8", "ban5_p9",
    # ---------------- on enleve tous les pickx qui correspondent aux lignes de champions mais il faut ajouter les pickx de team
    "pick1_p1", "pick1_p2", "pick1_p3", "pick1_p4", "pick1_p5",
    "pick1_p6", "pick1_p7", "pick1_p8", "pick1_p9", "pick1_p10",
    "pick2_p1", "pick2_p2", "pick2_p3", "pick2_p4", "pick2_p5",
    "pick2_p6", "pick2_p7", "pick2_p8", "pick2_p9", "pick2_p10",
    "pick3_p1", "pick3_p2", "pick3_p3", "pick3_p4", "pick3_p5",
    "pick3_p6", "pick3_p7", "pick3_p8", "pick3_p9", "pick3_p10",
    "pick4_p1", "pick4_p2", "pick4_p3", "pick4_p4", "pick4_p5",
    "pick4_p6", "pick4_p7", "pick4_p8", "pick4_p9", "pick4_p10",
    "pick5_p1", "pick5_p2", "pick5_p3", "pick5_p4", "pick5_p5",
    "pick5_p6", "pick5_p7", "pick5_p8", "pick5_p9", "pick5_p10",
    "gamelength_p1", "gamelength_p2", "gamelength_p3", "gamelength_p4",
    "gamelength_p5", "gamelength_p6", "gamelength_p7", "gamelength_p8",
    "gamelength_p9",
    "result_p1", "result_p2", "result_p3", "result_p4", "result_p5",
    "result_p6", "result_p7", "result_p8", "result_p9",
    "teamkills_p1", "teamkills_p2", "teamkills_p3", "teamkills_p4",
    "teamkills_p6", "teamkills_p7", "teamkills_p8", "teamkills_p9",
    "teamdeaths_p1", "teamdeaths_p2", "teamdeaths_p3", "teamdeaths_p4",
    "teamdeaths_p6", "teamdeaths_p7", "teamdeaths_p8", "teamdeaths_p9",
    "team kpm_p1", "team kpm_p2", "team kpm_p3", "team kpm_p4",
    "team kpm_p6", "team kpm_p7", "team kpm_p8", "team kpm_p9",
    "ckpm_p1", "ckpm_p2", "ckpm_p3", "ckpm_p4",
    "ckpm_p6", "ckpm_p7", "ckpm_p8", "ckpm_p9",
    # tout ca on supprime pour les joueurs et on ne garde que par équipe firstdragon  dragons  opp_dragons  elementaldrakes  opp_elementaldrakes  infernals  mountains  clouds  oceans  chemtechs  hextechs  dragons (type unknown)  elders  opp_elders  firstherald  heralds  opp_heralds  void_grubs  opp_void_grubs  firstbaron
    # tout ca pareil : atakhans  opp_atakhans  firsttower  towers  opp_towers  firstmidtower  firsttothreetowers  turretplates  opp_turretplates
    #  on enlève tous les opp_quelquechose
    #ca on ne garde que par joueur et on enleve par equipe : damageshare
]

df_games_very_light = df_games.copy()
df_games_very_light.drop(columns=COLS_TO_DELETE, inplace=True)

In [47]:
print(df_games_very_light.head().to_string())

               gameid league  year    split  playoffs                 date  game  patch side_p1 side_p6 position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10                                playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10         teamname_p5        teamname_p10                                teamid_p5                               teamid_p10 champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8   champion_p9 champion_p10  ban1_p5 ban1_p10       ban2_p5 ban2_p10   ban3_p5      ban3_p10   ban4_p5      ban4_p10       ban5_p5  ban5_p10  gamelength_p10  result_p10  kills_p1  kills_p2  kills_p3  kills_p4  kills_p5  kills_p6  kills_p7  kills_p8  kills_p9  kills_p10  deaths_p1  deaths_p2  deaths_p3  deaths_p4  deaths_p5  deaths_p6  deaths_p7  deaths_p8  deaths_p9  deaths_p10  assists_p1  assists_p2  assists_p3  assists_p4  assists_p5  assists_p6  assists_p7  assists_p8  assists_p9  assists_p10  teamkills_p5  teamkills_p10  teamdeaths_p5  teamdeaths_p10  doublekills_p1  doublekills_p2  doublekills_p3  doublekills_p4  doublekills_p5  doublekills_p6  doublekills_p7  doublekills_p8  doublekills_p9  doublekills_p10  triplekills_p1  triplekills_p2  triplekills_p3  triplekills_p4  triplekills_p5  triplekills_p6  triplekills_p7  triplekills_p8  triplekills_p9  triplekills_p10  quadrakills_p1  quadrakills_p2  quadrakills_p3  quadrakills_p4  quadrakills_p5  quadrakills_p6  quadrakills_p7  quadrakills_p8  quadrakills_p9  quadrakills_p10  pentakills_p1  pentakills_p2  pentakills_p3  pentakills_p4  pentakills_p5  pentakills_p6  pentakills_p7  pentakills_p8  pentakills_p9  pentakills_p10  firstblood_p1  firstblood_p2  firstblood_p3  firstblood_p4  firstblood_p5  firstblood_p6  firstblood_p7  firstblood_p8  firstblood_p9  firstblood_p10  firstbloodkill_p1  firstbloodkill_p2  firstbloodkill_p3  firstbloodkill_p4  firstbloodkill_p5  firstbloodkill_p6  firstbloodkill_p7  firstbloodkill_p8  firstbloodkill_p9  firstbloodkill_p10  firstbloodassist_p1  firstbloodassist_p2  firstbloodassist_p3  firstbloodassist_p4  firstbloodassist_p5  firstbloodassist_p6  firstbloodassist_p7  firstbloodassist_p8  firstbloodassist_p9  firstbloodassist_p10  firstbloodvictim_p1  firstbloodvictim_p2  firstbloodvictim_p3  firstbloodvictim_p4  firstbloodvictim_p5  firstbloodvictim_p6  firstbloodvictim_p7  firstbloodvictim_p8  firstbloodvictim_p9  firstbloodvictim_p10  team kpm_p5  team kpm_p10  ckpm_p5  ckpm_p10  firstdragon_p1  firstdragon_p2  firstdragon_p3  firstdragon_p4  firstdragon_p5  firstdragon_p6  firstdragon_p7  firstdragon_p8  firstdragon_p9  firstdragon_p10  dragons_p1  dragons_p2  dragons_p3  dragons_p4  dragons_p5  dragons_p6  dragons_p7  dragons_p8  dragons_p9  dragons_p10  opp_dragons_p1  opp_dragons_p2  opp_dragons_p3  opp_dragons_p4  opp_dragons_p5  opp_dragons_p6  opp_dragons_p7  opp_dragons_p8  opp_dragons_p9  opp_dragons_p10  elementaldrakes_p1  elementaldrakes_p2  elementaldrakes_p3  elementaldrakes_p4  elementaldrakes_p5  elementaldrakes_p6  elementaldrakes_p7  elementaldrakes_p8  elementaldrakes_p9  elementaldrakes_p10  opp_elementaldrakes_p1  opp_elementaldrakes_p2  opp_elementaldrakes_p3  opp_elementaldrakes_p4  opp_elementaldrakes_p5  opp_elementaldrakes_p6  opp_elementaldrakes_p7  opp_elementaldrakes_p8  opp_elementaldrakes_p9  opp_elementaldrakes_p10  infernals_p1  infernals_p2  infernals_p3  infernals_p4  infernals_p5  infernals_p6  infernals_p7  infernals_p8  infernals_p9  infernals_p10  mountains_p1  mountains_p2  mountains_p3  mountains_p4  mountains_p5  mountains_p6  mountains_p7  mountains_p8  mountains_p9  mountains_p10  clouds_p1  clouds_p2  clouds_p3  clouds_p4  clouds_p5  clouds_p6  clouds_p7  clouds_p8  clouds_p9  clouds_p10  oceans_p1  oceans_p2  oceans_p3  oceans_p4  oceans_p5  oceans_p6  oceans_p7  oceans_p8  oceans_p9  oceans_p10  chemtechs_p1  chemtechs_p2  chemtechs_p3  chemtechs_p4  chemtechs_p5  chemtechs_p6  chemtechs_p7  chemtechs_p8  chemtechs_p9  chemtechs_p10  hextechs_p1  hextechs_p2  hextechs_p3  hextechs_p4  hextechs_p5  hextechs_p6  hextechs_p7  hextechs_p8  hextechs_p9  hextechs_p10  dragons (type unknown)_p1  dragons (type unknown)_p2  dragons (type unknown)_p3  dragons (type unknown)_p4  dragons (type unknown)_p5  dragons (type unknown)_p6  dragons (type unknown)_p7  dragons (type unknown)_p8  dragons (type unknown)_p9  dragons (type unknown)_p10  elders_p1  elders_p2  elders_p3  elders_p4  elders_p5  elders_p6  elders_p7  elders_p8  elders_p9  elders_p10  opp_elders_p1  opp_elders_p2  opp_elders_p3  opp_elders_p4  opp_elders_p5  opp_elders_p6  opp_elders_p7  opp_elders_p8  opp_elders_p9  opp_elders_p10  firstherald_p1  firstherald_p2  firstherald_p3  firstherald_p4  firstherald_p5  firstherald_p6  firstherald_p7  firstherald_p8  firstherald_p9  firstherald_p10  heralds_p1  heralds_p2  heralds_p3  heralds_p4  heralds_p5  heralds_p6  heralds_p7  heralds_p8  heralds_p9  heralds_p10  opp_heralds_p1  opp_heralds_p2  opp_heralds_p3  opp_heralds_p4  opp_heralds_p5  opp_heralds_p6  opp_heralds_p7  opp_heralds_p8  opp_heralds_p9  opp_heralds_p10  void_grubs_p1  void_grubs_p2  void_grubs_p3  void_grubs_p4  void_grubs_p5  void_grubs_p6  void_grubs_p7  void_grubs_p8  void_grubs_p9  void_grubs_p10  opp_void_grubs_p1  opp_void_grubs_p2  opp_void_grubs_p3  opp_void_grubs_p4  opp_void_grubs_p5  opp_void_grubs_p6  opp_void_grubs_p7  opp_void_grubs_p8  opp_void_grubs_p9  opp_void_grubs_p10  firstbaron_p1  firstbaron_p2  firstbaron_p3  firstbaron_p4  firstbaron_p5  firstbaron_p6  firstbaron_p7  firstbaron_p8  firstbaron_p9  firstbaron_p10  barons_p1  barons_p2  barons_p3  barons_p4  barons_p5  barons_p6  barons_p7  barons_p8  barons_p9  barons_p10  opp_barons_p1  opp_barons_p2  opp_barons_p3  opp_barons_p4  opp_barons_p5  opp_barons_p6  opp_barons_p7  opp_barons_p8  opp_barons_p9  opp_barons_p10  atakhans_p1  atakhans_p2  atakhans_p3  atakhans_p4  atakhans_p5  atakhans_p6  atakhans_p7  atakhans_p8  atakhans_p9  atakhans_p10  opp_atakhans_p1  opp_atakhans_p2  opp_atakhans_p3  opp_atakhans_p4  opp_atakhans_p5  opp_atakhans_p6  opp_atakhans_p7  opp_atakhans_p8  opp_atakhans_p9  opp_atakhans_p10  firsttower_p1  firsttower_p2  firsttower_p3  firsttower_p4  firsttower_p5  firsttower_p6  firsttower_p7  firsttower_p8  firsttower_p9  firsttower_p10  towers_p1  towers_p2  towers_p3  towers_p4  towers_p5  towers_p6  towers_p7  towers_p8  towers_p9  towers_p10  opp_towers_p1  opp_towers_p2  opp_towers_p3  opp_towers_p4  opp_towers_p5  opp_towers_p6  opp_towers_p7  opp_towers_p8  opp_towers_p9  opp_towers_p10  firstmidtower_p1  firstmidtower_p2  firstmidtower_p3  firstmidtower_p4  firstmidtower_p5  firstmidtower_p6  firstmidtower_p7  firstmidtower_p8  firstmidtower_p9  firstmidtower_p10  firsttothreetowers_p1  firsttothreetowers_p2  firsttothreetowers_p3  firsttothreetowers_p4  firsttothreetowers_p5  firsttothreetowers_p6  firsttothreetowers_p7  firsttothreetowers_p8  firsttothreetowers_p9  firsttothreetowers_p10  turretplates_p1  turretplates_p2  turretplates_p3  turretplates_p4  turretplates_p5  turretplates_p6  turretplates_p7  turretplates_p8  turretplates_p9  turretplates_p10  opp_turretplates_p1  opp_turretplates_p2  opp_turretplates_p3  opp_turretplates_p4  opp_turretplates_p5  opp_turretplates_p6  opp_turretplates_p7  opp_turretplates_p8  opp_turretplates_p9  opp_turretplates_p10  inhibitors_p1  inhibitors_p2  inhibitors_p3  inhibitors_p4  inhibitors_p5  inhibitors_p6  inhibitors_p7  inhibitors_p8  inhibitors_p9  inhibitors_p10  opp_inhibitors_p1  opp_inhibitors_p2  opp_inhibitors_p3  opp_inhibitors_p4  opp_inhibitors_p5  opp_inhibitors_p6  opp_inhibitors_p7  opp_inhibitors_p8  opp_inhibitors_p9  opp_inhibitors_p10  damagetochampions_p1  damagetochampions_p2  damagetochampions_p3  damagetochampions_p4  damagetochampions_p5  damagetochampions_p6  damagetochampions_p7  damagetochampions_p8  damagetochampions_p9  damagetochampions_p10    dpm_p1    dpm_p2     dpm_p3    dpm_p4    dpm_p5    dpm_p6    dpm_p7    dpm_p8     dpm_p9   dpm_p10  damageshare_p1  damageshare_p2  damageshare_p3  damageshare_p4  damageshare_p5  damageshare_p6  damageshare_p7  damageshare_p8  damageshare_p9  damageshare_p10  damagetakenperminute_p1  damagetakenperminute_p2  damagetakenperminute_p3  damagetakenperminute_p4  damagetakenperminute_p5  damagetakenperminute_p6  damagetakenperminute_p7  damagetakenperminute_p8  damagetakenperminute_p9  damagetakenperminute_p10  damagemitigatedperminute_p1  damagemitigatedperminute_p2  damagemitigatedperminute_p3  damagemitigatedperminute_p4  damagemitigatedperminute_p5  damagemitigatedperminute_p6  damagemitigatedperminute_p7  damagemitigatedperminute_p8  damagemitigatedperminute_p9  damagemitigatedperminute_p10  damagetotowers_p1  damagetotowers_p2  damagetotowers_p3  damagetotowers_p4  damagetotowers_p5  damagetotowers_p6  damagetotowers_p7  damagetotowers_p8  damagetotowers_p9  damagetotowers_p10  wardsplaced_p1  wardsplaced_p2  wardsplaced_p3  wardsplaced_p4  wardsplaced_p5  wardsplaced_p6  wardsplaced_p7  wardsplaced_p8  wardsplaced_p9  wardsplaced_p10  wpm_p1  wpm_p2  wpm_p3  wpm_p4  wpm_p5  wpm_p6  wpm_p7  wpm_p8  wpm_p9  wpm_p10  wardskilled_p1  wardskilled_p2  wardskilled_p3  wardskilled_p4  wardskilled_p5  wardskilled_p6  wardskilled_p7  wardskilled_p8  wardskilled_p9  wardskilled_p10  wcpm_p1  wcpm_p2  wcpm_p3  wcpm_p4  wcpm_p5  wcpm_p6  wcpm_p7  wcpm_p8  wcpm_p9  wcpm_p10  controlwardsbought_p1  controlwardsbought_p2  controlwardsbought_p3  controlwardsbought_p4  controlwardsbought_p5  controlwardsbought_p6  controlwardsbought_p7  controlwardsbought_p8  controlwardsbought_p9  controlwardsbought_p10  visionscore_p1  visionscore_p2  visionscore_p3  visionscore_p4  visionscore_p5  visionscore_p6  visionscore_p7  visionscore_p8  visionscore_p9  visionscore_p10  vspm_p1  vspm_p2  vspm_p3  vspm_p4  vspm_p5  vspm_p6  vspm_p7  vspm_p8  vspm_p9  vspm_p10  totalgold_p1  totalgold_p2  totalgold_p3  totalgold_p4  totalgold_p5  totalgold_p6  totalgold_p7  totalgold_p8  totalgold_p9  totalgold_p10  earnedgold_p1  earnedgold_p2  earnedgold_p3  earnedgold_p4  earnedgold_p5  earnedgold_p6  earnedgold_p7  earnedgold_p8  earnedgold_p9  earnedgold_p10  earned gpm_p1  earned gpm_p2  earned gpm_p3  earned gpm_p4  earned gpm_p5  earned gpm_p6  earned gpm_p7  earned gpm_p8  earned gpm_p9  earned gpm_p10  earnedgoldshare_p1  earnedgoldshare_p2  earnedgoldshare_p3  earnedgoldshare_p4  earnedgoldshare_p5  earnedgoldshare_p6  earnedgoldshare_p7  earnedgoldshare_p8  earnedgoldshare_p9  earnedgoldshare_p10  goldspent_p1  goldspent_p2  goldspent_p3  goldspent_p4  goldspent_p5  goldspent_p6  goldspent_p7  goldspent_p8  goldspent_p9  goldspent_p10  gspd_p1  gspd_p2  gspd_p3  gspd_p4  gspd_p5  gspd_p6  gspd_p7  gspd_p8  gspd_p9  gspd_p10  gpr_p1  gpr_p2  gpr_p3  gpr_p4  gpr_p5  gpr_p6  gpr_p7  gpr_p8  gpr_p9  gpr_p10  total cs_p1  total cs_p2  total cs_p3  total cs_p4  total cs_p5  total cs_p6  total cs_p7  total cs_p8  total cs_p9  total cs_p10  minionkills_p1  minionkills_p2  minionkills_p3  minionkills_p4  minionkills_p5  minionkills_p6  minionkills_p7  minionkills_p8  minionkills_p9  minionkills_p10  monsterkills_p1  monsterkills_p2  monsterkills_p3  monsterkills_p4  monsterkills_p5  monsterkills_p6  monsterkills_p7  monsterkills_p8  monsterkills_p9  monsterkills_p10  monsterkillsownjungle_p1  monsterkillsownjungle_p2  monsterkillsownjungle_p3  monsterkillsownjungle_p4  monsterkillsownjungle_p5  monsterkillsownjungle_p6  monsterkillsownjungle_p7  monsterkillsownjungle_p8  monsterkillsownjungle_p9  monsterkillsownjungle_p10  monsterkillsenemyjungle_p1  monsterkillsenemyjungle_p2  monsterkillsenemyjungle_p3  monsterkillsenemyjungle_p4  monsterkillsenemyjungle_p5  monsterkillsenemyjungle_p6  monsterkillsenemyjungle_p7  monsterkillsenemyjungle_p8  monsterkillsenemyjungle_p9  monsterkillsenemyjungle_p10  cspm_p1  cspm_p2  cspm_p3  cspm_p4  cspm_p5  cspm_p6  cspm_p7  cspm_p8  cspm_p9  cspm_p10  goldat10_p1  goldat10_p2  goldat10_p3  goldat10_p4  goldat10_p5  goldat10_p6  goldat10_p7  goldat10_p8  goldat10_p9  goldat10_p10  xpat10_p1  xpat10_p2  xpat10_p3  xpat10_p4  xpat10_p5  xpat10_p6  xpat10_p7  xpat10_p8  xpat10_p9  xpat10_p10  csat10_p1  csat10_p2  csat10_p3  csat10_p4  csat10_p5  csat10_p6  csat10_p7  csat10_p8  csat10_p9  csat10_p10  opp_goldat10_p1  opp_goldat10_p2  opp_goldat10_p3  opp_goldat10_p4  opp_goldat10_p5  opp_goldat10_p6  opp_goldat10_p7  opp_goldat10_p8  opp_goldat10_p9  opp_goldat10_p10  opp_xpat10_p1  opp_xpat10_p2  opp_xpat10_p3  opp_xpat10_p4  opp_xpat10_p5  opp_xpat10_p6  opp_xpat10_p7  opp_xpat10_p8  opp_xpat10_p9  opp_xpat10_p10  opp_csat10_p1  opp_csat10_p2  opp_csat10_p3  opp_csat10_p4  opp_csat10_p5  opp_csat10_p6  opp_csat10_p7  opp_csat10_p8  opp_csat10_p9  opp_csat10_p10  golddiffat10_p1  golddiffat10_p2  golddiffat10_p3  golddiffat10_p4  golddiffat10_p5  golddiffat10_p6  golddiffat10_p7  golddiffat10_p8  golddiffat10_p9  golddiffat10_p10  xpdiffat10_p1  xpdiffat10_p2  xpdiffat10_p3  xpdiffat10_p4  xpdiffat10_p5  xpdiffat10_p6  xpdiffat10_p7  xpdiffat10_p8  xpdiffat10_p9  xpdiffat10_p10  csdiffat10_p1  csdiffat10_p2  csdiffat10_p3  csdiffat10_p4  csdiffat10_p5  csdiffat10_p6  csdiffat10_p7  csdiffat10_p8  csdiffat10_p9  csdiffat10_p10  killsat10_p1  killsat10_p2  killsat10_p3  killsat10_p4  killsat10_p5  killsat10_p6  killsat10_p7  killsat10_p8  killsat10_p9  killsat10_p10  assistsat10_p1  assistsat10_p2  assistsat10_p3  assistsat10_p4  assistsat10_p5  assistsat10_p6  assistsat10_p7  assistsat10_p8  assistsat10_p9  assistsat10_p10  deathsat10_p1  deathsat10_p2  deathsat10_p3  deathsat10_p4  deathsat10_p5  deathsat10_p6  deathsat10_p7  deathsat10_p8  deathsat10_p9  deathsat10_p10  opp_killsat10_p1  opp_killsat10_p2  opp_killsat10_p3  opp_killsat10_p4  opp_killsat10_p5  opp_killsat10_p6  opp_killsat10_p7  opp_killsat10_p8  opp_killsat10_p9  opp_killsat10_p10  opp_assistsat10_p1  opp_assistsat10_p2  opp_assistsat10_p3  opp_assistsat10_p4  opp_assistsat10_p5  opp_assistsat10_p6  opp_assistsat10_p7  opp_assistsat10_p8  opp_assistsat10_p9  opp_assistsat10_p10  opp_deathsat10_p1  opp_deathsat10_p2  opp_deathsat10_p3  opp_deathsat10_p4  opp_deathsat10_p5  opp_deathsat10_p6  opp_deathsat10_p7  opp_deathsat10_p8  opp_deathsat10_p9  opp_deathsat10_p10  goldat15_p1  goldat15_p2  goldat15_p3  goldat15_p4  goldat15_p5  goldat15_p6  goldat15_p7  goldat15_p8  goldat15_p9  goldat15_p10  xpat15_p1  xpat15_p2  xpat15_p3  xpat15_p4  xpat15_p5  xpat15_p6  xpat15_p7  xpat15_p8  xpat15_p9  xpat15_p10  csat15_p1  csat15_p2  csat15_p3  csat15_p4  csat15_p5  csat15_p6  csat15_p7  csat15_p8  csat15_p9  csat15_p10  opp_goldat15_p1  opp_goldat15_p2  opp_goldat15_p3  opp_goldat15_p4  opp_goldat15_p5  opp_goldat15_p6  opp_goldat15_p7  opp_goldat15_p8  opp_goldat15_p9  opp_goldat15_p10  opp_xpat15_p1  opp_xpat15_p2  opp_xpat15_p3  opp_xpat15_p4  opp_xpat15_p5  opp_xpat15_p6  opp_xpat15_p7  opp_xpat15_p8  opp_xpat15_p9  opp_xpat15_p10  opp_csat15_p1  opp_csat15_p2  opp_csat15_p3  opp_csat15_p4  opp_csat15_p5  opp_csat15_p6  opp_csat15_p7  opp_csat15_p8  opp_csat15_p9  opp_csat15_p10  golddiffat15_p1  golddiffat15_p2  golddiffat15_p3  golddiffat15_p4  golddiffat15_p5  golddiffat15_p6  golddiffat15_p7  golddiffat15_p8  golddiffat15_p9  golddiffat15_p10  xpdiffat15_p1  xpdiffat15_p2  xpdiffat15_p3  xpdiffat15_p4  xpdiffat15_p5  xpdiffat15_p6  xpdiffat15_p7  xpdiffat15_p8  xpdiffat15_p9  xpdiffat15_p10  csdiffat15_p1  csdiffat15_p2  csdiffat15_p3  csdiffat15_p4  csdiffat15_p5  csdiffat15_p6  csdiffat15_p7  csdiffat15_p8  csdiffat15_p9  csdiffat15_p10  killsat15_p1  killsat15_p2  killsat15_p3  killsat15_p4  killsat15_p5  killsat15_p6  killsat15_p7  killsat15_p8  killsat15_p9  killsat15_p10  assistsat15_p1  assistsat15_p2  assistsat15_p3  assistsat15_p4  assistsat15_p5  assistsat15_p6  assistsat15_p7  assistsat15_p8  assistsat15_p9  assistsat15_p10  deathsat15_p1  deathsat15_p2  deathsat15_p3  deathsat15_p4  deathsat15_p5  deathsat15_p6  deathsat15_p7  deathsat15_p8  deathsat15_p9  deathsat15_p10  opp_killsat15_p1  opp_killsat15_p2  opp_killsat15_p3  opp_killsat15_p4  opp_killsat15_p5  opp_killsat15_p6  opp_killsat15_p7  opp_killsat15_p8  opp_killsat15_p9  opp_killsat15_p10  opp_assistsat15_p1  opp_assistsat15_p2  opp_assistsat15_p3  opp_assistsat15_p4  opp_assistsat15_p5  opp_assistsat15_p6  opp_assistsat15_p7  opp_assistsat15_p8  opp_assistsat15_p9  opp_assistsat15_p10  opp_deathsat15_p1  opp_deathsat15_p2  opp_deathsat15_p3  opp_deathsat15_p4  opp_deathsat15_p5  opp_deathsat15_p6  opp_deathsat15_p7  opp_deathsat15_p8  opp_deathsat15_p9  opp_deathsat15_p10  goldat20_p1  goldat20_p2  goldat20_p3  goldat20_p4  goldat20_p5  goldat20_p6  goldat20_p7  goldat20_p8  goldat20_p9  goldat20_p10  xpat20_p1  xpat20_p2  xpat20_p3  xpat20_p4  xpat20_p5  xpat20_p6  xpat20_p7  xpat20_p8  xpat20_p9  xpat20_p10  csat20_p1  csat20_p2  csat20_p3  csat20_p4  csat20_p5  csat20_p6  csat20_p7  csat20_p8  csat20_p9  csat20_p10  opp_goldat20_p1  opp_goldat20_p2  opp_goldat20_p3  opp_goldat20_p4  opp_goldat20_p5  opp_goldat20_p6  opp_goldat20_p7  opp_goldat20_p8  opp_goldat20_p9  opp_goldat20_p10  opp_xpat20_p1  opp_xpat20_p2  opp_xpat20_p3  opp_xpat20_p4  opp_xpat20_p5  opp_xpat20_p6  opp_xpat20_p7  opp_xpat20_p8  opp_xpat20_p9  opp_xpat20_p10  opp_csat20_p1  opp_csat20_p2  opp_csat20_p3  opp_csat20_p4  opp_csat20_p5  opp_csat20_p6  opp_csat20_p7  opp_csat20_p8  opp_csat20_p9  opp_csat20_p10  golddiffat20_p1  golddiffat20_p2  golddiffat20_p3  golddiffat20_p4  golddiffat20_p5  golddiffat20_p6  golddiffat20_p7  golddiffat20_p8  golddiffat20_p9  golddiffat20_p10  xpdiffat20_p1  xpdiffat20_p2  xpdiffat20_p3  xpdiffat20_p4  xpdiffat20_p5  xpdiffat20_p6  xpdiffat20_p7  xpdiffat20_p8  xpdiffat20_p9  xpdiffat20_p10  csdiffat20_p1  csdiffat20_p2  csdiffat20_p3  csdiffat20_p4  csdiffat20_p5  csdiffat20_p6  csdiffat20_p7  csdiffat20_p8  csdiffat20_p9  csdiffat20_p10  killsat20_p1  killsat20_p2  killsat20_p3  killsat20_p4  killsat20_p5  killsat20_p6  killsat20_p7  killsat20_p8  killsat20_p9  killsat20_p10  assistsat20_p1  assistsat20_p2  assistsat20_p3  assistsat20_p4  assistsat20_p5  assistsat20_p6  assistsat20_p7  assistsat20_p8  assistsat20_p9  assistsat20_p10  deathsat20_p1  deathsat20_p2  deathsat20_p3  deathsat20_p4  deathsat20_p5  deathsat20_p6  deathsat20_p7  deathsat20_p8  deathsat20_p9  deathsat20_p10  opp_killsat20_p1  opp_killsat20_p2  opp_killsat20_p3  opp_killsat20_p4  opp_killsat20_p5  opp_killsat20_p6  opp_killsat20_p7  opp_killsat20_p8  opp_killsat20_p9  opp_killsat20_p10  opp_assistsat20_p1  opp_assistsat20_p2  opp_assistsat20_p3  opp_assistsat20_p4  opp_assistsat20_p5  opp_assistsat20_p6  opp_assistsat20_p7  opp_assistsat20_p8  opp_assistsat20_p9  opp_assistsat20_p10  opp_deathsat20_p1  opp_deathsat20_p2  opp_deathsat20_p3  opp_deathsat20_p4  opp_deathsat20_p5  opp_deathsat20_p6  opp_deathsat20_p7  opp_deathsat20_p8  opp_deathsat20_p9  opp_deathsat20_p10  goldat25_p1  goldat25_p2  goldat25_p3  goldat25_p4  goldat25_p5  goldat25_p6  goldat25_p7  goldat25_p8  goldat25_p9  goldat25_p10  xpat25_p1  xpat25_p2  xpat25_p3  xpat25_p4  xpat25_p5  xpat25_p6  xpat25_p7  xpat25_p8  xpat25_p9  xpat25_p10  csat25_p1  csat25_p2  csat25_p3  csat25_p4  csat25_p5  csat25_p6  csat25_p7  csat25_p8  csat25_p9  csat25_p10  opp_goldat25_p1  opp_goldat25_p2  opp_goldat25_p3  opp_goldat25_p4  opp_goldat25_p5  opp_goldat25_p6  opp_goldat25_p7  opp_goldat25_p8  opp_goldat25_p9  opp_golda

In [48]:
colonnes_a_garder = ["gameid", "league", "patch", "side_p1", "position_p1", "position_p2", "position_p3", "position_p4", "position_p5", "position_p6", "position_p7", "position_p8", "position_p9", "position_p10",
                      "playername_p1", "playername_p2", "playername_p3", "playername_p4", "playername_p5", "playername_p6", "playername_p7", "playername_p8", "playername_p9", "playername_p10",
                      "playerid_p1", "playerid_p2", "playerid_p3", "playerid_p4", "playerid_p5", "playerid_p6", "playerid_p7", "playerid_p8", "playerid_p9", "playerid_p10",
                      "teamname_p5", "teamname_p10",
                      "champion_p1", "champion_p2", "champion_p3", "champion_p4", "champion_p5", "champion_p6", "champion_p7", "champion_p8", "champion_p9", "champion_p10",
                      "gamelength_p10", "result_p1"

                      ]
df_very_light = df_games[colonnes_a_garder]

In [49]:
print(df_very_light.head().to_string())

               gameid league  patch side_p1 position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10                                playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10         teamname_p5        teamname_p10 champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8   champion_p9 champion_p10  gamelength_p10  result_p1
0  11715-11715_game_1    LPL  15.01    Blue         top         jng         mid         bot         sup         top         jng         mid         bot          sup       Breathe          Tian        Xiaohu         Light          Hang          Hery          Heng       Linfeng        Starry          Moham  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03        Weibo Gaming           Oh My God     K'Sante       Viego      Aurora        Ashe       Braum        Gnar    Nocturne     Orianna         Varus        Neeko          2123.0        1.0
1  11715-11715_game_2    LPL  15.01    Blue         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Hery          Heng       Linfeng        Starry         Moham       Breathe          Tian        Xiaohu         Light           Hang  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f           Oh My God        Weibo Gaming      Rumble      Maokai     Ambessa        Jhin        Rell       Jayce      Wukong      Viktor  Miss Fortune        Rakan          1952.0        0.0
2  11715-11715_game_3    LPL  15.01    Blue         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Hery          Heng       Linfeng        Starry         Moham       Breathe          Tian        Xiaohu         Light           Hang  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f           Oh My God        Weibo Gaming      Aatrox        Zyra        Yone       Ziggs       Leona         Jax     Sejuani       Sylas          Jinx        Poppy          2014.0        0.0
3  11716-11716_game_1    LPL  15.01    Blue         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Zika        Weiwei       haichao        Photic          Zhuo          HOYA      Beichuan         SeTab           1xn        Feather  oe:player:65ed20b21e2993fb00dbd21a2fd991b  oe:player:57da8dfcfbdb4e5b019fe93003db1c4  oe:player:f886838ee1808c2f217208267a829ce  oe:player:1c42d9266c8b391c7870b7a39f25a12  oe:player:e78da55d6db43d982f841204a8e51ac  oe:player:57ac9f77eae511aeee1e854434f73f2  oe:player:05326a1c42e9c27a1067768c88955e7  oe:player:4ff7b91bbc9492e9f96d28dda496653  oe:player:d2b317a92a71a850ae3da1e0d83e883  oe:player:5000a68e43f946c726a17e1008e230a         LNG Esports  ThunderTalk Gaming     K'Sante    Pantheon    Vladimir     Kalista       Neeko      Rumble          Vi      Aurora        Ezreal        Leona          2098.0        1.0
4  11716-11716_game_2    LPL  15.01    Blue         top         jng         mid         bot         sup         top         jng         mid         bot          sup          HOYA      Beichuan         SeTab           1xn       Feather          Zika        Weiwei       haichao        Photic           Zhuo  oe:player:57ac9f77eae511aeee1e854434f73f2  oe:player:05326a1c42e9c27a1067768c88955e7  oe:player:4ff7b91bbc9492e9f96d28dda496653  oe:player:d2b317a92a71a850ae3da1e0d83e883  oe:player:5000a68e43f946c726a17e1008e230a  oe:player:65ed20b21e2993fb00dbd21a2fd991b  oe:player:57da8dfcfbdb4e5b019fe93003db1c4  oe:player:f886838ee1808c2f217208267a829ce  oe:player:1c42d9266c8b391c7870b7a39f25a12  oe:player:e78da55d6db43d982f841204a8e51ac  ThunderTalk Gaming         LNG Esports        Gnar      Wukong       Akali      Kai'Sa       Rakan    Renekton     Lee Sin     Taliyah         Corki         Rell          2053.0        1.0

In [50]:
nouvel_ordre = ["gameid", "patch", "result_p1", 
                "champion_p1", "champion_p2", "champion_p3", "champion_p4", "champion_p5", "champion_p6", "champion_p7", "champion_p8", "champion_p9", "champion_p10",
                      "gamelength_p10",
                      
                      "position_p1", "position_p2", "position_p3", "position_p4", "position_p5", "position_p6", "position_p7", "position_p8", "position_p9", "position_p10",
                      "playername_p1", "playername_p2", "playername_p3", "playername_p4", "playername_p5", "playername_p6", "playername_p7", "playername_p8", "playername_p9", "playername_p10",
                      "playerid_p1", "playerid_p2", "playerid_p3", "playerid_p4", "playerid_p5", "playerid_p6", "playerid_p7", "playerid_p8", "playerid_p9", "playerid_p10",
                      "teamname_p5", "teamname_p10",
                       "league", "side_p1"
                      ]
df_very_light = df_very_light[nouvel_ordre]

In [52]:
df_very_light = df_very_light.rename(columns={"side_p1": "Blue side", "result_p1": "Blue win", "gamelength_p10": "Game length"})

In [54]:
print(df_very_light.head().to_string())

               gameid  patch  Blue win champion_p1 champion_p2 champion_p3 champion_p4 champion_p5 champion_p6 champion_p7 champion_p8   champion_p9 champion_p10  Game length position_p1 position_p2 position_p3 position_p4 position_p5 position_p6 position_p7 position_p8 position_p9 position_p10 playername_p1 playername_p2 playername_p3 playername_p4 playername_p5 playername_p6 playername_p7 playername_p8 playername_p9 playername_p10                                playerid_p1                                playerid_p2                                playerid_p3                                playerid_p4                                playerid_p5                                playerid_p6                                playerid_p7                                playerid_p8                                playerid_p9                               playerid_p10         teamname_p5        teamname_p10 league Blue side
0  11715-11715_game_1  15.01       1.0     K'Sante       Viego      Aurora        Ashe       Braum        Gnar    Nocturne     Orianna         Varus        Neeko       2123.0         top         jng         mid         bot         sup         top         jng         mid         bot          sup       Breathe          Tian        Xiaohu         Light          Hang          Hery          Heng       Linfeng        Starry          Moham  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03        Weibo Gaming           Oh My God    LPL      Blue
1  11715-11715_game_2  15.01       0.0      Rumble      Maokai     Ambessa        Jhin        Rell       Jayce      Wukong      Viktor  Miss Fortune        Rakan       1952.0         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Hery          Heng       Linfeng        Starry         Moham       Breathe          Tian        Xiaohu         Light           Hang  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f           Oh My God        Weibo Gaming    LPL      Blue
2  11715-11715_game_3  15.01       0.0      Aatrox        Zyra        Yone       Ziggs       Leona         Jax     Sejuani       Sylas          Jinx        Poppy       2014.0         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Hery          Heng       Linfeng        Starry         Moham       Breathe          Tian        Xiaohu         Light           Hang  oe:player:407b2b8fcb2fd977fc766d5df3f4dff  oe:player:92f0831b560a15d8be3be25275adb08  oe:player:cb6616189a21f8e8ed43ccdb3f6904a  oe:player:0be01924125adebc1a95bbb09d0c4d1  oe:player:dfc279de8d7bd571aa8edfd7eb89c03  oe:player:0d9b0a3b3a93a8f759c9d8ac8eef97c  oe:player:0da0eeb199e8fa3ab773cf84f9de9ab  oe:player:beea9fe15bff6a7ab0b3913d3d5fde6  oe:player:3c4d21c7addb20fea3fec30418ac3d3  oe:player:ab2455e33b8ddb6a9d2d41107a2ed4f           Oh My God        Weibo Gaming    LPL      Blue
3  11716-11716_game_1  15.01       1.0     K'Sante    Pantheon    Vladimir     Kalista       Neeko      Rumble          Vi      Aurora        Ezreal        Leona       2098.0         top         jng         mid         bot         sup         top         jng         mid         bot          sup          Zika        Weiwei       haichao        Photic          Zhuo          HOYA      Beichuan         SeTab           1xn        Feather  oe:player:65ed20b21e2993fb00dbd21a2fd991b  oe:player:57da8dfcfbdb4e5b019fe93003db1c4  oe:player:f886838ee1808c2f217208267a829ce  oe:player:1c42d9266c8b391c7870b7a39f25a12  oe:player:e78da55d6db43d982f841204a8e51ac  oe:player:57ac9f77eae511aeee1e854434f73f2  oe:player:05326a1c42e9c27a1067768c88955e7  oe:player:4ff7b91bbc9492e9f96d28dda496653  oe:player:d2b317a92a71a850ae3da1e0d83e883  oe:player:5000a68e43f946c726a17e1008e230a         LNG Esports  ThunderTalk Gaming    LPL      Blue
4  11716-11716_game_2  15.01       1.0        Gnar      Wukong       Akali      Kai'Sa       Rakan    Renekton     Lee Sin     Taliyah         Corki         Rell       2053.0         top         jng         mid         bot         sup         top         jng         mid         bot          sup          HOYA      Beichuan         SeTab           1xn       Feather          Zika        Weiwei       haichao        Photic           Zhuo  oe:player:57ac9f77eae511aeee1e854434f73f2  oe:player:05326a1c42e9c27a1067768c88955e7  oe:player:4ff7b91bbc9492e9f96d28dda496653  oe:player:d2b317a92a71a850ae3da1e0d83e883  oe:player:5000a68e43f946c726a17e1008e230a  oe:player:65ed20b21e2993fb00dbd21a2fd991b  oe:player:57da8dfcfbdb4e5b019fe93003db1c4  oe:player:f886838ee1808c2f217208267a829ce  oe:player:1c42d9266c8b391c7870b7a39f25a12  oe:player:e78da55d6db43d982f841204a8e51ac  ThunderTalk Gaming         LNG Esports    LPL      Blue

In [55]:
df_very_light.to_csv("games_pro_2025_very_light.csv", index=False)

In [56]:
df_very_light.shape

(10053, 48)