In [2]:
import requests
import tarfile
import io
import os
import json
import csv

# ================== CONFIG ==================
LANG = "fr_FR"

BASE_DIR = r"D:\lol draft analyzer\part 2\data champions"
TGZ_DIR = os.path.join(BASE_DIR, "tgz")
JSON_DIR = os.path.join(BASE_DIR, "collect")
CSV_DIR = os.path.join(BASE_DIR, "csv")

os.makedirs(TGZ_DIR, exist_ok=True)
os.makedirs(JSON_DIR, exist_ok=True)
os.makedirs(CSV_DIR, exist_ok=True)

# ================== UTILS ==================
def dump(value):
    """Serialize dict/list for CSV"""
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False)
    return value

# ================== SPELL FLATTENER ==================
def flatten_spell(spell, prefix):
    row = {}
    for k, v in spell.items():
        row[f"{prefix}_{k}"] = dump(v)
    return row

# ================== CHAMPION FLATTENER ==================
def flatten_champion(champ, patch):
    row = {
        "patch": patch,
        "id": champ.get("id"),
        "key": champ.get("key"),
        "name": champ.get("name"),
        "title": champ.get("title"),
        "partype": champ.get("partype"),
        "tags": dump(champ.get("tags")),
        "lore": champ.get("lore"),
        "blurb": champ.get("blurb"),
        "allytips": dump(champ.get("allytips")),
        "enemytips": dump(champ.get("enemytips")),
        "skins": dump(champ.get("skins")),
        "skins_count": len(champ.get("skins", [])),
    }

    # info
    for k, v in champ.get("info", {}).items():
        row[f"info_{k}"] = v

    # stats
    for k, v in champ.get("stats", {}).items():
        row[f"stats_{k}"] = v

    # passive
    passive = champ.get("passive", {})
    row["passive_name"] = passive.get("name")
    row["passive_description"] = passive.get("description")
    row["passive_image"] = dump(passive.get("image"))

    # spells
    spells = champ.get("spells", [])
    labels = ["q", "w", "e", "r"]

    for i, label in enumerate(labels):
        if i < len(spells):
            row.update(flatten_spell(spells[i], f"spell_{label}"))
        else:
            row[f"spell_{label}_missing"] = True

    return row

# ================== PATCH PROCESSOR ==================
def process_patch(patch):
    print(f"\n=== PATCH {patch} ===")

    tgz_path = os.path.join(TGZ_DIR, f"dragontail-{patch}.tgz")
    csv_path = os.path.join(CSV_DIR, f"champions_{patch}.csv")
    patch_json_dir = os.path.join(JSON_DIR, patch)
    os.makedirs(patch_json_dir, exist_ok=True)

    # ---- DOWNLOAD IF NEEDED ----
    if not os.path.exists(tgz_path):
        print("⬇ Downloading tgz...")
        url = f"https://ddragon.leagueoflegends.com/cdn/dragontail-{patch}.tgz"
        r = requests.get(url)
        r.raise_for_status()
        with open(tgz_path, "wb") as f:
            f.write(r.content)
    else:
        print("✔ Using cached tgz")

    # ---- OPEN ARCHIVE ----
    with tarfile.open(tgz_path, "r:gz") as tar:
        prefix = f"{patch}/data/{LANG}/champion/"
        members = [
            m for m in tar.getmembers()
            if m.name.startswith(prefix) and m.name.endswith(".json")
        ]

        print(f"✔ {len(members)} champions")

        rows = []

        for m in members:
            try:
                raw = json.load(tar.extractfile(m))
                champ = next(iter(raw["data"].values()))
            except Exception as e:
                print("❌ JSON error:", m.name, e)
                continue

            # save raw json
            with open(
                os.path.join(patch_json_dir, os.path.basename(m.name)),
                "w",
                encoding="utf-8"
            ) as f:
                json.dump(raw, f, ensure_ascii=False, indent=2)

            rows.append(flatten_champion(champ, patch))

    # ---- WRITE CSV ----
    if rows:
        with open(csv_path, "w", newline="", encoding="utf-8") as f:
            writer = csv.DictWriter(f, fieldnames=rows[0].keys())
            writer.writeheader()
            writer.writerows(rows)

    print(f"✅ CSV written: {csv_path}")

# ================== RUN ==================
if __name__ == "__main__":
    PATCHES = [
        "15.24.1",
        "15.23.1",
        "15.22.1",
        "15.21.1",
        "15.20.1",
        "15.19.1",
        "15.18.1",
        "15.17.1",
        "15.16.1",
        "15.15.1",
        "15.14.1",
        "15.13.1",
        "15.12.1",
        "15.11.1",
        "15.10.1",
        "15.9.1",
        "15.8.1",
        "15.7.1",
        "15.6.1",
        "15.5.1",
        "15.4.1",
        "15.3.1",
        "15.2.1",
        "15.1.1",
        "14.24.1",
    ]

    for patch in PATCHES:
        process_patch(patch)

    print("\n🎉 ALL PATCHES DONE")

=== PATCH 15.24.1 ===
✔ Using cached tgz
✔ 172 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.24.1.csv

=== PATCH 15.23.1 ===
✔ Using cached tgz
✔ 172 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.23.1.csv

=== PATCH 15.22.1 ===
✔ Using cached tgz
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.22.1.csv

=== PATCH 15.21.1 ===
✔ Using cached tgz
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.21.1.csv

=== PATCH 15.20.1 ===
✔ Using cached tgz
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.20.1.csv

=== PATCH 15.19.1 ===
✔ Using cached tgz
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.19.1.csv

=== PATCH 15.18.1 ===
✔ Using cached tgz
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.18.1.csv

=== PATCH 15.17.1 ===
⬇ Downloading tgz...
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.17.1.csv

=== PATCH 15.16.1 ===
⬇ Downloading tgz...
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.16.1.csv

=== PATCH 15.15.1 ===
⬇ Downloading tgz...
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.15.1.csv

=== PATCH 15.14.1 ===
⬇ Downloading tgz...
✔ 171 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.14.1.csv

=== PATCH 15.13.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.13.1.csv

=== PATCH 15.12.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.12.1.csv

=== PATCH 15.11.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.11.1.csv

=== PATCH 15.10.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.10.1.csv

=== PATCH 15.9.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.9.1.csv

=== PATCH 15.8.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.8.1.csv

=== PATCH 15.7.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.7.1.csv

=== PATCH 15.6.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.6.1.csv

=== PATCH 15.5.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.5.1.csv

=== PATCH 15.4.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.4.1.csv

=== PATCH 15.3.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.3.1.csv

=== PATCH 15.2.1 ===
⬇ Downloading tgz...
✔ 170 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.2.1.csv

=== PATCH 15.1.1 ===
⬇ Downloading tgz...
✔ 169 champions
✅ CSV written: D:\lol draft analyzer\part 2\data champions\csv\champions_15.1.1.csv

=== PATCH 14.24.1 ===
⬇ Downloading tgz...

ChunkedEncodingError: ("Connection broken: ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None)", ConnectionResetError(10054, 'Une connexion existante a dû être fermée par l’hôte distant', None, 10054, None))

In [3]:
import os
import pandas as pd
import re

# ================== CONFIG ==================
CSV_DIR = r"D:\lol draft analyzer\part 2\data champions\csv"
OUTPUT_DIR = CSV_DIR
# ============================================

def extract_patch(filename):
    """
    Extrait le patch depuis champions_15.24.1.csv
    """
    match = re.search(r"champions_(\d+\.\d+\.\d+)\.csv", filename)
    return match.group(1) if match else None

def aggregate_csvs():
    csv_files = [
        f for f in os.listdir(CSV_DIR)
        if f.startswith("champions_") and f.endswith(".csv")
    ]

    if not csv_files:
        raise RuntimeError("❌ Aucun CSV trouvé")

    dfs = []
    patches = []

    for file in csv_files:
        patch = extract_patch(file)
        if not patch:
            print("⚠ Fichier ignoré:", file)
            continue

        path = os.path.join(CSV_DIR, file)
        print("✔ Loading:", file)

        df = pd.read_csv(path)
        dfs.append(df)
        patches.append(patch)

    # concat
    final_df = pd.concat(dfs, ignore_index=True)

    # tri par patch + champion
    final_df.sort_values(by=["patch", "id"], inplace=True)

    # nom du fichier final
    patches_sorted = sorted(
        patches,
        key=lambda p: tuple(map(int, p.split(".")))
    )

    first_patch = patches_sorted[0]
    last_patch = patches_sorted[-1]

    output_name = f"champions_{first_patch}_{last_patch}.csv"
    output_path = os.path.join(OUTPUT_DIR, output_name)

    final_df.to_csv(output_path, index=False, encoding="utf-8")

    print("\n🎉 AGGREGATION TERMINÉE")
    print("➡ Fichier généré :", output_path)
    print("➡ Lignes :", len(final_df))
    print("➡ Champions uniques :", final_df['id'].nunique())
    print("➡ Patchs :", final_df['patch'].nunique())

if __name__ == "__main__":
    aggregate_csvs()

✔ Loading: champions_15.1.1.csv
✔ Loading: champions_15.10.1.csv
✔ Loading: champions_15.11.1.csv
✔ Loading: champions_15.12.1.csv
✔ Loading: champions_15.13.1.csv
✔ Loading: champions_15.14.1.csv
✔ Loading: champions_15.15.1.csv
✔ Loading: champions_15.16.1.csv
✔ Loading: champions_15.17.1.csv
✔ Loading: champions_15.18.1.csv
⚠ Fichier ignoré: champions_15.18.1_15.24.1.csv
✔ Loading: champions_15.19.1.csv
✔ Loading: champions_15.2.1.csv
✔ Loading: champions_15.20.1.csv
✔ Loading: champions_15.21.1.csv
✔ Loading: champions_15.22.1.csv
✔ Loading: champions_15.23.1.csv
✔ Loading: champions_15.24.1.csv
✔ Loading: champions_15.3.1.csv
✔ Loading: champions_15.4.1.csv
✔ Loading: champions_15.5.1.csv
✔ Loading: champions_15.6.1.csv
✔ Loading: champions_15.7.1.csv
✔ Loading: champions_15.8.1.csv
✔ Loading: champions_15.9.1.csv
⚠ Fichier ignoré: champions_cleaned_15.18.1_15.24.1.csv

🎉 AGGREGATION TERMINÉE
➡ Fichier généré : D:\lol draft analyzer\part 2\data champions\csv\champions_15.1.1_15.24.1.csv
➡ Lignes : 4092
➡ Champions uniques : 172
➡ Patchs : 24

In [ ]:
import pandas as pd

jhkhkhkhkCSV_PATH = r"D:\lol draft analyzer\part 2\data champions\csv\champions_15.1.1_15.24.1.csv"

df = pd.read_csv(CSV_PATH)

print("Shape:", df.shape)

Shape: (4092, 120)

In [6]:
print(df.head())
print(df.info())
print(df.describe())
print(df.describe(include="object"))
print(df.columns.tolist())

    patch       id  key     name                 title        partype  \
0  15.1.1   Aatrox  266   Aatrox       Épée des Darkin  Puits de sang
1  15.1.1     Ahri  103     Ahri  Renard à neuf queues           Mana
2  15.1.1    Akali   84    Akali      Assassin rebelle        Énergie
3  15.1.1   Akshan  166   Akshan    Sentinelle rebelle           Mana
4  15.1.1  Alistar   12  Alistar             Minotaure           Mana

                       tags  \
0               ["Fighter"]
1      ["Mage", "Assassin"]
2              ["Assassin"]
3  ["Marksman", "Assassin"]
4       ["Tank", "Support"]

                                                lore  \
0  Autrefois, Aatrox et ses frères étaient honoré...
1  Connectée à la magie du royaume spirituel, Ahr...
2  Ayant abandonné l'Ordre Kinkou et le titre de ...
3  Se jouant du danger, Akshan combat le mal sans...
4  Alistar est un guerrier redoutable cherchant à...

                                               blurb  \
0  Autrefois, Aatrox et ses frères étaient honoré...
1  Connectée à la magie du royaume spirituel, Ahr...
2  Ayant abandonné l'Ordre Kinkou et le titre de ...
3  Se jouant du danger, Akshan combat le mal sans...
4  Alistar est un guerrier redoutable cherchant à...

                                            allytips  ... spell_r_datavalues  \
0  ["Utilisez Ruée obscure tout en lançant Épée d...  ...                 {}
1  ["Utilisez Charme pour préparer vos combos, ce...  ...                 {}
2  ["Akali peut facilement tuer les champions fra...  ...                 {}
3  ["Se jouant du danger, Akshan combat le mal sa...  ...                 {}
4  ["Atomisation peut vous aider à mieux vous pla...  ...                 {}

                                      spell_r_effect  \
0  [null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...
1  [null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...
2  [null, [0, 0, 0], [0, 0, 0], [1, 1, 1], [0, 0,...
3  [null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...
4  [null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...

                                  spell_r_effectBurn  spell_r_vars  \
0  [null, "0", "0", "0", "0", "0", "0", "0", "0",...            []
1  [null, "0", "0", "0", "0", "0", "0", "0", "0",...            []
2  [null, "0", "0", "1", "0", "0", "0", "0", "0",...            []
3  [null, "0", "0", "0", "0", "0", "0", "0", "0",...            []
4  [null, "0", "0", "0", "0", "0", "0", "0", "0",...            []

             spell_r_costType  spell_r_maxammo          spell_r_range  \
0                 Pas de coût               -1  [25000, 25000, 25000]
1   {{ abilityresourcename }}               -1        [450, 450, 450]
2                 Pas de coût               -1        [675, 675, 675]
3   {{ abilityresourcename }}               -1     [2500, 2500, 2500]
4   {{ abilityresourcename }}               -1              [1, 1, 1]

   spell_r_rangeBurn                                      spell_r_image  \
0              25000  {"full": "AatroxR.png", "sprite": "spell0.png"...
1                450  {"full": "AhriR.png", "sprite": "spell0.png", ...
2                675  {"full": "AkaliR.png", "sprite": "spell0.png",...
3               2500  {"full": "AkshanR.png", "sprite": "spell0.png"...
4                  1  {"full": "FerociousHowl.png", "sprite": "spell...

                       spell_r_resource
0                           Pas de coût
1  {{ cost }} {{ abilityresourcename }}
2                           Pas de coût
3  {{ cost }} {{ abilityresourcename }}
4  {{ cost }} {{ abilityresourcename }}

[5 rows x 120 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4092 entries, 0 to 4091
Columns: 120 entries, patch to spell_r_resource
dtypes: float64(10), int64(25), object(85)
memory usage: 3.7+ MB
None
               key  skins_count  info_attack  info_defense   info_magic  \
count  4092.000000  4092.000000  4092.000000   4092.000000  4092.000000
mean    197.568915    11.622923     5.423509      4.511730     5.218231
std     246.007649     4.692895     2.877226      2.157592     2.861768
min       1.000000     2.000000     0.000000      0.000000     0.000000
25%      43.000000     8.000000     3.000000      3.000000     3.000000
50%     102.000000    12.000000     6.000000      4.000000     5.000000
75%     233.000000    15.000000     8.000000      6.000000     8.000000
max     950.000000    23.000000    10.000000     10.000000    10.000000

       info_difficulty     stats_hp  stats_hpperlevel      stats_mp  \
count      4092.000000  4092.000000       4092.000000   4092.000000
mean          5.699658   617.884164        104.004643    372.878543
std           2.289801    39.069966          8.460022    749.007376
min           0.000000   410.000000         69.000000      0.000000
25%           4.000000   598.000000         99.000000    280.000000
50%           6.000000   625.000000        104.000000    330.000000
75%           7.000000   645.000000        109.000000    400.000000
max          10.000000   696.000000        126.000000  10000.000000

       stats_mpperlevel  ...  stats_attackspeed  spell_q_maxrank  \
count       4092.000000  ...        4092.000000      4092.000000
mean          36.174731  ...           0.653286         5.023460
std           19.550148  ...           0.035264         0.151379
min            0.000000  ...           0.475000         5.000000
25%           25.000000  ...           0.625000         5.000000
50%           40.000000  ...           0.656000         5.000000
75%           50.000000  ...           0.668000         5.000000
max           87.000000  ...           0.850000         6.000000

       spell_q_maxammo  spell_w_maxrank  spell_w_maxammo  spell_e_maxrank  \
count      4092.000000      4092.000000      4092.000000      4092.000000
mean         -0.917889         5.017595        -0.818182         5.017595
std           0.477407         0.131491         0.690885         0.131491
min          -1.000000         5.000000        -1.000000         5.000000
25%          -1.000000         5.000000        -1.000000         5.000000
50%          -1.000000         5.000000        -1.000000         5.000000
75%          -1.000000         5.000000        -1.000000         5.000000
max           3.000000         6.000000         3.000000         6.000000

       spell_e_maxammo  spell_e_rangeBurn  spell_r_maxrank  spell_r_maxammo
count      4092.000000        4092.000000      4092.000000      4092.000000
mean         -0.841642        1532.461877         3.023460        -0.923754
std           0.653177        4526.902870         0.305473         0.541644
min          -1.000000           0.000000         1.000000        -1.000000
25%          -1.000000         450.000000         3.000000        -1.000000
50%          -1.000000         650.000000         3.000000        -1.000000
75%          -1.000000         900.000000         3.000000        -1.000000
max           3.000000       25000.000000         6.000000         4.000000

[8 rows x 35 columns]
          patch      id    name            title partype                 tags  \
count      4092    4092    4092             4092    4068                 4092
unique       24     172     172              175      13                   27
top     15.24.1  Aatrox  Aatrox  Épée des Darkin    Mana  ["Fighter", "Tank"]
freq        172      24      24               24    3420                  456

                                                     lore  \
count                                                4092
unique                                                174
top     Autrefois, Aatrox et ses frères étaient honoré...
freq                                                   24

                                                    blurb allytips enemytips  \
count                                                4092     4092      4092
unique                                                173      149       147
top     Autrefois, Aatrox et ses frères étaient honoré...       []        []
freq                                                   24      517       565

        ... spell_r_costBurn spell_r_datavalues  \
count   ...             4092               4092
unique  ...               14                  1
top     ...              100                 {}
freq    ...             2883               4092

                                           spell_r_effect  \
count                                                4092
unique                                                 48
top     [null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...
freq                                                 3105

                                       spell_r_effectBurn spell_r_vars  \
count                                                4092         4092
unique                                                 44            1
top     [null, "0", "0", "0", "0", "0", "0", "0", "0",...           []
freq                                                 3177         4092

                  spell_r_costType          spell_r_range spell_r_rangeBurn  \
count                         4092                   4092              4092
unique                           6                     74                71
top      {{ abilityresourcename }}  [25000, 25000, 25000]             25000
freq                          3252                    383               383

                                            spell_r_image  \
count                                                4092
unique                                                276
top     {"full": "Highlander.png", "sprite": "spell8.p...
freq                                                   24

                            spell_r_resource
count                                   4092
unique                                     6
top     {{ cost }} {{ abilityresourcename }}
freq                                    3252

[4 rows x 85 columns]
['patch', 'id', 'key', 'name', 'title', 'partype', 'tags', 'lore', 'blurb', 'allytips', 'enemytips', 'skins', 'skins_count', 'info_attack', 'info_defense', 'info_magic', 'info_difficulty', 'stats_hp', 'stats_hpperlevel', 'stats_mp', 'stats_mpperlevel', 'stats_movespeed', 'stats_armor', 'stats_armorperlevel', 'stats_spellblock', 'stats_spellblockperlevel', 'stats_attackrange', 'stats_hpregen', 'stats_hpregenperlevel', 'stats_mpregen', 'stats_mpregenperlevel', 'stats_crit', 'stats_critperlevel', 'stats_attackdamage', 'stats_attackdamageperlevel', 'stats_attackspeedperlevel', 'stats_attackspeed', 'passive_name', 'passive_description', 'passive_image', 'spell_q_id', 'spell_q_name', 'spell_q_description', 'spell_q_tooltip', 'spell_q_leveltip', 'spell_q_maxrank', 'spell_q_cooldown', 'spell_q_cooldownBurn', 'spell_q_cost', 'spell_q_costBurn', 'spell_q_datavalues', 'spell_q_effect', 'spell_q_effectBurn', 'spell_q_vars', 'spell_q_costType', 'spell_q_maxammo', 'spell_q_range', 'spell_q_rangeBurn', 'spell_q_image', 'spell_q_resource', 'spell_w_id', 'spell_w_name', 'spell_w_description', 'spell_w_tooltip', 'spell_w_leveltip', 'spell_w_maxrank', 'spell_w_cooldown', 'spell_w_cooldownBurn', 'spell_w_cost', 'spell_w_costBurn', 'spell_w_datavalues', 'spell_w_effect', 'spell_w_effectBurn', 'spell_w_vars', 'spell_w_costType', 'spell_w_maxammo', 'spell_w_range', 'spell_w_rangeBurn', 'spell_w_image', 'spell_w_resource', 'spell_e_id', 'spell_e_name', 'spell_e_description', 'spell_e_tooltip', 'spell_e_leveltip', 'spell_e_maxrank', 'spell_e_cooldown', 'spell_e_cooldownBurn', 'spell_e_cost', 'spell_e_costBurn', 'spell_e_datavalues', 'spell_e_effect', 'spell_e_effectBurn', 'spell_e_vars', 'spell_e_costType', 'spell_e_maxammo', 'spell_e_range', 'spell_e_rangeBurn', 'spell_e_image', 'spell_e_resource', 'spell_r_id', 'spell_r_name', 'spell_r_description', 'spell_r_tooltip', 'spell_r_leveltip', 'spell_r_maxrank', 'spell_r_cooldown', 'spell_r_cooldownBurn', 'spell_r_cost', 'spell_r_costBurn', 'spell_r_datavalues', 'spell_r_effect', 'spell_r_effectBurn', 'spell_r_vars', 'spell_r_costType', 'spell_r_maxammo', 'spell_r_range', 'spell_r_rangeBurn', 'spell_r_image', 'spell_r_resource']

In [7]:
COLUMNS_TO_DROP = [
    "skins_count",
    "skins",
    "lore",
    "id",
    "title",
    "blurb",
    "allytips",
    "enemytips",
    "spell_q_description",
    "spell_w_description",
    "spell_e_description",
    "spell_r_description",
    "passive_description",
    "passive_name",
    "spell_q_name",
    "spell_w_name",
    "spell_e_name",
    "spell_r_name",
    "spell_r_tooltip",
    "spell_r_leveltip",
    "spell_e_tooltip",
    "spell_e_leveltip",
    "spell_w_tooltip",
    "spell_w_leveltip",
    "spell_q_tooltip",
    "spell_q_leveltip",
    "spell_q_image",
    "spell_w_image",
    "spell_e_image",
    "spell_r_image",
    "passive_image",

    "spell_q_cooldownBurn",
    "spell_q_costBurn",
    "spell_q_effectBurn",
    "spell_q_rangeBurn",
    "spell_w_cooldownBurn",
    "spell_w_costBurn",
    "spell_w_effectBurn",
    "spell_w_rangeBurn",
    "spell_e_cooldownBurn",
    "spell_e_costBurn",
    "spell_e_effectBurn",
    "spell_e_rangeBurn",
    "spell_r_cooldownBurn",
    "spell_r_costBurn",
    "spell_r_effectBurn",
    "spell_r_rangeBurn",
]

df_clean = df.drop(columns=COLUMNS_TO_DROP, errors="ignore")

In [8]:
OUTPUT_PATH = r"D:\lol draft analyzer\part 2\data champions\csv\champions_cleaned_15.1.1_15.24.1.csv"

df_clean.to_csv(OUTPUT_PATH, index=False, encoding="utf-8")

print("✅ CSV nettoyé sauvegardé :", OUTPUT_PATH)

✅ CSV nettoyé sauvegardé : D:\lol draft analyzer\part 2\data champions\csv\champions_cleaned_15.1.1_15.24.1.csv

In [13]:
counts = df_clean["name"].value_counts()

champions_less_than_3 = counts[counts < 24]

print(champions_less_than_3)

name
Mel       23
Yunara    11
Zaahen     2
Name: count, dtype: int64

In [16]:
df_clean.tail(10)

,patch,key,name,partype,tags,info_attack,info_defense,info_magic,info_difficulty,stats_hp,...,spell_r_maxrank,spell_r_cooldown,spell_r_cost,spell_r_datavalues,spell_r_effect,spell_r_vars,spell_r_costType,spell_r_maxammo,spell_r_range,spell_r_resource
4082,15.9.1,777,Yone,Impulsion,"[""Fighter"", ""Assassin""]",8,4,4,8,620,...,3,"[120, 100, 80]","[0, 0, 0]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],Pas de coût,-1,"[1000, 1000, 1000]",Pas de coût
4083,15.9.1,83,Yorick,Mana,"[""Fighter"", ""Tank""]",6,6,4,6,650,...,3,"[160, 130, 100]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[600, 600, 600]",{{ cost }} {{ abilityresourcename }}
4084,15.9.1,350,Yuumi,Mana,"[""Support"", ""Mage""]",5,1,8,2,500,...,3,"[120, 110, 100]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[1100, 1100, 1100]",{{ cost }} {{ abilityresourcename }}
4085,15.9.1,154,Zac,Aucune,"[""Tank"", ""Fighter""]",3,7,7,8,685,...,3,"[120, 105, 90]","[0, 0, 0]",{},"[null, [150, 250, 350], [1.1, 1.1, 1.1], [700,...",[],Pas de coût,-1,"[300, 300, 300]",Pas de coût
4086,15.9.1,238,Zed,Énergie,"[""Assassin""]",9,2,1,7,654,...,3,"[120, 110, 100]","[0, 0, 0]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],Pas de coût,-1,"[625, 625, 625]",Pas de coût
4087,15.9.1,221,Zeri,Mana,"[""Marksman""]",8,5,3,6,600,...,3,"[80, 75, 70]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[800, 800, 800]",{{ cost }} {{ abilityresourcename }}
4088,15.9.1,115,Ziggs,Mana,"[""Mage""]",2,4,9,4,606,...,3,"[120, 95, 70]","[100, 100, 100]",{},"[null, [300, 450, 600], [66.6667, 66.6667, 66....",[],{{ abilityresourcename }},-1,"[5000, 5000, 5000]",{{ cost }} {{ abilityresourcename }}
4089,15.9.1,26,Zilean,Mana,"[""Support"", ""Mage""]",2,5,8,6,574,...,3,"[120, 90, 60]","[125, 150, 175]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[900, 900, 900]",{{ cost }} {{ abilityresourcename }}
4090,15.9.1,142,Zoé,Mana,"[""Mage""]",1,7,8,5,630,...,3,"[11, 8, 5]","[40, 40, 40]",{},"[null, [-0.3, -0.4, -0.5], [1.5, 2, 2.5], [4, ...",[],{{ abilityresourcename }},-1,"[575, 575, 575]",{{ cost }} {{ abilityresourcename }}
4091,15.9.1,143,Zyra,Mana,"[""Mage"", ""Support""]",4,3,8,7,574,...,3,"[110, 100, 90]","[100, 100, 100]",{},"[null, [1, 1, 1], [50, 50, 50], [180, 265, 350...",[],{{ abilityresourcename }},-1,"[700, 700, 700]",{{ cost }} {{ abilityresourcename }}

In [1]:
df_clean.loc[df_clean["name"] == "Teemo", ["spell_q_effect"]].iloc[0]
# .to_string(index=False)

NameError: name 'df_clean' is not defined

In [28]:
pd.set_option("display.max_colwidth", None)

print(
    df_clean.loc[df_clean["name"] == "Teemo", ["spell_q_effect"]]
    .iloc[0]
    .to_string()
)

spell_q_effect    [null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [29]:
pd.set_option("display.max_colwidth", None)

print(
    df_clean.loc[df_clean["name"] == "Quinn", ["spell_q_effect"]]
    .iloc[0]
    .to_string()
)

spell_q_effect    [null, [20, 40, 60, 80, 100], [-1000, -1000, -1000, -1000, -1000], [1.75, 1.75, 1.75, 1.75, 1.75], [0.8, 0.9, 1, 1.1, 1.2], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [30]:
pd.set_option("display.max_colwidth", None)

print(
    df_clean.loc[df_clean["name"] == "Malphite", ["spell_r_effect"]]
    .iloc[0]
    .to_string()
)

spell_r_effect    [null, [1.5, 1.75, 2], [200, 300, 400], [1.5, 1.5, 1.5], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0, 0]]

In [34]:
pd.set_option("display.max_colwidth", None)

print(
    df_clean.loc[df_clean["name"] == "Fiddlesticks", ["spell_q_effect"]]
    .iloc[0]
    .to_string()
)

spell_q_effect    [null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]

In [5]:
import pandas as pd
INPUT_PATH = r"D:\lol draft analyzer\part 2\data champions\csv\champions_cleaned_15.1.1_15.24.1.csv"

df_champs= pd.read_csv(INPUT_PATH, encoding="utf-8")

In [6]:
df_champs.head()

,patch,key,name,partype,tags,info_attack,info_defense,info_magic,info_difficulty,stats_hp,...,spell_r_maxrank,spell_r_cooldown,spell_r_cost,spell_r_datavalues,spell_r_effect,spell_r_vars,spell_r_costType,spell_r_maxammo,spell_r_range,spell_r_resource
0,15.1.1,266,Aatrox,Puits de sang,"[""Fighter""]",8,4,3,4,650,...,3,"[120, 100, 80]","[0, 0, 0]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],Pas de coût,-1,"[25000, 25000, 25000]",Pas de coût
1,15.1.1,103,Ahri,Mana,"[""Mage"", ""Assassin""]",3,4,8,5,590,...,3,"[130, 115, 100]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[450, 450, 450]",{{ cost }} {{ abilityresourcename }}
2,15.1.1,84,Akali,Énergie,"[""Assassin""]",5,3,8,7,600,...,3,"[120, 90, 60]","[0, 0, 0]",{},"[null, [0, 0, 0], [0, 0, 0], [1, 1, 1], [0, 0,...",[],Pas de coût,-1,"[675, 675, 675]",Pas de coût
3,15.1.1,166,Akshan,Mana,"[""Marksman"", ""Assassin""]",0,0,0,0,630,...,3,"[100, 85, 70]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[2500, 2500, 2500]",{{ cost }} {{ abilityresourcename }}
4,15.1.1,12,Alistar,Mana,"[""Tank"", ""Support""]",6,9,5,7,685,...,3,"[120, 100, 80]","[100, 100, 100]",{},"[null, [0, 0, 0], [0, 0, 0], [0, 0, 0], [0, 0,...",[],{{ abilityresourcename }},-1,"[1, 1, 1]",{{ cost }} {{ abilityresourcename }}

In [7]:
df_champs.columns.tolist()

['patch',
 'key',
 'name',
 'partype',
 'tags',
 'info_attack',
 'info_defense',
 'info_magic',
 'info_difficulty',
 'stats_hp',
 'stats_hpperlevel',
 'stats_mp',
 'stats_mpperlevel',
 'stats_movespeed',
 'stats_armor',
 'stats_armorperlevel',
 'stats_spellblock',
 'stats_spellblockperlevel',
 'stats_attackrange',
 'stats_hpregen',
 'stats_hpregenperlevel',
 'stats_mpregen',
 'stats_mpregenperlevel',
 'stats_crit',
 'stats_critperlevel',
 'stats_attackdamage',
 'stats_attackdamageperlevel',
 'stats_attackspeedperlevel',
 'stats_attackspeed',
 'spell_q_id',
 'spell_q_maxrank',
 'spell_q_cooldown',
 'spell_q_cost',
 'spell_q_datavalues',
 'spell_q_effect',
 'spell_q_vars',
 'spell_q_costType',
 'spell_q_maxammo',
 'spell_q_range',
 'spell_q_resource',
 'spell_w_id',
 'spell_w_maxrank',
 'spell_w_cooldown',
 'spell_w_cost',
 'spell_w_datavalues',
 'spell_w_effect',
 'spell_w_vars',
 'spell_w_costType',
 'spell_w_maxammo',
 'spell_w_range',
 'spell_w_resource',
 'spell_e_id',
 'spell_e_maxrank',
 'spell_e_cooldown',
 'spell_e_cost',
 'spell_e_datavalues',
 'spell_e_effect',
 'spell_e_vars',
 'spell_e_costType',
 'spell_e_maxammo',
 'spell_e_range',
 'spell_e_resource',
 'spell_r_id',
 'spell_r_maxrank',
 'spell_r_cooldown',
 'spell_r_cost',
 'spell_r_datavalues',
 'spell_r_effect',
 'spell_r_vars',
 'spell_r_costType',
 'spell_r_maxammo',
 'spell_r_range',
 'spell_r_resource']

In [ ]:
for col in df_champs.columns:
    print("Column:", col)
    print(df_champs[col].unique())
    print(len(df_champs[col].unique()))

Column: patch
['15.1.1' '15.10.1' '15.11.1' '15.12.1' '15.13.1' '15.14.1' '15.15.1'
 '15.16.1' '15.17.1' '15.18.1' '15.19.1' '15.2.1' '15.20.1' '15.21.1'
 '15.22.1' '15.23.1' '15.24.1' '15.3.1' '15.4.1' '15.5.1' '15.6.1'
 '15.7.1' '15.8.1' '15.9.1']
24
Column: key
[266 103  84 166  12 799  32  34   1 523  22 136 893 268 432 200  53  63
 201 233  51 164  69  31  42 122 131  36 119 245  60  28  81   9 114 105
   3  41  86 150  79 104 887 120  74 910 420  39 427  40  59  24 126 202
 222 897 145 429  43  30  38  55  10 141  85 121 203 240  96   7  64  89
 876 127 236 117  99  54  90  57  11 902  21  62  82  25 950 267  75 111
 518  76 895  56  20   2  61 516  80  78 555 246 133 497  33 421 526 888
  58 107  92  68  13 360 113 235 147 875  35  98 102  27  14  15  72 901
  37  16  50 517 134 223 163  91  44  17 412  18  48  23   4  29  77   6
 110  67  45 161 711 254 234 112   8 106  19 498 101   5 157 777  83 350
 154 238 221 115  26 142 143 800 804 904]
172
Column: name
['Aatrox' 'Ahri' 'Akali' 'Akshan' 'Alistar' 'Ambessa' 'Amumu' 'Anivia'
 'Annie' 'Aphelios' 'Ashe' 'Aurelion Sol' 'Aurora' 'Azir' 'Bard'
 "Bel'Veth" 'Blitzcrank' 'Brand' 'Braum' 'Briar' 'Caitlyn' 'Camille'
 'Cassiopeia' "Cho'Gath" 'Corki' 'Darius' 'Diana' 'Dr. Mundo' 'Draven'
 'Ekko' 'Elise' 'Evelynn' 'Ezreal' 'Fiddlesticks' 'Fiora' 'Fizz' 'Galio'
 'Gangplank' 'Garen' 'Gnar' 'Gragas' 'Graves' 'Gwen' 'Hecarim'
 'Heimerdinger' 'Hwei' 'Illaoi' 'Irelia' 'Ivern' 'Janna' 'Jarvan IV' 'Jax'
 'Jayce' 'Jhin' 'Jinx' "K'Santé" "Kai'Sa" 'Kalista' 'Karma' 'Karthus'
 'Kassadin' 'Katarina' 'Kayle' 'Kayn' 'Kennen' "Kha'Zix" 'Kindred' 'Kled'
 "Kog'Maw" 'LeBlanc' 'Lee Sin' 'Leona' 'Lillia' 'Lissandra' 'Lucian'
 'Lulu' 'Lux' 'Malphite' 'Malzahar' 'Maokai' 'Maître Yi' 'Milio'
 'Miss Fortune' 'Wukong' 'Mordekaiser' 'Morgana' 'Naafiri' 'Nami' 'Nasus'
 'Nautilus' 'Neeko' 'Nidalee' 'Nilah' 'Nocturne' 'Nunu et Willump' 'Olaf'
 'Orianna' 'Ornn' 'Pantheon' 'Poppy' 'Pyke' 'Qiyana' 'Quinn' 'Rakan'
 'Rammus' "Rek'Sai" 'Rell' 'Renata Glasc' 'Renekton' 'Rengar' 'Riven'
 'Rumble' 'Ryze' 'Samira' 'Sejuani' 'Senna' 'Séraphine' 'Sett' 'Shaco'
 'Shen' 'Shyvana' 'Singed' 'Sion' 'Sivir' 'Skarner' 'Smolder' 'Sona'
 'Soraka' 'Swain' 'Sylas' 'Syndra' 'Tahm Kench' 'Taliyah' 'Talon' 'Taric'
 'Teemo' 'Thresh' 'Tristana' 'Trundle' 'Tryndamere' 'Twisted Fate'
 'Twitch' 'Udyr' 'Urgot' 'Varus' 'Vayne' 'Veigar' "Vel'Koz" 'Vex' 'Vi'
 'Viego' 'Viktor' 'Vladimir' 'Volibear' 'Warwick' 'Xayah' 'Xerath'
 'Xin Zhao' 'Yasuo' 'Yone' 'Yorick' 'Yuumi' 'Zac' 'Zed' 'Zeri' 'Ziggs'
 'Zilean' 'Zoé' 'Zyra' 'Mel' 'Yunara' 'Zaahen']
172
Column: partype
['Puits de sang' 'Mana' 'Énergie' nan 'Fureur' 'Aucune' 'Rage' 'Courage'
 'Bouclier' 'Férocité' 'Vapeur' 'Agressivité' 'Afflux sanguin' 'Impulsion']
14
Column: tags
['["Fighter"]' '["Mage", "Assassin"]' '["Assassin"]'
 '["Marksman", "Assassin"]' '["Tank", "Support"]'
 '["Fighter", "Assassin"]' '["Mage"]' '["Mage", "Support"]' '["Marksman"]'
 '["Marksman", "Support"]' '["Mage", "Marksman"]' '["Support", "Mage"]'
 '["Tank", "Mage"]' '["Marksman", "Mage"]' '["Fighter", "Tank"]'
 '["Tank", "Fighter"]' '["Assassin", "Mage"]' '["Assassin", "Fighter"]'
 '["Fighter", "Mage"]' '["Marksman", "Fighter"]' '["Tank"]'
 '["Support", "Assassin"]' '["Support"]' '["Support", "Marksman"]'
 '["Support", "Tank"]' '["Mage", "Fighter"]' '["Fighter", "Marksman"]']
27
Column: info_attack
[ 8  3  5  0  6  9  2  1  7  4 10]
11
Column: info_defense
[ 4  3  0  9  2  6  8  5  7 10  1]
11
Column: info_magic
[ 3  8  0  5 10  1  2  7  9  4  6]
11
Column: info_difficulty
[ 4  5  7  0 10  3  6  9  2  8  1]
11
Column: stats_hp
[650 590 600 630 685 550 560 610 607 570 625 580 644 652 640 613 675 655
 620 642 632 690 540 558 656 665 646 672 670 643 595 410 635 598 645 605
 641 669 631 585 660 565 545 530 575 563 658 615 696 604 664 596 500 654
 606 574]
56
Column: stats_hpperlevel
[114 104 119 107 120 110  94  92 102 101  90 103  99 109 105 112  95 100
  98 106 126  79 115 108  84 111  88 124  89  87  91 122  69  96  93 121]
36
Column: stats_mp
[    0   418   200   350   285   495   348   280   530   475   320    60
   267   469   311   315   339   400   270   263   375   361   324   500
   300   317   410   100   325   330   385   480   450   360   260   345
   374   467   327   302   251   365   340   326   295   275   316   341
   415   269   310     4   150   349   297   425   470   334   274   333
   271   232   490 10000   405     2   440   250   452]
69
Column: stats_mpperlevel
[ 0.  25.  40.  45.  42.  35.  30.  50.  21.  52.  60.  58.  39.  70.
 28.  47.  20.  55.  31.  87.  43.  23.5 65.  62.  33.  38.  29.  37.
 44.  32.  26.  22. ]
32
Column: stats_movespeed
[345 330 335 325 340 328 350 355 315]
9
Column: stats_armor
[38 21 23 26 47 35 33 19 22 25 34 32 37 27 30 18 39 31 29 24 36 28 43 20
 40 42]
26
Column: stats_armorperlevel
[4.8  4.7  4.9  4.   4.5  4.2  4.6  5.   5.2  4.3  3.7  5.45 4.95 4.45
 5.5  4.4  4.55 0.   3.9  4.35]
20
Column: stats_spellblock
[32 30 37 29 22 28 26 31 36 25]
10
Column: stats_spellblockperlevel
[2.05 1.3  2.3  1.55 2.1  1.45 1.8  1.5  2.55 1.1 ]
10
Column: stats_attackrange
[175 550 125 500 600 625 525 150 650 480 425 200 475 450 325 225 300 350
 575]
19
Column: stats_hpregen
[ 3.    2.5   9.    3.75  8.5   5.5   3.25  3.5   6.    7.    7.5   0.
 10.    6.5   4.    8.    4.5   9.5   5.  ]
19
Column: stats_hpregenperlevel
[0.5  0.6  0.9  0.65 0.85 0.75 0.55 1.   0.   0.8  0.95 0.7  1.25 0.4 ]
14
Column: stats_mpregen
[ 0.    8.   50.    8.2   8.5   7.4   6.5   7.    6.    9.    8.15  7.2
  6.6   8.05  8.11  9.5   7.5  11.5   7.6   6.7   6.3  13.    7.59  8.75
 11.    7.3   7.25  7.45  8.65  7.35  7.85 10.    9.6   6.25  8.25  6.85
 11.35]
37
Column: stats_mpregenperlevel
[0.   0.8  0.7  0.55 0.4  0.65 0.75 0.45 0.6  0.35 1.   0.95 0.5  0.9 ]
14
Column: stats_crit
[0]
1
Column: stats_critperlevel
[0]
1
Column: stats_attackdamage
[60 53 62 52 63 57 51 50 55 59 58 56 68 69 64 61 66 54 65 47 46 48 67 44
 49]
25
Column: stats_attackdamageperlevel
[5.     3.     3.3    3.75   3.8    3.2    2.65   2.3    2.95   3.5
 1.5    4.2    2.     2.5    3.6    2.75   3.7    4.5    4.     2.7
 4.25   4.4    3.25   2.6    3.9    3.1    2.2    2.9    2.4    2.1
 4.7    4.15   0.     3.4    2.35   3.1416 2.8    3.45   4.75  ]
39
Column: stats_attackspeedperlevel
[2.5   2.2   3.2   4.    2.125 2.18  1.68  1.36  2.1   3.33  1.5   2.
 6.    0.    1.13  3.5   1.44  2.8   1.    3.3   2.7   1.75  2.11  3.1
 3.65  2.05  3.    2.25  3.4   1.4   1.8   4.5   2.3   3.7   2.74  2.65
 2.35  2.9   1.53  2.61  3.48  3.22  2.95  2.215 2.75  1.85  1.9   1.3
 2.14  3.38  3.75  2.24  1.59  3.9   1.6   2.13  5.5   5.    2.6  ]
59
Column: stats_attackspeed
[0.651 0.668 0.625 0.638 0.736 0.658 0.61  0.64  0.85  0.681 0.644 0.647
 0.67  0.679 0.688 0.667 0.69  0.675 0.475 0.656 0.694 0.669 0.665 0.8
 0.663 0.706 0.697 0.721 0.635 0.751 0.645 0.65  0.643 0.7  ]
34
Column: spell_q_id
['AatroxQ' 'AhriQ' 'AkaliQ' 'AkshanQ' 'Pulverize' 'AmbessaQ' 'BandageToss'
 'FlashFrost' 'AnnieQ' 'ApheliosQ_ClientTooltipWrapper' 'AsheQ'
 'AurelionSolQ' 'AuroraQ' 'AzirQWrapper' 'BardQ' 'BelvethQ' 'RocketGrab'
 'BrandQ' 'BraumQ' 'BriarQ' 'CaitlynQ' 'CamilleQ' 'CassiopeiaQ' 'Rupture'
 'PhosphorusBomb' 'DariusCleave' 'DianaQ' 'DrMundoQ' 'DravenSpinning'
 'EkkoQ' 'EliseHumanQ' 'EvelynnQ' 'EzrealQ' 'FiddleSticksQ' 'FioraQ'
 'FizzQ' 'GalioQ' 'GangplankQWrapper' 'GarenQ' 'GnarQ' 'GragasQ'
 'GravesQLineSpell' 'GwenQ' 'HecarimRapidSlash' 'HeimerdingerQ' 'HweiQ'
 'IllaoiQ' 'IreliaQ' 'IvernQ' 'HowlingGale' 'JarvanIVDragonStrike' 'JaxQ'
 'JayceToTheSkies' 'JhinQ' 'JinxQ' 'KSanteQ' 'KaisaQ' 'KalistaMysticShot'
 'KarmaQ' 'KarthusLayWasteA1' 'NullLance' 'KatarinaQ' 'KayleQ' 'KaynQ'
 'KennenShurikenHurlMissile1' 'KhazixQ' 'KindredQ' 'KledQ' 'KogMawQ'
 'LeblancQ' 'LeeSinQOne' 'LeonaShieldOfDaybreak' 'LilliaQ' 'LissandraQ'
 'LucianQ' 'LuluQ' 'LuxLightBinding' 'SeismicShard' 'MalzaharQ' 'MaokaiQ'
 'AlphaStrike' 'MilioQ' 'MissFortuneRicochetShot' 'MonkeyKingDoubleAttack'
 'MordekaiserQ' 'MorganaQ' 'NaafiriQ' 'NamiQ' 'NasusQ'
 'NautilusAnchorDrag' 'NeekoQ' 'JavelinToss' 'NilahQ'
 'NocturneDuskbringer' 'NunuQ' 'OlafAxeThrowCast' 'OrianaIzunaCommand'
 'OrnnQ' 'PantheonQ' 'PoppyQ' 'PykeQ' 'QiyanaQ' 'QuinnQ' 'RakanQ'
 'PowerBall' 'RekSaiQ' 'RellQ' 'RenataQ' 'RenektonCleave' 'RengarQ'
 'RivenTriCleave' 'RumbleFlameThrower' 'RyzeQWrapper' 'SamiraQ' 'SejuaniQ'
 'SennaQ' 'SeraphineQ' 'SettQ' 'Deceive' 'ShenQ' 'ShyvanaDoubleAttack'
 'PoisonTrail' 'SionQ' 'SivirQ' 'SkarnerQ' 'SmolderQ' 'SonaQ' 'SorakaQ'
 'SwainQ' 'SylasQ' 'SyndraQ' 'TahmKenchQ' 'TaliyahQ' 'TalonQ' 'TaricQ'
 'TeemoQ' 'ThreshQ' 'TristanaQ' 'TrundleTrollSmash' 'TryndamereQ'
 'WildCards' 'TwitchHideInShadows' 'UdyrQ' 'UrgotQ' 'VarusQ' 'VayneTumble'
 'VeigarBalefulStrike' 'VelkozQ' 'VexQ' 'ViQ' 'ViegoQ' 'ViktorQ'
 'VladimirQ' 'VolibearQ' 'WarwickQ' 'XayahQ' 'XerathArcanopulseChargeUp'
 'XinZhaoQ' 'YasuoQ1Wrapper' 'YoneQ' 'YorickQ' 'YuumiQ' 'ZacQ' 'ZedQ'
 'ZeriQ' 'ZiggsQ' 'ZileanQ' 'ZoeQ' 'ZyraQ' 'MelQ' 'YunaraQ' 'ZaahenQ']
172
Column: spell_q_maxrank
[5 6]
2
Column: spell_q_cooldown
['[14, 12, 10, 8, 6]' '[7, 7, 7, 7, 7]' '[1.5, 1.5, 1.5, 1.5, 1.5]'
 '[8, 7.25, 6.5, 5.75, 5]' '[14, 13, 12, 11, 10]' '[3, 3, 3, 3, 3]'
 '[12, 11, 10, 9, 8]' '[4, 4, 4, 4, 4]' '[9, 9, 9, 9, 9, 9]'
 '[0, 0, 0, 0, 0]' '[9, 8.5, 8, 7.5, 7]' '[11, 10, 9, 8, 7]'
 '[1, 1, 1, 1, 1]' '[20, 19, 18, 17, 16]' '[8, 7.5, 7, 6.5, 6]'
 '[13, 12, 11, 10, 9]' '[10, 9, 8, 7, 6]' '[9, 8, 7, 6, 5]'
 '[3.5, 3.5, 3.5, 3.5, 3.5]' '[6, 6, 6, 6, 6]' '[5.5, 5.25, 5, 4.75, 4.5]'
 '[15, 14.5, 14, 13.5, 13]' '[13, 11.25, 9.5, 7.75, 6]'
 '[4.5, 4.5, 4.5, 4.5, 4.5]' '[8, 8, 8, 8, 8]' '[20, 17.5, 15, 12.5, 10]'
 '[6.5, 5.75, 5, 4.25, 3.5]' '[14, 14, 14, 14, 14]'
 '[16, 14, 12, 10, 8, 6]' '[7, 6.5, 6, 5.5, 5]'
 '[0.9, 0.9, 0.9, 0.9, 0.9]' '[10, 9.5, 9, 8.5, 8]'
 '[7, 6.25, 5.5, 4.75, 4]' '[9, 9, 9, 9, 9]' '[5, 5, 5, 5, 5]'
 '[6, 5.5, 5, 4.5, 4]' '[8, 7, 6, 5, 4]' '[11, 10.5, 10, 9.5, 9]'
 '[20, 19.5, 19, 18.5, 18]' '[10, 10, 10, 10, 10]' '[7, 6, 5, 4, 3]'
 '[7.5, 6.5, 5.5, 4.5, 3.5]' '[6, 5.25, 4.5, 3.75, 3]'
 '[11, 10.25, 9.5, 8.75, 8]' '[12, 10.5, 9, 7.5, 6]' '[4, 3.5, 3, 2.5, 2]'
 '[16, 16, 16, 16, 16]' '[0.25, 0.25, 0.25, 0.25, 0.25]'
 '[13, 13, 13, 13, 13]' '[6, 5, 4, 3, 2]' '[19, 17.5, 16, 14.5, 13]'
 '[15, 15, 15, 15, 15]' '[12, 11.5, 11, 10.5, 10]'
 '[13, 11.5, 10, 8.5, 7]' '[5.5, 5, 4.5, 4, 3.5]'
 '[19, 16.5, 14, 11.5, 9]' '[12, 12, 12, 12, 12]'
 '[6, 5.75, 5.5, 5.25, 5]' '[6, 6, 6, 6, 6, 6]' '[16, 15, 14, 13, 12]'
 '[5, 4.5, 4, 3.5, 3]' '[9, 7.9, 6.8, 5.7, 4.6]'
 '[6.5, 6.5, 6.5, 6.5, 6.5, 6.5]' '[14, 12.5, 11, 9.5, 8]'
 '[8.5, 8, 7.5, 7, 6.5]' '[16, 14.5, 13, 11.5, 10]'
 '[13, 12.5, 12, 11.5, 11]' '[8, 6.75, 5.5, 4.25, 3]'
 '[18, 16.5, 15, 13.5, 12]']
69
Column: spell_q_cost
['[0, 0, 0, 0, 0]' '[55, 65, 75, 85, 95]' '[110, 100, 90, 80, 70]'
 '[60, 65, 70, 75, 80]' '[50, 55, 60, 65, 70]' '[70, 70, 70, 70, 70]'
 '[45, 50, 55, 60, 65]' '[80, 85, 90, 95, 100]' '[60, 60, 60, 60, 60, 60]'
 '[30, 30, 30, 30, 30]' '[35, 40, 45, 50, 55]' '[60, 60, 60, 60, 60]'
 '[70, 80, 90, 100, 110]' '[100, 100, 100, 100, 100]'
 '[55, 60, 65, 70, 75]' '[25, 25, 25, 25, 25]' '[50, 50, 50, 50, 50]'
 '[25, 30, 35, 40, 45]' '[45, 45, 45, 45, 45]' '[50, 60, 70, 80, 90]'
 '[40, 45, 50, 55, 60]' '[28, 31, 34, 37, 40]' '[65, 65, 65, 65, 65]'
 '[20, 25, 30, 35, 40]' '[70, 75, 80, 85, 90]' '[55, 50, 45, 40, 35]'
 '[80, 80, 80, 80, 80]' '[40, 40, 40, 40, 40]' '[28, 26, 24, 22, 20]'
 '[20, 20, 20, 20, 20]' '[80, 90, 100, 110, 120]' '[15, 15, 15, 15, 15]'
 '[90, 95, 100, 105, 110]' '[40, 40, 40, 40, 40, 40]'
 '[55, 55, 55, 55, 55]' '[40, 50, 60, 70, 80]' '[60, 55, 50, 45, 40]'
 '[35, 35, 35, 35, 35]' '[48, 56, 64, 72, 80]' '[30, 35, 40, 45, 50]'
 '[40, 38, 36, 34, 32]' '[60, 70, 80, 90, 100]'
 '[140, 130, 120, 110, 100]' '[13, 13, 13, 13, 13]' '[50, 46, 42, 38, 34]'
 '[65, 70, 75, 80, 85]' '[20, 20, 20, 20, 20, 20]'
 '[50, 55, 60, 65, 70, 75]' '[75, 70, 65, 60, 55]' '[50, 45, 40, 35, 30]']
50
Column: spell_q_datavalues
['{}']
1
Column: spell_q_effect
['[null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [70, 95, 120, 145, 170], [1, 1, 1, 1, 1], [1800, 1800, 1800, 1800, 1800], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0], [0, 0, 0, 0, 0, 0]]'
 '[null, [4, 4, 4, 4, 4], [4, 4, 4, 4, 4], [6, 6, 6, 6, 6], [25, 35, 45, 55, 65], [0.22, 0.23, 0.24, 0.25, 0.26], [1.1, 1.15, 1.2, 1.25, 1.3], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0]]'
 '[null, [60, 80, 100, 120, 140], [25, 25, 25, 25, 25], [0, 0, 0, 0, 0], [70, 70, 70, 70, 70], [1600, 1600, 1600, 1600, 1600], [200, 200, 200, 200, 200], [325, 325, 325, 325, 325], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [90, 140, 190, 240, 290], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [70, 100, 130, 160, 190], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [75, 125, 175, 225, 275], [70, 70, 70, 70, 70], [30, 30, 30, 30, 30], [0.02, 0.02, 0.02, 0.02, 0.02], [2, 2, 2, 2, 2], [1050, 1050, 1050, 1050, 1050], [4, 4, 4, 4, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [50, 50, 50, 50, 50], [1, 1, 1, 1, 1], [1.3, 1.45, 1.6, 1.75, 1.9], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [75, 110, 145, 180, 215], [3, 3, 3, 3, 3], [30, 35, 40, 45, 50], [3, 3, 3, 3, 3], [7, 7, 7, 7, 7], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [60, 60, 60, 60, 60], [1.5, 1.5, 1.5, 1.5, 1.5], [0.625, 0.625, 0.625, 0.625, 0.625], [1, 1, 1, 1, 1], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [100, 110, 120, 130, 140], [50, 80, 110, 140, 170], [99, 99, 99, 99, 99], [0.1, 0.1, 0.1, 0.1, 0.1], [15, 15, 15, 15, 15], [35, 35, 35, 35, 35], [45, 45, 45, 45, 45], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [60, 95, 130, 165, 200], [1, 1, 1, 1, 1], [1.5, 1.5, 1.5, 1.5, 1.5], [3, 3, 3, 3, 3], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [100, 100, 100, 100, 100], [75, 85, 95, 105, 115], [30, 35, 40, 45, 50], [5.75, 5.75, 5.75, 5.75, 5.75], [40, 45, 50, 55, 60], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [70, 85, 100, 115, 130], [40, 45, 50, 55, 60], [40, 65, 90, 115, 140], [100, 100, 100, 100, 100], [0, 0, 0, 0, 0], [165, 165, 165, 165, 165], [1.75, 1.75, 1.75, 1.75, 1.75], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [40, 75, 110, 145, 180], [75, 100, 125, 150, 175], [15, 20, 25, 30, 35], [36, 42, 48, 54, 60], [60, 90, 120, 150, 180], [4, 4, 4, 4, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [30, 30, 30, 30, 30], [60, 60, 60, 60, 60], [15, 25, 35, 45, 55], [25, 30, 35, 40, 45], [6, 6, 6, 6, 6], [30, 30, 30, 30, 30], [50, 50, 50, 50, 50], [4, 4, 4, 4, 4], [-0.25, -0.25, -0.25, -0.25, -0.25]]'
 '[null, [10, 25, 40, 55, 70], [0, 0, 0, 0, 0], [650, 750, 850, 950, 1050], [1.5, 1.5, 1.5, 1.5, 1.5], [600, 600, 600, 600, 600], [1, 1, 1, 1, 1], [0.35, 0.35, 0.35, 0.35, 0.35], [40, 40, 40, 40, 40], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [10, 40, 70, 100, 130], [3, 4, 5, 6, 7], [0, 0, 0, 0, 0], [500, 500, 500, 500, 500], [4, 5, 6, 7, 8], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [80, 120, 160, 200, 240], [40, 45, 50, 55, 60], [2, 2, 2, 2, 2], [4, 4, 4, 4, 4], [2, 2, 2, 2, 2], [150, 150, 150, 150, 150], [70, 70, 70, 70, 70], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [3, 3, 3, 3, 3], [1, 1, 1, 1, 1], [3, 3, 3, 3, 3], [60, 60, 60, 60, 60], [8, 8, 8, 8, 8], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [900, 900, 900, 900, 900], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [10, 10, 10, 10, 10], [200, 200, 200, 200, 200], [800, 800, 800, 800, 800], [10, 8, 6, 4, 2], [5, 5, 5, 5, 5], [0.1, 0.15, 0.2, 0.25, 0.3], [1.2, 1.2, 1.2, 1.2, 1.2], [-0.3, -0.35, -0.4, -0.45, -0.5], [1.5, 1.5, 1.5, 1.5, 1.5], [0, 0, 0, 0, 0]]'
 '[null, [80, 120, 160, 200, 240], [10, 14, 18, 22, 26], [3, 3, 3, 3, 3], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [40, 55, 70, 85, 100], [6, 6, 6, 6, 6], [25, 25, 25, 25, 25], [2, 2, 2, 2, 2], [0.35, 0.35, 0.35, 0.35, 0.35], [100, 100, 100, 100, 100], [12, 12, 12, 12, 12], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [45, 65, 85, 105, 125], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [65, 95, 125, 155, 185], [0, 0, 0, 0, 0], [80, 110, 140, 170, 200], [1.5, 1.5, 1.5, 1.5, 1.5], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [2, 2, 2, 2, 2], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [75, 95, 115, 135, 155], [0.65, 0.65, 0.65, 0.65, 0.65], [5, 5, 5, 5, 5], [3.5, 3.5, 3.5, 3.5, 3.5], [200, 250, 300, 350, 400], [40, 40, 40, 40, 40], [300, 300, 300, 300, 300], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [75, 125, 175, 225, 275], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [80, 105, 130, 155, 180], [110, 110, 110, 110, 110], [50, 50, 50, 50, 50], [45, 45, 45, 45, 45], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [40, 65, 90, 115, 140], [0, 0, 0, 0, 0], [500, 500, 500, 500, 500], [4, 3.5, 3, 2.5, 2], [100, 100, 100, 100, 100], [12, 12, 12, 12, 12], [0.35, 0.35, 0.35, 0.35, 0.35], [4, 4, 4, 4, 4], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [30, 55, 80, 105, 130], [0.65, 0.65, 0.65, 0.65, 0.65], [1.75, 1.75, 1.75, 1.75, 1.75], [2, 2, 2, 2, 2], [40, 45, 50, 55, 60], [9, 8.5, 8, 7.5, 7], [1.5, 1.5, 1.5, 1.5, 1.5], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [90, 140, 190, 240, 290], [10, 15, 20, 25, 30], [16, 20, 24, 28, 32], [4, 4, 4, 4, 4], [1, 1, 1, 1, 1], [1, 1, 1, 1, 1], [100, 100, 100, 100, 100], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [65, 90, 115, 140, 165], [65, 90, 115, 140, 165], [3.5, 3.5, 3.5, 3.5, 3.5], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [60, 60, 60, 60, 60], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [1, 1, 1, 1, 1], [10, 35, 60, 85, 110], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [0, 0, 0, 0, 0], [1.5, 1.5, 1.5, 1.5, 1.5], [20, 24, 28, 32, 36], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'
 '[null, [85, 115, 145, 175, 205], [60, 75, 90, 105, 120], [1000, 1000, 1000, 1000, 1000], [0.41, 0.41, 0.41, 0.41, 0.41], [100, 100, 100, 100, 100], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0], [0, 0, 0, 0, 0]]'

: